pingcap/docs-cn

- op-guide/docker.md
@siddontang @iamxy @qiuyesuifeng PTAL
> op-guide: Add document for deploying TiDB with docker

- op-guide/binary-deployment.md
- op-guide/docker-compose.md
- op-guide/docker-deployment.md
+ Remove the unnecessary `dsn` flag
+ Command line uses long options just like PD and TiDB.
@shenli @queenypingcap @iamxy
> op-guide: update TiKV command flags.

- op-guide/binary-deployment.md
Correct the link address of -config section in binary-deployment.md
In binary-deployment.md file two hyper-links' address has doubled **op_guide**
https://github.com/pingcap/docs-cn/blob/master/op-guide/op-guide/configuration.md#--config
> Correct the hyper-link address of -config section in binary-deployment.md

- tools/loader.md
Since  TiDB has deprecated the environment variable `@@session.tidb_skip_constraint_check`, so loader is no need to support this feature.
@GregoryIan  @buggithubs  @queenypingcap  @sunhao2017  PTAL
> loader: deprecate skip  unique check

- tools/syncer.md
Need to add language keywords to escape special character  `-`, which prevents content from being parsed as a markdown list.
@lilin90 @buggithubs PTAL
> fix: add `yaml` keyword for syncer config code block

- op-guide/binary-deployment.md
The name of download and decompress file name are different.
> Modify the compressed file name

- scripts/generate_pdf.sh
Is `v1.0.0~` necessary to keep？
@lilin90 @gaohailang PTAL
> fix: remove hardcode 'rc4+' for pdf version

- op-guide/binary-deployment.md
When I use pd-sever to create a pd cluster, parameters -initial-cluster and -join will conflict.
There are two ways to modify, remove directly.
Displayed error：
FATA[0000] parse cmd flags error: -initial-cluster and -join can not be provided at the same time
> Wrong use of -join parameter of pd

- README.md
- tools/tidb-controller.md
Add TiDB Controller usage. PTAL @lilin90
> tools: Add TiDB Controller usage

- releases/11alpha.md
Via: https://github.com/pingcap/docs/pull/447
> releases: fix typo in 1.1 Alpha

- releases/2.0.1.md
- releases/rn.md
Via: https://github.com/pingcap/docs/pull/469
> releases: add the release notes for TiDB 2.0.1

- op-guide/tidb-config-file.md
@XuHuaiyu @shenli PTAL
@lilin90
> op-guide: add lower-case-table-names notice

- ROADMAP.md
The roadmap is out of date. So we need to update it.
@coocood @zz-jason @winkyao PTAL
/cc @ilovesoup
> ROADMAP: Update roadmap

- ROADMAP.md
Via: https://github.com/pingcap/docs/pull/503
> roadmap: fix the list format

- FAQ.md
@shenli @zhengwanbo @lilin90 
PTAL
> FAQ: add FAQ questions

- op-guide/ansible-deployment-rolling-update.md
op-guide:
- use `scheduler remove` command instead of `curl` command
- add tidb-ansible upgrade note
> op-guide: use scheduler remove command instead of curl command

- tools/pd-control.md
related PR: https://github.com/pingcap/pd/pull/1140
> tools/pd-control: add more schedule options

- tools/tidb-binlog-kafka.md
as title
when dowload from http://download.pingcap.org/tidb-binlog-latest-linux-amd64.tar.gz, it only contains the binary, i think it may be better if it can include the default config template file?
> add about db-type=kafka

- tools/tikv-control.md
1. Add `--threads` argument
2. Add `compact-cluster` command
> tikv-control: update compact command

- tools/pd-control.md
See: https://github.com/pingcap/pd/pull/1140
> tools: update pd-control.md

- tools/pd-control.md
See https://github.com/pingcap/pd/pull/1126
> tools: add jq examples for pd-ctl

- tools/tikv-control.md
add how to use tikv-ctl to modify config dynamically
> tools: update tikv-control.md

- op-guide/docker-compose.md
fix: description does not match, used two different suffix of file generated-docker-compose
> op-guide: fix description that does not match

- README.md
- tools/pd-recover.md
add `pd-recover` usage document.
> tools: add pd recover usage document

- op-guide/ansible-deployment-scale.md
Add a step to remove pd.
@LinuxGit @lilin90 PTAL
> op-guide: update ansible-deployment-scale.md

- FAQ.md
@shenli @lilin90  @lamxTyler PTAL
> FAQ: add 4 questions and update description

- overview.md
Via: https://github.com/pingcap/docs-cn/pull/838/commits/39449275e458dbceceaff1fb82cebaaa75e84a46
> overview: add content about TiSpark

- tools/tikv-control.md
Via: https://github.com/pingcap/docs/pull/572/. Term issue addressed. PTAL. @lilin90 @hicqu
> tools: add sub commands for tikv-ctl

- sql/string-functions.md
@CaitinChen PTAL Via: https://github.com/pingcap/docs/pull/607
> sql: remove unsupported functions

- sql/time-zone.md
Updated change to adapt https://github.com/pingcap/tidb/pull/7656
> sql: update time-zone.md

- op-guide/history-read.md
Via: https://github.com/pingcap/docs/pull/612
> op-guide: update format, fix typo, add notes

- sql/mysql-compatibility.md
@tiancaiamao @CaitinChen PTAL Via: https://github.com/pingcap/docs/pull/604
> sql: add incompatibilities with MySQL

- op-guide/docker-compose.md
see https://github.com/pingcap/tidb-docker-compose/pull/3
option `buildFrom` has removed, new options are `buildPath` and `dockerfile`.
> docker-compose: move buildFrom to buildPath

- sql/json-functions-generated-column.md
Via https://github.com/pingcap/docs/pull/632
@lilin90 PTAL
> sql: add recent JSON functions

- tools/pd-control.md
related pr: [#642](https://github.com/pingcap/docs/pull/642)
> pd-ctl: update the output of health command

- ROADMAP.md
Via: https://github.com/tikv/tikv/pull/3641, https://github.com/pingcap/docs/pull/651
> roadmap: update TiKV transaction list

- tools/tikv-control.md
> tools: fix some tikv-ctl parameters

- sql/encryption-and-compression-functions.md
Via: https://github.com/pingcap/docs/pull/648
> sql: remove deprecation note

- README.md
- releases/208.md
- releases/rn.md
Via: https://github.com/pingcap/docs/pull/676
> releases, readme: add 2.0.8 releases notes

- tools/tidb-binlog-cluster.md
This PR removes an invalid character that causes CircleCI failure. It is at the beginning of `_tidb_rowid`, which is hard to detect during the review process. 
@WangXiangUSTC @CaitinChen PTAL
> tools: fix invalid character causing CircleCI failure

- sql/tidb-specific.md
After https://github.com/pingcap/tidb/pull/8298, the join hint `TIDB_INLJ` specifies the inner table in the join operator. This PR updates the document about this behavior change.
> sql: change the specification of "TIDB_INLJ"

- tispark/tispark-quick-start-guide.md
> tispark: fix a broken link caused by a period

- sql/mysql-compatibility.md
Via: https://github.com/pingcap/docs/pull/853/ PTAL @lilin90
> sql: allow_invalid_dates is now supported

- sql/dml.md
Sorry for my mistake in https://github.com/pingcap/docs-cn/pull/1134.
This PR rectify the `SQL_NO_CACHE` definition
> sql/dml: rectify SQL_NO_CACHE definition

- tools/dm/shard-merge-scenario.md
Added doc for DM use in shard merge scenario. The corresponding source file in English is:https://github.com/pingcap/docs/blob/master/tools/dm/shard-merge-scenario.md
@lilin90 @GregoryIan  PTAL
There are 4 external links included in this file, which are to be consistent with **data-synchronization-features.md** to be done by @GregoryIan 
/tools/dm/data-synchronization-features.md##table-routing
/tools/dm/data-synchronization-features.md#binlog-event-filtering
/tools/dm/data-synchronization-features.md#black-and-white-table-lists
/tools/dm/data-synchronization-features.md#column-mapping
> tools/dm: add doc for DM use in shard merge scenario

- FAQ.md
解答了 为什么`information_schema.tables.data_length` 记录的大小和 TiKV 监控面板上的 store size 不一样？
> FAQ: add a question about store size

- tools/dm/data-synchronization-features.md
This PR adds the SQL statements unsupported by the TiDB parser to the binlog event filter section.
Ref: [original text link](https://github.com/pingcap/tidb-tools/blob/docs/docs/dm/zh_CN/features/binlog-filter.md#%E8%BF%87%E6%BB%A4-TiDB-parser-%E4%B8%8D%E6%94%AF%E6%8C%81%E7%9A%84-SQL-%E8%AF%AD%E5%8F%A5)
@GregoryIan @csuzhangxc @amyangfei PTAL
> tools/dm: add SQL unsupported by TiDB parser

- op-guide/upgrade-FAQ.md
- The incorrect indentation causes display errors at the PingCAP website. 
- The Tab spaces cause the CI failure.
- Keep the code fences in lowercase.
This PR fixes them. @CaitinChen @crazycs520 PTAL
@CaitinChen Please pay attention to the above issues in https://github.com/pingcap/docs/pull/947 when you help review it. Thanks!
> op-guide: remove tab space, update indentation and code fences

- tools/tidb-binlog-cluster.md
TiDB-binlog backup-restore uses a link to https://github.com/pingcap/docs-cn/blob/master/op-guide/backup-restore.md while link to the local markdown file.
This lead to a problem that when you click the back-store on the document website of tidb-binlog, it will route you to the github rathar than to the document website of backup-store.
This PR aims to fix this problem. Pls take a review.
> tools: change the link of back-restore in tidb-binlog document

- sql/util.md
- v1.0/sql/util.md
- v2.0/sql/util.md
- v2.1/sql/util.md
User provided feedback that our explanation of TiDB 'USE' command in util document is not quite accurate: the meaning of default database is confusing.
Detailed at the issue link: https://github.com/pingcap/docs-cn/issues/1112
I updated the  explanation of TiDB 'USE' command in sql/util.md documents (1.0/2.0/2.1).
Previously: '切换默认 Database，当 SQL 语句中的表没有显式指定的 Database 时，即使用默认 Database。'
Updated: '切换需要使用的 Database 的时候，如果 SQL 语句中的表没有显式指定的 Database ，即默认使用当前选定的 Database。'
> sql: update the USE command explanation in util document

- tools/loader.md
This PR update the pprof-addr default port in Loader documents.
According to the https://internal.pingcap.net/confluence/pages/viewpage.action?pageId=21273346, Loader pprof-addr default port has changed from 10084 to 8272 while the public documents is out of date. 
Loader code for reference: 
https://github.com/pingcap/tidb-enterprise-tools/blob/master/loader/config.go
fs.StringVar(&cfg.PprofAddr, "pprof-addr", ":8272", "Loader pprof addr")
> tools: update the loader pprof-addr default port

- trouble-shooting.md
Via: https://github.com/pingcap/docs/pull/1091
@lilin90 PTAL
> trouble-shooting: update the issue report link

- tools/dm/deployment.md
When checking the [dm-deployment](https://pingcap.com/docs-cn/tools/dm/deployment/), i found an mistake in the return value of `ansible -i inventory.ini all -m shell -a 'whoami'`. 
In the document Step 9, it mentioned that you will get `root` when running the command of `ansible -i inventory.ini all -m shell -a 'whoami'` while the correct value should be `tidb`.
My testing:
```
tidb@OPS:~/dm-ansible$ ansible -i inventory.ini all -m shell -a 'whoami'
dm-worker1 | SUCCESS | rc=0 >>
tidb
dm_master | SUCCESS | rc=0 >>
tidb
tidb@OPS:~/dm-ansible$ ansible -i inventory.ini all -m shell -a 'whoami' -b
dm-worker1 | SUCCESS | rc=0 >>
root
dm_master | SUCCESS | rc=0 >>
root
```
BTW, i also checked the [dm-deployment](https://pingcap.com/docs/tools/dm/deployment/), it's correct.
> tools/dm: fix the error in valus from ansible command

- tools/syncer.md
https://github.com/pingcap/docs-cn/pull/1300 had an indentation as below: 
Should be caused by the tag indentation. 
This PR aims to fix it.
> tools: fix the format error in Syncer

- op-guide/dashboard-tikv-info.md
- op-guide/tune-tikv.md
- tools/tikv-control.md
Via: https://github.com/pingcap/docs/pull/1114 & https://github.com/pingcap/docs/pull/1134/ 
PTAL @lilin90 @yiwu-arbug 
There's an update for "dev/reference/performance/tune-tikv.md" in [#1134](https://github.com/pingcap/docs/pull/1134/files). And because tune-tikv.md has not been added to the dev folder in the docs-cn repo yet, this file is pending for updating.
> op-guide, tools: add descriptions for shared block cache

- sql/util.md
1. Currently TiDB  supports `FORMAT = "ROW"`, which is missing in the doc.
2. TiDB don't support `FORMAT = JSON` as MySQL do, this should be mentioned in the doc.
3. I've supported `FORMAT = TRADITIONAL` in https://github.com/pingcap/parser/pull/316 . Since that pr is not in the latest release, I'm not sure whether to add this change into doc
> sql: refine description for `EXPLAIN`

- tools/lightning/deployment.md
- tools/lightning/errors.md
- tools/lightning/monitor.md
Via: https://pingcap.com/docs/dev/reference/tools/tidb-lightning/monitor/ 
PTAL @dcalvin
> tools/lightning: update lightning docs

- releases/3.0.0-rc.2.md
Checked with devs, tidb binlog doesn't upgrade the Parser in 3.0, it's in 2.1. So remove this note.
> releases: remove one note of tidb binlog: 

- TOC.md
Reverts pingcap/docs-cn#1372  which was released earlier than supposed.
> Revert "TOC: remove release notes"

- TOC.md
This PR removed a redundant level of TOC above "migrate from Aurora" PTAL @lilin90
> TOC: remove a redundant level above migrate from aurora

- dev/reference/security/privilege-system.md
Make the document description more clear
> dev/reference/security: fix description about "grant" to a non-exist user

- TOC.md
- dev/reference/tools/tikv-control.md
Per feedback in the Wechat group, updated and added the Chinese version of TiKV control instead of linking it to the external file in English.  @yikeke PTAL
Link to the English version: https://github.com/tikv/tikv/blob/master/docs/tools/tikv-control.md
> reference/tools/tikv-control: add TiKV control in Chinese

- circle.yml
- scripts/generate_pdf.sh
CI failed at generating PDF for v2.1 and v3.0, so remove v2.1 and v3.0 from generate_pdf.sh
> generate_pdf.sh: stop generating PDFs for v3.0 and v2.1

- tidb-in-kubernetes/configuration.md
this PR mainly defined configurations of `tidb-cluster`.
- the table of variables is collated from [values.yaml](https://github.com/pingcap/tidb-operator/blob/master/charts/tidb-cluster/values.yaml)
- the other text is collated from [configuration](https://github.com/pingcap/tidb-operator/blob/master/docs/operation-guide.md#configuration)
@tennix @dcalvin @lilin90 @aylei  PTAL
> tidb-in-kubernetes:add configuration doc of tidb-cluster

- dev/how-to/upgrade/from-previous-version.md
- dev/how-to/upgrade/to-tidb-2.1.md
- dev/reference/tidb-binlog-overview.md
- dev/reference/tools/tidb-binlog/tidb-binlog-kafka.md
- v2.1/how-to/upgrade/from-previous-version.md
- v2.1/how-to/upgrade/to-tidb-2.1.md
- v2.1/reference/tidb-binlog-overview.md
- v3.0/how-to/upgrade/from-previous-version.md
- v3.0/how-to/upgrade/rolling-updates-with-ansible.md
- v3.0/how-to/upgrade/tidb-binlog.md
- v3.0/how-to/upgrade/to-tidb-2.1.md
- v3.0/reference/tidb-binlog-overview.md
- v3.0/reference/tools/tidb-binlog/tidb-binlog-kafka.md
In the https://pingcap.com/docs-cn/v3.0/how-to/upgrade/from-previous-version/ and https://pingcap.com/docs-cn/v3.0/how-to/upgrade/to-tidb-2.1/ links of TiDB Binlog are out of date, so users will get 404 when they click these links. 
And also for the reparo link in the https://pingcap.com/docs-cn/v3.0/reference/tidb-binlog-overview/ .
So i changed the below: 
* Update TiDB Binlog links in **/how-to/upgrade/to-tidb-2.1/** and **/how-to/upgrade/from-previous-version/**
* Update Reparo link in **/reference/tidb-binlog-overview/**
Apply in dev/v3.0/v2.1.
> dev/how-to/, dev/reference: fix some links in the upgrade documents

- dev/how-to/upgrade/from-previous-version.md
- dev/how-to/upgrade/tidb-binlog.md
- dev/how-to/upgrade/to-tidb-2.1.md
- dev/reference/tidb-binlog-overview.md
- v2.1/how-to/upgrade/from-previous-version.md
- v2.1/how-to/upgrade/tidb-binlog.md
- v2.1/how-to/upgrade/to-tidb-2.1.md
- v2.1/reference/tidb-binlog-overview.md
- v3.0/how-to/upgrade/from-previous-version.md
- v3.0/how-to/upgrade/tidb-binlog.md
- v3.0/how-to/upgrade/to-tidb-2.1.md
- v3.0/reference/tidb-binlog-overview.md
The kafka binlog links in https://pingcap.com/docs-cn/v3.0/how-to/upgrade/from-previous-version/ and https://pingcap.com/docs-cn/v3.0/how-to/upgrade/to-tidb-2.1/ are wrong, should be correct to `/reference/tools/tidb-binlog/tidb-binlog-kafka.md`
The Reparo link in https://pingcap.com/docs-cn/v3.0/reference/tidb-binlog-overview/ is wrong , should be correct to `/reference/tools/tidb-binlog/reparo.md`
Apply to 3.0/2.1/dev
> dev, v3.0, v2.1: fix the wrong tidb binlog links

- dev/reference/configuration/tikv-server/configuration-file.md
- dev/reference/system-databases/information-schema.md
- v3.0/reference/configuration/tikv-server/configuration-file.md
- v3.0/reference/system-databases/information-schema.md
fix incorrect links in dev and v3.0 folders @CaitinChen  PTAL
dev and v3.0
> dev, v3.0: fix incorrect links

- tidb-in-kubernetes/maintain-node.md
Fix typo and empty command in maintain-node documentation
@yikeke @tennix PTAL
> tidb-in-kubernetes/maintain-node: fix typo and empty command

- dev/benchmark/sysbench-v4.md
- v3.0/benchmark/sysbench-v4.md
> Fix bug: wrong AWS sysbench VM information

- dev/reference/system-databases/information-schema.md
- v2.1/reference/system-databases/information-schema.md
- v3.0/reference/system-databases/information-schema.md
Both @winoros and @crazycs520 updated the Information Schema doc:
- https://github.com/pingcap/docs-cn/pull/1445
- https://github.com/pingcap/docs-cn/pull/1488
This caused different versions of the doc.
This PR reorganizes the content of Information Schema.
- https://github.com/pingcap/docs-cn/pull/1445 -> https://github.com/pingcap/docs-cn/pull/1537
- https://github.com/pingcap/docs-cn/pull/1488
dev, v3.0
@yikeke PTAL
> dev, v3.0: reorganize the content of Information Schema

- dev/faq/upgrade.md
- v2.1-legacy/op-guide/upgrade-faq.md
- v2.1/faq/upgrade.md
- v3.0/faq/upgrade.md
faq/upgrade: update upgrade faq.
add doc for `treat-old-version-utf8-as-utf8mb4`  config.
https://github.com/pingcap/tidb/pull/9820
dev, v3.0, v2.1, v2.1-legacy
> faq/upgrade: update upgrade faq

- .circleci/config.yml
- .markdownlint.yaml
ref: https://github.com/pingcap/docs-cn/pull/1494
Ignore `.github` dir in CI check and disable single trailing new line rule
@disksing @yikeke  PTAL
> Ignore .github and comment out single trailing new line

- dev/reference/performance/tune-tikv.md
- v2.1/reference/key-monitoring-metrics/tikv-dashboard.md
- v2.1/reference/performance/tune-tikv.md
- v2.1/reference/tools/tikv-control.md
- v3.0/reference/performance/tune-tikv.md
- Remove the inapplicable shared block cache description from `v2.1` (change it back for 2.1)
- Update description in `dev` and `v3.0`
https://github.com/pingcap/docs-cn/pull/1329
> dev, v2.1, v3.0: remove shared block cache from 2.1

- dev/reference/tidb-operator-overview.md
- v3.0/reference/tidb-operator-overview.md
This PR fixes a broken link in the `TiDB Operator Overview` document.
`v3.0` `dev`
> v3.0, dev/reference: fix a broken link in TiDB operator overview

- dev/reference/configuration/tidb-in-kubernetes/backup-configuration.md
- v3.0/reference/configuration/tidb-in-kubernetes/backup-configuration.md
This PR fixed two links.
TiDB 3.0/Dev
> tidb-in-kubernetes/*/backup: fix bad links

- dev/tidb-in-kubernetes/reference/configuration/tidb-cluster.md
- v3.0/tidb-in-kubernetes/reference/configuration/tidb-cluster.md
this PR adds the resource configuration requirements for NUMA architecture CPU
> configuration: fix resource configuration

- dev/reference/sql/language-structure/keywords-and-reserved-words.md
- v2.1/reference/sql/language-structure/keywords-and-reserved-words.md
- v3.0/reference/sql/language-structure/keywords-and-reserved-words.md
Reorganize the list of keywords and reserved words
https://github.com/pingcap/docs/pull/1428
> dev, v2.1, v3.0: reorganize the list of keywords and reserved words

- dev/reference/configuration/tidb-server/tidb-specific-variables.md
- v2.1/reference/configuration/tidb-server/tidb-specific-variables.md
- v3.0/reference/configuration/tidb-server/tidb-specific-variables.md
Rename `tidb_back_off_weight` to `tidb_backoff_weight` to make it consistent with `tidb_backoff_lock_fast`.
> tidb-server: rename tidb_back_off_weight to tidb_backoff_weight

- dev/releases/3.0.2.md
- v3.0/releases/3.0.2.md
The release in TiDB Binlog has a mistake in 
```
Add the node-id configuration in Drainer to specify a specific logic used by Drainer
```
The configuration should be `node-id` rather than `note-id`
V3.0, Dev
> dev/releases, v3.0/releases: fix the 3.0.2 tidb binlog releaes mistake

- dev/reference/tools/data-migration/configure/task-configuration-file.md
- dev/reference/tools/data-migration/dm-portal.md
- v2.1/reference/tools/data-migration/configure/task-configuration-file.md
- v2.1/reference/tools/data-migration/dm-portal.md
- v3.0/reference/tools/data-migration/configure/task-configuration-file.md
- v3.0/reference/tools/data-migration/dm-portal.md
1. Fix the typo in DM Portal
2. Fix the mistake in DM task configuration file
> dev/reference, v3.0/reference, v2.1/reference: DM doc issue fix

- dev/reference/tools/data-migration/dm-upgrade.md
- v2.1/reference/tools/data-migration/dm-upgrade.md
- v3.0/reference/tools/data-migration/dm-upgrade.md
Add incompatible DM upgrade version advice after this [PR](https://github.com/pingcap/dm/pull/212) is merged.
https://github.com/pingcap/dm/pull/212
> dev, v3.0, v2.1: add DM upgrade advice

- dev/how-to/upgrade/from-previous-version.md
- v2.1/how-to/upgrade/from-previous-version.md
- v3.0/how-to/upgrade/from-previous-version.md
When users upgrading the TiDB from 2.1 to 3.0, may confuse the difference of `rolling_update` and `excessive_rolling_update ` and operate with mistake. 
So, i changed the the doc in **/how-to/upgrade/from-previous-version/**, optimize the explanation of `rolling_update` and `excessive_rolling_update `. 
N/A
> how-to: optimize the explanation of ansible-excessive_rolling_update

- dev/reference/sql/data-types/string.md
- v2.0/sql/datatype.md
- v2.1/reference/sql/data-types/string.md
- v3.0/reference/sql/data-types/string.md
Change `TINYTEXT[(M)]` to `TINYTEXT`. 
Because both MySQL and TiDB don't support create a column with type `TINYTEXT(number)` but `TINYTEXT`.
```SQL
> select tidb_version() \G
tidb_version() | Release Version: v4.0.0-alpha-103-g9d71884e0
Git Commit Hash: 9d71884e0fc6a7ccb31bf0bfc91baec6b85e79a7
Git Branch: master
UTC Build Time: 2019-08-21 03:43:29
GoVersion: go version go1.12.5 darwin/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
> create table t_1(tt5 tinytext(5))  -- This will throw error
(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 30 near "(5))" ')
> create table t_1(tt5 tinytext) -- This is OK
``` …
> reference/sql/data-types/string : fix syntax for tinytext

- dev/how-to/deploy/tidb-binlog.md
- v2.1-legacy/tools/tidb-binlog-cluster.md
- v2.1/how-to/deploy/tidb-binlog.md
- v3.0/how-to/deploy/tidb-binlog.md
add tags=pump when deploy pump, otherwise may deploy other server
v2.1, v3.0, dev
> tools: add tags when deploy pump by ansible

- dev/tidb-in-kubernetes/deploy/gcp-gke.md
- v3.0/tidb-in-kubernetes/deploy/gcp-gke.md
Update deploy doc on GCP to make it clearer
dev, v3.0
> tidb-in-kubernetes: make deploy doc clearer on GCP

- dev/reference/performance/follower-read.md
- v3.1/reference/performance/follower-read.md
- Remove words that might cause misunderstanding: `单行数据读取的线性一致性`->`数据读取的线性的一致性`
- Make Follower Read capitalization consistent
https://github.com/pingcap/docs-cn/pull/2019
dev, v3.1
> reference/performance: improve the wording of Follower Read

- dev/reference/tools/tidb-lightning/config.md
- v2.1/reference/tools/tidb-lightning/config.md
- v3.0/reference/tools/tidb-lightning/config.md
- v3.1/reference/tools/tidb-lightning/config.md
This PR adds a reference to -tidb-password command line flag for tidb-lightning in the config section.
https://github.com/pingcap/docs/pull/1711
dev, v2.1, v3.0 and v3.1
> reference/tools: add "-tidb-password" cli flag in tidb-lightning config

- v3.0/reference/best-practices/java-app.md
- The term "prepared statements" and its variations (prepare, prepared, 预处理语句 etc.) appear multiples times. I tried to employ the uniform translation, "预处理语句", in this document.
- In some of the code blocks in this document, there is no space before and after the operator "=". According to Google Java Style Guide, a single space is required on both sides of the operator. I also took a look at parts of PingCAP's source code in the tidb repository and found that operators are indeed accompanied by spaces. Therefore, I took the liberty of adding spaces to most operators in this document, except for a few code blocks with an XML identifier. 
- Other miscellaneous changes.
[Java-app.md](https://github.com/pingcap/docs-cn/blob/master/v3.0/reference/best-practices/java-app.md)
v3.0
> reference: update description and format in java app

- .github/pull_request_template.md
- dev/reference/best-practices/java-app.md
- v2.1/reference/best-practices/java-app.md
- v3.1/reference/best-practices/java-app.md
- The term "prepared statements" and its variations (prepare, prepared, 预处理语句 etc.) appear multiples times. I tried to employ the uniform translation, "预处理语句", in this document.
- In some of the code blocks in this document, there is no space before and after the operator "=". According to Google Java Style Guide, a single space is required on both sides of the operator. I also took a look at parts of PingCAP's source code in the tidb repository and found that operators are indeed accompanied by spaces. Therefore, I took the liberty of adding spaces to most operators in this document, except for a few code blocks with an XML identifier. 
- Other miscellaneous changes.
**Note:** If your changes apply to multiple TiDB versions, make sure you update the documents in the corresponding version …
> best-practice: update the description and format for Java best practice

- dev/reference/configuration/tidb-server/mysql-variables.md
- v2.1/reference/configuration/tidb-server/mysql-variables.md
- v3.0/reference/configuration/tidb-server/mysql-variables.md
- v3.1/reference/configuration/tidb-server/mysql-variables.md
> dev/2.1/3.0/3.1/4.0: add global variable latency resulted by gvc.

- dev/TOC.md
- dev/faq/tidb-lightning.md
- dev/reference/tools/tidb-lightning/config.md
- dev/reference/tools/tidb-lightning/deployment.md
- dev/reference/tools/tidb-lightning/overview.md
- dev/reference/tools/tidb-lightning/table-filter.md
- dev/reference/tools/tidb-lightning/tidb-backend.md
- v3.0/TOC.md
- v3.0/faq/tidb-lightning.md
- v3.0/reference/tools/tidb-lightning/config.md
- v3.0/reference/tools/tidb-lightning/deployment.md
- v3.0/reference/tools/tidb-lightning/overview.md
- v3.0/reference/tools/tidb-lightning/table-filter.md
- v3.0/reference/tools/tidb-lightning/tidb-backend.md
- v3.1/TOC.md
- v3.1/faq/tidb-lightning.md
- v3.1/reference/tools/tidb-lightning/config.md
- v3.1/reference/tools/tidb-lightning/deployment.md
- v3.1/reference/tools/tidb-lightning/overview.md
- v3.1/reference/tools/tidb-lightning/table-filter.md
- v3.1/reference/tools/tidb-lightning/tidb-backend.md
This PR
* adds document changes introduced in TiDB Lightning v3.0.5.
* ~updates the download links of Lightning to the latest version.~ (updated in https://github.com/pingcap/docs-cn/pull/2165)
* adds a doc for TiDB Lightning TiDB-Backend.
* updates config to include changes from https://github.com/pingcap/tidb-lightning/pull/248
* updates the required privileges in FAQ to include TiDB-backend.
https://github.com/pingcap/docs/pull/1620/
https://github.com/pingcap/docs/pull/1693/ (update glossary in https://github.com/pingcap/docs-cn/pull/2214)
dev, v3.0 and v3.1
> tidb-lightning: document backend and that system DBs are filtered

- dev/reference/sql/statements/load-data.md
`LOAD DATA` has supported using hex or binary literal to represent ascii character for `ENCLOSED BY` and `TERMINATED BY` in 4.0
This pr add example for `LOAD DATA` doc
> sql: add doc of hex and binary expression support for `LOAD DATA`

- reference/sql/attributes/auto-random.md
Refine the language of the `AUTO_RANDOM` document.
- This PR is to align with:https://github.com/pingcap/docs-cn/pull/2209 
> sql/attributes: refine the language of auto random doc

- reference/configuration/tidb-server/configuration-file.md
**
The note in master should not be the same as it is in 3.0.
> reference/configuration: fix note for stmt-count-limit

- reference/configuration/tidb-server/tidb-specific-variables.md
…b_ddl_reorg_batch_size
change `tidb_ddl_reorg_worker_cnt` default value from 16 to 4
change `tidb_ddl_reorg_batch_size` default value from 1024 to 256
- This PR is translated from: https://github.com/pingcap/docs/pull/1971
> reference: change default value for two tidb-specific variables

- reference/configuration/tikv-server/configuration-file.md
Correct spelling mistakes:unify-thread-pool -> unify-read-pool.
> reference/configuration: correct a spelling mistake

- reference/sql/statements/admin.md
remove `ADMIN REPAIR TABLE tbl_name`
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/2504, https://github.com/pingcap/docs-cn/pull/2571
> sql: remove `repair` in admin doc

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
> *: update some guiding resources

- how-to/configure/placement-rules.md
Fix typos in the Placement Rules document.
> how-to: fix typos in placement rules doc

- reference/tiflash/upgrade.md
tiflash currently does not support `tiup cluster upgrade`
> tiflash: update tiflash upgrade document

- _index.md
- faq/tidb.md
- how-to/deploy/orchestrated/ansible.md
- how-to/deploy/orchestrated/docker.md
- how-to/deploy/orchestrated/tiup.md
- how-to/get-started/deploy-tidb-from-docker-compose.md
- overview.md
> *: update recommended deployment method in multiple docs to TiUP method 

- TOC.md
- releases/3.1.0-ga.md
- releases/rn.md
> releases, toc: add 3.1.0 GA release notes

- how-to/upgrade/using-tiup.md
> tiup: add description in tiup upgrade doc

- how-to/deploy/orchestrated/tiup.md
- how-to/get-started/quick-start-with-tidb.md
fix some descriptions and typos in tiup quick start doc
- This PR is translated in: https://github.com/pingcap/docs/pull/2320
- Other reference link(s): to fix https://github.com/pingcap/docs-cn/pull/2710
> get-started: fix some descriptions and typos in tiup quick start doc

- reference/tiflash/maintain.md
add more explanation on how to clear syncing rules about tiflash in pd.
> tiflash: add more explanation on how to clear syncing rules about tiflash in pd

- how-to/deploy/orchestrated/tiup.md
- quick-start-with-tidb.md
1. Fix grammar mistakes
2. Unify format
- Other reference link(s):https://github.com/pingcap-incubator/tiup-cluster/pull/298
> TiUP: fix grammar and format for topology.example.yaml

- reference/sql/characterset-and-collation.md
refine expressions in characterset-and-collation.md
> reference: refine expressions in characterset-and-collation.md

- .github/workflows/add-docs-sig-issue.yml
- .github/workflows/add-docs-sig-pr.yml
- .github/workflows/translation-welcome.yml
**(This is not a special week PR.)**
Add three github action workflows.
> .github: add three github action workflows

- sql-statements/sql-statement-commit.md
- sql-statements/sql-statement-execute.md
- sql-statements/sql-statement-insert.md
- sql-statements/sql-statement-replace.md
- sql-statements/sql-statement-rollback.md
- sql-statements/sql-statement-set-transaction.md
- sql-statements/sql-statement-start-transaction.md
> update several statements

- TOC.md
- _index.md
Update the `_index.md` file by introducing 9 columns
> index: udpate the index file

- upgrade-tidb-using-tiup.md
It needs to execute `tiup update --self`  before executing `tiup upgrade cluster` if the version of tiup is lower than v1.0.0.
> TiUP:Add tiup upgrade notice

- execution-plan-binding.md
- sql-statements/sql-statement-show-bindings.md
- add descriptions about the parameter `source` introduced by https://github.com/pingcap/tidb/pull/17254
- fix https://github.com/pingcap/tidb/issues/16748
> add descriptions about binding source

- production-offline-deployment-using-tiup.md
- tiup/tiup-mirror.md
TiUP offline package doesn't support private http mirror now. This PR delete related documents.
> remove invalid tiup cmd

- TOC.md
- ecosystem-tool-user-case.md
- ecosystem-tool-user-guide.md
- export-or-backup-using-dumpling.md
- update the ecosystem tools user guide to make it clearer.
- replace BR with Dumpling & Lightning compare with #3497
- copy _export-or-backup-using-dumpling.md_ from master branch
- but remove the content about BR.
#3497 
#3151
> reference refine the ecosystem tools user guide

- .github/auto-label.json
- .github/workflows/auto-label.yml
> github action: add PTAL label for release-xxx PRs

- .github/auto-label.json
- .github/workflows/auto-label.yml
- Other reference link(s): revert https://github.com/pingcap/docs-cn/pull/3630
> Revert "github action: add PTAL label for release-xxx PRs"

- .github/assign-by-files.yml
- .github/workflows/auto-assign.yml
makes TomShawn the default reviewer for all prs in docs-cn repo
add github action https://github.com/marketplace/actions/auto-assign-reviewer-by-files
> add auto assign reviewer github action

- system-tables/system-table-information-schema.md
Add column description for several information_schema tables:
* COLLATIONS
* COLLATION_CHARACTER_SET_APPLICABILITY
* CHARACTER_SETS
> system_tables: add column description for several information_schema tables

- schedule-replicas-by-topology-labels.md
- three-data-centers-in-two-cities-deployment.md
> *: fix typo

- system-tables/system-table-information-schema.md
Signed-off-by: AilinKid <314806019@qq.com>
add some column explanation about `tables`, `tidb_hot_regions` and `session_variable` in information_schema.
> doc: refine tables, tidb_hot_regions and session_variable in information schema

- telemetry.md
Add a note about TiDB Operator v1.1.2 requirement 
> zh: Add operator version requirement for telemetry config

- benchmark/v3.0-performance-benchmarking-with-sysbench.md
- benchmark/v3.0-performance-benchmarking-with-tpcc.md
Add aliases for `benchmark/v3.0-performance-benchmarking-with-sysbench.md` and `benchmark/v3.0-performance-benchmarking-with-tpcc.md` deleted in `release-4.0` branch.
- This PR is translated from: https://github.com/pingcap/docs/pull/3182
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/3904
> Add aliases for 3.0 sysbench docs

- wrong-index-solution.md
Refine some anchors to make the content more readable.
> perf-tuning: update anchors in wrong-index-solution

- blacklist-control-plan.md
- troubleshoot-hot-spot-issues.md
- Optimize description issues, add multiple missing links brought by #3276 and #3253 
- Change 热点可视化 (deprecated now) to 流量可视化
**NOTE:** Changes for `blacklist-control-plan.md` also apply to v3.1 and v3.0. I'll update them in another PR.
> Optimize description and add missing links

- tiup/tiup-cluster.md
Signed-off-by: Lonng <heng@lonng.org>
> Update 'tiup cluster edit-config' documentation

- tikv-configuration-file.md
This PR cherry-picks the change made in https://github.com/pingcap/docs-cn/pull/3420. 
> Unify the calculation of defaultCF - block-cache-size

- br/backup-and-restore-faq.md
- br/backup-and-restore-tool.md
Cherry-picking #3750 
===
现今 CDC 和 Drainer 无法同步 BR 所恢复的数据，同时 BR 恢复到上游集群可能会让 CDC / Drainer 工作异常。
于是在文档中标注出来。
> [cherry-pick] br: add use constraint with CDC and drainer (#3750)

- auto-random.md
- system-variables.md
Some of the descriptions in auto-random.md are outdated. This PR correct the description.
> correct the content in auto-random.md

- statement-summary-tables.md
Statement summary tables include history tables and cluster tables, but users may take it for granted that statement summary table is `statements_summary` and history tables won't lose after TiDB rebooting.
This PR emphasize that all tables, including history tables and cluster tables, may lose after TiDB rebooting.
- N/A
> Emphasize that statement summary history tables may lose after TiDB rebooting

- check-before-deployment.md
> remove extra spaces to fix a display error

- download-ecosystem-tools.md
remove unnecessary download version(kafka specific version) for binlog. it's is confusing because current binlog version already support kafka sink.
> tools: remove unnecessary kafka version binlog

- sql-statements/sql-statement-alter-index.md
- sql-statements/sql-statement-create-index.md
This only applies to master, which features invisible indexes.
It improves the consistency of the docs for ALTER INDEX to follow the common format (including `## MySQL compatibility`). There is some duplication in the page where it has examples, and then a section for invisible indexes with examples. Since the main use case for this statement is for invisible indexes, I merged the two together. The `## syntax` section is also somewhat redundant with both the synposis and examples sections. So I've removed it.
The `CREATE INDEX` docs are also updated to remove a broken link, pointing to `ALTER INDEX` for invisible index docs. Really invisible indexes should have its own documentation page, with these pages just being for statement reference - but that's for a different task. The text also …
> sql-statements: improve alter index docs

- functions-and-operators/aggregate-group-by-functions.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/19195
> functions-and-operators: function STDDEV is supported

- tidb-configuration-file.md
- tikv-configuration-file.md
`pessimistic-txn.enable` has already been removed in both TiDB and TiKV on master branch. Update the docs.
> config: remove useless config in pessimistic-txn

- connectors-and-apis.md
- faq/tidb-faq.md
- security-compatibility-with-mysql.md
- user-account-management.md
Remove note about MySQL 8.0 auth plugin.
- This PR is translated from: https://github.com/pingcap/docs/pull/3896
> auth: Remove note about MySQL 8.0 auth plugin

- functions-and-operators/aggregate-group-by-functions.md
The description of `GROUP BY` functions are incorrectly copied from https://dev.mysql.com/doc/refman/5.7/en/aggregate-functions.html#function_var-samp.
> Fix wrong description

- multi-data-centers-in-one-city-deployment.md
Manually cherry-pick https://github.com/pingcap/docs-cn/pull/4596 to the master branch.
Update a config example in multi-data-centers-in-one-city-deployment.md
> Update a config example in multi-data-centers-in-one-city-deployment.md

- ticdc/manage-ticdc.md
add more protocol in ticdc sink config
> ticdc: add more protocol in ticdc sink config

- ticdc/manage-ticdc.md
Correct cyclic-sync-ddl usage.
> ticdc: correct cyclic-sync-ddl usage

- choose-index.md
> Fix a note display error

- sql-logical-optimization.md
- system-variables.md
To migrate https://github.com/pingcap/docs-cn/pull/4600 and https://github.com/pingcap/docs-cn/pull/4561
> Migrate contributor PRs with pending CLA

- pessimistic-transaction.md
After TiDB v4.0.6, autocommit transactions will turn to use pessimistic transaction in retries.
This PR supercedes https://github.com/pingcap/docs-cn/pull/4750
> tidb: update autocommit behavior description of pessimistic transactions

- command-line-flags-for-tidb-configuration.md
update the tidb configuration documents. Related: https://github.com/pingcap/tidb/issues/19732.
- This PR is translated from: https://github.com/pingcap/docs/pull/4056
> update the tidb configuration documents

- tikv-configuration-file.md
Remove storage.scheduler-notify-capacity config.
- This PR is translated from: https://github.com/pingcap/docs/pull/4194
- Other reference link(s): https://github.com/tikv/tikv/pull/5827
> tikv: remove storage.scheduler-notify-capacity

- auto-random.md
- backup-and-restore-using-dumpling-lightning.md
- backup-and-restore-using-mydumper-lightning.md
- basic-sql-operations.md
- blacklist-control-plan.md
- character-set-and-collation.md
Capitalize sql keywords in:
```
auto-random.md
backup-and-restore-using-dumpling-lightning.md
backup-and-restore-using-mydumper-lightning.md
basic-sql-operations.md
blacklist-control-plan.md
character-set-and-collation.md
```
- This PR is translated from: https://github.com/pingcap/docs/pull/4117
> Capitalize sql keywords in several files

- tidb-binlog/tidb-binlog-relay-log.md
> zh: refine TiDB-Binlog relay log

- sql-statements/sql-statement-create-index.md
- tidb-configuration-file.md
Reverts pingcap/docs-cn#4641
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>
- Other reference link(s):https://github.com/pingcap/tidb/pull/19998
> Revert "*: remove expression index out of experimental feature."

- pd-configuration-file.md
- pd-control.md
We have added a new configuration `region-score-formula-version` and updated the default value of `enable-cross-table-merge` for v5.0.
- Other reference link(s): https://github.com/tikv/pd/pull/3269 https://github.com/tikv/pd/pull/3129
> pd: add new configurations

- system-variables.md
- tidb-configuration-file.md
Async commit and 1PC configurations have been moved from config file to system variables.
And there are known correctness issues about 1PC, so 1PC content is hidden.
> update async commit related configurations

- releases/release-5.0.0-rc.md
tbl_name change to table_name
请进行技术评估
> Fix a typo in 5.0 RC release notes

- TOC.md
- releases/release-4.0.10.md
- releases/release-notes.md
Add tidb 4.0.10 release notes
- This PR is translated from: https://github.com/pingcap/docs/pull/4608
> release: add tidb 4.0.10 release notes

- faq/tidb-faq.md
- system-variables.md
This is the documentation for https://github.com/pingcap/tidb/pull/22351
It has version specific changes, because the default is `WARN` in 4.0.11 and `OFF` in master/5.0.
- This PR is translated from: https://github.com/pingcap/docs/pull/4741 https://github.com/pingcap/docs/pull/5011
> faq, sysvars: add tidb_multi_statement_mode

- system-variables.md
remove system variable `tidb_track_aggregate_memory_usage`
- Other reference link(s): https://github.com/pingcap/tidb/pull/23184
> remove system variable `tidb_track_aggregate_memory_usage`

- explain-joins.md
- explain-overview.md
- explain-subqueries.md
- optimizer-hints.md
- sql-statements/sql-statement-kill.md
- tidb-configuration-file.md
The feature is not an experimental feature, thus we need to hide the config description.
- Other reference link(s): https://github.com/pingcap/tidb/pull/23395
> hide the config global-kill

- tidb-binlog/tidb-binlog-overview.md
Increase the restriction of using binlog in version 5.0
- Other reference link(s): 
- Async Commit: https://github.com/pingcap/docs-cn/pull/5607/files
- Clustered Index: https://github.com/pingcap/docs-cn/pull/5771/files
> add binlog usage restrictions

- br/backup-and-restore-tool.md
- clustered-indexes.md
- system-variables.md
- tidb-configuration-file.md
- This PR is translated from: NA
- Other reference link(s): #5771 #5774
> update the description related to clustered indexes

- clustered-indexes.md
Fix some wrong statements in clustered-indexes.md
- This PR is translated from: NA
- Other reference link(s): pingcap/docs-cn#5771, pingcap/docs-cn#5834
> fix some wrong statements in clustered-indexes.md

- command-line-flags-for-tidb-configuration.md
- sql-statements/sql-statement-restore.md
In 'dev' and 'v5.0' version, the default value of `--store` TiDB command-line argument has been changed to 'unistore'.
- This PR is translated from: NA
- Other reference link(s): https://github.com/pingcap/tidb/pull/17674
> update the local storage description from 'mocktikv' to 'unistore'

- tidb-configuration-file.md
Changed default value of `tikv-client.grpc-connection-count` from 16 to 4. This default value is actually changed before releasing 4.0, and is included in all 4.x versions, without updating the document.
> tidb: Fix default value of grpc-connection-count

- tikv-configuration-file.md
- tune-tikv-performance.md
Update the default value of `grpc-raft-conn-num` from `10` to `1`.
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/5669/files#r603843190
> Update the default value of grpc-raft-conn-num

- get-started-with-tidb-lightning.md
- tidb-lightning/deploy-tidb-lightning.md
- tiflash/use-tiflash.md
- The TiDB download page link is different between v3.0 and v5.0
> lightning: update lightning example binary version and download link

- tidb-lightning/tidb-lightning-backends.md
Clarify Local-backend in tidb-lightning-backends.md 
- This PR is translated from: https://github.com/pingcap/docs/pull/5278
> Clarify Local-backend in tidb-lightning-backends.md

- tiflash/tune-tiflash-performance.md
> add some tiflash tune instructions

- tidb-binlog/tidb-binlog-configuration-file.md
- tidb-scheduling.md
- tiup/tiup-faq.md
update the GitHub external links that do not point to master.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/6056 https://github.com/pingcap/docs-cn/pull/6054
> update the external links

- ticdc/troubleshoot-ticdc.md
TiCDC provides two parameters to control the message size and batch size of Kafka messages.
> ticdc: fix kafka message size limit

- pd-control.md
- tidb-binlog/binlog-control.md
- tidb-control.md
- tikv-control.md
> ctl: add a note for all ctl docs

- error-codes.md
- sql-statements/sql-statement-admin.md
- tidb-computing.md
Remove all F1 related content from docs-cn in v4.0 and v5.0. For other versions, @bb7133 will create a separate PR.
- This PR is translated from: https://github.com/pingcap/docs/pull/5352 https://github.com/pingcap/docs/pull/5346 https://github.com/pingcap/docs/pull/5423
> remove all F1 related contents

- benchmark/benchmark-sysbench-v5-vs-v4.md
remove the config from v5.0, otherwise the TiKV can not startup
> server.request-batch-enable-cross-command is obsolete in v5

- tikv-configuration-file.md
ttl-poll-check-interval -> ttl-check-poll-interval
`
mysql> show config;    
| tikv | 10.186.1.1:20160 | storage.ttl-check-poll-interval                                      | 12h
`
> correct a tikv config name

- TOC.md
- releases/release-5.0.1.md
- releases/release-notes.md
Add tidb 5.0.1 release notes
- This PR is translated from: https://github.com/pingcap/docs/pull/5392
> releases: add tidb 5.0.1 release notes

- dumpling-overview.md
- table-filter.md
close https://github.com/pingcap/dumpling/issues/268
Update dumpling's description about behaviors about table-filter.
> dumpling: update table-filter doc

- br/use-br-command-line-tool.md
add a description about br's s3 permission.
- Other reference link(s):https://github.com/pingcap/docs-cn/issues/6015
> br: add s3 permission description

- comment-syntax.md
With the 8.0.23 MySQL client TiDB specific comments are cleared out, so
even with the latest client you still need to add --comments.
- This PR is translated from: https://github.com/pingcap/docs/pull/5421
> comment-syntax: Correct the note about --comments

- pd-control.md
The usage of `tiup ctl` with version in pd-ctl is wrong. Fix it.
> fix tiup ctl with cluster version

- best-practices/tidb-best-practices.md
- error-codes.md
- faq/migration-tidb-faq.md
- storage-engine/titan-overview.md
- tidb-limitations.md
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>
TiDB introduced `txn-entry-size-limit` in v5.0 and added it to the doc https://github.com/pingcap/docs-cn/pull/5158, but there are some outdated descriptions left.
> update TiDB 6MB limit

- statistics.md
- tidb-configuration-file.md
The feature`feedback-probability` has been disabled by default since v4.0.9 because its behavior is unstable (see https://github.com/pingcap/tidb/pull/21923). So I update the default value of it to `0` and modify some descriptions.
After this PR is cherry-picked to the release-4.0 branch, I will add the information that the feature`feedback-probability` is disabled from the patch version v4.0.9.
> config: update the default value of `feedback-probability`

- sql-statements/sql-statement-add-index.md
Remove the legacy unsupported info for VISIBLE/INVISIBLE index because INVISIBLE index is supported starting from TiDB 5.0.
> Remove the legacy unsupported info for VISIBLE/INVISIBLE index

- sql-mode.md
Update the support 'PAD_CHAR_TO_FULL_LENGTH', remove the 'full support' description due to pingcap/tidb#14007.
- This PR is translated from: https://github.com/pingcap/docs/pull/5646
> sql-mode: remove 'full support' for 'PAD_CHAR_TO_FULL_LENGTH' 

- overview.md
Add a few doc links in `overview.md` for better doc findability.
> overview: add a few doc links

- hardware-and-software-requirements.md
RHEL/OEL/CentOS 8 is not supported yet
#5283 (comment)
Start with removing Ubuntu 16.04
#4943
Mention CentOS 8 Linux and CentOS 8 Stream
#4943 (comment)
Mention that Fedora, Debian, etc is likely to work but not supported.
- This PR is translated from: https://github.com/pingcap/docs/pull/5587
> hardware-and-software-requirements: Update supported platforms

- tidb-lightning/tidb-lightning-overview.md
TiFlash does not support Lightning currently. We must explicitly notify the issue.
- This PR is translated from: https://github.com/pingcap/docs/pull/5119
> Highlight TiFlash does not support Lightning

- ticdc/troubleshoot-ticdc.md
ref: https://github.com/pingcap/ticdc/pull/1835
Add more instructions about how to find `start-ts` when cdc log doesn't contain it.
> ticdc: update troubleshoot for ddl skip

- pd-control.md
Fix description about hot-region-cache-hits-threshold
> Fix description about hot-region-cache-hits-threshold

- ticdc/deploy-ticdc.md
- ticdc/manage-ticdc.md
> ticdc: add more docs about unified sorter

- ticdc/troubleshoot-ticdc.md
Add explicit_defaults_for_timestamp compatibility troubleshoot in TiCDC. ref: https://github.com/pingcap/ticdc/pull/1638
> [v5.0.1/v4.0.13] ticdc: add explicit_defaults_for_timestamp compatibility troubleshoot

- TOC.md
- releases/release-5.0.2.md
- releases/release-notes.md
add tidb 5.0.2 release notes
- docs PR: https://github.com/pingcap/docs/pull/5739 
> releases: add tidb 5.0.2 release notes

- tiflash/use-tiflash.md
> Update tiflash supported pushdown expression list

- sql-statements/sql-statement-backup.md
- sql-statements/sql-statement-restore.md
TIDB v5.1 supports fine grained privileges (aka Dynamic privileges), so it's recommended to use these over `SUPER`. This adds the fine grained privileges for `BACKUP` and `RESTORE` commands.
- This PR is translated from: https://github.com/pingcap/docs/pull/5771
> update permissions required for BACKUP and RESTORE

- sql-statements/sql-statement-show-table-regions.md
Correct the region IDs in the show table example 
- Other reference link(s): https://asktug.com/t/topic/93796
> Correct the region IDs in the show table example 

- download-ecosystem-tools.md
- pd-control.md
- pd-recover.md
- production-deployment-using-tiup.md
- quick-start-with-tidb.md
- scale-tidb-using-tiup.md
- ticdc/manage-ticdc.md
- tiup/tiup-bench.md
- tiup/tiup-command-mirror-rotate.md
- tiup/tiup-component-cluster-deploy.md
- tiup/tiup-component-management.md
- tiup/tiup-mirror.md
- tiup/tiup-playground.md
> Bump version for v5.1.0

- as-of-timestamp.md
Signed-off-by: linning <linningde25@gmail.com>
> Fix stale read note

- system-variables.md
The system variables are not in alphabetical order. This is useful for users when a list is long because it makes it easier to search for them.
- This PR is translated from: https://github.com/pingcap/docs/pull/5711
> system-variables: ensure alphabetical order

- tikv-configuration-file.md
Signed-off-by: Yi Wu <yiwu@pingcap.com>
TiKV max-peer-down-duration default value had changed after https://github.com/tikv/tikv/pull/10459. Update docs.
>  TiKV configuration: update max-peer-down-duration default value

- system-variables.md
This adds 2 missing system variables that function correctly in TiDB: datadir and license.
The language is intentionally a little vague and says "typically" because in mocktikv/unistore cases it will show a path, but that is for developers to know. I don't believe we ever change the license string for enterprise edition but the language doesn't preclude that.
- This PR is translated from: https://github.com/pingcap/docs/pull/5761
> system-variables: add datadir and license

- system-variables.md
This updates the system variables, generated against the tidb source code. i.e. this PR is derived from #5720 , but the generator source code will be submitted separately.
This allows this PR to potentially be cherry picked and handled like a regular contribution.
- This PR is translated from: https://github.com/pingcap/docs/pull/5752
> system-variables: update from generated source

- .zhmdyaml
- ticdc/manage-ticdc.md
- ticdc/monitor-ticdc.md
- ticdc/ticdc-overview.md
- ticdc/troubleshoot-ticdc.md
```
/Users/wph95/hackathon/2021/base_docs/docs-cn/ticdc/deploy-ticdc.md: no issues found
/Users/wph95/hackathon/2021/base_docs/docs-cn/ticdc/integrate-confluent-using-ticdc.md: no issues found
/Users/wph95/hackathon/2021/base_docs/docs-cn/ticdc/manage-ticdc.md
239:132  warning  shouldn't spaces between Chinese characters  ZH425
767:13  warning  shouldn't spaces between Chinese characters  ZH425
⚠ 2 warnings
/Users/wph95/hackathon/2021/base_docs/docs-cn/ticdc/monitor-ticdc.md: no issues found
/Users/wph95/hackathon/2021/base_docs/docs-cn/ticdc/ticdc-glossary.md: no issues found
/Users/wph95/hackathon/2021/base_docs/docs-cn/ticdc/ticdc-open-protocol.md: no issues found
/Users/wph95/hackathon/2021/base_docs/docs-cn/ticdc/ticdc-overview.md
84:87  warning  shouldn't spaces between Chinese …
```
> zh.md bot checking /tidcd, fix typo error

- sql-statements/sql-statement-create-index.md
Update the related variable description for CREATE INDEX because the scope of tidb_ddl_reorg_priority is SESSION instead of GLOBAL.
- Other reference link(s): https://asktug.com/t/topic/94169
> Update the related variable description for CREATE INDEX

- check-before-deployment.md
> Remove the swappiness parameter

- functions-and-operators/aggregate-group-by-functions.md
- functions-and-operators/expressions-pushed-down.md
- functions-and-operators/json-functions.md
Batch fix broken external links
> Batch fix broken external links

- tidb-lightning/tidb-lightning-faq.md
> Add steps to get lightning goroutine

- config-templates/complex-tidb-binlog.yaml
Add kafka downstream example for convenience, and change the dirs of pumps to a better path that correspond to its default port.
> Add kafka downstream example

- tidb-binlog/deploy-tidb-binlog.md
- tidb-binlog/tidb-binlog-configuration-file.md
Part solve https://github.com/pingcap/tidb-binlog/issues/1045
- Other reference link(s): https://github.com/pingcap/tidb-binlog/issues/1045
> binlog: update documents for committs and passoword

- check-before-deployment.md
On CentOS 8 Chrony is used by default for NTP services.
- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-chrony-to-configure-ntp#sect-checking_if_chrony_is_synchronized
- This PR is translated from: https://github.com/pingcap/docs/pull/5283
> check-before-deployment: add info about chronyd/chronyc on CentOS 8

- ticdc/manage-ticdc.md
Add documentation on how to modify gcttl by tiup.
[#1825](https://github.com/pingcap/ticdc/issues/1825)
> Add documentation on how to modify gcttl by tiup

- functions-and-operators/tidb-functions.md
Extend documentation for `TIDB_DECODE_KEY`.
- This PR is translated from: https://github.com/pingcap/docs/pull/5877
> tidb-functions: extend tidb_decode_key docs

- configure-memory-usage.md
Fix a typo in configure-memory-usage.md
> Fix a typo in configure-memory-usage.md

- tikv-configuration-file.md
The description for "pin" l0 index and filter block needs to be more descriptive.
> TiKV configuration: better description for pin-l0-filter-and-index-blocks

- ticdc/troubleshoot-ticdc.md
Add mysql sink privilege in TiCDC FAQ
> ticdc: add mysql sink user privilege

- benchmark/v5.1-performance-benchmarking-with-tpch.md
This variable is deprecated and useless when mpp is enabled, but may confuse users, so I remove it.
> remove useless variable.

- best-practices/java-app-best-practices.md
> best-practices: add timeout options for Java best practices

- system-variables.md
updated for consistency in the system-variables document
- This PR is translated from: https://github.com/pingcap/docs/pull/5826
> system-variables: update for consistency

- tidb-monitoring-api.md
issue: https://github.com/pingcap/tidb/issues/4989
pull request: https://github.com/pingcap/tidb/pull/22859
> *: add table storage info status api

- statement-summary-tables.md
fix a typo in statement summary of Chinese docs.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/6695
> statement summary: fix typo in statement-summary

- ticdc/manage-ticdc.md
- ticdc/troubleshoot-ticdc.md
* ticdc: aggregate interruption FAQs
* update oom faq 
* ticdc: add partition table faq, close https://github.com/pingcap/ticdc/issues/2404
> ticdc: update interruption FAQs

- sql-statements/sql-statement-select.md
added a line for 'FOR-UPDATE-NOWAIT'
- This PR is translated from: [#6085](https://github.com/pingcap/docs/pull/6085)
> sql statement select: add 'FOR-UPDATE-NOWAIT'

- tikv-configuration-file.md
integrated rockdb.writecf and rockdb.lockcf in one part with defaultcf
- This PR is translated from: [#5746](https://github.com/pingcap/docs/pull/5746), [#5936](https://github.com/pingcap/docs/pull/5936).
> TiKV configuration: integrate writecf and lockcf to one part with defaultcf

- tikv-control.md
Signed-off-by: Xintao <hunterlxt@live.com>
- This PR is translated from: https://github.com/pingcap/docs/pull/6109
- Other reference link(s): https://github.com/tikv/tikv/pull/10259
> Add print the bad sst files and related information for tikv-ctl

- tidb-lightning/tidb-lightning-backends.md
- tidb-lightning/tidb-lightning-configuration.md
Remove default backend setting from the configuration and move local backend to the first. 
> lightning: remove default backend setting from the configuration

- pd-control.md
Signed-off-by: HunDunDM <hundundm@gmail.com>
pd-control: add new config of balance-hot-region-scheduler
Related features are GA at v5.2.0.
- Features: [PD#3869](https://github.com/tikv/pd/issues/3869) [PD#3900](https://github.com/tikv/pd/pull/3900)
> pd-control: add new config of balance-hot-region-scheduler

- system-variables.md
- tiflash/use-tiflash.md
> update bcj threshold

- config-templates/geo-redundancy-deployment.yaml
- configure-memory-usage.md
- geo-distributed-deployment-topology.md
- multi-data-centers-in-one-city-deployment.md
- three-data-centers-in-two-cities-deployment.md
Signed-off-by: nolouch <nolouch@gmail.com>
> docs: update rereject leader docs

- tikv-configuration-file.md
Because the reserve-space config-param feature will not enter the v5.2 feature list, this PR reverts https://github.com/pingcap/docs-cn/pull/6845
> Revert "TiKV update reserve-space config-param"

- dashboard/dashboard-statement-list.md
Add a note to explain the blue bar and yellow line based on https://asktug.com/t/topic/123094
> dashboard-statement-list.md：add a note to explain the blue bar and yellow line 

- releases/release-5.1.0.md
Updated the compatibility changes based on the feedback from https://asktug.com/t/topic/122897/2
> release-5.1.0.md: add compatibility change for tidb_enable_noop_functions

- alert-rules.md
This logic was removed in version 3.0.19 and does not exist in subsequent versions, please release the time through v3.0.19
> Remove some desc

- quick-start-with-tidb.md
> update version and tiup playground supports M1 silicon

- tikv-configuration-file.md
Fix wrong description in TiKV configuration file.
The description of `compaction-readahead-size` referred to https://docs.pingcap.com/zh/tidb/stable/tune-tikv-memory-performance#%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E.
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/7038
> tikv-config: Fix wrong description

- command-line-flags-for-tidb-configuration.md
Remove two deprecated flags.
Now tidb-server has following flags:
```
Usage of ./tidb-server:
-L string
log level: info, debug, warn, error, fatal (default "info")
-P string
tidb server port (default "4000")
-V    print version information and exit (default false)
-advertise-address string
tidb server advertise IP
-affinity-cpus string
affinity cpu (cpu-no. separated by comma, e.g. 1,2,3)
-config string
config file path
-config-check
check config file validity and exit (default false)
-config-strict
enforce config file validity (default false)
-cors string
tidb server allow cors origin
-enable-binlog
enable generate binlog (default false)
-help
show the usage
-host string
tidb server host (default "0.0.0.0")
-lease string
schema lease duration, very dangerous to change only if you know …
```
> Remove two deprecated flags

- sql-statements/sql-statement-kill.md
updated the description about `KILL` in "sql-statements/sql-statement-kill.md" document.
- This PR is translated from: https://github.com/pingcap/docs/pull/6233
> `kill`: improve kill's description

- system-variables.md
Update doc for `tidb_opt_prefer_range_scan`.
- Other reference link(s): [tidb/pull/27123](https://github.com/pingcap/tidb/pull/27123)
> sysvar: update doc for tidb_opt_prefer_range_scan

- partitioned-table.md
- This PR is translated from: https://github.com/pingcap/docs/pull/5498
> partitioning: Corrected partition management

- TOC.md
- information-schema/information-schema-referential-constraints.md
- information-schema/information-schema.md
added a document `referential_constraints` under "information-schema"
- This PR is translated from: https://github.com/pingcap/docs/pull/6139
> add `referential_constraints` under "information-schema"

- system-variables.md
revised a part (`1` to `ON`) for `tidb_opt_prefer_range_scan` for consistency.
- The translation of this part has already been revised in the [#6389](https://github.com/pingcap/docs/pull/6389), so no new PR for translation is needed.
> system variables: revise description about `tidb_opt_prefer_range_scan`

- .github/workflows/dispatch.yml
Trigger website build when pr merged.
- This PR is translated from: https://github.com/pingcap/docs/pull/6404
> chore: add dispatch back

- br/use-br-command-line-tool.md
In all backup and recovery commands, add ratelimit
> br: add ratelimit in br commands

- tikv-configuration-file.md
The enable-compaction-filter in tikv-configuration-file.md is default false now , but actually it is default true.
I have used 'tiup playground' to test v5.0.0,v5.0.1,v5.0.2,v5.0.3,v5.1.0,v5.1.1 ,  and enable-compaction-filter is default true in all versions.
- Other reference link(s): from jira …
> fix-enable-compaction-filter-in-tikv-configuration-file

- tune-tikv-thread-performance.md
Changed the default value of `server.grpc-concurrency` from 4 to 5 in "tune-tikv-thread-performance.md" according to "tikv-configuration-file.md".
- Other reference link(s): [#7088](https://github.com/pingcap/docs-cn/issues/7088)
> Tune TiKV: change the default value of `grpc-concurrency`

- TOC.md
- releases/release-4.0.15.md
- releases/release-notes.md
releases: add tidb 4.0.15 release notes
- This PR is translated from: https://github.com/pingcap/docs/pull/6475
> releases: add tidb 4.0.15 release notes

- TOC.md
- releases/release-5.0.4.md
- releases/release-notes.md
releases: add tidb 5.0.4 release notes
- This PR is translated from: https://github.com/pingcap/docs/pull/6449
> releases: add tidb 5.0.4 release notes

- tiflash/monitor-tiflash.md
- This PR is translated from: https://github.com/pingcap/docs/pull/6524
> Add desc of "Storage Write Stall" row in the TiFlash grafana

- security-compatibility-with-mysql.md
- This PR is translated from: https://github.com/pingcap/docs/pull/6650
> Add auth_socket support

- configure-placement-rules.md
I have updated version info about default enabled Placement Rules in "configure-placement-rules.md" because this feature is enabled by default since TiDB v 5.0.
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/7239
> Update version info about default enabled Placement Rules

- sql-statements/sql-statement-create-sequence.md
Signed-off-by: ailinkid <314806019@qq.com>
- **Attention**
> There are nothing change about the code (since this `order` keyword hasn't existed since the very beginning), which means this pr is just a doc revisement.
> sequence: remove the `order` keyword of sequence

- dynamic-config.md
- tikv-configuration-file.md
Removed stale configuration `raftstore.raft-reject-transfer-leader-duration` in "dynamic-config.md“ and "tikv-configuration-file.md".
- This PR is translated from: https://github.com/pingcap/docs/pull/6836
> remove stale configuration `raftstore.raft-reject-transfer-leader-duration`

- check-before-deployment.md
Optimize the description of disabling swap
> Optimize the description of disabling swap

- sql-plan-replayer.md
> update plan replayer doc

- releases/release-5.3.0.md
Added links for the newly added configuration items `raftstore.store-io-pool-size`, `raftstore.raft-write-size-limit`, `raftstore.raft-msg-flush-interval` in "releases/release-5.3.0.md".
> add links for some config items to release notes 5.3.0

- experimental-features.md
- sql-prepare-plan-cache.md
The SQL prepare execution plan cache feature is experimental for v4.0, v5.0, v5.1, and v5.2. This PR adds the experimental feature warning for this feature.
> SQL prepare execution plan cache: add the experimental feature warning

- tidb-binlog/deploy-tidb-binlog.md
- tidb-binlog/tidb-binlog-configuration-file.md
update kafka-max-message-size configuration
- Other reference link(s): https://github.com/pingcap/tidb-binlog/pull/1039
> tidb-binlog: update kafka-max-message-size configuration

- sync-diff-inspector/shard-diff.md
Fix a typo in sync diff.
close https://github.com/pingcap/docs-cn/issues/7906
None
> Fix a typo in sync diff

- ticdc/manage-ticdc.md
- ticdc/ticdc-open-api.md
- ticdc/troubleshoot-ticdc.md
* Use open-protocol instead of default protocol.
* Fix some wrong default values.(compressionType/max-batch-size)
* Fix some typos
> ticdc: Use open-protocol instead of default protocol and add missing params

- dm/task-configuration-file-full.md
Add DM `collation_compatible ` config description.
- Other reference link(s): https://github.com/pingcap/tiflow/pull/4121
> Update the description about DM collation_compatible config

- dm/deploy-a-dm-cluster-using-tiup-offline.md
- dm/deploy-a-dm-cluster-using-tiup.md
- dm/dm-precheck.md
- dm/dmctl-introduction.md
- dm/maintain-dm-using-tiup.md
Merged dm: update version description
- This PR is translated from: https://github.com/pingcap/docs/pull/7464
> dm: update version description

- statement-summary-tables.md
- system-variables.md
Some system variables are changed to global only after 5.4. 
- Other reference link(s): https://github.com/pingcap/tidb/pull/30756
> `tidb_capture_plan_baselines` and statement summary related variables are global only

- pd-control.md
Signed-off-by: IcePigZDB <icepigzdb@gmail.com>
Support endKey in http interface `regions/key` and adjust the pdctl region command `region startKey` to `region keys`accordingly. This is originally proposed as a precondition of the push down optimisation of `infomation_schema.tikv_region_status`.
- This PR is translated from: pingcap/docs/pull/6951
- Other …
> tools: update the usage of region startkey to region keys

- clinic/clinic-data-instruction-for-tiup.md
> Update headings of "clinic data instruction"

- best-practices/pd-scheduling-best-practices.md
Signed-off-by: JmPotato <ghzpotato@gmail.com>
`disable-replace-offline-replica` and `disable-location-replacement` had been changed to `enable-replace-offline-replica` and `enable-location-replacement` since v3.1.0.
> pd-ctl: update the deprecated scheduler config names

- releases/release-3.0.3.md
- tidb-lightning/tidb-lightning-backends.md
- tidb-lightning/tidb-lightning-requirements.md
> Add Lightning memory usage in different backends

- tidb-lightning/tidb-lightning-distributed-import.md
- tidb-lightning/tidb-lightning-overview.md
- This PR is translated from: https://github.com/pingcap/docs/pull/7503, https://github.com/pingcap/docs/pull/7514
> Update tidb-lightning-overview and tidb-lightning-distributed-import

- pd-control.md
- tidb-scheduling.md
Signed-off-by: JmPotato <ghzpotato@gmail.com>
Refine the TiKV store status description.
- Other reference link(s): https://github.com/pingcap/docs/pull/6949
> docs: update the TiKV store status description

- sql-prepare-plan-cache.md
- system-variables.md
> planner: update documents related to Plan Cache

- functions-and-operators/expressions-pushed-down.md
- system-variables.md
> revise expressions pushed down

- system-variables.md
- transaction-isolation-levels.md
> txn: update the document about read-consistency read check ts variable

- functions-and-operators/expressions-pushed-down.md
- system-variables.md
- update descriptions of expressions supported to be pushed down in "functions-and-operators/expressions-pushed-down.md".
- revise the order of `tidb_sysdate_is_now` in "system-variables.md".
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/8684
> update descriptions of expressions supported to be pushed down

- placement-rules-in-sql.md
fix typo.
modify alter database grammer 
> Fix typos in placement-rules-in-sql.md

- certificate-authentication.md
According to the community feedback OPENSSL X509 command description error, this PR to improve the OPENSSL X509 command line parameters
- Other reference link(s): https://asktug.com/t/topic/573396
> Modify OpenSSL x509 command line parameters

- tidb-binlog/binlog-consumer-client.md
- tidb-binlog/tidb-binlog-overview.md
Fix broken links
- This PR is translated from: https://github.com/pingcap/docs/pull/6837
> Fix broken links

- dm/shard-merge-best-practices.md
- migrate-from-sql-files-to-tidb.md
Fix two broken links found in https://github.com/pingcap/docs-cn/issues/8928
> fix 2 broken links in dm docs

- migrate-aurora-to-tidb.md
- tidb-lightning/migrate-from-csv-using-tidb-lightning.md
- tidb-lightning/tidb-lightning-configuration.md
- tidb-lightning/tidb-lightning-faq.md
Remove all the `no-schema` config of Lightning  due to it can  automatically detect now.
> remove no-schema config

- get-started-with-tidb-lightning.md
- sync-diff-inspector/sync-diff-inspector-overview.md
- tidb-binlog/deploy-tidb-binlog.md
- tidb-binlog/get-started-with-tidb-binlog.md
- tidb-binlog/tidb-binlog-reparo.md
- tidb-lightning/deploy-tidb-lightning.md
Remove `/bin` from some toolkit commands: `dm-master`, `dm-worker`, `dmctl`, `dumpling`, `sync_diff_inspector`, `binlogctl`, `pump`, `drainer`.
> Remove `/bin` from toolkit commands

- faq/tidb-faq.md
> Update a TiDB FAQ about supported storage engine

- tiflash/tiflash-configuration.md
- Changed `format_version` default value to 4.
> Changed format_version default value to 4

- tiflash/use-tiflash.md
This PR is to fix https://github.com/pingcap/docs-cn/issues/9574
> TiFlash: Fix incorrect values of isolation_read_engines

- functions-and-operators/tidb-functions.md
Signed-off-by: TonsnakeLin <lpbgytong@163.com>
https://github.com/pingcap/tidb/pull/30659
> tidb-functions: update tidb-functions.md doc

- dm/feature-shard-merge-optimistic.md
- Other reference link(s): https://github.com/pingcap/tiflow/pull/5198
> DM: update optimistic shard ddl

- pd-control.md
> Add store cancel-delete command in pd-ctl

- character-set-gbk.md
> Add support for GBK charset in TiCDC

- check-before-deployment.md
Close https://github.com/pingcap/docs-cn/issues/9431
- Add deploy `tidb-test` step before `tiup cluster exec tidb-test`.
- Fix format.
> Add deploy `tidb-test` step before `tiup cluster exec tidb-test`

- TOC.md
- ticdc/ticdc-avro-protocol.md
ref https://github.com/pingcap/tiflow/issues/5338
> add ticdc-avro-protocol.md

- TOC.md
- develop/dev-guide-troubleshoot-overview.md
> [Update] TOC add dev-guide-index-best-practice.md

- dynamic-config.md
- system-variables.md
> dynamic config: add version info

- sql-statements/sql-statement-explain.md
According to some feedback, the example on the EXPLAIN page using a `desc` statement is a bit strange (though they are equivalent). So let's fix it.
> sql-statements: change an example in EXPLAIN page from `desc` to `explain`

- functions-and-operators/aggregate-group-by-functions.md
- functions-and-operators/window-functions.md
- Other reference link(s): close #7530
> refine window functions and aggregate functions description

- mysql-compatibility.md
- sql-statements/sql-statement-explain.md
sql-statements: update claims on optimizer/explain compatibility
- This PR is translated from: https://github.com/pingcap/docs/pull/6695
> sql-statements: update claims on optimizer/explain compatibility

- dm/dm-precheck.md
> dm: support ignore online-ddl in precheck

- dynamic-config.md
- tikv-configuration-file.md
> tikv: add a new config `server.simplify-metrics`

- dynamic-config.md
> tikv: add a new dynamic config

- tiflash/tiflash-configuration.md
According to https://github.com/pingcap/tiflash/issues/5576, if user deploys tiflash with explicit setting `profiles.default.dt_enable_logical_split = 1`.
After several logical split, PageStorage V3 will throw an exception for the third time logical split and make TiFlash crash.
Here we declare the config item to be deprecated
For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md# …
> Not recommend setting tiflash logical split since 6.2

- functions-and-operators/miscellaneous-functions.md
Remove locking function from the list of unsupported functions.
> Remove locking function from the list of unsupported functions

- tiup/tiup-bench.md
Close https://github.com/pingcap/docs-cn/issues/10803
- Modify the flag from `--output` to `--output-dir`. The `--output` flag has been modified to `--output-dir` in this [tiup/211](https://github.com/pingcap/tiup/pull/211) PR, but the flag in the `tiup/tiup-bench.md` document is not updated. Since this change is before TiDB v4.0, this PR needs to cherry pick from v4.0 to v6.2. (issue: https://github.com/pingcap/docs-cn/issues/10803)
- Add the `--output-type=csv` in each command to generate CSV file (suggestions from JaySon-Huang)
- Remove the enable pprof step (suggestions from JaySon-Huang)
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature …
> tiup bench: modify command from --output to --output-dir

- system-variables.md
add doc for tidb_last_query_info and tidb_shard_allocate_step
- This PR is translated from: https://github.com/pingcap/docs/pull/9770
> add doc for tidb_last_query_info and tidb_shard_allocate_step

- TOC.md
- clinic/clinic-collect-sql-query-plan.md
Support collection of SQL query plan related information in Clinic v0.8.0
> clinic v0.8.0: Support collection of SQL query plan related information

- br/backup-and-restore-design.md
> br: refine sst file naming format

- dm/dm-safe-mode.md
- dm/task-configuration-file-full.md
- Other reference link(s): https://github.com/pingcap/tiflow/pull/6225
> dm: add a configuration to adjust safe mode duration when dm task abnormal reboot

- optimizer-hints.md
> doc: update the doc for hash_join_build and hash_join_probe hints

- config-templates/complex-cdc.yaml
- tiup/tiup-cluster-topology-reference.md
Doc change for https://internal.pingcap.net/jira/browse/FD-991 
> doc changes for tiup deploy multiple ticdc

- develop/dev-guide-delete-data.md
- system-variables.md
- Other reference link(s): pingcap/tidb#36514
> docs:Add tidb_opt_force_inline_cte system vars usage description in docs.

- develop/dev-guide-choose-driver-or-orm.md
- This PR is translated from:https://github.com/pingcap/docs/pull/10565
> develop: update description of jdbc

- statistics.md
> add some point desc

- system-variables.md
> update some system variable

- faq/high-availability-faq.md
- faq/high-reliability-faq.md
- faq/sql-faq.md
- tidb-troubleshooting-map.md
faq: refine the writing style of 3 faqs
> faq: refine the writing style of 3 faqs

- system-variables.md
> update system variable

- functions-and-operators/aggregate-group-by-functions.md
- functions-and-operators/date-and-time-functions.md
- functions-and-operators/encryption-and-compression-functions.md
- system-variables.md
sysvar: add 13 sysvars to docs-cn
- This PR is translated from: https://github.com/pingcap/docs/pull/6492 https://github.com/pingcap/docs/pull/6485 https://github.com/pingcap/docs/pull/10525
> sysvar: add 12 sysvars to docs-cn

- configure-load-base-split.md
Signed-off-by: JmPotato <ghzpotato@gmail.com>
Add an example for the adjustment of `byte-threshold` and `region-cpu-overload-threshold-ratio` of the Load Base Split.
> Add an example for byte-threshold and region-cpu-overload-threshold-ratio adjustment

- clustered-indexes.md
- releases/release-6.3.0.md
- system-variables.md
> Change default value of tidb_enable_clustered_index back to INT_ONLY

- TOC.md
- releases/release-6.1.2.md
- releases/release-notes.md
- releases/release-timeline.md
> add v6.1.2 release notes

- dm/task-configuration-file-full.md
- migrate-aurora-to-tidb.md
- migrate-large-mysql-shards-to-tidb.md
- migrate-large-mysql-to-tidb.md
- Other reference link(s): https://github.com/pingcap/tiflow/pull/7394
> dm: add description about mysql-instance.meta

- character-set-and-collation.md
- constraints.md
- log-redaction.md
- system-variables.md
- transaction-overview.md
Signed-off-by: ekexium <eke@fastmail.com>
The PR complenets the changes happened in recent TiDB master: 
- The message of error 1062 has changed. 
- ~~PessimisticLockError can occur when users use the lazy uniqueness check feature inappropriately.~~
> complement errors relating to lazy uniqueness check

- TOC.md
- sql-statements/sql-statement-flashback-database.md
feature link https://github.com/pingcap/tidb/pull/30217
ref https://docs.pingcap.com/zh/tidb/stable/sql-statement-flashback-table
> sql: add doc for `flashback database`

- br/backup-and-restore-storages.md
- dm/quick-start-create-task.md
- pd-control.md
- quick-start-with-tidb.md
- ticdc/manage-ticdc.md
- tidb-binlog/get-started-with-tidb-binlog.md
> v6.4: bump version for tools

- tiflash/create-tiflash-replicas.md
Signed-off-by: Wish <breezewish@outlook.com>
Add example about how to fill the <cluster_version>
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/11653
> Add example about how to fill the <cluster_version>

- tikv-control.md
Signed-off-by: husharp <jinhao.hu@pingcap.com>
- Other reference link(s): ref https://github.com/tikv/tikv/issues/13760 & Pr is merged https://github.com/tikv/tikv/pull/13768
> tikv-control.md: update tikv-control.md for raft region

- .github/pull_request_template.md
v6.6: add v6.6 checkbox in pr template
> chore: add v6.6 checkbox in pr template

- br/br-batch-create-table.md
> br: incorrect description of batch create table

- tiflash/tune-tiflash-performance.md
Signed-off-by: yibin <huyibin@pingcap.com>
> Add tiflash execution tuning materials

- develop/dev-guide-paginate-results.md
Change the paging SQL example with multiple columns for the cluster index table.
The old example will make a bad full table scan, the new one can use indexes.
- This PR is translated from: https://github.com/pingcap/docs/pull/10478
> develop: fix paging sql with multiple columns for cluster index table

- faq/migration-tidb-faq.md
- faq/sql-faq.md
Fix typos (具体看参考) in `faq/migration-tidb-faq.md` and `faq/sql-faq.md`
> fix typos in FAQ

- br-usage-backup-for-maintain.md
- br/br-usage-backup.md
The br debug feature has a known issue https://github.com/pingcap/tidb/issues/40878, which will only be resolved in v6.1 and 6.5 and their patch versions. For this reason, we remove this part from v6.3, which receives no bug fix.
> br: remove br debug info due to a known issue

- system-variables.md
Correct the wrong sysvar default value (`tidb_row_format_version` = 1) from 1 to 2.
> sysvar: correct a wrong sysvar default value

- develop/dev-guide-use-follower-read.md
- follower-read.md
- system-variables.md
Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>
Add a new mode `prefer-leader` for the system variable `tidb_replica_read`.
- Other reference link(s): https://github.com/pingcap/docs/pull/12337
> [TiDB] Add new mode option `prefer-leader` for `tidb_replica_read`.

- tikv-configuration-file.md
Deprecate a TiKV config `enable-statistics` because it is deprecated in code in https://github.com/tikv/tikv/pull/13942.
- This PR is translated from: https://github.com/pingcap/docs/pull/11626
> deprecate enable-statistics

- sql-plan-management.md
- sql-statements/sql-statement-create-binding.md
- sql-statements/sql-statement-drop-binding.md
update user document for the v6.6 feature "binding from history GA"
- https://github.com/pingcap/tidb/issues/39199
> planner: binding from history GA user doc

- system-variables.md
This is an addition to https://github.com/pingcap/docs-cn/pull/12677.
> stmtsummary: add system vars description

- system-variables.md
Update the table name because we renamed it in the code. Related PR: https://github.com/pingcap/tidb/pull/41093
- https://github.com/pingcap/docs-cn/pull/12885
- https://github.com/pingcap/docs/pull/12400
> *: update table name to tidb_background_subtask_history

- sql-statements/sql-statement-admin-show-ddl.md
close https://github.com/pingcap/docs/issues/9698
Add syntax 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n', which can retrieve DDL commands' content within a certain range (n+1, n+m).
A new syntax is added.
Add description for syntax 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n', which can retrieve DDL commands' content within a certain range (n+1, n+m).
I added a new syntax 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n', and the details can refer to:
https://github.com/pingcap/tidb/pull/36285
https://github.com/pingcap/tidb/pull/36480
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED …
> Add new syntax 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n'

- releases/release-6.3.0.md
- system-variables.md
Rename `tidb_enable_general_plan_cache` and `tidb_general_plan_cache_size` to `tidb_enable_non_prepared_plan_cache` and `tidb_non_prepared_plan_cache_size`.
> sysvar: change prepared-plan-cache variable names

- sql-statements/sql-statement-flashback-to-timestamp.md
> sql-statement: update `flashback cluster` related msg

- alert-rules.md
fix the rule of NODE_memory_used_more_than_80%
node_export 里 metric 不叫这个。
> fix the rule of NODE_memory_used_more_than_80%

- dynamic-config.md
Ref https://github.com/tikv/tikv/pull/10121 These config are support early to v5.1.0 but not documented.
- This PR is translated from: https://github.com/pingcap/docs/pull/12707
> tikv: add some missing dynamic config items

- sql-statements/sql-statement-drop-table.md
Fix a wrong description of `DROP TABLE IF EXISTS` warning message. The origin related issue is resolved before v4.0.0.
> tidb: add warning message of drop table

- .github/workflows/dispatch.yml
- .github/workflows/link-fail-fast.yaml
- .github/workflows/link.yaml
- Remove `assignees` in the Create Issue From File step. 
- Close #12060 
- This PR is translated from: https://github.com/pingcap/docs/pull/13034
> ci: remove assignees in Links, update the deprecated set-output command

- sql-statements/sql-statement-grant-privileges.md
- sql-statements/sql-statement-revoke-privileges.md
增加 `grant` 和 `revoke` 语句与 MySQL 兼容性的一个说明
- Other reference link(s): https://github.com/pingcap/tidb/issues/39356
> Add the incompatibility about `grant` and `revoke`

- alert-rules.md
> alert rules: update the solution of some rules

- sql-statements/sql-statement-alter-user.md
- sql-statements/sql-statement-create-resource-group.md
- tidb-resource-control.md
> resource_control: add a example to reset user resource group to default value

- TOC.md
- releases/release-6.5.2.md
- releases/release-notes.md
- releases/release-timeline.md
- Other reference link(s):https://github.com/pingcap/docs/pull/13273
> add 6.5.2 release notes

- releases/release-6.5.2.md
- ticdc/ticdc-changefeed-config.md
Modify the default value of `enable-partition-separator` for v6.5.2.
- Other reference link(s): https://github.com/pingcap/tiflow/pull/8779
> v6.5: modify default value descriptions for enable-partition-separator

- develop/dev-guide-use-stale-read.md
Add notice to avoid incorrect usage of `now` in stale read.
> add notice for now usage in stale read

- config-templates/complex-tiflash.yaml
- hardware-and-software-requirements.md
- tiflash/tiflash-configuration.md
- tiup/tiup-cluster-topology-reference.md
> Remove TiFlash http service

- ticdc/ticdc-faq.md
Fix an inconsistency issue in the TiCDC FAQ by updating the description from **if I set `enable-old-value` to `true`** to **if I set `safe-mode` to `true`**. The following content of this FAQ is focused on the `safe-mode` feature rather than `enable-old-value`.
```
TiCDC guarantees that all data is replicated at least once. When there is duplicate data in the downstream, write conflicts occur. To avoid this problem, TiCDC converts `INSERT` and `UPDATE` statements into `REPLACE INTO` statements. This behavior is controlled by the `safe-mode` parameter.
```
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, …
> ticdc: fix the description of safe-mode

- dm/maintain-dm-using-tiup.md
- tiup/tiup-component-cluster-patch.md
- tiup/tiup-component-cluster-reload.md
- tiup/tiup-component-cluster-scale-in.md
- tiup/tiup-component-cluster-upgrade.md
The default value of transfer-timeout is `600`.
- Other reference link(s): https://github.com/pingcap/tiup/pull/1972
> tiup: update the default value of transfer-timeout from 300 to 600

- tidb-lightning/tidb-lightning-physical-import-mode.md
> lightning: update the import capability spec 

- system-variables.md
> add config unit for tidb_adaptive_closest_read_threshold

- identify-slow-queries.md
Signed-off-by: crazycs520 <crazycs520@gmail.com>
update slow query doc to add the missing metrics about backoff
> update slow query doc

- alert-rules.md
- auto-increment.md
- Describe the behavior of auto_id_cache=0
- Add a link to describe how to address TiKV_pending_task alert
- This PR is translated from: https://github.com/pingcap/docs/pull/13085, https://github.com/pingcap/docs/pull/13049, https://github.com/pingcap/docs/pull/13479
> Describe auto_id_cache = 0 behavior and add link how to address TiKV_pending_task alert 

- dumpling-overview.md
- glossary.md
- tidb-troubleshooting-map.md
- This PR is translated from: https://github.com/pingcap/docs/pull/12446, https://github.com/pingcap/docs/pull/12443, https://github.com/pingcap/docs/pull/12493
> update links; clarify dumpling auto gc setting

- data-type-date-and-time.md
Fix the precision of DATETIME and TIMESTAMP values from milliseconds to microseconds.
> update precision of DATETIME and TIMESTAMP values

- configure-load-base-split.md
- releases/release-7.1.0.md
- tikv-configuration-file.md
> multirocks related config update

- basic-features.md
- ddl-introduction.md
- releases/release-7.1.0.md
- smooth-upgrade-tidb.md
Reverts pingcap/docs-cn#13731
Remove `ADMIN PAUSE DDL JOBS job_id [, job_id]` and `ADMIN RESUME DDL JOBS job_id [, job_id]` in TiDB v7.1.0
> Revert "Add description on `admin pause ddl jobs` and `admin resume ddl jobs`"

- ticdc/ticdc-changefeed-config.md
TiDB v7.1.0 introduces only-output-updated-columns. This PR removes only-output-updated-columns from v7.0 and earlier versions.
> ticdc: remove only-output-updated-columns from v7.0 and earlier versions

- releases/release-7.1.0.md
- tikv-configuration-file.md
> v7.2: Update the support info of optimize-filters-for-memory

- constraints.md
- system-variables.md
Add a switch
https://github.com/pingcap/tidb/issues/41711
> sql: add switch for check constraint

- tikv-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs/pull/13980
> rocksdb.*cf: supply descriptions on `ttl` and `periodic-compaction-seconds`.

- best-practices/pd-scheduling-best-practices.md
Bugfix for the description on `Slow Score` part.
- This PR is translated from: https://github.com/pingcap/docs/pull/13974
> pd: bugfix for the descriptions on `Slow Score`.

- releases/release-7.1.0.md
- tikv-configuration-file.md
Added/modified check and compact related config parameters, which is added in https://github.com/tikv/tikv/pull/14536.
> tikv config doc: update check and compact related docs

- sql-statements/sql-statement-admin-show-ddl.md
- system-variables.md
- temp.md
- Expand `JOB_TYPE` documentation for `ADMIN SHOW DDL...` output.
- Add note about `temp-dir` to `tidb_enabe_fast_reorg` docs.
- This PR is translated from: https://github.com/pingcap/docs/pull/13395
> Expand JOB_TYPE documentation for ADMIN SHOW DDL... output

- sql-statements/sql-statement-select.md
- temp.md
Closes #5915
- This PR is translated from: https://github.com/pingcap/docs/pull/12979
- https://github.com/pingcap/tidb/issues/20567
- https://bugs.mysql.com/bug.php?id=92759
```
sql> SELECT * FROM item TABLESAMPLE REGIONS();
+------+---------+-------------------------+---------+----------------------------------- …
```
> select: Add tablesample

- releases/release-7.1.1.md
In TiDB v7.1.1, the default value of compaction-guard-min-output-file-size is 8MB
- Other reference link(s):  https://github.com/tikv/tikv/pull/15180
> revert "change compaction-guard-min-output-file-size to 1MB"

- sql-plan-replayer.md
https://github.com/pingcap/tidb/issues/45038
https://github.com/pingcap/tidb/pull/44592
>  sql-plan-replayer: add doc for historical stats integration into the plan replayer

- tidb-configuration-file.md
- upgrade-tidb-using-tiup.md
增加关于在升级过程中，对于 server-version 配置参数的说明。
updates for TiDB in K8s is included in https://github.com/pingcap/docs-tidb-operator/pull/2431
> Remove server version upgrade

- explain-walkthrough.md
- system-variables.md
https://github.com/pingcap/tidb/pull/45252
https://github.com/pingcap/tidb/pull/42296
> optimizer: add docs for shared cte and explain enhancement

- optimizer-hints.md
> planner: add document about some new introduced hints

- tikv-configuration-file.md
v7.3: update default values for RocksDB config
- This PR is translated from: https://github.com/pingcap/docs/pull/14129
> v7.3: update default values for RocksDB config

- tikv-control.md
This PR have changed the `--db` option in `compact` and `compact-cluster` to `-d`, due to an unexpected omit of `long` opt <del>when migrating to `structopt`</del>, `--db` is unavailable for a long time.
This PR also explicitly announce that `compact-cluster` needs to specify the pd server instead of individual TiKV nodes. …
> tikv: fixed some description about `--db` and `compact-cluster` 

- sql-statements/sql-statement-admin-check-table-index.md
Add more details to the `ADMIN CHECK TABLE` documentation.
- This PR is translated from: https://github.com/pingcap/docs/pull/13375
Some notes, if desired we could add some of this to the docs, but I don't think most of this belongs in user documentation.
In `executor/executor.go` there is `CheckTableExec` which …
> Document what ADMIN CHECK does

- develop/dev-guide-choose-driver-or-orm.md
- develop/dev-guide-insert-data.md
- develop/dev-guide-sample-application-golang-gorm.md
- develop/dev-guide-sample-application-golang-sql-driver.md
> feat: golang example simplify

- develop/dev-guide-choose-driver-or-orm.md
- develop/dev-guide-insert-data.md
- develop/dev-guide-sample-application-python-django.md
- develop/dev-guide-sample-application-python-mysql-connector.md
- develop/dev-guide-sample-application-python-pymysql.md
- develop/dev-guide-sample-application-python-sqlalchemy.md
> develop: refactor Python dev guide

- tiflash/tiflash-configuration.md
- Other reference link(s): https://github.com/pingcap/tiflash/issues/7564
> tiflash: add descriptions for some conf items under [flash] section

- dumpling-overview.md
> fix PDF build failure: escape special characters

- partitioned-table.md
- temp.md
Added `ALTER TABLE t REMOVE PARTITIONING` and `ALTER TABLE t PARTITION BY ...`
- This PR is translated from: https://github.com/pingcap/docs/pull/13167
https://github.com/pingcap/tidb/pull/42907
https://github.com/pingcap/tiflash/pull/7822
https://github.com/pingcap/tiflow/pull/9670
> Added REMOVE PARTITIONING and ALTER TABLE t PARTITION BY

- get-started-with-tidb-lightning.md
> lightning: update get started doc

- sql-statements/sql-statement-load-data.md
Add the behavior description about committing rows for v7.0.0 and later versions.
> load data: update the notes about committing rows

- mysql-schema.md
> *: add descriptions for some system tables

- releases/release-6.1.0.md
- tune-region-performance.md
Recorrect the previous release notes on the configuration `region-split-size` in tikv.
> tikv: recorrect the descriptions on the feature `region-split-size` part.

- tidb-resource-control.md
Explicitly declare the scope of runaway queries management
> declare the scope of runaway queries management

- sql-statements/sql-statement-show-master-status.md
- temp.md
Add info about `SHOW BINARY LOG STATUS` being a new alias for `SHOW MASTER STATUS`.
Related to https://github.com/pingcap/tidb/issues/48673
- This PR is translated from: https://github.com/pingcap/docs/pull/15380
> statements: Add SHOW BINARY LOG STATUS info

- external-storage-uri.md
- sql-statements/sql-statement-import-into.md
- tidb-lightning/tidb-lightning-overview.md
- tidb-lightning/tidb-lightning-physical-import-mode.md
> Removed unsupported Azure Blob storage via import into

- releases/release-6.5.7.md
> releases: add 6.5.7 release notes

- dynamic-config.md
- tikv-configuration-file.md
Document periodic-full-compact-start-times and periodic-full-compact-start-max-cpu
- This PR is translated from: https://github.com/pingcap/docs/pull/15630
> tikv: document periodic full compaction

- TOC.md
- information-schema/information-schema-keywords.md
- information-schema/information-schema.md
- keywords.md
Add documentation related to https://github.com/pingcap/tidb/pull/48807
- This PR is translated from: https://github.com/pingcap/docs/pull/15795
> Add docs for the I_S keyword table

- statistics.md
translate doc to zh pr#13840
- This PR is translated from: https://github.com/pingcap/docs/pull/13840
> stats: clarify configuration persistence of analyze statement

- dashboard/dashboard-slow-query.md
- information-schema/information-schema-slow-query.md
- system-variables.md
translate-docs-pr#15602
- This PR is translated from: https://github.com/pingcap/docs/pull/15602
> Add/clarify SQL length limits

- sql-statements/sql-statement-explain.md
translate doc en to cn#15601
- This PR is translated from: https://github.com/pingcap/docs/pull/15601
> Add missing explain formats

- develop/dev-guide-choose-driver-or-orm.md
MySQL Connector/J 8.0 has compatibility issues with TiDB v7.5. Earlier versions of TiDB are fine as they announce themselves as MySQL v5.7. Later versions are fine as they implement the information_schema.KEYWORD table.
- This PR is translated from: https://github.com/pingcap/docs/pull/15794
> Add info about compatibility issues with Connector/J 8.0 with TiDB v7.5

- tiup/tiup-overview.md
Fix: #14723  
Update tiup-overview.md, with the latest tiup version.
> tiup: Update tiup-overview.md

- TOC.md
- sql-statements/sql-statement-flush-status.md
- sql-statements/sql-statement-show-status.md
- status-variables.md
Fix PR15363 https://github.com/pingcap/docs/pull/15363
- This PR is translated from: https://github.com/pingcap/docs/pull/15363
> Update SHOW STATUS docs

- tiproxy/tiproxy-overview.md
- tiup/tiup-component-cluster-upgrade.md
- TiUP Cluster supports specifying versions of specific components:
```
Flags:
--alertmanager-version string        Fix the version of alertmanager and no longer follows the cluster version.
--blackbox-exporter-version string   Fix the version of blackbox-exporter and no longer follows the cluster version.
--cdc-version string                 Fix the version of cdc and no longer follows the cluster version.
--force                              Force upgrade without transferring PD leader
-h, --help                               help for upgrade
--ignore-config-check                Ignore the config check result
--ignore-version-check               Ignore checking if target version is bigger than current version
--node-exporter-version string       Fix the version of node-exporter and no …
```
> tiup, tiproxy: add version flags to tiup cluster upgrade

- .github/pull_request_template.md
- README.md
1. Remove v7.3 from the PR template because TiDB v7.3 documentation is archived on Feb 2nd, 2024 and it no longer receives new updates. 
2. Add v8.0.
> pr-template: remove v7.3 and add v8.0

- TOC.md
- releases/release-6.5.8.md
- releases/release-notes.md
- releases/release-timeline.md
Add release note for TiDB v6.5.8.
> add release note for v6.5.8

- character-set-and-collation.md
Add instructions about the connection collation, which is decided by the client. It may cause behavior change between TiDB v7.3 and v7.4 after TiDB supports `utf8mb4_0900_ai_ci`.
- This PR is translated from: https://github.com/pingcap/docs/pull/16423
> add instructions about connection collation

- .vaunt/config.yaml
> Update config.yaml to fix PR bonus points

- functions-and-operators/string-functions.md
- temp.md
- Fix (#15482)  
- Describe the `BIT_LENGTH()` and `CHAR()` functions
- Add three examples that illustrate how `BIT_LENGTH()` works and four examples that illustrate how `CHAR()` works.
- Add a blockquote under the second `BIT_LENGTH()` example to indicate that the example operates under the assumption that a database exist
- Add a blockquote before "Further Examples" to explain that `CHAR()` also works with non-ASCII character …
> function-and-operators: enrich instructions for string functions BIT_LENGTH() and CHAR() #15482

- functions-and-operators/string-functions.md
- temp.md
Fix #15489.
- This PR is translated from: https://github.com/pingcap/docs/pull/16144
> Enrich instructions for string functions INSTR() and LCASE()

- best-practices/java-app-best-practices.md
- develop/dev-guide-connection-parameters.md
> fix: wait_timeout update for the best practices

- dr-multi-replica.md
- geo-distributed-deployment-topology.md
- three-data-centers-in-two-cities-deployment.md
> adjust the recommend value of raft election-timeout in multi dc deployment

- placement-rules-in-sql.md
> Update placement-rules-in-sql.md to fix the incorrect part

- upgrade-tidb-using-tiup.md
When `force-init-stats` is `ON`, it could reach the timeout of TiDB rolling update.  We includes additional description, list the necessary steps to avoid such problem. 
- [] v8.0 (TiDB 8.0 versions)
- [] v7.6 (TiDB 7.6 versions)
> include description about extending timeout of TiUP when force-init-stats is ON

- TOC.md
- information-schema/information-schema-tidb-index-usage.md
- information-schema/information-schema.md
- sys-schema.md
- system-variables.md
- tidb-configuration-file.md
Add the document for index usage related system tables and databases.
- This PR is translated from: https://github.com/pingcap/docs/pull/16446
> Add documents for `information_schema.tidb_index_usage` and `sys.schema_unused_index`.

- command-line-flags-for-tidb-configuration.md
- tidb-configuration-file.md
- Other reference link(s): https://github.com/pingcap/tidb/issues/51248
> tidb: add `general-log-file` and `compression`

- system-variables.md
> add explaination for log densitive feat

- encryption-at-rest.md
> encryption: add tikv kms encryption for gcp and azure

- ticdc/ticdc-faq.md
- ticdc/ticdc-overview.md
TiCDC is incompatible with TiDB Lightning Physical Import Mode.
> cdc: fix compatibility with TiDB Lightning

- functions-and-operators/string-functions.md
Enrich instructions for the string functions FIELD() and FIND_IN_SET()
- This PR is translated from: https://github.com/pingcap/docs/pull/16936
> Add examples for FIELD() and FIND_IN_SET()

- sql-statements/sql-statement-explain.md
- This PR is translated from: https://github.com/pingcap/docs/pull/16721
> refine the description of EXPLAIN

- error-codes.md
According to these TiDB server error messages, "PD server timeout" should be the correct error message.
S and T are both lowercase.
https://github.com/pingcap/tidb/blob/60aa838790e36e33b4105d22e191dfa827fe3663/errors.toml#L3101
https://github.com/pingcap/tidb/blob/60aa838790e36e33b4105d22e191dfa827fe3663/pkg/errno/errname.go#L1151
- This …
> tidb: "PD server timeout" error message as lowercase

- sql-statements/sql-statement-show-collation.md
- sql-statements/sql-statement-show-errors.md
- This PR is translated from:https://github.com/pingcap/docs/pull/17018 https://github.com/pingcap/docs/pull/17012
> ebnf show errors

- releases/release-8.0.0.md
- system-variables.md
- This PR is translated from:https://github.com/pingcap/docs/pull/16871
> Add new order ratio being added to 8.0.0

- _docHome.md
- develop/dev-guide-build-cluster-in-cloud.md
- develop/dev-guide-sample-application-java-jdbc.md
- dm/dm-faq.md
- releases/release-2.1.2.md
- releases/release-6.5.7.md
- releases/release-7.1.3.md
- tidb-binlog/upgrade-tidb-binlog.md
- tidb-troubleshooting-map.md
Fix broken links:
- The link to the node-mysql2 documentation has been updated. The previous URL `https://github.com/sidorares/node-mysql2/tree/master/documentation/en` was removed in https://github.com/sidorares/node-mysql2/pull/2326. It now points to the current documentation site: https://sidorares.github.io/node-mysql2/docs/documentation.
- The link `https://docs.pingcap.com/tidb/stable/dev-guide-sample-application-java` is leading to a 404 error because `develop/dev-guide-sample-application-java.md` was removed without any redirect aliases being added.
- The TiDB Lightning package `https://github.com/pingcap/tidb/tree/master/br/pkg/lightning` was modified to `https://github.com/pingcap/tidb/tree/master/lightning` in https://github.com/pingcap/tidb/pull/52247.
**Tips for choosing the …
> *: fix broken links

- functions-and-operators/string-functions.md
Add REPEAT() example
- This PR is translated from: https://github.com/pingcap/docs/pull/16960
> Add REPEAT() example

- tiproxy/tiproxy-configuration.md
`require-backend-tls` was under `proxy` and was true by default, but since v0.2.0 it's under `security` and is false by default.
> tiproxy: fix config `require-backend-tls`

- functions-and-operators/string-functions.md
- This PR is translated from:https://github.com/pingcap/docs/pull/16957  https://github.com/pingcap/docs/pull/16962
> Add example for multi argument CHAR()

- sql-statements/sql-statement-savepoint.md
- sql-statements/sql-statement-set-names.md
- sql-statements/sql-statement-show-columns-from.md
- sql-statements/sql-statement-show-create-user.md
- sql-statements/sql-statement-show-grants.md
- sql-statements/sql-statement-show-profiles.md
- sql-statements/sql-statement-show-stats-healthy.md
- sql-statements/sql-statement-unlock-stats.md
- https://github.com/pingcap/docs/pull/17070
- https://github.com/pingcap/docs/pull/17072
- https://github.com/pingcap/docs/pull/17074
- https://github.com/pingcap/docs/pull/17081
- https://github.com/pingcap/docs/pull/17082
- https://github.com/pingcap/docs/pull/17083
- https://github.com/pingcap/docs/pull/17087
- …
> translate 8 EBNF related PRs

- functions-and-operators/bit-functions-and-operators.md
- functions-and-operators/date-and-time-functions.md
- functions-and-operators/encryption-and-compression-functions.md
- functions-and-operators/json-functions.md
- functions-and-operators/locking-functions.md
- functions-and-operators/string-functions.md
- https://github.com/pingcap/docs/pull/16847
- https://github.com/pingcap/docs/pull/16851
- https://github.com/pingcap/docs/pull/16852
- https://github.com/pingcap/docs/pull/16854
- https://github.com/pingcap/docs/pull/16857
- https://github.com/pingcap/docs/pull/16859
> translate 6 PRs for functions and operators

- grafana-tikv-dashboard.md
This PR added the explanation about the panels of log backup.
> grafana: explained metrics in log backup row

- sql-statements/sql-statement-show-create-table.md
- sql-statements/sql-statement-show-indexes.md
- sql-statements/sql-statement-show-table-next-rowid.md
- sql-statements/sql-statement-show-table-regions.md
- sql-statements/sql-statement-split-region.md
- sql-statements/sql-statement-update.md
Update synopsis to ebnf diagrams for 6 SQL statements, to make it clearer, and easier to maintain 
- https://github.com/pingcap/docs/pull/17085
- https://github.com/pingcap/docs/pull/17089
- https://github.com/pingcap/docs/pull/17093
- https://github.com/pingcap/docs/pull/17095
- https://github.com/pingcap/docs/pull/17097
- …
> sql-stmt: update synopsis to ebnf diagrams for 6 statements

- information-schema/information-schema-runaway-watches.md
- sql-statements/sql-statement-query-watch.md
- tidb-resource-control.md
> resource-control: remove warning about runaway

- system-variables.md
> document INSERT IGNORE ON DUP for pipelined dml

- sql-statements/sql-statement-import-into.md
> GA import into from select

- TOC.md
- mysql-compatibility.md
- tiproxy/tiproxy-api.md
- tiproxy/tiproxy-command-line-flags.md
More than one user asked about the TiProxy API: https://asktug.com/t/topic/1025865, https://asktug.com/t/topic/1024233/30
I didn't document it because it's only used for debugging and troubleshooting, but I found TiDB also documented it: https://docs.pingcap.com/zh/tidb/stable/tidb-monitoring-api
> tiproxy: add tiproxyctl commands and http api

- faq/manage-cluster-faq.md
- temp.md
Describe in what condition TiDB & RawKV can be used together.
Since `v6.1.0` TiDB & RawKV can be used together if [API V2](https://docs.pingcap.com/tidb/stable/tikv-configuration-file#api-version-new-in-v610)  is enabled:
> Data is scoped according to different usage and API V2 supports co-existence of TiDB, Transactional KV, and RawKV applications in a single cluster.
But the relevant FAQ has not been changed accordingly yet.
For details, see [tips for choosing the affected …
> faq: Describe in what condition TiDB and RawKV can be used together

- br/br-monitoring-and-alert.md
- pd-configuration-file.md
- releases/release-rc.1.md
- scripts/verify-links.sh
Fix several typos
Ref: https://github.com/tikv/tikv/pull/16931
- This PR is translated from: https://github.com/pingcap/docs/pull/17405
> *: fix several typos

- ticdc/ticdc-upstream-downstream-check.md
https://github.com/pingcap/tiflow/pull/11253
> ticdc: add new rules and information for syncpoint

- sql-statements/sql-statement-create-user.md
- temp.md
For reviewers: Preview ebnf on https://kennytm.github.io/website-docs/dist/
The `PASSWORD REQUIRE CURRENT DEFAULT` syntax is accepted to be able to parse the output of `SHOW CREATE USER`  from MySQL.  Especially as this is added by default by MySQL even if not specified when creating the user.
In MySQL `PASSWORD REQUIRE CURRENT` and `PASSWORD REQUIRE CURRENT OPTIONAL` are also accepted, but TiDB doesn't and the parser won't accept this.
As there is no `password_require_current` system variable in TiDB and no other options are accepted this syntax is meaningless / ignored.
See also: https://dev.mysql.com/doc/refman/8.4/en/password-management.html#password-reverification-policy
Note that the docs suggested that `CREATE USER 'foo3'@'%' IDENTIFIED BY 'abc' DEFAULT ROLE 'myrole'` should be …
> Update EBNF for password options

- releases/release-8.0.0.md
- releases/release-8.1.0.md
- system-variables.md
Update inaccurate descriptions for the `tidb_schema_cache_size` system variable
> Update descriptions for tidb_schema_cache_size

- releases/release-6.5.10.md
In v6.5, disabling `tidb_enable_async_merge_global_stats` is the default merge global status method.
> remove tidb_enable_async_merge_global_stats from v6.5.10 release notes

- tidb-configuration-file.md
- tikv-configuration-file.md
> doc: add more details to grpc-compression configs

- releases/release-4.0.10.md
- releases/release-4.0.6.md
- releases/release-4.0.8.md
- releases/release-5.0.6.md
- releases/release-5.1.4.md
- releases/release-5.2.4.md
- releases/release-5.3.1.md
- ticdc/ticdc-open-api-v2.md
- ticdc/ticdc-open-api.md
- ticdc/ticdc-sink-to-kafka.md
cdc: remove maxwell protocol, add simple protocol
> cdc: remove maxwell protocol, add simple protocol

- develop/dev-guide-timeouts-in-tidb.md
- dumpling-overview.md
- migrate-from-tidb-to-mysql.md
Fix the GC description of Dumpling. 
> dumpling: update the gc info

- br/use-br-command-line-tool.md
> br: add "tiup br debug" command

- pessimistic-transaction.md
- system-variables.md
Referenced tidb issue https://github.com/pingcap/tidb/issues/55022, the document for supporting upgrading `for share` lock statement to `for update` statement.
> sys var: add `tidb_enable_shared_lock_promotion` related doc change

- best-practices/java-app-best-practices.md
- develop/dev-guide-connection-parameters.md
- system-variables.md
Add a new variable `tidb_enable_lazy_cursor_fetch`, and introduce the effect and limitation of it.
- This PR is translated from: https://github.com/pingcap/docs/pull/18329
> variable: add document about lazy cursor fetch and its variable

- system-variables.md
v8.3: Changes the default value of `tidb_opt_projection_push_down` from `OFF` to `ON`.
> Change tidb_opt_projection_push_down default value to ON

- system-variables.md
Modify the scope of variable `tidb_gc_concurrency`.
https://github.com/pingcap/tidb/pull/54571
> doc: concurrency of gc delete-range

- system-variables.md
> v8.1.1: Turn off hash agg spill by default

- tikv-configuration-file.md
The description for the `right-derive-when-split` TiKV config item is not clear, not easy to understand. This PRs makes the description more clear. The description in English docs is clear: https://docs.pingcap.com/tidb/stable/tikv-configuration-file#right-derive-when-split …
> Make "right-derive-when-split" description more clear

- ticdc/ticdc-sink-to-kafka.md
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/15998/files  https://github.com/pingcap/docs-cn/pull/15115/files
> ticdc: add a note about schema

- sql-statements/sql-statement-import-into.md
> add limit to import into

- tidb-lightning/tidb-lightning-logical-import-mode-usage.md
> change lightning conflict resolution `ignore`

- TOC.md
- releases/release-6.5.11.md
- releases/release-notes.md
- releases/release-timeline.md
> add v6.5.11 release notes

- system-variables.md
> system-variables: optimize the persist info

- sql-statements/sql-statement-explain.md
> sql-statement-explain: add explanation related to scalar subquery

- configure-placement-rules.md
> cfg: fix wrong pd-ctl cmd

- basic-features.md
- develop/dev-guide-transaction-restraints.md
- releases/release-4.0.0-rc.2.md
- tidb-configuration-file.md
> txn: fix the maximum value of a transaction from 10GB to 1 TiB

- system-variables.md
> add doc for hash_join_v2

- tidb-configuration-file.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/55985
> config: update doc of tidb tikv-client.grpc-keepalive-timeout config

- system-variables.md
> sys-var: change `tidb_scatter_region` usage definition

- system-variables.md
> sysvars: add `tidb_shard_row_id_bits` and `tidb_pre_split_regions`

- ticdc/ticdc-integrity-check.md
> cdc: add description about checksum v2

- functions-and-operators/string-functions.md
TiDB v8.4.0 supports `MID(str, pos[, len])`
- This PR is translated from: https://github.com/pingcap/docs/pull/18669
> TiDB supports `MID(str, pos[, len])`

- system-variables.md
- This PR is translated from: https://github.com/pingcap/docs/pull/18830
- Other reference link(s): https://github.com/pingcap/tidb/issues/54057
> planner: add variables for instance plan cache

- system-variables.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/56172
> system variables: update the default value of tidb_enable_inl_join_inner_multi_pattern

- sql-statements/sql-statement-alter-resource-group.md
- sql-statements/sql-statement-create-resource-group.md
- sql-statements/sql-statement-query-watch.md
- tidb-resource-control.md
Add the newly added `SWITCH_GROUP(<name>)` syntax document by https://github.com/pingcap/tidb/pull/54804.
> Add new resource control action SWITCH_GROUP

- tidb-lightning/tidb-lightning-configuration.md
- This PR is translated from: https://github.com/pingcap/docs/pull/18902
> add logical-import-prep-stmt

- dynamic-config.md
- pessimistic-transaction.md
- tikv-configuration-file.md
> tikv config: Add in-memory lock tikv config

- functions-and-operators/json-functions.md
Fixes a JSON function typo introduced in https://github.com/pingcap/docs-cn/pull/17784: `JSON_DEPTH()` to `JSON_LENGTH()`.
- Other reference link(s): https://docs.pingcap.com/tidb/dev/json-functions#functions-that-return-json-value-attributes
> Fix a JSON function typo

- dm/dm-best-practices.md
- temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/19207
> dm-best-practices: Update for MySQL Compatible AUTO_INCREMENT

- releases/release-6.5.6.md
To align with https://github.com/pingcap/docs-cn/pull/18913. "changefeed-error-stuck-duration" in introduced in v6.5.6 for v6.x versions.
- Other reference link(s): https://github.com/pingcap/tiflow/pull/9877
> Add TiCDC config "changefeed-error-stuck-duration" to v6.5.6 release notes

- system-variables.md
- tidb-configuration-file.md
https://github.com/pingcap/docs/pull/19109
> *: add tidb_enable_stats_owner

- ticdc/ticdc-changefeed-config.md
> cdc: add warn for event filter

- alert-rules.md
> remove by name for alert of TiKV_raftstore_thread_cpu_seconds_total

- temp.md
- tiup/tiup-cluster-topology-reference.md
topology config supports TiCDC server and TiKV-CDC, they are different.
https://asktug.com/t/topic/1034131
- This PR is translated from: https://github.com/pingcap/docs/pull/19230
> tiup: add kvcdc server topylogy example

- dm/dm-customized-secret-key.md
- dm/dm-master-configuration-file.md
> add example to generate dm key

- schema-cache.md
> Updated the limitation of Schema Cache

- tiflash/tiflash-configuration.md
- tiflash/tiflash-mintso-scheduler.md
Adds TiFlash MinTSO config parameters
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/18621, https://github.com/pingcap/docs-cn/pull/18542
> Add mintso config parameters

- partitioned-table.md
- system-variables.md
- tiflash/use-tiflash-mpp-mode.md
Deprecated static prune mode, ref https://github.com/pingcap/tidb/issues/56490
- Other reference link(s): ref https://github.com/pingcap/tidb/pull/56543
> system-variable: add a warning message for `tidb_partition_prune_mode` variable

- system-variables.md
- tune-region-performance.md
- Other reference link(s): https://github.com/tikv/pd/issues/7431
> pd: GA active follower

- accelerated-table-creation.md
- system-variables.md
> enable fast create table on default

- data-type-numeric.md
- data-type-overview.md
- temp.md
- tidb-configuration-file.md
Update the docs to follow the change in default value for `deprecate-integer-display-length`. 
This follows the behavior in MySQL.
Integer types can be defined like `int(10)` or `int(8)` or `int`. People often misunderstand the meaning of the number that is specified here (e.g. the 10 and the 8 here). This does not change the capacity of the value that can be stored it only changes how it might be displayed.
See also https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html and https://github.com/pingcap/tidb/pull/56529
**Important**: This changes the documentation for the variable and updates the page describing numeric types. However this does _NOT_ update the output that might have changed. 
Output that changes based on this variable:
- `SHOW CREATE TABLE`
- `DESCRIBE …
> Update docs for deprecate-integer-display-length=true

- pd-control.md
> Add service-middleware config for pd-ctl

- hardware-and-software-requirements.md
According to https://github.com/pingcap/docs/pull/19539/files, TiDB ends the support for Red Hat Enterprise Linux 7 starting from the 8.4 DMR version. This PR adds a note about this for release-8.1 users.
> release-8.1: add a note for Red Hat Enterprise Linux 7 

- privilege-management.md
> privilege: change privilege for `SHOW PROCESSLIST` from `SUPER` to `PROCESS`

- ticdc/ticdc-alert-rules.md
Keep the doc consistent with https://github.com/pingcap/tiflow/blob/master/metrics/alertmanager/ticdc.rules.yml. Note that alert rules diffes in diffrent release branches.
> ticdc: fix alert doc

- releases/release-7.4.0.md
- system-variables.md
[`tidb_stats_cache_mem_quota`](/system-variables.md#tidb_stats_cache_mem_quota-从-v610-版本开始引入) was generally available on v7.4.0.  Include missing announcement in release notes. 
- This PR is translated from: https://github.com/pingcap/docs/pull/19604
> Announce GA of memory control on stats cache

- explain-overview.md
- sql-statements/sql-statement-explain-analyze.md
- sql-statements/sql-statement-explain.md
> Update explain and execution summary related docs

- optimizer-fix-controls.md
Before v8.5.0, the default value of 46177 is OFF
> planner: fix the default value of 46177 to OFF for versions earlier than 8.5

- sql-statements/sql-statement-flashback-cluster.md
> flashback: add limitation with stale read/snapshot

- sql-statements/sql-statement-import-into.md
> Improve usage of `IMPORT FROM SELECT`

- develop/dev-guide-connect-to-tidb.md
- partitioned-table.md
Update how to connect TiDB by MySQL Client and the limits of the global indexes 
> Update how to connect TiDB by MySQL Client and the limitations of the global indexes

- .github/pull_request_template.md
- README.md
- resources/cdnfresh.txt
Remove v5.3/v8.2 from the PR template because v5.3/v8.2 docs have been archived at [docs-archive.pingcap.com/zh/tidb](https://docs-archive.pingcap.com/zh/tidb) and will no longer receive new updates.
> chore: remove v5.3/v8.2 from PR template

- tidb-binlog/tidb-binlog-configuration-file.md
Add the description of load schema snapshot 
> Add the description of load schema snapshot 

- sql-statements/sql-statement-rename-table.md
> sql: `RENAME TABLE` supports renaming multiple tables and across dbs

- tikv-configuration-file.md
Update recent TiKV default configuration changes
* `enable-compaction-guard`: https://github.com/tikv/tikv/pull/14009
* `min-blob-size`:  https://github.com/tikv/tikv/pull/16402
* `target-file-size-base`: https://github.com/tikv/tikv/pull/14361
* `ribbon-filter-above-level`: https://github.com/tikv/tikv/pull/14527
* `write-buffer-limit`: https://github.com/tikv/tikv/pull/15453
* `ttl`/`periodic-compaction-seconds`: https://github.com/tikv/tikv/pull/14880
Touch: https://github.com/tikv/tikv/issues/18068 …
> Update recent TiKV config changes

- data-type-default-values.md
- This PR is translated from:https://github.com/pingcap/docs/pull/19685
> Update docs for expression defaults

- functions-and-operators/tidb-functions.md
- glossary.md
- This PR is translated from:https://github.com/pingcap/docs/pull/19715
> functions: Add TIDB_MVCC_INFO, TIDB_ENCODE_INDEX_KEY and TIDB_ENCODE_RECORD_KEY

- tiproxy/tiproxy-configuration.md
- tiproxy/tiproxy-deployment-topology.md
- tiproxy/tiproxy-overview.md
- tiup/tiup-cluster-topology-reference.md
Currently, I received some confusion about deploying TiProxy. The main reason is that the documents are spread everywhere.
Some of the confusion:
- I can't find the deployment sample of TiUP
- Are the TLS configs in the sample mandatory?
- How can I customize the deploy directory?
- The description of some configs is unclear
- What's the sample of configuring VIP?
One of the complaints: https://asktug.com/t/topic/1037753 …
> tiproxy: improve deployment instructions for deploying TiProxy

- cached-tables.md
- This PR is translated from:https://github.com/pingcap/docs/pull/19919
> Cached table size limit should be 64 MiB

- scale-tidb-using-tiup.md
- tiflash/tiflash-overview.md
- tiflash/troubleshoot-tiflash.md
* The "pd buddy" has been removed from TiFlash since v6.0 https://github.com/pingcap/tidb/issues/29924
> Refine tiflash docs to remove deprecated description

- schema-cache.md
> schema-cache: update doc for schema cache

- enable-tls-between-components.md
- tiup/tiup-cluster-topology-reference.md
`http_port` has been deprecated since v7.1.0, remove all description about it.
> tiflash: remove deprecated http_port

- ticdc/ticdc-avro-protocol.md
- This PR is translated from: https://github.com/pingcap/docs/pull/19573
> ticdc: add note to the Avro protocol

- ticdc/ticdc-faq.md
- This PR is translated from: https://github.com/pingcap/docs/pull/19369
> ticdc: add a faq about generated column

- tiproxy/tiproxy-deployment-topology.md
- tiup/tiup-cluster-topology-reference.md
- This PR is translated from:https://github.com/pingcap/docs/pull/20119
> tiup: fix tiproxy data_dir

- ticdc/ticdc-sink-to-mysql.md
> ticdc: add description about safe-mode arguments

- TOC.md
- releases/release-6.5.12.md
- releases/release-7.5.5.md
- releases/release-notes.md
- releases/release-timeline.md
> add v6.5.12 release notes

- mysql-schema/mysql-schema.md
> mysql-schema: add information about several missing system tables

- system-variables.md
This PR removes the default value descriptions for the following  last_xxx variables:
last_plan_from_binding
last_plan_from_cache
last_sql_use_alloc
Reason:  their values are determined by whether a function is used or not, so the default values are meaningless and confusing. 
> system-variables: remove the default value descriptions for  last_xxx variables 

- releases/release-6.5.0.md
> v6.5.0 release notes: add descriptions about tidb_store_batch_size

- benchmark/benchmark-sysbench-v6.2.0-vs-v6.1.0.md
- benchmark/v6.2-performance-benchmarking-with-tpcc.md
- benchmark/v6.2-performance-benchmarking-with-tpch.md
- temp.md
This PR adds aliases for the following stale benchmark docs removed in https://github.com/pingcap/docs/pull/20462.
- ./benchmark/benchmark-sysbench-v6.2.0-vs-v6.1.0.md
- ./benchmark/v6.2-performance-benchmarking-with-tpcc.md
- ./benchmark/v6.2-performance-benchmarking-with-tpch.md …
> v6.5: add aliases for stale benchmark docs

- keywords.md
variable tidb_enable_window_function可以控制R-Window中的关键词是否在语法树中生效，如果tidb_enable_window_function设置为OFF，则R-Window中的单词将不再作为关键词。
add tidb_enable_window_function can control the keyword list.
> add tidb_enable_window_function can control the keyword list

- clustered-indexes.md
Modify the limitation of `cluster index`. `PRE_SPLIT_REGION` is supported for auto random column.
- This PR is translated from: https://github.com/pingcap/docs/pull/20551
> Fix the desciption about cluster index and pre split region on auto random column

- tikv-configuration-file.md
Doc of 3 TiKV config items, introduced in https://github.com/tikv/tikv/pull/17917
https://github.com/tikv/tikv/issues/17916
https://github.com/tikv/tikv/pull/17917
> doc: configs of max-ts checker

- system-variables.md
after fix of https://github.com/pingcap/tidb/pull/60272, we add tidb_enable_point_get_cache back, so we just add the variable document back
> add system variable tidb_enable_point_get_cache back

- develop/dev-guide-sample-application-java-jdbc.md
- faq/sql-faq.md
- faq/upgrade-faq.md
> add FAQs about collation for JDBC connections

- pd-configuration-file.md
- releases/release-8.0.0.md
> fix(pd): add missing configuration items for PD

- releases/release-7.6.0.md
- releases/release-8.0.0.md
- releases/release-8.1.0.md
- releases/release-8.1.2.md
- tikv-configuration-file.md
As the title mentioned, this PR is used to recorrect the settings for some configurations in TiKV.
Meanwhile, for some newly introduced configurations, it supplements annotations for them.
> tikv: recorrect the settings of some configs and supplement missing annotations for several configs.

- sql-statements/sql-statement-import-into.md
Added a new restriction to the `IMPORT INTO` documentation specifying that the target table must be entirely empty for import operations, including all partitions.
- This PR is translated from: https://github.com/pingcap/docs/pull/20562
> Add restriction for IMPORT INTO regarding empty

- releases/release-7.2.0.md
I got inquiries from customers. The change of default value for `tidb_remove_orderby_in_subquery` (v7.2.0) would cause disordered outputs.  Even though this is expected, we'd better include a notice in release notes. 
> include compatibility notice for tidb_remove_orderby_in_subquery

- information-schema/information-schema-tidb-index-usage.md
Add a limitation to the tidb usage limitation. The description is aligned with the "index-advisor.md":
> The data in `INFORMATION_SCHEMA.CLUSTER_TIDB_INDEX_USAGE` might be delayed by up to five minutes, and the usage data is reset whenever a TiDB node restarts. Additionally, index usage is only recorded if the table has valid statistics. …
> Add tidb index usage limitation for valid stats

- dm/dm-worker-configuration-file.md
- log-redaction.md
- This PR is translated from: https://github.com/pingcap/tiflow/pull/11709
> dm: add log redaction configuration item in dm worker log file

- develop/dev-guide-paginate-results.md
> dev doc: update the example of paginate results

- storage-engine/titan-configuration.md
- tikv-configuration-file.md
This PR updates release-8.1 docs according to https://github.com/pingcap/docs-cn/pull/20304. 
> titan-configuration: remove the unrecommended steps of updating TiKV configuration 

- tiproxy/tiproxy-deployment-topology.md
- tiproxy/tiproxy-load-balance.md
- tiproxy/tiproxy-overview.md
TiProxy needs around 3s to detect TiDB gracefully shutting down and 5s to start migrating the last connection, so it will take another 10s to migrate the connections.
We should recommend a longer `graceful-wait-before-shutdown`.
> tiproxy: update the recommended graceful-wait-before-shutdown

- .github/pull_request_template.md
- README.md
Remove v8.3 and v8.4 from the PR template because these docs have been archived at [docs-archive.pingcap.com/zh/tidb](https://docs-archive.pingcap.com/zh/tidb) and will no longer receive new updates.
> chore: remove v8.3 and v8.4 from PR template

- tidb-lightning/tidb-lightning-prechecks.md
Update tidb-lightning-prechecks 
> tidb-lightning: add checking PITR and active changefeed task

- releases/release-7.1.2.md
- releases/release-7.1.6.md
As in the title, this PR moves [tiflow/issues/9855](https://github.com/pingcap/tiflow/issues/9855) from v7.1.6 release notes to v7.1.2 release notes, because the corresponding PR (https://github.com/pingcap/tiflow/pull/9859) was merged during v7.1.2 preparation. 
> Move tiflow/issues/9855 from v7.1.6 release notes to v7.1.2 release notes

- tiup/tiup-bench.md
> tiup: clarify `tiup bench` command

- ticdc/ticdc-csv.md
1. Add a new field `output-field-header`
1. Add the header description about CSV protocol
- Other reference link(s): https://github.com/pingcap/tiflow/pull/12183
> ticdc: add header line for CSV protocol

- tidb-resource-control-runaway-queries.md
> resouce control: add desp about `QUERY WATCH REMOVE RESOURCE GROUP`

- tiflash/tiflash-configuration.md
> tiflash: add config of enable_version_chain

- ticdc/ticdc-faq.md
- ticdc/ticdc-sink-to-kafka.md
Added a new FAQ for TiCDC Kafka synchronization scenarios. It explains that a short Kafka idle connection timeout may cause changefeed failures, and suggests adjusting the configuration to avoid the issue. It also clarifies that the problem does not affect continued operation, and only causes a brief lag spike during changefeed restarts. …
> cdc: add solution for kafka broken pipe error

- system-variables.md
> sys var: consider global sort for `tidb_ddl_reorg_max_write_speed`

- follower-read.md
The description of follower-read and learner-read is inaccurate, and related behaviors have been adjusted in the newer version of tidb, so the corresponding documentation has been revised accordingly.
> Update follower read and learner read descriptions

- identify-slow-queries.md
- statement-summary-tables.md
Document extra attributes added to identify the storage engine in both the statement summary and slow query log.
- This PR is translated from: https://github.com/pingcap/docs/pull/21155
> include storage engines in slow query logs and statements summary
