- _index.md
> *: corrected alias in index

- _index.md
Correct alias in index for 6.1
> *: correct alias in index for 6.1

- tikv-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs/pull/10281
> add tikv configuration item simplify-metrics

- ticdc/manage-ticdc.md
> Revert "ticdc: add a warning for the eventually consistent replication feature"

- ticdc/manage-ticdc.md
deprecated mem sorter for ticdc.
> ticdc: deprecated mem sorter

- dm/dm-webui-guide.md
> modify prerequisite for DM dashboard

- cached-tables.md
- releases/release-6.0.0-dmr.md
- sql-plan-management.md
- sql-prepared-plan-cache.md
- system-variables.md
- transaction-isolation-levels.md
Fix the format of version mark
> fix version mark

- tidb-binlog/tidb-binlog-faq.md
mysql> show grants for repl;
+----------------------------------------------------------------------------------------+
| Grants for repl@%                                                                      |
+----------------------------------------------------------------------------------------+
| GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,EXECUTE,INDEX ON *.* TO 'repl'@'%' |
+----------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
mysql> CREATE TABLE t1 (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, c1 INT NOT NULL);
Query OK, 0 rows affected (0.10 sec)
mysql> INSERT INTO t1 (c1) VALUES (1),(2),(3),(4),(5);
Query OK, 5 rows affected (0.02 sec)
Records: 5  Duplicates: 0  Warnings: 0
mysql> CREATE VIEW v1 AS SELECT * …
> Add Create View Privilege

- system-variables.md
Add tidb_last_ddl_info system vars usage description in docs
- This PR is translated from: https://github.com/pingcap/docs/pull/10117
> Add tidb_last_ddl_info system vars usage description in docs

- develop/dev-guide-client-connection-parameters.md
- develop/dev-guide-connect-to-tidb.md
Fix the typo in `develop/dev-guide-client-connection-parameters.md` from "链接" to "连接"
> Developer guide: fix typo

- clustered-indexes.md
- system-variables.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/37384
> clustered-indexes.md: change the system variable default value to `ON`

- tikv-configuration-file.md
As title.
- This PR is translated from:https://github.com/pingcap/docs/pull/10258
> add two configs for raft engine log recycling

- schedule-replicas-by-topology-labels.md
placement rules: remove experimental note
> placement rules: remove experimental note

- best-practices/pd-scheduling-best-practices.md
best-practices: fix a wrong description
> best-practices: fix a wrong description

- ticdc/deploy-ticdc.md
- ticdc/manage-ticdc.md
add doc about ticdc `cluster-id` and `server` parameter
https://github.com/pingcap/tiflow/pull/5893
https://docs.google.com/document/d/1MSJ9SnpXLhzCKwNE-G38tEfS0Y3maHxYW74DUBYcNNE/edit?n=TiCDC_On-Cloud_Deployment_and_Network_Topology--SPEC#
> update ticdc doc about server and cli parameters

- tiflash/tiflash-supported-pushdown-calculations.md
> tiflash: add docs about lead/lag push down to tiflash

- best-practices/pd-scheduling-best-practices.md
Refine wording
- Other reference link(s): #11243
> best-practices: update wording in PD scheduling

- sql-statements/sql-statement-explain.md
revise explain format by list
- Other reference link(s): https://asktug.com/t/topic/903234
> revise explain format by list

- best-practices/pd-scheduling-best-practices.md
> Add a link to explain how to change weight

- experimental-features.md
- storage-engine/titan-configuration.md
- tikv-configuration-file.md
https://github.com/pingcap/docs/pull/10257
- This PR is translated from: https://github.com/pingcap/docs/pull/10257
> update tikv docs for titan fallback

- encryption-at-rest.md
> v6.3: add sm4 for tiflash to encryption-at-rest.md

- follower-read.md
- schedule-replicas-by-topology-labels.md
- system-variables.md
> tidb: config tidb server labels

- basic-features.md
- functions-and-operators/encryption-and-compression-functions.md
- security-compatibility-with-mysql.md
- sql-statements/sql-statement-show-builtins.md
- system-variables.md
Add description about SM3 encryption authentication
- Other reference link(s): https://github.com/pingcap/tidb/pull/36193
> v6.3: Add description about SM3 encryption authentication

- generated-columns.md
- system-variables.md
> gcolumn: add `tidb_enable_unsafe_substitute` to control generated column substitute

- br/pitr-troubleshoot.md
- br/point-in-time-recovery.md
Signed-off-by: Yu Juncen <Yu745514916@live.com>
This PR added the new adaption for tiflash of PiTR.
N/A
> added newer pitr & tiflash adapt information

- system-variables.md
Added  new variable `tidb_opt_three_stage_distinct_agg`
- This PR is translated from: https://github.com/pingcap/docs/pull/10419
> Add new variable tidb_opt_three_stage_distinct_agg

- placement-rules-in-sql.md
- This PR is translated from: https://github.com/pingcap/docs/pull/10207
- Other reference link(s): https://github.com/pingcap/tidb/pull/37252
> remove tiflash and placement in sql incompatible descrption

- sync-diff-inspector/upstream-downstream-diff.md
- ticdc/manage-ticdc.md
> ticdc: add sync point config

- security-compatibility-with-mysql.md
- system-variables.md
Add the link of TiDB-JDBC in the description of `tidb_sm3_password`.
> v6.3: Add TiDB-JDBC link for tidb_sm3_password

- dynamic-config.md
- tikv-configuration-file.md
- tune-tikv-thread-performance.md
> tikv: add new config for auto adjust read pool thread count

- sql-statements/sql-statement-change-column.md
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/11319
> fix a link in sql-statement-change-column.md

- pd-configuration-file.md
correct placement rules config
> correct placement rules config

- develop/dev-guide-build-cluster-in-cloud.md
- This PR is translated from: https://github.com/pingcap/docs/pull/10140
> dev-guide: rename active clusters 

- develop/dev-guide-get-data-from-single-table.md
> [Update] add sort/limit/aggregate java example codes

- storage-engine/titan-configuration.md
titan: update the step of disabling titan
- This PR is translated from: https://github.com/pingcap/docs/pull/10496
> titan: update the step of disabling titan

- sql-statements/sql-statement-create-index.md
Updated the doc according to the feedback in https://asktug.com/t/topic/933611
- Other reference link(s): https://asktug.com/t/topic/933611
> sql: update sql-statement-create-index.md

- encryption-at-rest.md
> remove tiflash sm4 encryption support

- experimental-features.md
- grafana-tikv-dashboard.md
add fast tune doc
- This PR is translated from: https://github.com/pingcap/docs/pull/10487
> add fast tune doc

- ticdc/deploy-ticdc.md
> update deploy cdc docs

- resources/cdnfresh.txt
Add tidb-in-kubernetes pdf in the list.
> *: update pdf list for cdn flush

- tikv-configuration-file.md
Add configuration for sm4-ctr.
> Add sm4 to tikv-configuration-file.md

- partitioned-table.md
Fixed some minor errors in SQL cases
> Fix typos in partitioned-table.md

- system-variables.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/37811
> system-varables: set default value of tidb_enable_rate_limit_action to OFF

- tikv-configuration-file.md
Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>
Supplement the doc on how to degrade TiKV - v6.3.0 with  `format-version: 2` to previous version, such as v6.1.0.
- This PR is translated from: https://github.com/pingcap/docs/pull/10538.
- Other reference link(s): N/A.
> [RaftEngine] Supplement the way of degrading RaftEngine with new format.

- sync-diff-inspector/sync-diff-inspector-overview.md
Signed-off-by: Leavrth <jianjun.liao@outlook.com>
- https://github.com/pingcap/tidb-tools/pull/675
- https://github.com/pingcap/tidb-tools/pull/674
- https://github.com/pingcap/tidb-tools/pull/664
> sync-diff-inspector: update sync_diff

- follower-read.md
> TiDB Operator v1.4 supports setting labels for TiDB

- faq/manage-cluster-faq.md
- tispark-overview.md
Close #11411 
- Other reference link(s): https://github.com/pingcap/tispark/pull/2533
> fix broken links in tispark-overview

- partitioned-table.md
- system-variables.md
- This PR is translated from: https://github.com/pingcap/docs/pull/10436
> Changed tidb_partition_prune_mode default from 'static' to 'dynamic'

- dm/dm-manage-source.md
- dm/dmctl-introduction.md
Close https://github.com/pingcap/docs-cn/issues/11439
> Remove the `operate-source update` command

- faq/tidb-faq.md
- tidb-architecture.md
- user-account-management.md
- Refine and update descriptions in `tidb-faq.md`, such as wording, missing info or links
- Update two related documents
> Note: The changes in this PR don't affect technical correctness.
> *: refine TiDB product basic FAQs descriptions

- system-variables.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/34990
> system-variable.md: add description for tidb_simplified_metrics

- basic-features.md
- experimental-features.md
Update basic features and experimental features for v6.3.0. The changes are listed as follows:
- 新增基本功能：
- Range COLUMNS 分区
- Range INTERVAL 分区
-  experimental 转 GA：
- JSON 类型
- JSON 函数
- EXCHANGE PARTITION 功能
- 提升多并发下的数据扫描性能
- 新增 experimental：
- Range INTERVAL 分区
- 元数据锁
- 添加索引加速
> update experimental features and basic features for 6.3

- _docHome.md
Fixed TiDB links on the Docs Home page.
> *. fix links on docs home page

- br/pitr-known-issues.md
Signed-off-by: Leavrth <jianjun.liao@outlook.com>
add a known issue
> log-backup: add known issue: azure or gcs first truncate

- production-deployment-using-tiup.md
- scale-tidb-using-tiup.md
- tiup/tiup-cluster.md
- tiup/tiup-component-cluster-deploy.md
- tiup/tiup-component-management.md
- tiup/tiup-mirror.md
- tiup/tiup-playground.md
- upgrade-tidb-using-tiup.md
> bump version

- _index.md
> v6.3: bump version for learning path

- cached-tables.md
- sql-statements/sql-statement-create-index.md
- tiflash/use-tiflash-mpp-mode.md
The copyable snippet in code block will be removed during processing markdown pages and `> {{copyable xxx}}` will be modified to `> >`. The following is an example:
> Remove copyable in code block

- resources/cdnfresh.txt
> add 6.3 to pdf

- backup-and-restore-using-dumpling-lightning.md
> trigger update

- _index.md
Added reference in TiDB learning path.
> learning path: add reference in TiDB learning path

- _index.md
Added reference in TiDB learning path for v6.3
> learning path: add reference in TiDB learning path for v6.3

- _index.md
Add reference in TiDB learning path for v6.1
> learning path: add reference in TiDB learning path for v6.1

- ecosystem-tool-user-guide.md
Corrected decriptions about lightning modes.
- Other reference link(s):https://github.com/pingcap/docs/pull/10540
> tools: corrected decriptions about lightning modes

- releases/release-notes.md
Add release date for each release according to [TiDB Release Timeline](https://docs.pingcap.com/tidb/dev/release-timeline).
- This PR is translated from: https://github.com/pingcap/docs/pull/10658
> Release notes: add release date

- releases/release-6.3.0.md
- This PR is translated from: https://github.com/pingcap/docs/pull/10631
> add avx2 description to 6.3 release notes

- tiup/tiup-component-dm-import.md
Make clear that this command is only used for upgrading DM v1.0 to later versions.
> tiup: add a notice to tiup dm import

- config-templates/complex-multi-instance.yaml
Fix the data dir of monitored instance from "/tidb-data-monitored-9100" to "/tidb-data/monitored-9100"
- This PR is translated from: https://github.com/pingcap/docs/pull/10684
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/3279
> Fix the data dir of monitored

- dm/dm-overview.md
- dumpling-overview.md
- explore-htap.md
- faq/manage-cluster-faq.md
- overview.md
- quick-start-with-tidb.md
- ticdc/ticdc-overview.md
- tidb-architecture.md
- tidb-binlog/tidb-binlog-overview.md
- tidb-lightning/tidb-lightning-overview.md
- tidb-monitoring-framework.md
Updated video size to make it fill the div automatically
> video: updated video size to make it fill the div automatically

- faq/manage-cluster-faq.md
Close https://github.com/pingcap/docs/issues/6540
> faq: correct description about TiDB versions

- tikv-configuration-file.md
change the location of `s3-multi-part-size` from causal-ts to backup
> backup: change the location for s3-multi-part-size

- dm/dm-ddl-compatible.md
Close https://github.com/pingcap/docs-cn/issues/11578
> Fix typo and table format in dm-ddl-compatible

- system-variables.md
sysvar: add a few sysvars to docs-cn
> sysvar: add 12 sysvars to docs-cn

- user-account-management.md
- 更新了‘忘记root密码’一栏的内容，使得操作更加清晰
- Other reference link(s): https://github.com/pingcap/docs-cn/commit/1344d306d7f920ec75b7fc5cd50239e19ae40f44
> update the Forgot root password

- hardware-and-software-requirements.md
Add RHE Linux 8 stream and AWS linux to software requirement doc
> Add RHE Linux 8 stream and AWS linux to software requirement doc

- system-variables.md
sysvar: add 3 sysvars
- This PR is translated from: https://github.com/pingcap/docs/pull/10566 https://github.com/pingcap/docs/pull/10549
> sysvar: add 3 sysvars

- performance-tuning-methods.md
> fix typos in performance tuning methods

- ticdc/ticdc-faq.md
Some FAQs in [TiCDC FAQ-Knowledge sharing](https://pingcap.feishu.cn/wiki/wikcnVPiFKmGFGOOqKLSOE5Y2sg) can be added to the official document site.
> ticdc: add three ticdc faqs

- develop/dev-guide-third-party-tools-compatibility.md
```
[2022-10-14T02:56:52.152Z] ! Paragraph ended before \hyperlink was complete.
[2022-10-14T02:56:52.152Z] <to be read again> 
[2022-10-14T02:56:52.152Z]                    \par 
[2022-10-14T02:56:52.152Z] l.19506 
[2022-10-14T02:56:52.152Z] 
[2022-10-14T02:56:52.152Z] pandoc: Error producing PDF
```
The docs-cn-merge pipeline fails due to the https://github.com/pingcap/docs-cn/commit/c77527f635a755e628a316289a54e0fe2fcbd3d7 commit. …
> Fix the docs-cn-merge pipeline failure issue

- tiup/tiup-cluster.md
> Add backup and restore content for tiup-cluster.md

- placement-rules-in-sql.md
- This PR is translated from: https://github.com/pingcap/docs/pull/10945
> remove tiflash and placement in sql incompatible description

- system-variables.md
sysvar: add 12 missing planner-related sysvars
- This PR is translated from: https://github.com/pingcap/docs/pull/10906
> sysvar: add 12 missing planner-related sysvars

- statistics.md
> Add white space after ANALYZE TABLE

- system-variables.md
sysvar: add a sysvar to v6.1
- Other reference link(s): https://github.com/pingcap/docs/pull/10906
> sysvar: add a sysvar to v6.1

- online-unsafe-recovery.md
Signed-off-by: Connor1996 <zbk602423539@gmail.com>
Fix tiup scale-in commands after online unsafe recovery
> Fix tiup scale-in commands after online unsafe recovery

- analyze-slow-queries.md
- enable-tls-between-clients-and-servers.md
- information-schema/information-schema-tidb-indexes.md
- This PR is translated from: https://github.com/pingcap/docs/pull/10808
> Fix format in TiDB INDEXES

- system-variables.md
refine document for the block_encryption_mode function
- This PR is translated from: https://github.com/pingcap/docs/pull/10862
> refine document for the block_encryption_mode function

- develop/dev-guide-sample-application-golang.md
- develop/dev-guide-sample-application-java.md
> Modify the recommended way as the first tab

- system-variables.md
> sysvar: add a sysvar

- best-practices/java-app-best-practices.md
- develop/dev-guide-connection-parameters.md
Change jdbc maxPerformance properties
The original description is inconsistent with the MySQL Connector/J 5.1 Developer Guide
Change jdbc maxPerformance properties
The original description is inconsistent with the MySQL Connector/J 5.1 Developer Guide
> Change jdbc maxPerformance properties

- three-data-centers-in-two-cities-deployment.md
According to @nolouch, using the default value of tolerant-size-ratio is sufficient so there is no need to configure it separately in the scenario of three data centers in two cities. 
> remove the info about configuring tolerant-size-ratio

- releases/release-6.3.0.md
- This PR is translated from: https://github.com/pingcap/docs/pull/10983
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/11779
> v6.3 release notes: Add HAProxy note

- placement-rules-in-sql.md
>  Fix format in advanced placement options

- experimental-features.md
- tidb-configuration-file.md
> add description for enable-table-lock

- develop/dev-guide-build-cluster-in-cloud.md
> [Update] remove cloud picture link in the doc

- TOC.md
- migrate-from-csv-files-to-tidb.md
- migrate-from-parquet-files-to-tidb.md
- migration-overview.md
A followup of v6.3: revert this commit https://github.com/pingcap/docs-cn/pull/11261/commits/23c2684ba70ea3095569bbf88fa20f604488c9ed
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/11261
> lightning: add doc for migrating parquet files

- dm/dm-faq.md
- tidb-lightning/troubleshoot-tidb-lightning.md
> add workaround for charset error when migrate data

- ecosystem-tool-user-case.md
- migration-tools.md
> ticdc: recommand user to use ticdc

- information-schema/information-schema-processlist.md
- This PR is translated from: https://github.com/pingcap/docs/pull/11104
> Update the processlist column information

- hardware-and-software-requirements.md
Fix OS info
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/11459
> Fix OS info

- releases/release-6.2.0.md
- releases/release-6.3.0.md
- system-variables.md
- This PR is translated from: https://github.com/pingcap/docs/pull/11100
> sysvar: correct sysvar information

- tiflash/create-tiflash-replicas.md
Signed-off-by: Wish <breezewish@outlook.com>
Add some instructions about how to sync TiFlash replica faster.
- Other reference link(s): master branch has a simplified process: https://github.com/pingcap/docs-cn/pull/11405
> [release-6.1] tiflash: Add instructions to improve replica sync performance

- releases/release-6.1.0.md
- releases/release-6.2.0.md
- releases/release-6.3.0.md
> release note: add the TiDB downloading info

- functions-and-operators/json-functions.md
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>
Add documents for a new function `json_storage_free`.
- This PR is translated from: https://github.com/pingcap/docs/pull/10943
- Other reference link(s): https://github.com/pingcap/tidb/issues/38517
> json: add document for json_storage_free

- data-type-json.md
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>
Remove the json path restrictions, as the TiDB doesn't have this restriction after 6.4.
- Other reference link(s): https://github.com/pingcap/docs/pull/11152
> remove json path restrictions

- hardware-and-software-requirements.md
Fix incorrect ngmonitoring port number. This file tiup/tiup-cluster-topology-reference.md is not modified because the content is already there.
- This PR is translated from: https://github.com/pingcap/docs/pull/11153
> fix ngm port

- exporting-grafana-snapshots.md
> Fix a link

- dashboard/dashboard-ops-deploy.md
`tiup ctl pd` must specify ctl version explicitly.
> dashboard: fix a pd-ctl command

- configure-placement-rules.md
- encryption-at-rest.md
- tiflash/tiflash-configuration.md
> add back tiflash sm4 encryption support

- system-variables.md
Add description for new variable and  alter scope of two modified variables
- Other reference link(s): https://github.com/pingcap/tidb/pull/38824
> planner: add description for plan cache variable

- best-practices/three-nodes-hybrid-deployment.md
- clinic/clinic-data-instruction-for-tiup.md
- dashboard/dashboard-ops-deploy.md
- enable-tls-between-components.md
- migrate-from-tidb-to-mysql.md
- pd-control.md
- replicate-data-to-kafka.md
- three-data-centers-in-two-cities-deployment.md
- ticdc/integrate-confluent-using-ticdc.md
- ticdc/manage-ticdc.md
- tidb-control.md
- tiflash/create-tiflash-replicas.md
- tiflash/tiflash-configuration.md
- tikv-control.md
- tiup/tiup-cluster.md
- troubleshoot-lock-conflicts.md
- troubleshoot-write-conflicts.md
- This PR is translated from: https://github.com/pingcap/docs/pull/11180, https://github.com/pingcap/docs/pull/11186
> add version to tiup ctl to make the command work

- releases/release-6.1.1.md
- releases/release-6.1.2.md
- releases/release-6.2.0.md
- releases/release-6.3.0.md
> update downloading info

- tidb-in-kubernetes.md
- tidb-operator-overview.md
ref: https://github.com/pingcap/docs/pull/11224
> fix: in k8s -> on k8s

- experimental-features.md
- statistics.md
- system-variables.md
> enable tidb_stats_load_sync_wait by default

- dm/task-configuration-file-full.md
extend routes are added in full task configuration to help users do the right configure.
> dm: update full doc about extend routes

- system-variables.md
add variables `tidb_analyze_partition_concurrency` and `tidb_merge_partition_stats_concurrency`
> add variables `tidb_analyze_partition_concurrency` and `tidb_merge_partition_stats_concurrency`

- scale-tidb-using-tiup.md
> Update TiFlash scale-in guidance.

- alert-rules.md
- This PR is translated from: https://github.com/pingcap/docs/pull/11013
> metrics: Add the PD_cluster_unhealthy_tikv_nums alert

- troubleshoot-lock-conflicts.md
troubleshoot: fix a metric name
> troubleshoot: fix a metric name

- .github/pull_request_template.md
> pull_request_template: add v6.5 

- clustered-indexes.md
- system-variables.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/38447
> clustered-indexes.md: change the system variable default value to ON

- troubleshoot-hot-spot-issues.md
Fix typo in troubleshoot-hot-spot-issues.md
> Fix typo in troubleshoot-hot-spot-issues.md

- mysql-compatibility.md
Use an unordered list at the beginning of MySQL Compatibility.
> Refine the style of MySQL Compatibility

- develop/dev-guide-third-party-tools-compatibility.md
> add sequelize section to Dev Guide 3rd party tools compatibility

- config-templates/complex-cdc.yaml
- config-templates/complex-mini.yaml
- config-templates/complex-tidb-binlog.yaml
- config-templates/complex-tiflash.yaml
- config-templates/complex-tispark.yaml
> Add aliases for configuration files

- explain-overview.md
- system-variables.md
sysvar: delete two sysvar that has been removed from code
tidb_auth_signing_cert
tidb_auth_signing_key
- Other reference link(s): https://github.com/pingcap/tidb/blob/release-6.4/sessionctx/variable/sysvar.go
> sysvar: delete two sysvar that has been removed from code

- system-variables.md
> Add a prerequisite before query "GENERAL_LOG"

- hardware-and-software-requirements.md
Update os supports for dmr versions
> Update os supports for dmr versions

- _index.md
- [x ] v6.4 (TiDB 6.4 versions)
> v6.4: update _index.md

- production-deployment-using-tiup.md
- scale-tidb-using-tiup.md
- tiup/tiup-cluster.md
- tiup/tiup-component-cluster-deploy.md
- tiup/tiup-component-management.md
- tiup/tiup-mirror.md
- tiup/tiup-playground.md
- upgrade-tidb-using-tiup.md
> tiup: bump version to 6.4

- br/pitr-known-issues.md
Signed-off-by: Leavrth <jianjun.liao@outlook.com>
> pitr: uncommenting the annotation in the known-issues: pitr truncate

- resources/cdnfresh.txt
> Update cdnfresh.txt for v6.4

- releases/release-6.1.0.md
- releases/release-6.2.0.md
- releases/release-6.4.0.md
> Remove "v" from release notes titles

- tiup/tiup-overview.md
- tiup/tiup-reference.md
remove arg -B in TiUP
- Other reference link(s): https://github.com/pingcap/tiup/pull/1698
> remove arg -B in tiup

- releases/release-6.3.0.md
> release-6.3.0.md: update the download link

- download-ecosystem-tools.md
> Keep the download description consistent with the product-community

- develop/dev-guide-build-cluster-in-cloud.md
- develop/dev-guide-create-table.md
- develop/dev-guide-sample-application-golang.md
- develop/dev-guide-sample-application-java.md
- develop/dev-guide-sample-application-spring-boot.md
- develop/dev-guide-tidb-crud-sql.md
- This PR is translated from: https://github.com/pingcap/docs/pull/11374
> Remove free sign, avoid effect the update of billing plan

- releases/release-6.4.0.md
This github issue is more relevant.
The previous github issue could cause confusion.  We will replace it with a new github issue. 
> replace github issue for FD-863

- configure-memory-usage.md
- system-variables.md
sysvar: add a note to disable tidb_enable_rate_limit_action
> sysvar: add a note to disable tidb_enable_rate_limit_action

- metadata-lock.md
> Update wording to make text more accurate

- releases/release-6.4.0.md
add ticdc release note fro https://github.com/pingcap/tiflow/pull/7504, split transaction and disable safeMode by default
- This PR is translated from:  
https://github.com/pingcap/tiflow/pull/7504
> add split transaction release note for ticdc

- faq/deploy-and-maintain-faq.md
- hardware-and-software-requirements.md
- multi-data-centers-in-one-city-deployment.md
- overview.md
A complement to https://github.com/pingcap/docs-cn/pull/12153
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/12153
> *: add annotation for localization

- releases/release-6.3.0.md
- This PR is translated from: https://github.com/pingcap/docs/pull/11477
> Fix incorrect description of a ticdc improvement in 6.3 RN

- migration-tools.md
Fix a term error: 
- Changed Local-backend to Physical Import Mode
- Changed TiDB-backend to Logical Import Mode
- Other reference link(s):https://github.com/pingcap/docs-cn/issues/12147
> lightning: fix a term error

- identify-slow-queries.md
Changed [tidb_enable_slow_log](https://docs.pingcap.com/zh/tidb/v6.4/system-variables#tidb_enable_slow_log) to [`tidb_slow_log_threshold`](/system-variables.md#tidb_slow_log_threshold)
> slow log: fix an error in slow log

- experimental-features.md
- tidb-lightning/tidb-lightning-physical-import-mode-usage.md
The disk quota feature goes GA.
> lightning: disk quota GA

- tidb-lightning/tidb-lightning-configuration.md
- tidb-lightning/tidb-lightning-physical-import-mode-usage.md
Docs change to make Lightning's 'disk-quota' function GA.
> lightning: docs change for 'disk-quota' GA

- experimental-features.md
- metadata-lock.md
- sql-statements/sql-statement-commit.md
- system-variables.md
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>
> enable metadata lock by default

- tikv-configuration-file.md
Signed-off-by: qupeng <qupeng@pingcap.com>
- Other reference link(s): https://github.com/tikv/tikv/pull/12839
> tikv: change cdc.min-ts-interval from 1s to 200ms

- sync-diff-inspector/sync-diff-inspector-overview.md
Update description about `sync-diff-inspector`'s password configuration for base64 encoded password.
- Other reference link(s): https://github.com/pingcap/tidb-tools/pull/688
> sync-diff: update passwd description

- configure-memory-usage.md
- experimental-features.md
- system-variables.md
- tidb-configuration-file.md
- troubleshoot-tidb-oom.md
> Add docs for global memory control GA

- TOC.md
- ecosystem-tool-user-case.md
- [x ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.
Hello, I have modified the translation of 适用 into 使用. According to the dictionary, the former means being suitable or application while the latter means to use, employ or apply. It seems that use case is a terminology that can be translatedd as y用例 or 使用案例. I've found the translation of 用例 on Microsoft's website but not sure if it is a machine translation. I've attached it for your reference. 
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE …
> improved Chinese translation

- tiflash/tiflash-supported-pushdown-calculations.md
Add new support tiflash pushdown functions: "->, ->>, json_extract"
> tiflash: support pushing down json extract

- tidb-configuration-file.md
Add configuration descriptions for `session-token-signing-cert` and `session-token-signing-key`.
> configuration: add configurations for signing-cert and signing-key

- TOC.md
- br/external-storage.md
> remove external storage from toc

- sql-statements/sql-statement-create-user.md
- This PR is translated from: https://github.com/pingcap/docs/pull/11564
> sql: fix statement bug

- system-variables.md
Signed-off-by: you06 <you1474600@gmail.com>
ref: pingcap/tidb#39361
Document the experimental feature `tidb_store_batch_size`.
> add doc for experimental variable tidb_store_batch_size

- follower-read.md
- system-variables.md
> tidb: update the description of closest-adaptive

- system-variables.md
> docs: add tidb_enable_amend_pessimistic_txn depreciation

- releases/release-6.1.3.md
> add a ticdc compatibility change to 6.1.3 RN

- ticdc/manage-ticdc.md
> fix incorrect default value of transaction atomicity

- releases/release-6.4.0.md
> add a ticdc compability change to 6.4 RN

- faq/sql-faq.md
> remote session level force priority

- system-variables.md
> update the support info of amending pessimistic txn

- functions-and-operators/string-functions.md
> tidb: update builtin string function

- statistics.md
- tidb-configuration-file.md
v5.3-v5.0: emphasize experimental for stats feedback
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/12165 https://github.com/pingcap/docs-cn/pull/12166
> v5.3-v5.0: emphasize experimental for stats feedback

- statistics.md
Update version description for statistics feedback, as a follow-up PR for #12167 
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/12167
> v5.3: update stats feedback description

- releases/release-6.4.0.md
The input is provided by @nongfushanquan.
> add the reason for changing the default value

- develop/dev-guide-use-follower-read.md
> tidb: update follower read guide

- pd-control.md
Delete 2 pd parameters that have been deleted in code
- This PR is translated from: https://github.com/pingcap/docs/pull/11644
> Delete 2 pd parameters that have been deleted in code

- ticdc/ticdc-sink-to-kafka.md
> add a title for best practices for better findability

- tiflash/tiflash-configuration.md
Delete deprecated tiflash configs
- This PR is translated from: https://github.com/pingcap/docs/pull/11646
> Delete deprecated tiflash configs

- best-practices/java-app-best-practices.md
- develop/dev-guide-connection-parameters.md
> update metric: CPS by instance

- system-variables.md
> change tidb_enable_gc_aware_memory_track default value to off

- ticdc/ticdc-sink-to-kafka.md
Add `compression` to TiCDC Kafka sink config.
> Add `compression` to TiCDC Kafka sink config

- functions-and-operators/encryption-and-compression-functions.md
> format: use the standard ASCII vertical bar in table

- _index.md
> index page: bump up to v6.5

- functions-and-operators/set-operators.md
- sql-statements/sql-statement-admin-checksum-table.md
- sql-statements/sql-statement-create-role.md
- sql-statements/sql-statement-drop-role.md
- sql-statements/sql-statement-grant-role.md
- sql-statements/sql-statement-revoke-role.md
- sql-statements/sql-statement-set-default-role.md
- sql-statements/sql-statement-table.md
> Update the command and output in SQL statements

- production-deployment-using-tiup.md
- scale-tidb-using-tiup.md
- tiup/tiup-cluster.md
- tiup/tiup-component-cluster-deploy.md
- tiup/tiup-component-management.md
- tiup/tiup-mirror.md
- tiup/tiup-playground.md
- upgrade-tidb-using-tiup.md
> TiUP bumpversion 6.5

- br/backup-and-restore-use-cases.md
- dm/quick-start-create-task.md
- pd-control.md
- quick-start-with-tidb.md
- ticdc/deploy-ticdc.md
- tidb-binlog/get-started-with-tidb-binlog.md
> v6.5: bump version for tools

- resources/cdnfresh.txt
> chore: update cdnfresh.txt for v6.5

- configure-placement-rules.md
> placement rules: add a role "voter"

- hardware-and-software-requirements.md
> Update OS info for v6.5

- ticdc/ticdc-manage-changefeed.md
`http://docs.pingcap.com/zh/tidb/stable/manage-ticdc` is 404.
> add aliases for manage-ticdc

- releases/release-5.1.5.md
> modify release notes 5.1.5

- releases/release-6.4.0.md
> v6.4: update download address

- br/br-snapshot-guide.md
> add aliases for br snapshot guide

- system-variables.md
sysvar: add type info and correct some other info
- This PR is translated from: https://github.com/pingcap/docs/pull/11273
> sysvar: add type info and correct some other info

- releases/release-6.1.0.md
- releases/release-6.5.0.md
- Add `summary` metadata for v6.5.0 & v6.1.0 release notes
- Refine wording, punctuation for v6.5.0
- Other reference link(s): https://docs.pingcap.com/zh/tidb/stable/release-6.5.0
> releases: update release notes wording, summary, punctuation

- tidb-configuration-file.md
Maintain consistency in the order and hierarchy of the temp-dir parameter with https://github.com/pingcap/tidb/blob/master/config/config.toml.example
- Other reference link(s): https://github.com/pingcap/tidb/blob/master/config/config.toml.example#L32
> tidb configuration file: adjust the position of temp-dir

- tiflash/tune-tiflash-performance.md
Signed-off-by: hehechen <awd123456sss@gmail.com>
Update tune-tiflash-performance.md.
> modify tune-tiflash-performance.md

- faq/sql-faq.md
- This PR is translated from: https://github.com/pingcap/docs/pull/10271
> FAQ: add a faq (blacklist a sql execution)

- sql-statements/sql-statement-alter-user.md
- sql-statements/sql-statement-create-user.md
> sql: fix ebnf diagram

- privilege-management.md
- system-variables.md
See the details in the issue
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/12150
> privileges: provide descriptions about 3 dynamic privileges

- ticdc/ticdc-sink-to-mysql.md
> fix cdc consistent config

- dashboard/dashboard-cluster-info.md
- tiup/tiup-command-status.md
- tiup/tiup-component-cluster-display.md
Make the status document more specific and add reference links.
> More verbose status docs

- mysql-compatibility.md
Added descriptions for each default value.
> mysql-compatibility: refined descriptions about lower_case_table_names

- time-to-live.md
- This PR is translated from:https://github.com/pingcap/docs/pull/12021
> ttl: improve seo

- auto-increment.md
- functions-and-operators/miscellaneous-functions.md
mention force and add 2 uuid functions
- This PR is translated from: https://github.com/pingcap/docs/pull/7629 https://github.com/pingcap/docs/pull/7502
> mention force and add 2 uuid functions

- tiflash/tune-tiflash-performance.md
> Correct the unit of tidb_max_tiflash_threads

- sql-statements/sql-statement-drop-stats.md
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>
I synchronize the syntax tree of drop stats with the newest one. It has two changes:
1. Allow drop the stats of multiple tables at the same time.
The `DROP STATS ... PARTITION ...` and `DROP STATS ... GLOBAL` syntax are deprecated, so I didn't update them to documents.
- Other …
> Synchronise the syntax tree of drop stats

- dashboard/dashboard-cluster-info.md
> dashboard: fix a typo in disk list

- releases/release-5.3.1.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/11407
> fix a typo in 5.3.1 RN

- resources/cdnfresh.txt
> chore: add the TiDB Cloud doc PDF to cdnfresh.txt

- enable-tls-between-components.md
> Update enable-tls-between-components and add TLS rotation description

- upgrade-tidb-using-tiup.md
Add a note that CPU must support the AVX2 command set.
> add notice of tiflash avx3

- tiflash/tiflash-overview.md
Add the description that to deploy TiFlash under the Linux AMD64 architecture, the CPU must support AVX2 instruction sets
- This PR is translated from: https://github.com/pingcap/docs/pull/10635
> add description of avx2 in tiflash overview

- online-unsafe-recovery.md
Clarify the requirement of unsafe recovery.
> Clarify unsafe recovery cmd input requirements

- develop/dev-guide-choose-driver-or-orm.md
- The auto-increment IDs can be globally unique in TiDB v6.4.0 and the description "但无法保证全局自增" is outdated.
- Maintaining two copies of the same content might bring additional costs. When there are changes needed in the MySQL Compatibility doc, it would be easy to forget to update the same information in `dev-guide-choose-driver-or-orm.md`.
- Remove detailed description of MySQL compatibility from `dev-guide-choose-driver-or-orm.md` and use the link instead.
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND …
> develop: remove details of mysql compatibility

- basic-features.md
Refine the note in basic-features.md to lower the exphasis level.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/12687
> basic-features: refine note

- maintain-tidb-using-tiup.md
To fix the incorrect indentation in "config".
- This PR is translated from: https://github.com/pingcap/docs/pull/7884
> tiup: correct indentation in config

- hardware-and-software-requirements.md
- This PR is translated from: https://github.com/pingcap/docs/pull/10310
> hardware-and-software-requirements: Correct CentOS info

- sql-statements/sql-statement-load-data.md
- This PR is translated from: https://github.com/pingcap/docs/pull/7916
> sql-statement-load-data: update compatibility info

- command-line-flags-for-tidb-configuration.md
- dm/dm-overview.md
- dumpling-overview.md
- explore-htap.md
- faq/manage-cluster-faq.md
- overview.md
- quick-start-with-tidb.md
- tidb-architecture.md
- tidb-binlog/tidb-binlog-overview.md
- tidb-lightning/tidb-lightning-overview.md
- tidb-monitoring-framework.md
- user-account-management.md
Updated poster links for all videos.
> *: updated video poster links

- faq/manage-cluster-faq.md
- tidb-architecture.md
Updated video links.
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/12815/files
> *: correct video links

- _index.md
Added more links in the Reference section in Learning Path.
> learning path: add more popular links to Reference

- dm/dm-worker-intro.md
tidb user needs to create dm_meta database
> Modify downstream database permissions

- tidb-lightning/tidb-lightning-configuration.md
improve wording for the description of config `on-duplicate`
> lightning: improve wording for the description of config on-duplicate

- optimizer-hints.md
Signed-off-by: AilinKid <314806019@qq.com>
> optimizer: fix optimizer hint identifier

- tiup/tiup-component-cluster-check.md
[TiUP v1.9.0](https://github.com/pingcap/tiup/releases/tag/v1.9.0) supports checking the yaml file before scale out. This feature is very useful and should be documented.
- This PR is translated from: https://github.com/pingcap/docs/pull/12273
> [TiUP] add support check the yaml file before scale out

- two-data-centers-in-one-city-deployment.md
update description about contact support to reduce user confusion.
> dr: update support contact

- metadata-lock.md
Translate from https://github.com/pingcap/docs/pull/12305
Add link to CHANGE COLUMN from Metadata Lock.
- This PR is translated from: https://github.com/pingcap/docs/pull/12305
> ALTER TABLE .. CHANGE COLUMS is affected by metadata lock

- pd-configuration-file.md
Signed-off-by: Sen Han <00hnes@gmail.com>
Keep the layer of flow-round-by-digit consistent with [config.go](https://github.com/tikv/pd/blob/40b6daffec969295544ab082891a01d67ade09f1/server/config/config.go#L1201).
> fix flow-round-by-digit in pd cfg docs

- releases/release-6.0.0-dmr.md
- releases/release-6.2.0.md
This PR adds a note to v6.0 and v6.2 release notes to let users know their doc locations.
> v6.0 and v6.2: add a note for docs archiving

- shard-row-id-bits.md
Update shard-row-id-bits description for non-clustered-index
> sql: Update shard-row-id-bits description for non-clustered-index

- system-variables.md
This adds units wherever possible, and removes it from the body description if redundant.
This helps improve readability and slightly reduce risk of misconfiguration.
- This PR is translated from: https://github.com/pingcap/docs/pull/6622
> system-variables: Add units wherever possible

- .github/workflows/media.yml
- scripts/upload.py
> chore: stop uploading media and pdf to aws 

- dynamic-config.md
Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>
Add docs on the dynamic modification supports to `raftstore.store-io-pool-size`.
Ref: https://github.com/tikv/tikv/issues/13964
> tikv: support dynamic modifications on `raftstore.store-io-pool-size`

- hardware-and-software-requirements.md
- releases/release-6.3.0.md
- tiflash/tiflash-overview.md
- upgrade-tidb-using-tiup.md
Add the minimum requirement when deploying TiFlash in Linux ARM64 architecture.
> Add minimum requirement in arm when deploying TiFlash

- tiflash/create-tiflash-replicas.md
A note in [Speed up TiFlash replication](https://github.com/pingcap/docs/blob/release-6.1/tiflash/create-tiflash-replicas.md#speed-up-tiflash-replication) seems missing in the Chinese in v6.1.
- Other reference link(s): https://github.com/pingcap/docs/blob/release-6.1/tiflash/create-tiflash-replicas.md#speed-up-tiflash-replication
> tiflash: add a missing note

- sync-diff-inspector/sync-diff-inspector-overview.md
Add a description for the new parameter `skip-non-existing-table`, which is used to skip validation for tables that do not exist upstream or downstream.
- Other reference link(s):https://github.com/pingcap/tidb-tools/pull/693
> sync-diff: add description for the new parameter `skip-non-existing-table`

- basic-features.md
Refine TiDB features document:
- Abbreviate “实验特性” as "E" to save table space.
- Delete DMR version info before v6.5.
- Add a note to inform users that even if a feature is GA in a DMR version, they are not recommended to use that DMR version for the feature.
> Refine TiDB features document

- dm/dm-precheck.md
- dm/monitor-a-dm-cluster.md
- dm/task-configuration-file-full.md
- Other reference link(s):https://github.com/pingcap/docs/pull/12272
> integrate lightning into DM

- system-variables.md
Signed-off-by: you06 <you1474600@gmail.com>
> sysvar: stabilize `tidb_store_batch_size`

- explain-mpp.md
- system-variables.md
> update system-variables.md: add `mpp_version` and `mpp_exchange_compression_mode`

- sql-prepared-plan-cache.md
Update document to add plan cache diagnostics and some examples for v6.6
> planner: update docs related to plan cache

- releases/release-6.4.0.md
> fix a typo in 6.4.0 release notes

- as-of-timestamp.md
- develop/dev-guide-use-stale-read.md
- stale-read.md
- tidb-external-ts.md
Signed-off-by: hehechen <awd123456sss@gmail.com>
Update stale_read doc since TiFlash supports stale read.
> Update stale_read doc for the support of TiFlash

- dm/dm-handle-alerts.md
Enhance description about error triggering condition
> dm: enhance description about error triggering condition

- ticdc/ticdc-sink-to-kafka.md
ref https://github.com/pingcap/tiflow/pull/8154
> ticdc: add `required-acks` configuration

- faq/deploy-and-maintain-faq.md
Fix typo in `faq/deploy-and-maintain-faq.md` and use `ZooKeeper` instead of `zookeeper`.
> fix typo in Deployment FAQs

- tidb-lightning/tidb-lightning-configuration.md
> lightning: support compression when sending kv pairs to tikv

- tikv-configuration-file.md
Add a configuration item `raftstore.report-min-resolved-ts-interval` in TiKV configuration file.
`raftstore.report-min-resolved-ts-interval` is introduced in https://github.com/tikv/tikv/pull/12157 (on Mar 17, 2022) and the item applies to TiDB v6.1 and later versions. …
> tikv: add raftstore.report-min-resolved-ts-interval

- tiup/tiup-component-dm-patch.md
The tidb version used in the example should be 5.3.0, not 5.4.0. See the following code example:
```
Release Version: v5.3.0
Git Commit Hash: 20626babf21fc381d4364646c40dd84598533d66
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-29 08:29:49
Go Version: go version go1.16.4 linux/amd64
```
> tiup&dm: update a wrong tidb version

- faq/backup-and-restore-faq.md
Signed-off-by: 3pointer <luancheng@pingcap.com>
Add a section describing how to quickly recovering data in the case of misoperations.
> add backup faq for flashback

- best-practices/three-nodes-hybrid-deployment.md
- clinic/clinic-data-instruction-for-tiup.md
- dashboard/dashboard-ops-deploy.md
- enable-tls-between-components.md
- migrate-from-tidb-to-mysql.md
- pd-control.md
- replicate-data-to-kafka.md
- scale-tidb-using-tiup.md
- three-data-centers-in-two-cities-deployment.md
- ticdc/deploy-ticdc.md
- ticdc/integrate-confluent-using-ticdc.md
- ticdc/ticdc-changefeed-overview.md
- tidb-control.md
- tiflash/create-tiflash-replicas.md
- tiflash/tiflash-configuration.md
- tikv-control.md
- tiup/tiup-cluster.md
- troubleshoot-lock-conflicts.md
- troubleshoot-write-conflicts.md
- It's not clear whether the `<cluster-version>` placeholder contains `v` or not.
- To make it more accurate, this PR replaces `tiup ctl:<cluster-version>` with `tiup ctl:v<CLUSTER_VERSION>`.
> update tiup ctl:<version> to tiup clt:v<version>

- grafana-tidb-dashboard.md
This PR lists these key metrics using H3 instead of list.
Close #12312 
> TiDB Monitoring Metrics: update key metrics from list to headings

- ticdc/ticdc-changefeed-config.md
- ticdc/ticdc-sink-to-kafka.md
Add experimental warning for TiCDC scale out feature.
> TiCDC scale out: experimental feature

- develop/dev-guide-build-cluster-in-cloud.md
Update the step for Serverless Tier cluster creation.
- This PR is translated from: https://github.com/pingcap/docs/pull/12082
> cloud: update quick start for Serverless Tier cluster creation

- grafana-tidb-dashboard.md
- releases/release-6.5.0.md
- sql-statements/sql-statement-alter-table.md
- sql-statements/sql-statement-create-table.md
- system-variables.md
- time-to-live.md
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>
We have made some modification for the TTL:
1. Remove the system variable `tidb_ttl_job_run_interval`
2. Add a table option `ttl_job_interval`
3. Add some metrics about the distributed execution
- This PR is translated from: https://github.com/pingcap/docs/pull/12318
> update document about TTL

- tikv-configuration-file.md
Remove the note "TiDB Dashboard will have a display error" from the description of `grpc-compression-type`.
> tikv config: remove note of grpc-compression-type

- tiflash/tiflash-configuration.md
To keep it consistent with other configuration files, use abbreviation (info, warn) as value options of logger.level in tiflash.toml.
- This PR is translated from: https://github.com/pingcap/docs/pull/12537
> TiFlash config: fix the value options of logger.level

- sql-statements/sql-statement-explain.md
`EXPLAIN FOR CONNECTION` is used to get the execution plan of the currently executed SQL query or the last executed SQL query in a connection.
Fix the compatibility to make it consistent with https://github.com/pingcap/tidb/pull/10030
```
Differences with MySQL EXPLAIN FOR
If one connection is sleeping, query for query plan for that connection will get nothing in MySQL. However, in this PR, query play for last query will be returned.
Side effect of 1., EXPLAIN FOR CONNECTION <id of this connection> will get error in MySQL, but will get query plan of last query in this PR.
If one without ProcessPriv queries plan for another user's connection, MySQL won't return error if that connection does not running any queries, however, in this PR, an error will always returns, even if that connection …
```
> explain for connection: fix the compatibility with MySQL

- tikv-configuration-file.md
This PR changes the default values of rocksdb.defaultcf.block-size and rocksdb.writecf.block-size to `16KB`
> update default value of block-size

- tiunimanager/tiunimanager-manage-clusters.md
Remove redundant character in TiUniManager
> TiUniManager: remove redundant character

- br/backup-and-restore-overview.md
- br/backup-and-restore-storages.md
- br/br-incremental-guide.md
- br/br-pitr-manual.md
- br/br-snapshot-guide.md
- br/use-br-command-line-tool.md
- dumpling-overview.md
- migrate-aurora-to-tidb.md
- migrate-large-mysql-shards-to-tidb.md
- migrate-large-mysql-to-tidb.md
- sql-statements/sql-statement-backup.md
- sql-statements/sql-statement-restore.md
- ticdc/ticdc-sink-to-cloud-storage.md
- tidb-lightning/tidb-lightning-command-line-full.md
- tidb-lightning/tidb-lightning-configuration.md
- tidb-lightning/tidb-lightning-data-source.md
- tidb-lightning/tidb-lightning-distributed-import.md
- tidb-lightning/tidb-lightning-logical-import-mode-usage.md
- tidb-lightning/tidb-lightning-overview.md
- tidb-lightning/tidb-lightning-physical-import-mode-usage.md
add session-token to external storage url
Now we use the iam user with its access key id and secret access key to access s3. But the best practice from aws is using the iam role with its access ket id, secret access key and session token to access s3. Because the session token is time-limited. …
> lightning/br/dumpling: add session-token to external storage url

- tikv-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13077
> block-size default value change

- upgrade-tidb-using-tiup.md
Move compatibility changes to a more noticeable position in upgrade guide.
- This PR is translated from:https://github.com/pingcap/docs/pull/12408
> upgrade: move compatibility changes to a more noticeable position

- faq/sql-faq.md
- privilege-management.md
This PR fixes two issues:
- issue 1: https://github.com/pingcap/docs-cn/issues/11670. Reference: https://docs.pingcap.com/zh/tidb/stable/optimistic-transaction#:~:text=%E8%87%AA%20v3.0.8%20%E5%BC%80%E5%A7%8B%EF%BC%8CTiDB%20%E9%9B%86%E7%BE%A4%E9%BB%98%E8%AE%A4%E4%BD%BF%E7%94%A8%E6%82%B2%E8%A7%82%E4%BA%8B%E5%8A%A1%E6%A8%A1%E5%BC%8F%E3%80%82
- issue 2: six dynamic privileges are missing in the user doc and should be documented …
> sql: add missing dynamic privileges and update optm lock version

- _index.md
update _index.md for v6.6
- This PR is translated from: https://github.com/pingcap/docs/pull/12584
> update _index.md for v6.6

- dashboard/dashboard-statement-details.md
- dashboard/dashboard-user.md
> Add priviledge info for dashboard-statement-details.md

- resources/cdnfresh.txt
> Update cdnfresh.txt for v6.6

- partitioned-table.md
Fix a wrong link in partitioned-table.md.
> Fix a wrong link in partitioned-table.md

- releases/release-6.5.0.md
> update download link for v6.5

- .github/workflows/flush.yaml
- resources/cdnfresh.txt
> chore: Update pdf list and flush workflow

- tiflash/troubleshoot-tiflash.md
Some descriptions in troubleshooting tiflash are outdated and should be updated for better troubleshooting efficiency.
> tiflash: update some description in troubleshooting

- best-practices/java-app-best-practices.md
- develop/dev-guide-choose-driver-or-orm.md
- develop/dev-guide-connection-parameters.md
- faq/tidb-faq.md
- tispark-overview.md
- Update URLs to use Connector/J 8.0 docs instead of 5.1
- Correct naming to "MySQL Connector/J" in a few places.
- Update the status of the EOF bug ( see https://bugs.mysql.com/bug.php?id=106252 )
- This PR is translated from: https://github.com/pingcap/docs/pull/11916
> Update JDBC information

- develop/dev-guide-connect-to-tidb.md
There are two official command-line clients for MySQL, both open-source and released by the Oracle MySQL team.
1. MySQL Client (`mysql`), which is part of the MySQL Server code base, but can be installed separately via `yum install mysql` on most YUM based linux distributions. With [the offical YUM repo](https://dev.mysql.com/doc/refman/8.0/en/linux-installation-yum-repo.html) this becomes `yum install mysql-community-client`. This client is written in C and has existed for as long as MySQL does.
2. MySQL Shell (`mysqlsh`), which is a separate code base and can be installed separately. This is a newer tool and supports SQL, but also JS and Python. It has a more modern code base and is more extendable than the 'old' client.
It looks like these …
> Correct MySQL Shell/Client section

- .github/pull_request_template.md
chore: update pr template for v7.0
- This PR is translated from: https://github.com/pingcap/docs/pull/12627
> chore: update pr template for v7.0

- config-templates/complex-mini.yaml
- config-templates/simple-mini.yaml
- minimal-deployment-topology.md
update tidb minimal topology from 3 to 2
> *: update tidb minimal topology from 3 to 2

- online-unsafe-recovery.md
Use a numbered procedure for "Step 3. Check the consistency of data and index (not required for RawKV)"
- This PR is translated from: https://github.com/pingcap/docs/pull/12618
> online unsafe recovery: use a numbered procedure for step 3

- best-practices/three-dc-local-read.md
Update three-dc-local-read.md.
After https://github.com/pingcap/tidb/pull/28033/files merged, need to set tidb_replica_read as closest-replicas for local read.
> three-dc-local-read: set tidb_replica_read as closest replicas

- tiup/tiup-mirror.md
Update tiup mirror documentation
Closes https://github.com/pingcap/docs/issues/7362
Closes https://github.com/pingcap/tiup/issues/1304
- This PR is translated from: https://github.com/pingcap/docs/pull/7367
> tiup-mirror: Extend and update

- dr-multi-replica.md
Fix the toml format in dr-multi-replica.md
Preview:
> fix format and admonitions in dr-multi-replica

- minimal-deployment-topology.md
A presales colleague mentioned that our docs does not clearly specify the minimal storage requirement for pd and tidb, which makes readers confused.
> add minimal storage for pd and tidb

- alert-rules.md
Keep the rule consistent with https://github.com/pingcap/tidb/blob/435dc5849f5d2f32bf52bc835df9bb585809ae79/infoschema/metric_table_def.go#L1368-L1372
> alert rule: fix the rule of TiKV_scheduler_command_duration_seconds

- releases/release-6.5.0.md
- ticdc/ticdc-overview.md
1. add bidirectional replication in cdc overview
2. fix 6.5.0 release notes
> fix cdc overview and some release notes

- auto-random.md
https://github.com/pingcap/tidb/pull/38617 supports defining `AUTO_RANDOM` on the first column in a composite clustered primary key.
- Other reference link(s): https://github.com/pingcap/tidb/pull/38617
> auto-random: support composite clustered primary key

- .github/workflows/flush.yaml
- resources/cdnfresh.txt
- remove 6.3 from pdf list
- only flush pdf on sundays.
> chore: change pdf list; change pdf update date

- sql-plan-management.md
> planner: supply privilege  description binding need

- config-templates/complex-cdc.yaml
Add some cdc configs to the `server_configs` part so that users know they can configure cdc para in this part as well, besides `cdc_servers`.
- This PR is translated from: https://github.com/pingcap/docs/pull/12705
> config: add important cdc configs to server_configs

- choose-index.md
Clarifed descriptions about TableReader.
> index: clarifed descriptions about TableReader

- system-variables.md
This PR fixes the issue that some variable names have a gray background and some do not.
> unify the format of system variable titles

- dm/task-configuration-file-full.md
Close https://github.com/pingcap/docs-cn/issues/10737
> dm: add a link to dm precheck for better user experience

- ticdc/ticdc-alert-rules.md
> update description of cdc_checkpoint_high_delay

- grafana-tidb-dashboard.md
- This PR is translated from: close https://github.com/pingcap/docs-cn/issues/8772
- Other reference link(s): edited by https://github.com/pingcap/tidb/pull/20401
> grafana-tidb-dashboard: update DDL related metrics

- privilege-management.md
添加关于 `SUPER` 权限的说明。
- Other reference link(s): close https://github.com/pingcap/docs-cn/issues/13145
> Add description about `SUPER` privilege

- ticdc/ticdc-sink-to-mysql.md
Add note about `/path` for the MySQL Sink of TiCDC
- This PR is translated from: https://github.com/pingcap/docs/pull/12370
> ticdc-sink-to-mysql: add note about path

- sql-statements/sql-statement-update.md
sql: update incorrect mysql compatibility info
> sql: update incorrect mysql compatibility info

- encryption-at-rest.md
Add more detailed explanation about how to enable tiflash data encryption.
> add more explanation about tiflash encryption

- partition-pruning.md
- partitioned-table.md
- Uppercase function names
- Add `()` to indicate it is a function
- Add link to docs
- This PR is translated from: https://github.com/pingcap/docs/pull/11894
> partitioning: change formatting

- tidb-resource-control.md
> resource_control: fix rfc link

- command-line-flags-for-tidb-configuration.md
`proxy-protocol-fallbackable` is introduced in TiDB v6.5.1
- Other reference link(s): https://github.com/pingcap/tidb/pull/41393
> tidb: add proxy-protocol-fallbackable

- information-schema/client-errors-summary-by-host.md
- information-schema/client-errors-summary-by-user.md
- information-schema/client-errors-summary-global.md
- information-schema/information-schema-character-sets.md
- information-schema/information-schema-collation-character-set-applicability.md
- information-schema/information-schema-columns.md
- information-schema/information-schema-deadlocks.md
- information-schema/information-schema-metrics-tables.md
- information-schema/information-schema-partitions.md
- information-schema/information-schema-referential-constraints.md
- information-schema/information-schema-sequences.md
- information-schema/information-schema-session-variables.md
- information-schema/information-schema-slow-query.md
- information-schema/information-schema-table-storage-stats.md
- information-schema/information-schema-tidb-servers-info.md
- information-schema/information-schema-tidb-trx.md
- information-schema/information-schema-tiflash-replica.md
- information-schema/information-schema-tikv-region-peers.md
- information-schema/information-schema-tikv-store-status.md
- information-schema/information-schema-user-privileges.md
- information-schema/information-schema-views.md
Update the format, command, and output of some information schemas according to TiDB v6.5.0
> update the format, command, and output of information schemas

- develop/dev-guide-sample-application-spring-boot.md
Update the version of JPA to the latest stable version
> [Update] new version of JPA adaption

- pd-control.md
Close #11744 
Updated the jq options for the region check command in the pd-control.md file.
- This PR is translated from: https://github.com/pingcap/docs/pull/12808
> pd control: use jq for region check command

- troubleshoot-lock-conflicts.md
The usage of tidb-ctl is out-of-date.
> fix the usage of tidb-ctl decoder

- pd-control.md
Close #10690 
`service-gc-safepoint` is introduced in https://github.com/tikv/pd/pull/2797
```
~$ tiup ctl:v6.5.0 pd service-gc-safepoint
Starting component `ctl`: /home/.tiup/components/ctl/v6.5.0/ctl pd service-gc-safepoint
{
"service_gc_safe_points": [
{
"service_id": "gc_worker",
"expired_at": 9223372036854775807,
"safe_point": 439923410637160448
}
],
"gc_safe_point": 0
}
```
For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRI …
> pd control: add service-gc-safepoint command

- dumpling-overview.md
Fix format in dumpling-overview.md
- This PR is translated from: https://github.com/pingcap/docs/pull/12892
> dumpling: fix format

- dumpling-overview.md
Most rds do not allow reload permission, so add necessary instructions
> add some desc

- data-type-json.md
> br: restore json type

- partitioned-table.md
> partitioned-table: fix a command

- ticdc/ticdc-open-api.md
- ticdc/ticdc-sink-to-kafka.md
> add encode password description for ticdc doc

- partitioned-table.md
> fix exchange partition

- tikv-configuration-file.md
Enable log recycling by default.
- This PR is translated from: https://github.com/pingcap/docs/pull/12869
> [TiKV] Enable log recycling by default.

- sql-statements/sql-statement-show-config.md
> sql: update the doc about show-config

- system-variables.md
- tiflash/tiflash-supported-pushdown-calculations.md
> tiflash: add docs about null-aware semi join push down to tiflash

- system-variables.md
Add the doc for `tidb_load_based_replica_read_threshold`.
- Other reference link(s): pingcap/tidb#41664
> add doc for load-based replica read variable

- releases/release-6.6.0.md
- tidb-lightning/tidb-lightning-configuration.md
> lightning: set compress-kv-pairs as experimental

- alert-rules.md
miss-peer-region-count is correct .
fix rule of PD_miss_peer_region_count
> fix rule of PD_miss_peer_region_count

- functions-and-operators/operators.md
- functions-and-operators/string-functions.md
One page already listed `SOUNDS LIKE` as unsupported, while it was listed as supported on another page.
MySQL 8.0.32:
```
sql> SELECT "FOO" SOUNDS LIKE "FOO";
+-------------------------+
| "FOO" SOUNDS LIKE "FOO" |
+-------------------------+
|                       1 |
+-------------------------+
1 row in set (0.0009 sec)
sql> SELECT SOUNDEX("FOO");
+----------------+
| SOUNDEX("FOO") |
+----------------+
| F000           |
+----------------+
1 row in set (0.0005 sec)
sql> SELECT VERSION();
+-----------+
| VERSION() |
+-----------+
| 8.0.32    |
+-----------+
1 row in set (0.0003 sec)
```
TiDB:
```
sql> SELECT "FOO" SOUNDS LIKE "FOO";
ERROR: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column …
```
> functions-and-operators: Correct support for SOUNDS LIKE

- tiflash/tiflash-configuration.md
Add three tiflash configurations.
> add TiFlash spill doc

- auto-increment.md
- mysql-compatibility.md
As the title says.
https://github.com/pingcap/tidb/pull/42305
> *: update document about auto-increment column must be key constraint

- dynamic-config.md
- tiflash/create-tiflash-replicas.md
- tikv-configuration-file.md
...to server.snap-io-max-bytes-per-sec.
https://github.com/tikv/tikv/pull/14275
> *: rename server.snap-max-write-bytes-per-sec

- tidb-resource-control.md
> resource_control: fix resource group rfc link

- system-variables.md
Change the variable description according to the feature change in v7.0.
> *: add a note to the `tidb_rc_read_check_ts` system variable

- TOC.md
- system-variables.md
- tiflash/tiflash-spill-disk.md
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/13342
> add TiFlash spill to disk doc

- tikv-configuration-file.md
Add a new configuration `raft-engine.prefill-for-recycle` in TiKV for supporting to make log recycling effective when starting in cold state.
> [TiKV] Introduce `raft-engine.prefill-for-recycle` configuration.

- releases/release-6.5.1.md
For v6.5.1, the batch update support for TiCDC is not provided. 
> release-6.5.1: remove batch update support description for TiCDC

- dm/task-configuration-file-full.md
https://github.com/pingcap/tiflow/issues/8654 add configurations for newly added lightning kv configurations
- Other reference link(s): https://github.com/pingcap/tiflow/pull/8653
> dm: add newly added lightning kv configurations

- tiflash/tiflash-spill-disk.md
- This PR is translated from: https://github.com/pingcap/docs/pull/13025
> tiflash-spill-disk: make SQL code stacked

- sql-plan-replayer.md
- system-variables.md
update plan replayer continuous capture feature
> update plan replayer continuous capture feature

- sql-plan-replayer.md
related to https://github.com/pingcap/docs-cn/pull/13332
- Fix heading levels to align with other headings.
- Fix a wrong anchor link.
> fix heading levels and wrong anchor link

- sql-statements/sql-statement-alter-table.md
- The old example didn't have a table name, causing it to always return errors in both TiDB and MySQL.
- The old example didn't work in MySQL.
- This PR is translated from: https://github.com/pingcap/docs/pull/12314
> sql-statement-alter-table: Beter example for schema dependency

- clustered-indexes.md
- shard-row-id-bits.md
- troubleshoot-hot-spot-issues.md
1. The change in default value for [`tidb_enable_clustered_index`](https://docs.pingcap.com/tidb/stable/system-variables#tidb_enable_clustered_index-new-in-v50) wasn't propagated to all docs as now non-integer PK's will also use a clustered index by default
2. A table without a primary key is not a good example.
3. Add links between related docs
- This PR is …
> Update docs of SHARD_ROW_ID_BITS

- _index.md
- dashboard/dashboard-user.md
- develop/dev-guide-third-party-support.md
- dm/task-configuration-file-full.md
- migrate-large-mysql-shards-to-tidb.md
- migrate-small-mysql-shards-to-tidb.md
- ticdc/ticdc-changefeed-config.md
- tidb-lightning/tidb-lightning-configuration.md
- tiflash/tiflash-configuration.md
- This PR is translated from:https://github.com/pingcap/docs/pull/13057
> *: update absolute links for learning path and others

- README.md
- resources/cdnfresh.txt
> *: update readme and pdf refresh list for 7.0

- ticdc/ticdc-avro-protocol.md
> cdc add description about avro float incompatible change

- sql-statements/sql-statement-load-data.md
- sql-statements/sql-statement-operate-load-data-job.md
- sql-statements/sql-statement-show-load-data.md
as tittle
- Other reference link(s):https://github.com/pingcap/docs/pull/12959
> migration: add note about experimental feature for sql-statement-load-data

- production-deployment-using-tiup.md
- scale-tidb-using-tiup.md
- tiup/tiup-cluster.md
- tiup/tiup-component-cluster-deploy.md
- tiup/tiup-component-management.md
- tiup/tiup-mirror.md
- tiup/tiup-playground.md
- upgrade-tidb-using-tiup.md
> bump tiup version to v7.0

- LICENSE
- README.md
Update the `LICENSE` to [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/)
- This PR is translated from: https://github.com/pingcap/docs/pull/13045
> Update the LICENSE

- br/backup-and-restore-use-cases.md
- dm/quick-start-create-task.md
- pd-control.md
- quick-start-with-tidb.md
- ticdc/deploy-ticdc.md
- tidb-binlog/get-started-with-tidb-binlog.md
> bump tool versions for v7.0

- basic-features.md
as title.
- This PR is translated from: https://github.com/pingcap/docs/pull/13047
> *: update basic features for 7.0

- best-practices/java-app-best-practices.md
- develop/dev-guide-connection-parameters.md
> [Update] tomcat-jdbc version update

- releases/release-6.6.0.md
- releases/release-7.0.0.md
as title.
will delete 7.0 release notes after cherrying-pick to 6.6
- This PR is translated from:https://github.com/pingcap/docs/pull/13070/files
> add highlight links to 7.0

- resources/cdnfresh.txt
> chore: Update cdnfresh.txt for k8s 1.3

- migration-tools.md
- tidb-lightning/troubleshoot-tidb-lightning.md
- avoid wide table
- `lighting` -> `lightning`
- Fix https://github.com/pingcap/docs-cn/issues/13392
- This PR is translated from:https://github.com/pingcap/docs/pull/9580
> migration-tools: avoid wide table

- time-to-live.md
> TTL: fix SQL statement

- .github/pull_request_template.md
chore: update pr template for v7.1
- This PR is translated from: https://github.com/pingcap/docs/pull/13105
> chore: update pr template for v7.1

- upgrade-tidb-using-tiup.md
> bump version in upgrade guide

- tidb-lightning/tidb-lightning-configuration.md
> lightning: update descriptions of some parameters

- faq/sql-faq.md
Add the missing `DELAYED` priority
```
sql> SELECT HIGH_PRIORITY 1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.0014 sec)
sql> SELECT LOW_PRIORITY 1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.0004 sec)
sql> SELECT DELAYED 1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.0004 sec)
```
see also: https://github.com/pingcap/tidb/blob/1e0956d5ba41182e603295e02ae8f767d62979e4/distsql/request_builder.go#L257-L267  …
> sql-faq: add missing DELAYED priority

- .github/ISSUE_TEMPLATE/config.yml
Direct users to AskTUG when they try to open a new issue.
The following is an example in pingcap/tidb repo.
> update issue template chooser

- basic-features.md
- [] master (the latest development version)
- [] v6.6 (TiDB 6.6 versions)
> fix the wrong description of the dump tool

- system-variables.md
The scope of these two variables (tidb_enable_gogc_tuner and tidb_gogc_tuner_threshold) is global acturally.
> fix the scope of `tidb_enable_gogc_tuner` and `tidb_gogc_tuner_threshold`

- metrics-schema.md
For line 119, the cause and the effect should appear together in Chinese so the first sentence is semantically incomplete, and it will be better to remove "因为". For line 147, "指” is more formal than "是“ in written language.
- This PR is translated from: https://docs.pingcap.com/zh/tidb/stable/metrics-schema#metrics-schema …
> improved-translation-metrics-schema.md

- releases/release-6.6.0.md
- sql-prepared-plan-cache.md
> planner: supply description about plan cache supporting limit

- sql-statements/sql-statement-create-index.md
List some known incompatible situation for mutli-valued index and tools.
> add description about the compatibility with tools for multi-valued index

- tidb-configuration-file.md
Fix https://github.com/pingcap/docs/issues/12987
> tidb: add missing labels in config file

- metadata-lock.md
Add related error code for development reference.
> Add error code description for 'Information schema is changed'

- sync-diff-inspector/sync-diff-inspector-overview.md
> sync-diff: update docker images

- .github/workflows/link-fail-fast.yaml
- .github/workflows/link.yaml
- .github/workflows/media.yml
- .github/workflows/rebase.yml
Node.js 12 actions and the `set-output` command are deprecated.
This PR updates the following actions to use Node.js 16:
- `actions/checkout@v2`
- `actions/setup-node@v1`
- `andstor/file-existence-action@v1`
> ci: update specified actions to the latest

- resources/cdnfresh.txt
> add k8s v1.5 to pdf list

- partitioned-table.md
Removed the line about the unsupported info of `REORGANIZE PARTITION` and updated the structure of Partition management 
> partitioned-table: updated the structure of Partition management 

- TOC.md
- _index.md
- migration-tools.md
> *: adjust tool order in toc and learning path

- TOC.md
TiUP is not the only recommended way of deployment, so remove _recommended_ from TiUP deployment.
- This PR is translated from:https://github.com/pingcap/docs/pull/11185
> toc: remove recommended from tiup deployment

- ticdc/ticdc-changefeed-config.md
- ticdc/ticdc-sink-to-cloud-storage.md
- ticdc/ticdc-sink-to-kafka.md
> ticdc: fix sink uri for storage sink

- system-variables.md
> system-variables: update description of datadir

- privilege-management.md
- sql-statements/sql-statement-calibrate-resource.md
> resource_control: add privilege for calibrate resource

- releases/release-6.5.2.md
- ticdc/ticdc-changefeed-config.md
> 6.5.2 release notes:  fix an issue number

- scale-tidb-using-tiup.md
- ticdc/deploy-ticdc.md
- tiup/tiup-component-cluster-check.md
Close https://github.com/pingcap/docs-cn/issues/13774
The scale-out.yml example is inaccurate. This PR updates some examples:
- Modify the file name from `scale-out.yaml` to `scale-out.yml`
- Modify the deploy_dir from `/data/deploy/install/deploy/...` to `/tidb-deploy/...`
- Modify the data_dir from `/data/deploy/install/data/...` to `/tidb-data/...`
- Modify the log_dir from `/data/deploy/install/log/...` to `/tidb-deploy/.../log` …
> tiup: fix the scale-out yaml example

- system-variables.md
as tittle
- This PR is translated from:https://github.com/pingcap/docs/pull/13336
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/13748
> system-variables: update the default value of datadir

- tidb-lightning/tidb-lightning-physical-import-mode.md
> lihgtning: add parrallel import method

- ticdc/ticdc-sink-to-cloud-storage.md
- ticdc/ticdc-sink-to-kafka.md
- ticdc/ticdc-sink-to-mysql.md
> add ticdc command line server flag description

- ddl-introduction.md
Add description about the new admin command:
- admin pause ddl jobs
- admin resume ddl jobs
- https://github.com/pingcap/tidb/pull/43081
- https://github.com/pingcap/tidb/pull/43159
- https://github.com/pingcap/tidb/issues/18015 
- https://github.com/pingcap/tidb/issues/40041
Related issue number: 
- …
> Add description on `admin pause ddl jobs` and `admin resume ddl jobs`

- system-variables.md
- tiflash/use-tiflash-mpp-mode.md
> add sys variables `tidb_prefer_broadcast_join_by_exchange_data_size` to docs-cn

- system-variables.md
- tiflash/tiflash-late-materialization.md
> TiFlash Late Materialization GA

- system-variables.md
- tiflash/tiflash-results-materialization.md
> update doc for insert select pushdown to tiflash

- partitioned-table.md
Removed the warning that INTERVAL partitioning is experimental, effectively making it GA.
- This PR is translated from: https://github.com/pingcap/docs/pull/13161
> Make INTERVAL Partitioning GA

- ticdc/ticdc-changefeed-config.md
Add information about keeping the default value unchanged for enable-partition-separator
> v7.1: modify default value descriptions for enable-partition-separator

- releases/release-6.5.2.md
this note is missing from v6.5.2 because the pull request https://github.com/pingcap/tidb/pull/43054 was merged after the code freeze. 
> add a note on max_prepared_stmt_count for 6.5.2

- releases/release-7.1.0.md
Remove a link of fast online ddl in release notes (preview version)
> v7.1: update the description of fast online ddl

- system-variables.md
- tidb-configuration-file.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/35425
> system-variables.md: add version tag for tidb_enable_ddl

- system-variables.md
- This PR is translated from: https://github.com/pingcap/docs/pull/12231
> system-variables: Link various resources related to MAX_EXECUTION_TIME

- .github/pull_request_template.md
- tiflash/tiflash-results-materialization.md
> chore: add v7.2 to the PR template

- mysql-compatibility.md
> Remove TRUNCATE PARTITION as non-supported

- releases/release-7.1.0.md
- tidb-configuration-file.md
Add configuration `performance.force-init-stats`.
- Other reference link(s): https://github.com/pingcap/tidb/pull/43381
> add configuration performance.force-init-stats

- develop/dev-guide-connection-parameters.md
> develop: fix typo

- sql-statements/sql-statement-operate-load-data-job.md
- sql-statements/sql-statement-show-load-data.md
LAOD -> LOAD
- This PR is translated from: https://github.com/pingcap/docs/pull/13106
> Fix typos for LOAD

- br/backup-and-restore-storages.md
- br/backup-and-restore-use-cases.md
> br: change the permission for external storage when do restore

- ticdc/ticdc-sink-to-mysql.md
> add the doc for cache-prep-stmt

- foreign-key.md
Add a note about inline references.
- This PR is translated from: https://github.com/pingcap/docs/pull/13056
> foreign-key: add note about inline references

- command-line-flags-for-tidb-configuration.md
Add the description about `proxy-protocol-networks`. It actually accepts connections without Proxy Protocol for the addresses outside the list.
- This PR is translated from: https://github.com/pingcap/docs/pull/13297
> tidb config: add description about proxy protocol

- tidb-configuration-file.md
Update description about `compatible-kill-query` configuration.
> update description about compatible-kill-query configuration

- tispark-overview.md
PDF pipeline is broken due to the svg image https://ci.pingcap.net/job/docs-cn-merge-pipeline/3990/
The log is as follows:
```
[2023-05-10T03:23:28.882Z] [pandoc warning] Unable to convert `/tmp/tex2pdf.84/d16af1cbb691bf7a1581deb103c49bcfa807f7e9.svg' for use with pdflatex.
[2023-05-10T03:39:21.441Z] ! Unable to load picture or PDF file '/tmp/tex2pdf.84/d16af1cbb691bf7a1581deb10
[2023-05-10T03:39:21.441Z] 3c49bcfa807f7e9.svg.'.
[2023-05-10T03:39:21.441Z] <to be read again> 
[2023-05-10T03:39:21.441Z]                    }
[2023-05-10T03:39:21.441Z] l.121941 ...b691bf7a1581deb103c49bcfa807f7e9.svg}}
[2023-05-10T03:39:21.442Z] 
[2023-05-10T03:39:21.442Z] pandoc: Error producing PDF
script returned exit code 43
```
By default, **CHOOSE MASTER …
> tispark: remove the svg image

- ticdc/manage-ticdc.md
> fix ticdc config descriptions in 6.1

- _index.md
> learning path: update the link for deployment on k8s

- statistics.md
Add description about `force-init-stats` in Introduction to Statistics.
- Other reference link(s): https://github.com/pingcap/tidb/pull/43381
> add description about force-init-stats in introduction to statistics

- sql-statements/sql-statement-alter-resource-group.md
- sql-statements/sql-statement-create-resource-group.md
- sql-statements/sql-statement-drop-resource-group.md
- sql-statements/sql-statement-set-resource-group.md
> resource_control: fix resource group related ebnf syntax

- sql-non-prepared-plan-cache.md
- system-variables.md
Non-prepared plan cache is an experimental feature in v7.1.0.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/13662
> disable non-prep plan cache

- sql-plan-replayer.md
- Plan replayer zip file has been no longer a one-time file since https://github.com/pingcap/tidb/pull/33497#pullrequestreview-922685815
- GC duration for plan replayer zip file from capture is increased from 1 hour to 1 week. https://github.com/pingcap/tidb/pull/43664
> sql-plan-replayer: update description about plan replayer zip file GC strategy

- foreign-key.md
> foreign_key: fix typo

- benchmark/benchmark-tidb-using-sysbench.md
> how-to-run-sysbench: update cmd

- sql-statements/sql-statement-load-data.md
To clarify the MySQL compatibility of `LOAD DATA`, something was missed in the past.
> sql-statements: clarify the MySQL compatibility of `LOAD DATA`

- pd-configuration-file.md
- releases/release-7.1.0.md
https://github.com/tikv/pd/pull/6265
> update the behavior change about schedule.enable-diagnostic

- configure-memory-usage.md
> Add tidb_server_memory_limit tip

- basic-features.md
- security-compatibility-with-mysql.md
- system-variables.md
> auth, variables: add description about ldap authentication

- dashboard/dashboard-resource-manager.md
- system-variables.md
> dashboard: fix a render issue

- br/backup-storage-gcs.md
> br: fix a command error

- basic-features.md
- faq/deploy-and-maintain-faq.md
- releases/release-6.3.0.md
- releases/release-7.0.0.md
- tiflash/tiflash-configuration.md
- Update outdated term "GCP" to "Google Cloud" because "[Google Cloud Platform is now called Google Cloud](https://cloud.google.com/blog/topics/developers-practitioners/introducing-new-homepage-google-cloud)"
- Update related descriptions
Note: I searched "GCP" in the whole main branch of this repo.
> *: update GCP name to Google Cloud

- auto-random.md
> auto-random.md: add description about max allocation times

- predicate-push-down.md
> Fix doc wrong related with `substring` which can be pushed down now

- _index.md
- dashboard/dashboard-user.md
- dm/task-configuration-file-full.md
- migrate-large-mysql-shards-to-tidb.md
- migrate-small-mysql-shards-to-tidb.md
- ticdc/ticdc-changefeed-config.md
- tidb-lightning/tidb-lightning-configuration.md
- tiflash/tiflash-configuration.md
Update absolute links in learning path and others
> update absolute links in learning path and others

- hardware-and-software-requirements.md
TiDB v7.1.0 supports openEuler 22.03 LTS SP1 (x86_64)
> support openEuler 22.03 LTS SP1 x86

- hardware-and-software-requirements.md
- Update `hardware-and-software-requirements.md` for v7.1
- Support openEuler 22.03 LTS SP1 x86 in v7.1
- This PR is translated from: https://github.com/pingcap/docs/pull/13702
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/13967
> update hardware-and-software-requirements for v7.1

- best-practices/java-app-best-practices.md
- develop/dev-guide-connect-to-tidb.md
- dm/dm-glossary.md
- tidb-configuration-file.md
The old internals manual has been replaced with a generic redirect. This replaces the links with new links in the new source code documentation of MySQL
- This PR is translated from: https://github.com/pingcap/docs/pull/13694
> Fix pages linking to the old MySQL Internals Manual

- ticdc/ticdc-sink-to-kafka.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/13896/files#r1206258847
> ticdc: add docs for insecure-skip-verify

- resources/cdnfresh.txt
Update `cdnfresh.txt` for v7.1:
- Add links for v6.5 `https://download.pingcap.org/tidb-v6.5-zh-manual.pdf` and `https://download.pingcap.org/tidb-v6.5-en-manual.pdf`
> Update cdnfresh.txt for v7.1

- README.md
README.md: add release-7.1 branch
> update README for v7.1

- releases/release-6.6.0.md
Update release notes for release-6.6.0
> Update release notes for release-6.6.0

- scale-tidb-using-tiup.md
Fix the table format in scale-tidb-using-tiup.md.
> tiup: fix table format

- releases/release-7.0.0.md
Update the v7.0.0 installation package link
> update installation package for v7.0.0

- releases/release-7.1.0.md
> release notes: fix broken link

- tiflash/use-tiflash-mpp-mode.md
Add a known issue for TiFlash mpp.
> Add a known issue for TiFlash mpp.

- auto-increment.md
- auto-random.md
> sql: add more descriptions about create table parameters

- releases/release-7.1.0.md
Update the configuration item in release notes.
> release note: update configuration item

- ecosystem-tool-user-guide.md
- tidb-in-kubernetes.md
- tidb-operator-overview.md
私有部署的 Kubernetes-> 自托管的 Kubernetes 集群
> 4.0: update the usage for self-hosted deployment

- time-to-live.md
rename TiDB Cloud Serverless Tier to TiDB Serverless Tier
> v6.6: rename TiDB Cloud Serverless Tier to TiDB Serverless

- system-variables.md
Resource control becomes GA in v7.1.0. Remove experimental note in tidb_enable_resource_control.
> remove experimental note in tidb_enable_resource_control

- releases/release-6.1.6.md
- releases/release-6.5.2.md
Fix broken links in release notes from `https://github.com/sojjy` to `https://github.com/sdojjy`.
Fix https://github.com/pingcap/docs/issues/13772
> fix broken links in release notes

- ticdc/ticdc-alert-rules.md
use the correct metric name for ticdc alert rule, some of them are removed or renamed
> update ticdc alert rule

- ticdc/ticdc-changefeed-overview.md
update the description of failed changefeed gc mechanism introduced by [#8646](https://github.com/pingcap/tiflow/pull/8464) 
- This PR is translated from: None
- Other reference link(s): None
> update ticdc failed changefeed gc mechanism description

- grafana-tidb-dashboard.md
TiDB v6.5.3 introduces two metrics for Stale Read.
- Other reference link(s): pingcap/docs#13842, https://github.com/pingcap/tidb/issues/43325, https://github.com/pingcap/tidb/pull/43324
> add description of stale read metrics

- br/backup-and-restore-use-cases.md
- dm/maintain-dm-using-tiup.md
- dm/quick-start-create-task.md
- pd-control.md
- production-deployment-using-tiup.md
- quick-start-with-tidb.md
- scale-tidb-using-tiup.md
- ticdc/deploy-ticdc.md
- ticdc/ticdc-avro-protocol.md
- ticdc/ticdc-sink-to-cloud-storage.md
- tidb-binlog/get-started-with-tidb-binlog.md
- tiflash/create-tiflash-replicas.md
- tiup/tiup-cluster.md
- tiup/tiup-component-cluster-deploy.md
- tiup/tiup-component-cluster-upgrade.md
- tiup/tiup-component-dm-upgrade.md
- tiup/tiup-component-management.md
- tiup/tiup-mirror.md
- tiup/tiup-playground.md
- upgrade-tidb-using-tiup.md
Bump versions to v6.5.3
- This PR is translated from:https://github.com/pingcap/docs/pull/13871
> bump versions to v6.5.3

- ticdc/deploy-ticdc.md
Fix https://github.com/pingcap/docs-cn/issues/14233
> fix deploy-ticdc

- download-ecosystem-tools.md
- pd-control.md
> fix wrong sha256 checksum

- TOC.md
- _index.md
manual cherry pick from https://github.com/pingcap/docs-cn/pull/13942
> add roadmap absolute link to toc and index

- ticdc/ticdc-sink-to-kafka.md
> update ticdc acl

- tidb-lightning/tidb-lightning-faq.md
The current solution provided in the FAQ is incorrect. The limitation can be bypassed by adjusting two configurations.
> lightning: fix a wrong solution in lightning faq

- releases/release-7.1.0.md
- tikv-configuration-file.md
> v7.1: remove the support info of optimize-filters-for-memory

- ticdc/ticdc-changefeed-config.md
Remove a miss added config item.
> ticdc: fix changefeed config doc

- data-type-string.md
- tidb-limitations.md
> *: remove the limit on single column data size

- system-variables.md
> change default value of `tidb_remove_orderby_in_subquery` to true

- ticdc/ticdc-changefeed-config.md
- Other reference link(s): https://github.com/pingcap/tiflow/pull/9136
> add new changefeed level config 

- br/backup-and-restore-storages.md
support access blob by [SAS (shared access signatures)](https://learn.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature).
> br: support access by azure sas token

- ticdc/ticdc-integrity-check.md
Add a new section to introduce the Golang implementation
> cdc: add ticdc integrity check golang implementation explanation.

- tidb-lightning/tidb-lightning-configuration.md
> add "latin1" encoding support for lightning

- dm/feature-shard-merge-optimistic.md
- dm/task-configuration-file-full.md
https://github.com/pingcap/tiflow/pull/9113
> dm: add description about strict-optimistic-shard-mode

- tiflash/tiflash-supported-pushdown-calculations.md
> `FIRST_VALUE` and `LAST_VALUE` pushdown

- migrate-from-tidb-to-mysql.md
Must use MyLoader v0.10 or earlier versions.
- Other reference link(s):https://github.com/pingcap/tidb/issues/44922
> migration: add MyLoader version requirement

- system-variables.md
After https://github.com/pingcap/tidb/pull/44578, the upper limit for `last_insert_id` change to 18446744073709551615 which equals to MaxUint64
> system-variables: update upper limit for `last_insert_id`

- mysql-compatibility.md
1. mysql 8.0 is mentioned explicitly
2. include the description of a few unsupported features from Mysql 8.0
* explicitly mention TiDB already included quite a few new features of MySQL 8.0
* append the remarkable unsupported features in MySQL 8.0 that has not been included in TiDB
PR for EN: https://github.com/pingcap/docs/pull/13835 …
> explicitly mention mysql 8.0 in MySQL compatibility

- read-historical-data.md
As tittle
- Other reference link(s):https://github.com/pingcap/docs/pull/5600
> sql: correct SELECT statement

- tidb-lightning/tidb-lightning-configuration.md
> lightning: correct send-kv-pairs value

- optimizer-fix-controls.md
> sql: update optimizer-fix-controls version

- br/backup-and-restore-storages.md
These params are added in https://github.com/pingcap/docs-cn/pull/11438 but later accidentally removed by BR refactor PRs.
> br: add s3 params that were mistakenly deleted during refactor

- .github/workflows/dispatch.yml
> chore: add v7.2 to dispatch.yml

- system-variables.md
TiDB PR: https://github.com/pingcap/tidb/pull/43904
> tidb: update the default value of variable `tidb_enable_non_prepared_plan_cache`

- statistics.md
- tidb-configuration-file.md
Turn on `lite-init-stats` and `force-init-stats` by default.
- Other reference link(s): https://github.com/pingcap/tidb/pull/44080
> turn on lite-init-stats and force-init-stats by default

- system-variables.md
tidb_opt_enable_mpp_shared_cte_execution
Add the description for the var which controls the CTE's shared scan in MPP.
> system-variables: add description for `tidb_opt_enable_cte_mpp_shared_execution`

- system-variables.md
> add runtime filter session variable

- _index.md
Update the docs links in v7.2 home page to v7.2 links
> v7.2.0: update v7.2 index page link

- resources/cdnfresh.txt
Add 7.2 PDF links for refreshing
> Update cdnfresh.txt for v7.2

- ticdc/ticdc-changefeed-config.md
add kafka oauth configurations.
- Other reference link(s): https://github.com/pingcap/tiflow/pull/8938
> ticdc: add kafka oauth configurations

- TOC.md
- develop/dev-guide-ticdc-checksum-verification.md
- ticdc/ticdc-avro-checksum-verification.md
- ticdc/ticdc-integrity-check.md
> cdc: add ticdc checksum verification sample

- ticdc/ticdc-changefeed-config.md
> fix cdc changefeed config error

- releases/release-7.1.0.md
> release-7.1.0: update package downloading link

- hardware-and-software-requirements.md
- temp.md
Since v6.1.2, only macOS 12+ is supported.
- This PR is translated from: https://github.com/pingcap/docs/pull/14056
> update the supported macos version

- README.md
- tidb-roadmap.md
> add the link of v7.2 release notes to TiDB roadmap

- tidb-resource-control.md
As tittle
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/14391
> resource-control: fix html tag issue

- ticdc/ticdc-changefeed-config.md
- ticdc/ticdc-sink-to-cloud-storage.md
> ticdc: fix date-separator config of storage sink

- tidb-resource-control.md
> *: fix html table in resource control

- tidb-control.md
Include warning messages to notify customers. We don't recommend to use tidb-ctl in application design.
- This PR is translated from: https://github.com/pingcap/docs/pull/14041
> include warning message in tidb control

- develop/dev-guide-choose-driver-or-orm.md
- develop/dev-guide-third-party-support.md
change django support level to full and update the latest tested version
> feat: change django support level to full cause of we added test cases to pipeline already

- migrate-large-mysql-to-tidb.md
Add a note for physical import mode of TiDB lightning. The import speed is affected by various factors such as hardware configuration, table schema, and the number of indexes.
> lightning: add a note for physical import mode

- sql-statements/sql-statement-import-into.md
> import into: add known issue

- .github/pull_request_template.md
- temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/14146
> .github: add 7.3 in pr template

- .github/workflows/dispatch.yml
> dispatch.yml: remove the achvied release-v6.6 

- .github/pull_request_template.md
- releases/release-6.3.0.md
- releases/release-6.4.0.md
- releases/release-6.6.0.md
1. v6.3/v6.4/v6.6 release notes: add archive info 
2. remove v6.6 from the pull request template
> v6.3/v6.4/v6.6 release notes: add archive info

- releases/release-7.1.0.md
> add experimental label to smooth upgrade

- TOC.md
- tidb-lightning/tidb-lightning-log-message-explanation.md
add detailed log message explanation for lightning.
- This PR is translated from:https://github.com/pingcap/docs/pull/11930, https://github.com/pingcap/docs/pull/13654
> lightning: add detailed log message explanation

- data-type-json.md
TiDB has supported pushing some JSON functions to TiFlash since v6.5. This PR fixes the non-support info in the doc.
> TiFlash: update the JSON push-down instruction

- sql-statements/sql-statement-show-indexes.md
Update the comments for `SHOW INDEX` after the pull [tidb#42441](https://github.com/pingcap/tidb/pull/42441)
> sql-statements: update the compability comment for `SHOW INDEX`

- system-variables.md
> system-variables: fix a typo for "GROUP"

- tikv-configuration-file.md
Move  `report-region-buckets-tick-interval` to the raftstore directory
> tikv config: correct location of report-region-buckets-tick-interval

- releases/release-5.2.2.md
- releases/release-6.1.6.md
- releases/release-6.2.0.md
- releases/release-6.5.0.md
- releases/release-6.5.1.md
Fix the issue and contributor format (`[#1234](link) @[contributor](link)`) in release notes
> releases: fix the issue and contributor format in release notes

- develop/dev-guide-choose-driver-or-orm.md
- develop/dev-guide-third-party-support.md
- develop/dev-guide-third-party-tools-compatibility.md
Update the support level of SQLAlchemy and Sequelize to full.
> feat: SQLAlchemy and Sequelize were added to test pipeline

- develop/dev-guide-sample-application-python.md
Update the code of `mysql_connector_python_example.py` to keep it consistent with https://github.com/pingcap-inc/tidb-example-python/pull/1.
> feat: MySQL Connector/Python example add some log to give some instructions

- tidb-lightning/tidb-lightning-command-line-full.md
> lightning: refine description about --check-requirements *bool* 

- tidb-lightning/tidb-lightning-configuration.md
> lightning: refine dsecription of check-requirements

- tidb-lightning/tidb-lightning-configuration.md
> lightning: refine description about checksum-via-sql

- ticdc/ticdc-sink-to-kafka.md
> cdc matcher rule explaination example

- grafana-pd-dashboard.md
fix the wrong position of `store limit`
> fix pd dashboard

- character-set-and-collation.md
- partitioned-table.md
- sql-statements/sql-statement-create-binding.md
- sql-statements/sql-statement-create-table.md
- sql-statements/sql-statement-drop-binding.md
- sql-statements/sql-statement-show-bindings.md
- transaction-overview.md
Command examples should be easily copy-pasteable.
> *: remove unnecessary character from sql examples

- dm/dm-safe-mode.md
- sql-statements/sql-statement-create-index.md
Fix SQL syntax error: replace the full-width semicolon with half-width
> sql statement: fix SQL syntax error

- hardware-and-software-requirements.md
v7.1.1: support ARM 64 for openEuler
> v7.1.1: support ARM 64 for openEuler

- optimizer-fix-controls.md
- sql-non-prepared-plan-cache.md
plan cache: TiDB v7.1.1 supports queries with more than 200 parameters
- Other reference link(s): v7.3 https://github.com/pingcap/docs-cn/pull/14535
> plan cache: TiDB v7.1.1 supports queries with more than 200 parameters

- system-variables.md
TiDB v7.1.1 introduces the tidb_lock_unchanged_keys system variable
(ref https://github.com/pingcap/docs-cn/pull/14290)
- This PR is translated from: https://github.com/pingcap/docs/pull/14222
> v7.1.1: add tidb_lock_unchanged_keys

- releases/release-7.1.1.md
> cdc update release-note about fix avro handle incorrect enum type value

- error-codes.md
error codes:
- remove a duplicate [
- update the support contact
> error codes: update the support contact

- sql-statements/sql-statement-select.md
- This PR is translated from:https://github.com/pingcap/docs/pull/14320
> sql: fix an error in sql-statement-select.md 

- telemetry.md
> Update TiSpark close telemetry time

- releases/release-6.2.0.md
- This PR is translated from:https://github.com/pingcap/docs/pull/14335
> Fix formatting of v620 release notes

- partitioned-raft-kv.md
- releases/release-7.1.0.md
Partitioned Raft KV: add incompatibility with TiFlash
> Partitioned Raft KV: add incompatibility with TiFlash

- br/backup-and-restore-storages.md
- encryption-at-rest.md
add `encryption-scope` and `encryption-key` for azure blob storage
- This PR is translated from: https://github.com/pingcap/docs/pull/14356
> br: support to write/ready azure blobs with customer provided key

- ticdc/ticdc-sink-to-kafka.md
> cdc add docs about handle-key only

- sql-statements/sql-statement-analyze-table.md
This pull request fixes typo `AnlyzeOption` that should be `AnalyzeOption`
- This PR is translated from: https://github.com/pingcap/docs/pull/14412
> analyze table: fix typo AnlyzeOption should be AnalyzeOption

- mysql-schema.md
- This PR is translated from: https://github.com/pingcap/docs/pull/14433
> add table `mysql.tidb_timers`

- system-variables.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/44598
> add a system variable tidb_lock_unchanged_keys

- resources/cdnfresh.txt
> change the stable of tidb-in-k8s pdf to v1.5

- tiflash/tiflash-configuration.md
> Add some security notation for tcp_port in sample config file

- partitioned-table.md
- temp.md
Added documentation for List DEFAULT partition.
- This PR is translated from: https://github.com/pingcap/docs/pull/13163
https://github.com/pingcap/tidb/pull/41537
> Added List DEFAULT partition

- statistics.md
- system-variables.md
Introduce the system variable `tidb_skip_missing_partition_stats`.
- Other reference link(s): https://github.com/pingcap/tidb/pull/41176
> add system variable tidb_skip_missing_partition_stats

- ticdc/ticdc-changefeed-config.md
- ticdc/ticdc-csv.md
> cdc: add hex encoding to csv

- sql-statements/sql-statement-add-index.md
> sql-statements: tiny update for smooth upgrade TiDB 

- releases/release-6.5.0.md
- This PR is translated from: https://github.com/pingcap/docs/pull/14438
> release-6.5.0: update the release note introduction 

- tikv-configuration-file.md
- tune-region-performance.md
> update default bucket size

- develop/dev-guide-third-party-support.md
> feat: full support for prisma

- TOC.md
- releases/release-6.2.0.md
> update the name of TiFlash upgrade help

- _index.md
- temp.md
Use v7.3 links in v7.3 learning path.
- This PR is translated from: https://github.com/pingcap/docs/pull/14470
> update learning path for v7.3

- partitioned-table.md
Fix https://github.com/pingcap/docs-cn/issues/14739
> fix the statement to update statistics of partitioned tables

- .github/pull_request_template.md
> pr template: add v7.4

- sql-statements/sql-statement-analyze-table.md
- Updated the `analyze` statement.
- Explained the `pseudo` stats.
> tidb: explain the `pseudo` stats

- releases/release-7.2.0.md
> update the package link in v7.2.0 release notes

- releases/release-7.3.0.md
> rm redundant heading in 7.3 rn

- develop/dev-guide-sample-application-python-mysqlclient.md
> feat: python example simplify

- sql-statements/sql-statement-alter-table.md
> fix a typo in sql statement alter table

- releases/release-6.1.0.md
- tiunimanager/tiunimanager-manage-host-resources.md
- tiunimanager/tiunimanager-quick-start.md
closes https://github.com/pingcap/docs-cn/issues/14801
> fix typo: 登陆 -> 登录

- basic-features.md
> update links to clustered index in basic feature

- statement-summary-tables.md
> sql: update statement summary doc

- develop/dev-guide-choose-driver-or-orm.md
Do not use `tidb-loadbalance` in production environments.
> dev-guide: add note about not using tidb-loadbalance in production environments

- develop/dev-guide-choose-driver-or-orm.md
> Revert "dev-guide: add note about not using tidb-loadbalance in production environments"

- develop/dev-guide-choose-driver-or-orm.md
> TiDB-JDBC SM3 introduce

- auto-increment.md
Does not support using ALTER TABLE to add columns with AUTO_INCREMENT
> sql: does not support using ALTER TABLE to add columns with AUTO_INCREMENT

- enable-tls-between-clients-and-servers.md
- faq/tidb-faq.md
- schedule-replicas-by-topology-labels.md
- tidb-limitations.md
Fix typos and update an example.
> fix typos and update example

- tidb-roadmap.md
add the link of v7.3 release notes to TiDB roadmap
> roadmap: add v7.3.0 release notes

- OWNERS_ALIASES
- develop/OWNERS
- This PR is translated from:https://github.com/pingcap/docs/pull/14655
> develop: add OWNERS for develop docs

- temp.md
- upgrade-monitoring-services.md
This PR synchronizes the new changes made in https://github.com/pingcap/docs/pull/14523.
- This PR is translated from: new changes in https://github.com/pingcap/docs/pull/14523
- Other reference link(s):  https://github.com/pingcap/docs-cn/pull/14510
> edit upgrade-monitoring-services.md

- develop/dev-guide-sample-application-python-mysqlclient.md
- This PR is translated from: https://github.com/pingcap/docs/pull/14544
> develop: improve python mysqlclient sample code doc

- two-data-centers-in-one-city-deployment.md
The `rule.json` in two-data-centers-in-one-city-deployment.md is invalid.
> placement rules: fix duplicate id in rule.json

- TOC.md
- develop/dev-guide-sample-application-nodejs-mysql2.md
- develop/dev-guide-sample-application-nodejs-mysqljs.md
- develop/dev-guide-sample-application-nodejs-prisma.md
- This PR is translated from:https://github.com/pingcap/docs/pull/14607
> feat: add Node.js mysql2/mysql.js/Prisma chinese tutorial

- develop/dev-guide-choose-driver-or-orm.md
- develop/dev-guide-sample-application-python-sqlalchemy.md
> develop: update python guide

- tiflash/tiflash-supported-pushdown-calculations.md
> Add window function push down restriction

- statement-summary-tables.md
Fix the description error about the proper size of the statement summary table 
> fix the size description of the statement summary table 

- keywords.md
- temp.md
Add the two keywords ROLLUP and HYPO, which have been introduced since v7.2 in https://github.com/pingcap/tidb/pull/43607 and https://github.com/pingcap/tidb/pull/43429
- This PR is translated from: https://github.com/pingcap/docs/pull/14781
> add keywords ROLLUP and HYPO

- TOC.md
- develop/dev-guide-sample-application-nodejs-typeorm.md
> develop: add TypeORM quickstart

- tiflash-performance-tuning-methods.md
> fix tiflash resource usage pic error

- optimizer-hints.md
As tittle
- Other reference link(s):https://github.com/pingcap/tidb/pull/44111
> sql planner: add `ORDER_INDEX` and `NO_ORDER_INDEX` hints for planner

- dumpling-overview.md
> dumpling: add PROCESS privilege

- config-templates/complex-tiflash.yaml
* Add the missing field "log_dir" in the yaml file tiflash section
* Use `"..."` for the dir path, use the same style as other components
- This PR is translated from: https://github.com/pingcap/docs/pull/14477
> Add missing field in deploy example yaml file

- tiflash-upgrade-guide.md
- tiflash/tiflash-configuration.md
> DTFile use V3 version as default

- ticdc/ticdc-manage-changefeed.md
> ticdc: delete useless contents 

- system-variables.md
In v6.0, Top SQL becomes GA. This PR removes the experimental warning from v6.1 to master.
> top sql: remove experimental warning

- optimizer-hints.md
> Modify the leading hint conflict information

- optimizer-hints.md
- system-variables.md
ref to https://github.com/pingcap/tidb/pull/45893
> optimizer hints: add the docs for hint SET_VAR

- functions-and-operators/tidb-functions.md
- temp.md
Add documentation for the new `TIDB_PARSE_TSO_LOGICAL()` function.
- This PR is translated from: https://github.com/pingcap/docs/pull/14719
* https://github.com/pingcap/docs/pull/14630
* https://github.com/pingcap/tidb/pull/46452
* https://github.com/pingcap/tidb/issues/46451
> Add TIDB_PARSE_TSO_LOGICAL()

- exporting-grafana-snapshots.md
Fix a broken link.
- This PR is translated from: https://github.com/pingcap/docs/pull/14930
> metricstool: fix a broken link

- system-variables.md
- tidb-configuration-file.md
> update tidb_stats_cache_mem_quota description

- system-variables.md
- This PR is translated from: https://github.com/pingcap/docs/pull/14725
> add doc for sysvar `tidb_session_alias`

- releases/release-6.5.4.md
> release-6.5.4: add missing fix note

- auto-increment.md
> sql: fix an error in AUTO_ID_CACHE

- optimizer-hints.md
- system-variables.md
As tittle
- This PR is translated from:https://github.com/pingcap/docs/pull/14905
> sysvar: add system variable `tidb_opt_enable_hash_join`

- constraints.md
> sql: refine description about compatibility with msql

- hardware-and-software-requirements.md
> hardware-and-software-requirements: clarify UOS name

- dumpling-overview.md
add csv line terminator option
https://github.com/pingcap/tidb/pull/46983
> dumpling: add csv line terminator option

- ticdc/ticdc-sink-to-kafka.md
> cdc: update topic expression description

- system-variables.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/46558
> *: add doc for system variable tidb_schema_version_cache_limit

- temp.md
- ticdc/ticdc-ddl.md
- This PR is translated from: https://github.com/pingcap/docs/pull/14947 https://github.com/pingcap/docs-cn/pull/14835
> ticdc: add ddl replication documents

- releases/release-7.0.0.md
- tiflash/tiflash-configuration.md
> Update the param size for mark cache and minmax index cache for TiFlash

- _index.md
> learning path: update links to v7.4

- develop/dev-guide-sample-application-python-peewee.md
> develop: update peewee guide

- releases/release-7.4.0.md
> fix PDF build failure: escape special characters

- resources/cdnfresh.txt
> Update cdnfresh.txt for v7.4, v7.3, v7.1

- releases/release-7.3.0.md
- releases/release-7.4.0.md
> v7.3: update download address

- .github/pull_request_template.md
> add v7.5 to the PR template

- releases/release-7.4.0.md
Add deprecation plan to release-7.4.0.
> Update 7.4.0 release notes to add deprecation plan

- releases/release-7.4.0.md
> v7.4: remove a note

- keywords.md
The TPCH_10 keyword is introduced in https://github.com/pingcap/tidb/pull/47095/files
> keywords: add TPCH_10

- ticdc/ticdc-sink-to-kafka.md
> add more desc about replicatuin-factor

- system-variables.md
> system-variables: write the version info of tidb_read_consistency in Chinese

- quick-start-with-tidb.md
- temp.md
- ticdc/ticdc-overview.md
- This PR is translated from: https://github.com/pingcap/docs/pull/13947
> *: optimize 4 docs descriptions

- deploy-monitoring-services.md
- develop/dev-guide-proxysql-integration.md
- functions-and-operators/precision-math.md
- maintain-tidb-using-tiup.md
- performance-tuning-methods.md
- production-deployment-using-tiup.md
- tidb-binlog/binlog-consumer-client.md
- tidb-configuration-file.md
- troubleshoot-lock-conflicts.md
Update some GitHub links for `pingcap/tidb` repo reorganization (move most of the packages to 'pkg')
- Other reference link(s): https://github.com/pingcap/tidb/pull/47123
> update some GitHub links for tidb repo reorganization

- statistics.md
> statistics: add info about tidb_auto_analyze_partition_batch_size

- glossary.md
- schedule-replicas-by-topology-labels.md
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/15076  https://github.com/pingcap/docs/pull/14904
> tiflash: refine descriptions

- .github/pull_request_template.md
Because v7.2 and v7.0 docs are achieved and no longer receive new updates, this PR removes them from the PR template to avoid unnecessary changes. 
- https://docs-archive.pingcap.com/zh/tidb/v7.2
- https://docs-archive.pingcap.com/zh/tidb/v7.0
> pull request template: remove v7.2 and v7.0

- mysql-compatibility.md
> removed description about not supporting FLOAT4/FLOAT8

- releases/release-7.1.2.md
Fix the displayed issue number for https://github.com/pingcap/tidb/issues/46033
> release-7.1.2.md: fix an issue number

- .github/pull_request_template.md
1. Add v7.4 back, which is removed in https://github.com/pingcap/docs-cn/pull/15283 by mistake
2. Remove v7.2 as its docs have been archived 
> chore: update pull_request_template

- external-storage-uri.md
- Other reference link(s):https://github.com/pingcap/docs/pull/15165
> update URI examples

- tiup/tiup-documentation-guide.md
Add the GitHub link of TiUP release notes
> tiup: add the GitHub link of release notes

- br/backup-and-restore-overview.md
- character-set-and-collation.md
- faq/backup-and-restore-faq.md
- migration-tools.md
- mysql-schema.md
- Other reference link(s): ref https://github.com/pingcap/tidb/issues/46136
> collation: improve some new_collation_enabled relateds doc

- releases/release-7.4.0.md
- tikv-configuration-file.md
> tikv: update the default value of periodic-compaction and ttl

- releases/release-6.5.3.md
- releases/release-6.5.5.md
- https://github.com/tikv/tikv/issues/15279 and https://github.com/tikv/tikv/issues/13638 were fixed in v6.5.4. This PR removes duplicate note in v6.5.5
- https://github.com/tikv/tikv/issues/14547 was fixed in v6.5.3
> release notes: remove duplicate notes

- tidb-resource-control.md
- This PR is translated from:https://github.com/pingcap/docs/pull/15166
> tidb-resource-control: Add info about unbind

- releases/release-7.4.0.md
Add experimental note for global sort in release-7.4.0.md
> global sort is experimental in v7.4

- dumpling-overview.md
- sql-statements/sql-statement-import-into.md
- storage-engine/titan-overview.md
- ticdc/ticdc-sink-to-kafka.md
- tidb-lightning/tidb-lightning-data-source.md
- tidb-lightning/troubleshoot-tidb-lightning.md
- tikv-configuration-file.md
- tune-tikv-memory-performance.md
- This PR is translated from:https://github.com/pingcap/docs/pull/15241
> add snappy restriction note

- keywords.md
- temp.md
Update the keyword docs
- This PR is translated from: https://github.com/pingcap/docs/pull/14740
- https://github.com/pingcap/tidb/pull/46649
> Add FLOAT4, FLOAT8 and MIDDLEINT to the docs

- temp.md
- tidb-configuration-file.md
Added docs for the undocumented `deprecate-integer-display-length` option.
See also: https://github.com/pingcap/tidb/blob/302786ffb91400f30d0be90abaca852a73ffa41c/config/config.toml.example#L102-L104
Note that I also filed a bug that is related to this issue: https://github.com/pingcap/tidb/issues/46650
Also related: https://github.com/pingcap/tidb/pull/18775
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the- …
> Add deprecate-integer-display-length to TIDB Config

- ticdc/ticdc-bidirectional-replication.md
> ticdc: remove source id desciption

- correlated-subquery-optimization.md
- explain-subqueries.md
- temp.md
Fix the operator IDs to match the explain results
- This PR is translated from: https://github.com/pingcap/docs/pull/15291
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/11624
> fix the operator info

- system-variables.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/47148
> add tidb_gogc_tuner_max_value and tidb_gogc_tuner_min_value

- hardware-and-software-requirements.md
TiDB v7.5 supports Rocky Linux 9.0
> v7.5 supports Rocky Linux 9.1

- dumpling-overview.md
- ecosystem-tool-user-guide.md
- mydumper-overview.md
Mydumper is deprecated in v7.5.0. This PR updates the note in v4.0-v7.4 to refeact that Mydumper is deprecated.
> deprecate Mydumper

- binary-package.md
- develop/dev-guide-timeouts-in-tidb.md
- dumpling-overview.md
- ecosystem-tool-user-guide.md
- migration-overview.md
- tidb-lightning/monitor-tidb-lightning.md
- tidb-lightning/tidb-lightning-command-line-full.md
- tidb-lightning/tidb-lightning-configuration.md
- tidb-lightning/tidb-lightning-faq.md
- tidb-lightning/tidb-lightning-physical-import-mode.md
- tidb-lightning/troubleshoot-tidb-lightning.md
- tidb-troubleshooting-map.md
Starting from v7.5.0, Mydumper and tikv-importer are deprecated.
- This PR is translated from: https://github.com/pingcap/docs/pull/15289
> deprecate Mydumper and tikv-importer

- ddl-introduction.md
- sql-statements/sql-statement-admin-pause-ddl.md
- sql-statements/sql-statement-admin-resume-ddl.md
GA the feature of pause/resume ddl jobs
> sql: pause and resume ddl jobs GA

- system-variables.md
> system-variable: add tidb_enable_async_merge_global_stats

- system-variables.md
- This PR is translated from:  
- Other reference link(s): #47275
> system-variable: update variable for analyze

- binary-package.md
- download-ecosystem-tools.md
> remove TiSpark from offline package

- .github/workflows/dispatch.yml
> update dispatch for release-7.5

- develop/dev-guide-sample-application-golang-gorm.md
- develop/dev-guide-sample-application-golang-sql-driver.md
- develop/dev-guide-sample-application-java-hibernate.md
- develop/dev-guide-sample-application-java-jdbc.md
- develop/dev-guide-sample-application-java-mybatis.md
- develop/dev-guide-sample-application-java-spring-boot.md
- develop/dev-guide-sample-application-nodejs-mysql2.md
- develop/dev-guide-sample-application-nodejs-mysqljs.md
- develop/dev-guide-sample-application-nodejs-prisma.md
- develop/dev-guide-sample-application-nodejs-typeorm.md
- develop/dev-guide-sample-application-python-django.md
- develop/dev-guide-sample-application-python-mysql-connector.md
- develop/dev-guide-sample-application-python-mysqlclient.md
- develop/dev-guide-sample-application-python-peewee.md
- develop/dev-guide-sample-application-python-pymysql.md
- develop/dev-guide-sample-application-python-sqlalchemy.md
- develop/dev-guide-sample-application-ruby-mysql2.md
- develop/dev-guide-sample-application-ruby-rails.md
Fix broken links: update `https://cn.pingcap.com/courses-catalog/back-end-developer` to `https://cn.pingcap.com/courses-catalog/category/back-end-developer`
> develop: fix broken links

- ticdc/ticdc-changefeed-config.md
- ticdc/ticdc-sink-to-mysql.md
> ticdc: change encoder tool
