functions-and-operators/string-functions.md
This PR converts the table of supported string functions to a list of sections so we can add instructions for each function in different PRs.
=> string-functions: convert the table of supported functions to a list

tidb-binlog/bidirectional-replication-between-tidb-clusters.md, tidb-binlog/tidb-binlog-overview.md, tidb-binlog/upgrade-tidb-binlog.md
=> tidb-binlog: depreciate binlog as a data sync tool

backup-and-restore-using-dumpling-lightning.md, dm/dm-hardware-and-software-requirements.md, migrate-large-mysql-to-tidb.md, tidb-lightning/tidb-lightning-requirements.md
- This PR is translated from:https://github.com/pingcap/docs/pull/15423
=> Clarify statement on backup-and-restore-using-dumpling page

dashboard/continuous-profiling.md, dashboard/dashboard-profiling.md
Add the support of TiKV for heap profiling
=> dashboard: Add the support of TiKV for heap profiling

tiflash/tune-tiflash-performance.md
=> Add some explanation for tiflash tuning performance doc

dm/dm-faq.md, dm/dm-online-ddl-tool-support.md, temp.md
- Cleanup typo in feature-online-ddl 
- Remove obsolete config `online-ddl-scheme` and replace with existing config `online-ddl`
- This PR is translated from: https://github.com/pingcap/docs/pull/14481 
- Other reference link(s): https://docs.pingcap.com/tidb/stable/feature-online-ddl
=> dm: Cleanup typo in feature-online-ddl and update dm-faq

.github/pull_request_template.md
=> pr template: add the option for v7.6

download-ecosystem-tools.md
=> v5.3: update downloading links of sync_diff_inspector

sql-statements/sql-statement-select.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/15104
=> add more explains and examples for `SELECT ... INTO OUTFILE` statements

best-practices/pd-scheduling-best-practices.md
Polish the advice on the `TiKV Trouble shooting` part in `pd-scheduling-best-practice.md`.
=> Polish pd-scheduling-best-practice on slow nodes.

migrate-from-tidb-to-tidb.md, replicate-between-primary-and-secondary-clusters.md, sql-statements/sql-statement-backup.md, sql-statements/sql-statement-restore.md
=> BRIE: add experimental notice in BACKUP and RESTORE sql

tiflash-upgrade-guide.md
=> fix typo "Tiflash"

develop/dev-guide-sample-application-java-jdbc.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/15433
=> Fix broken link to Connector/J docs

hardware-and-software-requirements.md
Update hardware-and-software-requirements for v7.5:
- Divide the original table into two tables: **provides enterprise-level production quality** and **does not guarantee enterprise-level production quality**
- Starting from v7.5.0, TiDB support **Rocky Linux 9.1 or later** as enterprise-level production quality
- Other reference …
=> update hardware-and-software-requirements for v7.5

ticdc/ticdc-changefeed-config.md, ticdc/ticdc-open-api-v2.md, ticdc/ticdc-server-config.md
=> ticdc: add binary_encoding_method to openapi v2

optimizer-hints.md, releases/release-7.4.0.md, system-variables.md
Add detailed info about in what versions the `tidb_opt_enable_hash_join` system variable is introduced
=> Update the introduced info for tidb_opt_enable_hash_join

br/br-pitr-guide.md
=> fix redundant quotation marks

system-variables.md
=> fix version comment

information-schema/information-schema-variables-info.md
=> update the variable scope 

sql-non-prepared-plan-cache.md, temp.md
Fix https://github.com/pingcap/docs/issues/15599
Fixed a typo, using `t` as table name instead of `t1`, since the previous examples using `t`.
- This PR is translated from: https://github.com/pingcap/docs/pull/15600
Close: https://github.com/pingcap/docs/issues/15599
=> Table name typo fixed

releases/release-7.5.0.md, tidb-configuration-file.md
Starting from v7.5.0, TiDB configuration item copr-req-timeout is introduced.
=> tidb config doc: coprocessor request timeout

releases/release-7.3.0.md, system-variables.md
=> add doc for tidb_allow_tiflash_cop

transaction-isolation-levels.md
=> transaction: add english for a term

sync-diff-inspector/route-diff.md
- This PR is translated from:https://github.com/pingcap/docs/pull/15242
=> sync-diff-inspector: add descriptions and examples of table routers

faq/manage-cluster-faq.md
从测试结果来看即使增加路径可读权限也无法绕过，只能换路径方式绕过。
期望通过 FAQ 让使用者更快解决问题。
=> faq: add PD encryption error "fail to get encryption key from file"

br/use-br-command-line-tool.md
add comments about backup config: compression && compression-level
=> br: add document for backup compression

releases/release-7.1.1.md
=> br: add one missing pitr bugfix

dm/dm-open-api.md
- This PR is translated from: https://github.com/pingcap/tiflow/pull/10300
=> dm: add new openapi config about import_mode

faq/backup-and-restore-faq.md, system-variables.md
https://github.com/pingcap/tidb/issues/38045 was fixed in v7.0.0 and https://github.com/pingcap/tidb/issues/37207 was fixed in v6.6.0. This PR updates the description of these two issues in FAQ document. https://github.com/pingcap/docs-cn/pull/15366 will remove these issues from v7.3, v7.4, v7.5, and master branch.
- Other …
=> br: update PITR FAQ for v7.1 branch

basic-features.md
closes https://github.com/pingcap/docs-cn/issues/15719
=> use code format in basic features

troubleshoot-tidb-oom.md
This PR updates the outdated OOM message in the docs.
=> update the error message of OOM

system-variables.md
require_secure_transport is forbidden to be set to on when SEM is enabled.
=> v7.1.2: update doc of `require_secure_transport`

migrate-from-tidb-to-mysql.md, replicate-data-to-kafka.md, ticdc/deploy-ticdc.md, ticdc/integrate-confluent-using-ticdc.md, ticdc/ticdc-changefeed-overview.md
=> ticdc: fix tiup cmd, change `tiup ctl:v<CLUSTER_VERSION> cdc` to `tiup cdc:v<CLUSTER_VERSION> cli`

releases/release-6.5.6.md, releases/release-7.1.3.md, ticdc/ticdc-changefeed-config.md
=> changefeed: add the info about configuring SQL mode

tiflash/create-tiflash-replicas.md
Close https://github.com/pingcap/docs-cn/issues/15893
=> fix rendering issue in create-tiflash-replicas

sql-mode.md
I added some single backticks to inline codes, making this document more unified with the English one.
给行内代码添加了单引号，让这个文件更加符合markdown rule，同时与英文的文档也更加一致
=> add single backticks to inline code

upgrade-tidb-using-tiup.md
When upgrading TiDB, check the DDL and backup status before checking cluster health.
=> upgrade TiDB: check DDL and backup status before checking cluster health

upgrade-monitoring-services.md
=> upgrade-monitoring-services: fix path errors

tidb-lightning/tidb-lightning-configuration.md
=> tidb-lightning: replace `NO_ENGINE_SUBSTITUTION` with `NO_AUTO_CREATE_USER`

system-variables.md
=> system-variable: indicate that max_allowed_packet is ready only in the session scope

follower-read.md
=> 补充说明同一事务内的调度策略

tiflash/tiflash-configuration.md
- Other reference link(s): https://github.com/pingcap/tiflash/pull/8616  https://github.com/pingcap/tiflash/pull/8569
=> Change the default log level of tiflash

control-execution-plan.md, optimizer-fix-controls.md, releases/release-7.1.0.md, releases/release-7.2.0.md, sql-non-prepared-plan-cache.md, system-variables.md
v6.5.7 supports tidb_opt_fix_control
=> update tidb_opt_fix_control for v6.5.7

releases/release-7.1.0.md, releases/release-7.2.0.md, statistics.md, tidb-configuration-file.md
v6.5.7 supports force-init-stats.
=> update force-init-stats for v6.5.7

TOC.md, releases/release-6.5.7.md, releases/release-notes.md, releases/release-timeline.md
=> update 6.5.7 release notes

releases/release-6.5.7.md
=> remove tidb_opt_fix_control from 6.5.7 release notes

dm/task-configuration-file-full.md, system-variables.md
=> dm: add a note about DM to `sql_require_primary_key`

tikv-control.md
The output of bad-ssts command is not up-to-date
- This PR is translated from: https://github.com/pingcap/docs/pull/14358
=> Update tikv-ctl bad-ssts output

control-execution-plan.md, optimizer-fix-controls.md, releases/release-7.1.0.md, releases/release-7.2.0.md, sql-non-prepared-plan-cache.md, system-variables.md
=> fix: tidb_opt_fix_control is introduced in v6.5.3

TOC.md, control-execution-plan.md, optimizer-fix-controls.md, system-variables.md
=> update tidb_opt_fix_control for v6.5

ticdc/ticdc-changefeed-config.md, ticdc/ticdc-sink-to-kafka.md
fix a typo introduced in https://github.com/pingcap/docs-cn/pull/15356
=> ticdc: fix typo tokne -> token

choose-index.md
=> doc-cn: add multi value index case from cnf and dnf combination

auto-random.md, system-variables.md
- Other reference link(s): close https://github.com/pingcap/docs-cn/issues/15959
=> Add explanation for auto_random ID allocation

dynamic-config.md
- Other reference link(s): https://github.com/tikv/tikv/pull/16049
=> tikv: add new dynamic config item "readpool.unified.max-tasks-per-worker"

tikv-control.md
=> tikv: fix dead code link

oracle-functions-to-tidb.md
According to oracle's doc of [nvl2(expr1, expr2, expr3)](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/NVL.html#GUID-3AB61E54-9201-4D6A-B48A-79F4C4A034B2),
> If expr1 is not null, then NVL2 returns expr2. If expr1 is null, then NVL2 returns expr3.
thus, the equivalent version in tidb should be `if(expr1 is not NULL, expr2, expr3)`. This PR fixes the sample shown in the `函数对照表` table of  'oracle-functions-to-tidb'. …
=> Fix the example of tidb's equivalent function for oracle's nvl2

resources/tidb-terms.md
=> resources: refine format for tidb-terms.md

develop/dev-guide-choose-driver-or-orm.md
几处“如果你使用的是”后面的Maven/Gradle格式不统一
=> develop: refine format in dev-guide-choose-driver-or-orm.md

temp.md, tidb-configuration-file.md
TiProxy is going to be released. This option is no more a pure warning.
- This PR is translated from: https://github.com/pingcap/docs/pull/15635
=> tidb: fix config value for tiproxy

.vaunt/config.yaml
Update PR merge dates and fix conditions for PR bonus points
=> Update config.yaml for TiDB Docs Dash

functions-and-operators/string-functions.md
Update the introduction of UCASE() and UNHEX(), fix https://github.com/pingcap/docs-cn/issues/15952
=> Update the introduction of UCASE() and UNHEX()

dm/task-configuration-file-full.md, get-started-with-tidb-lightning.md, tidb-lightning/tidb-lightning-command-line-full.md, tidb-lightning/tidb-lightning-configuration.md, tidb-lightning/tidb-lightning-physical-import-mode-usage.md
=> tidb-lightning: tidb.pd-addr supports multiple addresses

system-variables.md
- This PR is translated from:https://github.com/pingcap/docs/pull/15883
=> system-variable: add `tidb_analyze_distsql_scan_concurrency `

ticdc/ticdc-csv.md
=> ticdc: add explanation for csv delimiter config

identify-slow-queries.md, information-schema/information-schema-slow-query.md, mysql-schema.md, statement-summary-tables.md, system-variables.md
=> resource_control: enhance observability

dm/dm-compatibility-catalog.md, dm/dm-overview.md
DM supports MySQL 8.0 officially.
- Other reference link(s): https://github.com/pingcap/tiflow/pull/8373
=> DM: support for MySQL 8.0 GA

system-variables.md, temp.md
…as 128
- This PR is translated from: https://github.com/pingcap/docs/pull/15865
- Other reference link(s): https://github.com/pingcap/tidb/issues/48674
=> system-variables: set default tidb_auto_analyze_partition_batch_size as 128

migrate-from-parquet-files-to-tidb.md
=> data migration: add an example Parquet file name

ticdc/ticdc-canal-json.md
TiDB v7.6.0 supports compatibility with the data format of the official Canal
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/15579
=> ticdc: v7.6.0 supports compatibility with the data format of the official Canal

tidb-troubleshooting-map.md
=> Add MDL for DDL troubleshooting

tiup/tiup-cluster-topology-reference.md
=> tiup: add more fields and links from customized-montior-in-tiup-environment.md

support.md
企业版网站域名迁移至： https://www.pingcap.cn/
=> support: fix url, enterprise

quick-start-with-htap.md
Add `USE test` command before running the SQL to avoid error like "ERROR 1046 (3D000): No database selected".
- Other reference link(s):https://github.com/pingcap/docs-cn/issues/15774
=> Update quick-start-with-htap.md to add `USE test` command  

hardware-and-software-requirements.md
- This PR is translated from: https://github.com/pingcap/docs/pull/15669
=> update os support page

sql-statements/sql-statement-admin-cancel-ddl.md, sql-statements/sql-statement-kill.md
增加从v6.2.0版本开始，使用kill语句也能取消ddl作业的描述内容。
fix [#11069](https://github.com/pingcap/docs/issues/11069)
- This PR is translated from: https://github.com/pingcap/docs/pull/16124
=> 增加kill语句取消ddl作业的描述

develop/dev-guide-third-party-support.md
- This PR is translated from: https://github.com/pingcap/docs/pull/15187
=> develop: update the third party support table

develop/dev-guide-sample-application-python-peewee.md
Fix: #15956
update dev-guide-sample-application-python-peewee
=> develop: update dev-guide-sample-application-python-peewee

expression-syntax.md
更新链接， 
原仓库已不再维护： https://github.com/pingcap/parser 
更新为： https://github.com/pingcap/tidb/blob/master/pkg/parser/parser.y
=> fix link, parser.y

br/br-snapshot-guide.md
=> br: update new download method description

system-variables.md
translate docs to cn pr#15168
- This PR is translated from: https://github.com/pingcap/docs/pull/15168
=> Explain tidb_max_tiflash_threads default value -1 means

optimizer-hints.md
- [Added a reasonable example for INL_JOIN](https://github.com/pingcap/docs-cn/commit/c6d6e9c44fc7d9e5471019ccebb94b6b4157582a)
None
=> docs(tidb) add a reasonable example for INL_JOIN

releases/release-7.6.0.md
br: remove --tikv-max-restore-concurrency
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16353
=> br: remove --tikv-max-restore-concurrency

README.md
1. Add the info about v7.6.
2. Add the info about archived docs.
=> README.md: add info about v7.6

tidb-roadmap.md
=> tidb-roadmap.md: add a link to the v7.6 release notes

storage-engine/titan-configuration.md, storage-engine/titan-overview.md
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/15954
=> update titan doc to provide guidline on min-blob-size

.vaunt/config.yaml
=> Update config.yaml for the PR submission time stamp

tikv-configuration-file.md
这个 PR 修正了对参数 `log-backup.initial-scan-rate-limit` 的默认值的误导性描述。
实际上该配置项参数为 `ReadableSize`，并不是 `MiB`，直接传递 `60` 进去会导致增量扫被限速为 `60B/s`，进而导致增量扫卡住。
=> log_backup: fix initial scan rate limit description

templates/template.tex
Added tex commands to `templates/template.tex` to tweak Table's display of generated pdf file:
- Set the entire table to left aligned.
- Set the columns filled with the page's width.
- Corrected the pdf file's metadata parameter. This is related to [https://github.com/pingcap/docs/issues/15983]().
Fix [issue#186](https://github.com/pingcap/website-docs/issues/186) of pingcap/website-docs
Note: For truncated text, I found that the single column's with is controlled by **markdown source file** rather than latex template, see [Pandoc documention](https://pandoc.org/chunkedhtml-demo/8.9-tables.html):
> For example ---|- would make the first column 3/4 and the second column 1/4 of the full text width.
I tried to modify markdown file to adjust table column's width (changes of markdown file is …
=> Modify table layout of pdf tex template

ticdc/ticdc-bidirectional-replication.md, ticdc/ticdc-changefeed-config.md
=> ticdc: add example of how to show bdr role

templates/template.tex
=> pdf: implement automatic underscore wrapping table cells

tiflash/tiflash-configuration.md
* The config item in `flash.flash_cluster` are deprecated since v6.0 https://github.com/pingcap/tidb/issues/29924
* Align the style of `flash.proxy` with other config items
- This PR is translated from: https://github.com/pingcap/docs/pull/16071
- Other reference link(s): https://github.com/pingcap/tidb/issues/29924
=> tiflash: Clean deprecated configs; align style of flash.proxy

develop/dev-guide-sample-application-python-django.md
Fix: #15957
update dev-guide-sample-application-python-django
=> Debug TiDB Documentation: 使用 Django 连接到 TiDB

TOC.md
- Moved the Navicat doc after the MySQL Workbench connection doc (fix the wrong sequences in https://github.com/pingcap/docs-cn/pull/16165/files)
- This change is only needed for the master branch because the sequence in other branches have already been corrected.
=> develop: adjust the sequence of two GUI Database Tool connection docs

TOC.md, migrate-from-mariadb.md
- This PR is translated from:https://github.com/pingcap/docs/pull/15492
=> MariaDB Migration

tikv-configuration-file.md
=> [v6.5.8] tikv configuration doc: add gc thread number

develop/dev-guide-third-party-support.md
Use absolute URLs in `<a href="">`
=> develop: use absolute URLs in href

.vaunt/add-tidb-docs-dash-badge.md
=> add-tidb-docs-dash-badge.md: correct a link

develop/dev-guide-overview.md
=> dev guide: update link for backend sql courses

sql-statements/sql-statement-truncate.md, temp.md
Use ebnf diagram for `TRUNCATE`
- This PR is translated from: https://github.com/pingcap/docs/pull/16050
https://github.com/pingcap/docs/issues/4389
=> truncate statement ebnf

dm/dm-overview.md, error-codes.md, faq/tidb-faq.md, generated-columns.md, overview.md, temp.md
- Update for MySQL 8.0 compatibility
- Update for Foreign Key support
- This PR is translated from: https://github.com/pingcap/docs/pull/16270
=> More MySQL 8.x compatibility updates

tikv-configuration-file.md
=> fix the description of wal_dir

functions-and-operators/string-functions.md, temp.md
- Fix (https://github.com/pingcap/docs/issues/15483)  
- Describe the `CHAR_LENGTH()` and `CHARACTER_LENGTH()`  functions
- Add two examples that illustrate how `CHAR_LENGTH()` works
- Add a blockquote under the second `CHAR_LENGTH()` example to indicate that the example operates under the assumption that a SQL database exist
- This PR is …
=> functions-and-operators: enrich instructions for string functions CHAR_LENGTH() and CHARACTER_LENGTH #15483

develop/dev-guide-gui-mysql-workbench.md, develop/dev-guide-gui-navicat.md
Fix admonition syntax of "Tip" in develop documents.
=> develop: fix admonitions

releases/release-6.5.7.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/49782
=> add missing release note in 6.5.7

develop/dev-guide-sample-application-ruby-mysql2.md, develop/dev-guide-sample-application-ruby-rails.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/16474
=> develop: replace angle brackets with curly brackets

TOC.md, develop/dev-guide-sample-application-aws-lambda.md, develop/dev-guide-sample-application-nextjs.md, develop/dev-guide-sample-application-nodejs-sequelize.md
- This PR is translated from: https://github.com/pingcap/docs/pull/14705 https://github.com/pingcap/docs/pull/14532
=> add dev guide(zh)

external-storage-uri.md
=> reference: add an example for S3 URI in sink-uri

sql-statements/sql-statement-show-profiles.md, temp.md
Add a link to statement summary tables to help users looking for how to get profiling information in TiDB.
- This PR is translated from: https://github.com/pingcap/docs/pull/16187
=> Update sql-statement-show-profiles.md to reference statement summary tables

releases/release-6.1.0.md
This PR temporarily updates `<br/>` to `<br>` to test the build watcher. After the test, this PR will be reverted.
=> chore: test the build watcher 

releases/release-6.1.0.md
=> Revert "chore: test the build watcher "

pd-control.md
=> pd-ctl: add resource-manager command

tiflash/tiflash-disaggregated-and-s3.md
=> tiflash: fix scale-in command argument -R

functions-and-operators/string-functions.md, temp.md
Fix description errors in https://github.com/pingcap/docs-cn/pull/16112
=> fix desc for String Function SUBSTRING_INDEX () and TO_BASE64

configure-placement-rules.md, tiflash/troubleshoot-tiflash.md
Ref https://github.com/tikv/pd/pull/3163
=> update placement-rules doc about max-replica

identify-slow-queries.md
fix: transactin_ts in slow query is start_ts, not commit_ts
=> fix: transactin_ts in slow query is start_ts, not commit_ts

tiup/customized-montior-in-tiup-environment.md
Align with changes in https://github.com/pingcap/docs/pull/8007/commits/92b3cf8b33e3e1db547d97266f9ab12271a1b2f1
- Other reference link(s): https://github.com/pingcap/docs/pull/8007
=> customize-montior: remove a sentence with duplicated meaning 

ticdc/ticdc-sink-to-pulsar.md
=> ticdc: fix pulsar sink documentation error

system-variables.md
`require_secure_transport` is forbidden to be set to `on` when SEM is enabled.
Note that the TiDB PR is not merged into v7.5.x or master.
- Other reference link(s): https://github.com/pingcap/tidb/pull/48735
=> update doc of `require_secure_transport`

upgrade-tidb-using-tiup.md
=> v7.6: update upgrade-tidb-using-tiup.md

tidb-configuration-file.md
- This PR is translated from:https://github.com/pingcap/docs/pull/16336
=> tidb: add status.record-db-label docs

releases/release-7.5.0.md, releases/release-7.6.0.md
As in title
- [x ] v7.5 (TiDB 7.5 versions)
=> release-7.5.0 release notes: add two TiCDC parameter changes 

sql-statements/sql-statement-analyze-table.md
Follow up: https://github.com/pingcap/docs-cn/pull/15270
We should drop this syntax on the docs. This feature was removed by this PR: https://github.com/pingcap/tidb/pull/47544/files
Right now, if you try it on TiDB you will get
```console
mysql> analyze incremental table t index idx;
ERROR 1105 (HY000): the incremental analyze feature has already been removed in TiDB v7.5.0, so this will have no effect
```
https://github.com/pingcap/docs-cn/pull/15270
=> tidb: remove INCREMENTAL syntax of analyze table statement

develop/dev-guide-choose-driver-or-orm.md
- This PR is translated from: https://github.com/pingcap/docs/pull/16600
=> update the compatibility issue between Connector/J 8.0 and TiDB v7.5

tiflash/tiflash-disaggregated-and-s3.md
Fix typo
- This PR is translated from: https://github.com/pingcap/docs/pull/16560
=> fix: mycuster should be mycluster

tiproxy/tiproxy-overview.md
Add a warning for tiproxy v0.2.0.
=> tiproxy: add experimental warning for v0.2.0

enable-tls-between-clients-and-servers.md, tidb-configuration-file.md
The support of TLS v1.1 and v1.0 have been removed in the latest version.
- This PR is translated from: https://github.com/pingcap/docs/pull/16221
=> remove support for tls 1.1 and 1.0

tikv-configuration-file.md
=> v7.5.1: tikv configuration doc: add gc thread number

best-practices/haproxy-best-practices.md
1. The least hardware configuration for HAProxy was too low, making it almost impossible to work for users. I've added the highest QPS for this configuration so that users can estimate the configuration for their workload.
2. The recommended memory is inconsistent with HAProxy official docs.
=> HAProxy: update the recommended hardware configuration for HAProxy

troubleshoot-lock-conflicts.md
Translate https://github.com/pingcap/docs/pull/16619 to Chinese.
- This PR is translated from:https://github.com/pingcap/docs/pull/16619
=> use cluster_tidb_trx for lock troubleshooting

ticdc/ticdc-open-api-v2.md
https://github.com/pingcap/tiflow/pull/10507
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/16204
=> cdc: Remove useless code in filter

garbage-collection-overview.md
- [x ] v7.6 (TiDB 7.6 versions)
=> garbage-collection-overview: fix a typo

tikv-configuration-file.md
=> v7.1.4: tikv configuration doc: add gc thread number

dumpling-overview.md, temp.md
I was reading the section regarding Dumpling's GC auto extension feature.
I understood that if data is less than 1 TB this feature works, but if larger it does not.
Given this, I thought the part that I changed could be a typo. Thus raised this fix.
Changed "more" to "less"
https://docs.pingcap.com/tidb/stable/dumpling-overview
translated …
=> Correct typo in Dumpling's GC auto extend feature spec

tidb-resource-control.md
=> resource-control: reduce misunderstandings

sql-statements/sql-statement-alter-index.md, sql-statements/sql-statement-create-index.md, system-variables.md
https://github.com/pingcap/docs/pull/16762
https://github.com/pingcap/tidb/pull/50654
=> *: add tidb_opt_use_invisible_indexes

tiflash/tiflash-supported-pushdown-calculations.md
=> update tiflash function pushdown list to add `power`

optimistic-transaction.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/16592
=> txn: add description about deprecating the tidb_disable_txn_auto_retry system variable 

ticdc/ticdc-filter.md
- Other reference link(s): https://github.com/pingcap/tiflow/pull/10644
=> Add sql mode format restrictions to expr in ticdc filter

statistics.md, system-variables.md
Added the description for the `tidb_enable_auto_analyze_priority_queue` variable.
=> tidb: add the description for `tidb_enable_auto_analyze_priority_queue`

system-variables.md
Update the description for deprecating the `tidb_disable_txn_auto_retry` system variable in v8.0.0
- Other reference link(s): v7.6 PR https://github.com/pingcap/docs-cn/pull/16010
=> txn: deprecate the tidb_disable_txn_auto_retry system variable

choose-index.md, sql-prepared-plan-cache.md
=> planner: update Plan Cache doc

tikv-configuration-file.md
Update minimum value for initial-scan-rate-limit.
https://github.com/tikv/tikv/pull/16485
- This PR is translated from:https://github.com/pingcap/docs/pull/16549
=> Update minimum value for initial-scan-rate-limit

configure-memory-usage.md, system-variables.md
=> Spill of parallel aggregation in TiDB

tikv-configuration-file.md, tune-tikv-thread-performance.md
- Other reference link(s): issue: https://github.com/tikv/tikv/issues/16614, tikv-pr: https://github.com/tikv/tikv/pull/16615
=> tikv: enable async-io by setting `raftstore.store-io-pool-size == 1` as default.

system-variables.md
=> sys-var: add `tidb_schema_cache_size`

develop/dev-guide-update-data.md
=> Update dev-guide-update-data.md to fix a Chinese grammar problem

tiproxy/tiproxy-overview.md
Fix the issue that the images of TiProxy are not displayed:
=> TiProxy: update images

pd-microservices.md
=> pd-microservices: fix operator link 

resources/cdnfresh.txt
Add TiDB Operator v1.6 to PDF list
=> add k8s v1.6 to pdf list

sql-plan-replayer.md
- This PR is translated from:https://github.com/pingcap/docs/pull/16805
=> docs: Disable auto_analyze for plan_replayer

encryption-at-rest.md, sql-statements/sql-statement-import-into.md
=> add warnings for two experimental features:  Google Cloud KMS and IMPORT INTO SELECT

dm/deploy-a-dm-cluster-using-tiup-offline.md, dm/deploy-a-dm-cluster-using-tiup.md, dm/dm-error-handling.md, dm/dm-faq.md, dm/quick-start-with-dm.md, dm/shard-merge-best-practices.md, tidb-troubleshooting-map.md
https://github.com/pingcap/dm has been archived. DM has moved to https://github.com/pingcap/tiflow/tree/master/dm
- This PR is translated from: https://github.com/pingcap/docs/pull/16737
=> DM: Update GitHub URLs for DM

_index.md
=> V8.0.0: update learning path

ticdc/ticdc-faq.md, ticdc/ticdc-open-api-v2.md, ticdc/ticdc-open-api.md, ticdc/ticdc-sink-to-kafka.md
Remove canal protocol in TiCDC. The protocol has not been tested officially.
- This PR is translated from: https://github.com/pingcap/docs/pull/16773
=> ticdc: remove canal protocol

tidb-lightning/tidb-lightning-configuration.md, tidb-lightning/tidb-lightning-error-resolution.md, tidb-lightning/tidb-lightning-physical-import-mode-usage.md
- This PR is translated from: https://github.com/pingcap/docs/pull/16861
=> Revise conflict data resolution enhancement during data import

tiup/tiup-playground.md
=> tiup: Update tiup-playground.md

system-variables.md
=> fix descriptions for tidb_stmt_summary_max_sql_length

hardware-and-software-requirements.md
As in the title, fix https://asktug.com/t/topic/1023076
=> hardware-and-software-requirements: fix the name of the instruction set

_docHome.md
=> _docHome: update MySQL info

sql-prepared-plan-cache.md
One critical issue 51407 was found which could causes severe issue when prepared plan cache is enabled.  The doc of prepared plan cache was update with the description and workarounds.
=> include the description of one critical Issue 51407 in doc

ticdc/ticdc-open-api-v2.md, ticdc/ticdc-open-api.md
=> ticdc: fix incompatiable config description

basic-features.md
Update the link for invisible indexes to point correctly from `/sql-statements/sql-statement-add-index.md` to `/sql-statements/sql-statement-create-index.md#invisible-index`.
=> basic features: fix anchor link

best-practices/haproxy-best-practices.md, best-practices/java-app-best-practices.md
Add summary to `best-practices/*.md`
=> best-practices: add summary to docs

sql-statements/sql-statement-admin-show-telemetry.md, sql-statements/sql-statement-admin.md, sql-statements/sql-statement-flashback-table.md, sql-statements/sql-statement-recover-table.md, sql-statements/sql-statement-split-region.md
Add summary to `sql-statements/*.md`
=> sql-statements: add summary to docs

functions-and-operators/string-functions.md
Enrich instructions for the string function LPAD().
- This PR is translated from: https://github.com/pingcap/docs/pull/16946
=> Add LPAD() example

tidb-lightning/monitor-tidb-lightning.md, tidb-lightning/tidb-lightning-checkpoints.md, tidb-lightning/tidb-lightning-faq.md
Add summary to `tidb-lightning/*.md`
=> tidb-lightning: add summary to docs

dm/deploy-a-dm-cluster-using-binary.md, dm/dm-arch.md, dm/dm-config-overview.md, dm/dm-ddl-compatible.md, dm/dm-faq.md, dm/dm-master-configuration-file.md, dm/dm-release-notes.md, dm/dm-source-configuration-file.md, dm/dm-task-configuration-guide.md, dm/dm-worker-configuration-file.md, dm/dm-worker-intro.md, dm/feature-expression-filter.md, dm/feature-online-ddl.md, dm/feature-shard-merge.md, dm/manually-handling-sharding-ddl-locks.md, dm/migrate-data-using-dm.md, dm/task-configuration-file-full.md
=> dm: add summary to docs

sync-diff-inspector/route-diff.md, sync-diff-inspector/shard-diff.md, sync-diff-inspector/sync-diff-inspector-overview.md
Add summary to `sync-diff-inspector/*.md`
=> sync-diff-inspector: add summary to docs

ticdc/ticdc-overview.md, ticdc/ticdc-upstream-downstream-check.md
=> ticdc: add summary to docs

tiup/tiup-command-mirror-genkey.md, tiup/tiup-component-dm-disable.md, tiup/tiup-component-dm-start.md
=> tiup: add summary to docs

information-schema/information-schema.md
Add summary to `information-schema/*.md`
=> information-schema: add summary to docs

tiflash/maintain-tiflash.md, tiflash/monitor-tiflash.md, tiflash/tiflash-alert-rules.md, tiflash/tiflash-command-line-flags.md, tiflash/tiflash-configuration.md, tiflash/tiflash-overview.md
=> tiflash: add summary to docs

tidb-binlog/bidirectional-replication-between-tidb-clusters.md, tidb-binlog/binlog-consumer-client.md, tidb-binlog/deploy-tidb-binlog.md, tidb-binlog/get-started-with-tidb-binlog.md, tidb-binlog/handle-tidb-binlog-errors.md, tidb-binlog/maintain-tidb-binlog-cluster.md, tidb-binlog/monitor-tidb-binlog-cluster.md, tidb-binlog/tidb-binlog-configuration-file.md, tidb-binlog/tidb-binlog-faq.md, tidb-binlog/tidb-binlog-overview.md, tidb-binlog/tidb-binlog-relay-log.md, tidb-binlog/tidb-binlog-reparo.md, tidb-binlog/troubleshoot-tidb-binlog.md, tidb-binlog/upgrade-tidb-binlog.md
Add summary to `tidb-binlog/*.md`
=> tidb-binlog: add summary to docs

clinic/quick-start-with-clinic.md
update UI elements on the Clinic Server login page
=> clinic: update UI elements on the login page

.github/pull_request_template.md, temp.md
Remove TiDB 5.0 from the PR template as it is EOL
- This PR is translated from: https://github.com/pingcap/docs/pull/17021
=> Remove TiDB 5.0 from PR template

dashboard/dashboard-profiling.md
=> Add perl dependency requirement for tikv heap profiling

two-data-centers-in-one-city-deployment.md
add dr-auto-sync configuration description
=> dr-autosync: add configuration description

functions-and-operators/string-functions.md
Add example for QUOTE()
- This PR is translated from: https://github.com/pingcap/docs/pull/16958
=> Add example for QUOTE()

ticdc/ticdc-behavior-change.md
=> cdc: fix the description about the behavior change

system-variables.md
=> Update fine grained shuffle stream count description

releases/release-timeline.md
Tag 8.0.0 as DMR.
docs https://github.com/pingcap/docs/pull/17135
- This PR is translated from: https://github.com/pingcap/docs/pull/17135
=> fix release-timeline

tikv-configuration-file.md
=> RocksDB: Add track-and-verify-wals-in-manifest desc

br/backup-and-restore-storages.md, br/backup-and-restore-use-cases.md
- This PR is translated from:https://github.com/pingcap/docs/pull/17111
=> br: TiDB 7.1+ checkpoint restore requires s3:DeleteObject permission

tidb-lightning/tidb-lightning-data-source.md
Fix the inline code format by adding the missing `
=> tidb-lightning: fix inline code format

sql-statements/sql-statement-set-password.md, sql-statements/sql-statement-show-variables.md, sql-statements/sql-statement-show-warnings.md, sql-statements/sql-statement-trace.md
Updates synopsis ebnf and examples for `SET PASSWORD`, `SHOW WARNINGS`, `SHOW VARIABLES`, `TRACE` statements.
- https://github.com/pingcap/docs/pull/16996
- https://github.com/pingcap/docs/pull/16998
- https://github.com/pingcap/docs/pull/17000
- https://github.com/pingcap/docs/pull/17002
=> sql-stmt: update ebnf for four statements

releases/release-6.5.9.md, releases/release-7.1.4.md
=> update release notes

data-type-default-values.md
=> *: default value tiny update

TOC.md, sql-statements/sql-statement-set-role.md, sql-statements/sql-statement-set-variable.md, sql-statements/sql-statement-show-create-sequence.md, sql-statements/sql-statement-show-placement-for.md, sql-statements/sql-statement-show-placement-labels.md, sql-statements/sql-statement-show-placement.md, sql-statements/sql-statement-show-stats-histograms.md, sql-statements/sql-statement-show-table-status.md, sql-statements/sql-statement-show-tables.md, sql-statements/sql-statement-with.md, user-defined-variables.md
- https://github.com/pingcap/docs/pull/17045
- https://github.com/pingcap/docs/pull/17047
- https://github.com/pingcap/docs/pull/17049
- https://github.com/pingcap/docs/pull/17051
- https://github.com/pingcap/docs/pull/17052
- https://github.com/pingcap/docs/pull/17053
- https://github.com/pingcap/docs/pull/17065
- …
=> sql statement: refined Synopsis

.github/pull_request_template.md, README.md
1. Mark v4.0/v5.0/v7.4 docs as archived
2. Remove v7.4 from PR tempalte
=> Mark v4.0/v5.0/v7.4 docs as archived

CONTRIBUTING.md
Removes descriptions about TiDB Docs Dash 2024 event, and adds how to preview EBNF diagrams
- This PR is translated from: https://github.com/pingcap/docs/pull/16610
=> Remove docs dash and add EBNF preview to contributing

dm/deploy-a-dm-cluster-using-tiup-offline.md
Fix https://asktug.com/t/topic/1022704
=> deploy-a-dm-cluster-using-tiup-offline: fix a command

sql-statements/sql-statement-show-builtins.md, sql-statements/sql-statement-show-engines.md, sql-statements/sql-statement-show-plugins.md, sql-statements/sql-statement-shutdown.md
Use ebnf+diagram instead of images
- This PR is translated from: https://github.com/pingcap/docs/pull/17009, https://github.com/pingcap/docs/pull/16994, https://github.com/pingcap/docs/pull/17004, https://github.com/pingcap/docs/pull/17006
=> ebnf: show builtins, show engines, show plugins, and shutdown

sql-statements/sql-statement-show-bindings.md, sql-statements/sql-statement-show-config.md, sql-statements/sql-statement-show-databases.md, sql-statements/sql-statement-show-privileges.md
Update synopsis from images to ebnf
- This PR is translated from: https://github.com/pingcap/docs/pull/17033, https://github.com/pingcap/docs/pull/17031, https://github.com/pingcap/docs/pull/17027, https://github.com/pingcap/docs/pull/17025
=> ebnf: show bindings, show databases, show privileges, show config

sql-statements/sql-statement-set-default-role.md, sql-statements/sql-statement-show-character-set.md, sql-statements/sql-statement-show-processlist.md, sql-statements/sql-statement-show-stats-meta.md
Update synopsis from images to ebnf
- This PR is translated from:https://github.com/pingcap/docs/pull/17043, https://github.com/pingcap/docs/pull/17035, https://github.com/pingcap/docs/pull/17023, https://github.com/pingcap/docs/pull/17020
=> ebnf: set default role, show charset, show processlist, show stats_meta

sql-statements/sql-statement-use.md
- Change `USE` docs to use ebnf
- Cleanup sqlgram files
- This PR is translated from: https://github.com/pingcap/docs/pull/16049
- Other reference link(s): https://github.com/pingcap/docs/issues/4389
=> sql: change USE to ebnf

dm/manually-handling-sharding-ddl-locks.md
=> dm: refine details format

hardware-and-software-requirements.md
=> *: add openEuler 22.03 LTS SP3

faq/monitor-faq.md, sql-statements/sql-statement-set-password.md, sql-statements/sql-statement-show-engines.md, sync-diff-inspector/sync-diff-inspector-overview.md, temp.md, ticdc/integrate-confluent-using-ticdc.md, tidb-lightning/tidb-lightning-error-resolution.md, tidb-troubleshooting-map.md
Fix all code blocks that are not properly closed, checked by using the following command:
```
git grep -IE '```[a-z\+]*$' | grep '\.md:' | grep -vE '```(sql|ebnf\+diagram|shell|json|bash|go|yaml|toml|log|sh|java|xml|dotenv|scala|csv|ts|js|ini|railroad\+diagram|yml|text|python|ruby|javascript|typescript|golang|properties|haproxy|powershell|prisma|gradle|dockerfile|txt|nginx)?$'
```
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guide …
=> Fix EBNF for SET PASSWORD and SHOW ENGINES

CONTRIBUTING.md
Update an inappropriate link and make the description clearer
=> Update the contributing link and description

functions-and-operators/miscellaneous-functions.md, temp.md
Closes #16816
- This PR is translated from: https://github.com/pingcap/docs/pull/16855
=> miscellaneous-functions: Update reference manual

functions-and-operators/control-flow-functions.md, temp.md
Closes #16821
- This PR is translated from: https://github.com/pingcap/docs/pull/16849
=> control-flow-functions: Update reference manual links

error-codes.md, sql-mode.md
- This PR is translated from:https://github.com/pingcap/docs/pull/17198  https://github.com/pingcap/docs/pull/17232
=> extend sql_mode docs & fix 8216 error code explanation

system-variables.md
=> Pipelined-DML: document incompatibility with BR

releases/release-8.0.0.md
- 优化了 INFORMATION_SCHEMA.TABLES，INFORMATION_SCHEMA.STATISTICS，INFORMATION_SCHEMA.KEY_COLUMN_USAGE，INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 的这 4 个系统表的查询性能，相比之前版本，性能最高有 100 倍的提升。
=> *: add performance improvement of system tables in release notes v8.0

functions-and-operators/information-functions.md, temp.md, tidb-configuration-file.md
Closes #16818
- This PR is translated from: https://github.com/pingcap/docs/pull/16853
=> information-functions: Update reference manual and more

tikv-configuration-file.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/17201
=> track-and-verify-wals-in-manifes: update supported versions

TOC.md
=> lightning: updated toc sections

enable-tls-between-components.md
fix pd cert allowed cn description, according https://github.com/tikv/pd/issues/5134 and https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/enable-tls-between-components#%E7%AC%AC%E4%BA%8C%E6%AD%A5%E9%83%A8%E7%BD%B2-tidb-%E9%9B%86%E7%BE%A4
=> fix pd cert allowed cn description

basic-features.md
Change the support info for PD microservices from `Y` to `E`
=> basic-features: fix the support info for PD microservices

system-variables.md
Updated the range of `tidb_auto_analyze_ratio`.
We don't allow users to set it to 0 anymore.
See https://github.com/pingcap/tidb/pull/52190
=> tidb: update tidb_auto_analyze_ratio range

mysql-schema.md
=> mysql schema: delete `request_unit_by_group` in v7.5.0

.github/workflows/ci.yaml, .github/workflows/link-fail-fast.yaml, .github/workflows/link.yaml, .github/workflows/media.yml, .github/workflows/prevent-deletion.yaml, .github/workflows/rebase.yml
- This PR is translated from:https://github.com/pingcap/docs/pull/17431
=> CI: Update actions

develop/dev-guide-sample-application-python-sqlalchemy.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/17286
=> add disconnect handling note when using sqlalchemy against TiDB Serverless

information-schema/information-schema-ddl-jobs.md, sql-statements/sql-statement-admin-show-ddl.md, temp.md
- Remove EBNF that's not part of `ADMIN SHOW DDL...`
- Add column descriptions for `ADMIN SHOW DDL` output
- Change `ADMIN SHOW DDL` output to vertical to make it more readable
- Add some common `JOB_TYPE`'s
- Add description for `CREATE_TIME` and `END_TIME` for the `ADMIN SHOW DDL JOBS` output.
- Add more links to the `See also`
- Fix EBNF to add `LIMIT n,m` in addition to `LIMIT n OFFSET m`. (Thanks @kennytm )
For details, see [tips for choosing the affected …
=> Extend ADMIN SHOW DDL docs

sql-statements/sql-statement-select.md
Update the synopsis of `SELECT` from images to ebnf
- This PR is translated from: https://github.com/pingcap/docs/pull/17275
=> ebnf select

TOC.md
Make the wording in TOC.md consistent with the document title for [读写延迟增加](https://docs.pingcap.com/zh/tidb/v6.5/troubleshoot-cpu-issues), and with wording in the English version https://docs.pingcap.com/tidb/dev/troubleshoot-cpu-issues
=> Update toc wording for consistency

command-line-flags-for-tidb-configuration.md, system-variables.md
- Other reference link(s): pingcap/tidb#51306
=> tidb: add a new command line flag for redact

tidb-configuration-file.md
https://github.com/pingcap/docs/pull/17471
https://github.com/pingcap/tidb/issues/52102
=> tidb config: add `concurrently-init-stats`

mysql-compatibility.md
=> sql: add a link about regular expression compatibilit with MySQL

releases/release-6.5.6.md, releases/release-7.1.3.md, ticdc/ticdc-ddl.md
Remove useless description about sql mode in ddl for ticdc.
- Other reference link(s): https://github.com/pingcap/tiflow/pull/10644, https://github.com/pingcap/docs/pull/16626
=> ticdc: remove old description about SQL mode for DDL

mysql-compatibility.md
We now have this: [docs.pingcap.com/tidb/dev/sys-schema](https://docs.pingcap.com/tidb/dev/sys-schema)
I think it is best to remove this from the list and later on add specific sys schemas if required.
- This PR is translated from: https://github.com/pingcap/docs/pull/17469
=> mysql-compatibility: Remove sys schema

tidb-troubleshooting-map.md
update `tide-trouble-shooting-map.md`, update the tikv `server is busy` part
related Change Request https://github.com/pingcap/docs-cn/issues/8135
I'm participating the 2024-tidb-doc-dash https://github.com/orgs/pingcap/projects/51/views/3
=> feat(tidb-troubleshooting-map): 更新 TiKV 问题中 server is busy 指引说明

releases/release-7.5.0.md, tikv-configuration-file.md
Correct the descriptions of `raftstore.inspect-interval` in TiKV part, which has been changed from `500ms` to `100ms` by default from v7.5.
- Other reference link(s): https://github.com/tikv/tikv/pull/16087
=> raftstore: correct the description on `inspect-interval` from v7.5

tidb-lightning/tidb-lightning-configuration.md
=> TiDB Lightning: update the example value of max-record-rows

sql-statements/sql-statement-create-index.md, temp.md
- Uppercase SQL keywords
- Remove copyable hints
- Add more links
- This PR is translated from: https://github.com/pingcap/docs/pull/17220
=> Update CREATE INDEX statement docs

ticdc/ticdc-changefeed-config.md, ticdc/ticdc-csv.md
Add more doc info for the config output-old-value, which is introduced in v7.6
- Other reference link(s): https://github.com/pingcap/tiflow/pull/10542, https://github.com/pingcap/docs-cn/pull/16874
=> ticdc: add more info for config `output-old-value` in csv protocal

foreign-key.md
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/17357
=> sql: refine description about lightning

statistics.md
=> sql: fix an error in statistics

sql-statements/sql-statement-prepare.md
Add information about some limits
See also: https://github.com/pingcap/tidb/blob/cfbabfa705dbbc97c8e1e00af7f2d2620406304c/pkg/planner/core/plan_cache_utils.go#L101-L105
- This PR is translated from: https://github.com/pingcap/docs/pull/17309
=> Add info to PREPARE statement docs

get-started-with-tidb-lightning.md, tidb-lightning/troubleshoot-tidb-lightning.md
Fix the link of start `tidb-lightning`
=> lightning: fix the link of start `tidb-lightning`

tidb-lightning/tidb-lightning-configuration.md
Fix the behavior of the TiDB Lightning configuration item "tidb.tls"
=> lightning: fix the behavior of "tidb.tls"

functions-and-operators/set-operators.md
Remove ebnf images in `functions-and-operators/set-operators.md`
- This PR is translated from: https://github.com/pingcap/docs/pull/17466
=> remove ebnf images in set operator

system-variables.md
https://github.com/pingcap/docs/pull/17493
=> remove warning for tidb_analyze_partition_concurrency

sql-plan-replayer.md
Add description for how to **remove** `PLAN REPLAYER CAPTURE` to make docs complete
- Other reference link(s): https://github.com/pingcap/tidb/pull/41258
=> sql-plan-replayer: add description for `PLAN REPLAYER CAPTURE REMOVE`

ticdc/ticdc-overview.md
=> ticdc: add a new chapter in ticdc overview to show how we deal with data changes

.github/pull_request_template.md
=> pull_request_template: add v8.2

br/br-snapshot-guide.md, faq/backup-and-restore-faq.md
`https://github.com/pingcap/tidb/blob/master/br/pkg/restore/systable_restore.go` is moved to `https://github.com/pingcap/tidb/blob/master/br/pkg/restore/snap_client/systable_restore.go` in https://github.com/pingcap/tidb/pull/53197
=> br: fix broken links

ddl-introduction.md
=> remove multiple spaces

releases/release-7.5.0.md, releases/release-notes.md, releases/release-timeline.md
Add support for LTS release notes subscription
- This PR is translated from: https://github.com/pingcap/docs/pull/17605
- Other reference link(s): https://github.com/pingcap/docs-staging/pull/76
=> releases: add release notes subscription

tiproxy/tiproxy-overview.md
Fix a syntax error in the MDX code for machine translation. ref: https://github.com/pingcap/docs/pull/17636
=> fix MDX syntax error in machine translation

sql-statements/sql-statement-add-index.md, sql-statements/sql-statement-import-into.md, tidb-distributed-execution-framework.md
- This PR is translated from:https://github.com/pingcap/docs/pull/17522 https://github.com/pingcap/docs/pull/17637
=> Add links for DXF 

alert-rules.md
=> fix the description of tidb_query_duration

releases/release-7.5.1.md
This pr is used to supplement extra missing release docs on optimizing the HA ability of TiKV.
=> TiKV: supplement missing release docs on optimizing the HA.

functions-and-operators/tidb-functions.md, system-variables.md
- This PR is translated from:https://github.com/pingcap/docs/pull/17633
=> tidb_row_checksum(): Update docs

mysql-schema.md
Add missing system tables to v6.5 docs
Note: The added content in this PR already exists in v7.5 and later versions. See [mysql Schema](https://docs.pingcap.com/zh/tidb/v7.5/mysql-schema#%E5%85%83%E6%95%B0%E6%8D%AE%E9%94%81%E7%9B%B8%E5%85%B3%E7%B3%BB%E7%BB%9F%E8%A1%A8) (zh), [mysql Schema](https://docs.pingcap.com/tidb/v7.5/mysql-schema#system-tables-related-to-metadata-locks) (en). …
=> Add some table's description

best-practices/uuid.md
uuid: Link to functions etc
- This PR is translated from: https://github.com/pingcap/docs/pull/17618
=> uuid: Link to functions etc

tikv-configuration-file.md
=> Add cases for full compaction config for non-utc time zone

system-variables.md
=> system-variables: fix a typo for `hostname` description

information-schema/information-schema-tikv-region-status.md
Fix https://github.com/pingcap/docs-cn/issues/17482
=> information-schema: update the description for the tikv-region-status table

temp.md, ticdc/ticdc-sink-to-kafka.md
TiCDC supports multiple Kafka addresses, but the document does not indicate this. And `userinfo@` is unused.
- This PR is translated from: https://github.com/pingcap/docs/pull/17675
- Other reference link(s): https://asktug.com/t/topic/1026783
=> TiCDC: modify Kafka sink uri format

basic-features.md, temp.md
Remove fast analyze from the list of basic features [TiDB 功能概览 | PingCAP 文档中心](https://docs.pingcap.com/zh/tidb/stable/basic-features)
- This PR is translated from: https://github.com/pingcap/docs/pull/17727
=> Remove fast analyze from the list of basic features

ticdc/ticdc-overview.md
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/17325
=> ticdc: Fix sql case error

statistics.md
Removed the description about the 0 results of `STATS_META` after importing data, because the related issue is resolved in https://github.com/pingcap/tidb/issues/48562 starting from v7.6.0.
=> statistics: update the note for sampling rate

time-to-live.md
cloud: TiDB Serverless supports TTL
- This PR is translated from: https://github.com/pingcap/docs/pull/17676
=> cloud: TiDB Serverless supports TTL

tikv-configuration-file.md
=> track-and-verify-wals-in-manifest: add v7.5.2 as a supported version

sql-statements/sql-statement-import-into.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/53444
=> Update IMPORT INTO `SPLIT_FILE`

migrate-from-csv-files-to-tidb.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/53444
=> lightning: add description about terminator for strict-format CSV files

system-variables.md
Adds the type info for the `tidb_adaptive_closest_read_threshold` system variable
=> Add type info for tidb_adaptive_closest_read_threshold

troubleshoot-tidb-oom.md
update the incorrect command, add double quotes
=> troubleshoot-tidb-oom：update the incorrect command, add double quotes

dm/deploy-a-dm-cluster-using-tiup.md
=> DM: add a step about encrypting the database password

sql-statements/sql-statement-show-create-database.md
Correct the EBNF for SHOW CREATE DATABASE
- This PR is translated from: https://github.com/pingcap/docs/pull/17155
=> Fix EBNF for SHOW CREATE DATABASE

tidb-lightning/tidb-lightning-configuration.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/47414
=> tidb lightning: expose [tidb.session-vars] in lightning config

ticdc/ticdc-changefeed-config.md, ticdc/ticdc-sink-to-kafka.md
- This PR is translated from: https://github.com/pingcap/docs/pull/16396
=> ticdc: fix index config of kafka dispatcher

ticdc/ticdc-overview.md
=> ticdc: remove duplicated words

sql-statements/sql-statement-alter-table.md, sql-statements/sql-statement-create-index.md, sql-statements/sql-statement-create-table.md
- This PR is translated from:https://github.com/hfxsd/docs/pull/1
=> sql: Update EBNF related to indexing

sql-statements/sql-statement-add-index.md, sql-statements/sql-statement-create-index.md, sql-statements/sql-statement-create-table.md, sql-statements/sql-statement-show-indexes.md
- This PR is translated from:https://github.com/pingcap/docs/pull/17876
=> sql: add a note about `FULLTEXT`

ticdc/ticdc-sink-to-kafka.md
=> ticdc: clarify description about compression

configure-memory-usage.md, releases/release-8.0.0.md, system-variables.md
=> Rename `tidb_enable_concurrent_hashagg_spill` to `tidb_enable_parallel_hashagg_spill`

temp.md, tiflash/tiflash-results-materialization.md
modify samples for serverless, and add note for create tiflash replica
- This PR is translated from: https://github.com/pingcap/docs/pull/17878
=> modify the count of TiFlash replicas

best-practices/grafana-monitor-best-practices.md
fix the default port of TiKV servers from 20181 to 20180
=> tikv: fix default port from 20181 to 20180

ticdc/ticdc-ddl.md
=> ticdc: add event filter example

sql-plan-replayer.md
fix typo: change 'PLAN PLAYER CAPTURE' to 'PLAN REPLAYER CAPTURE'
```
mysql> PLAN PLAYER CAPTURE 'example_sql' 'example_plan';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 11 near "PLAYER CAPTURE 'example_sql' 'example_plan'"
``` …
=> fix typo: change 'PLAN PLAYER CAPTURE' to 'PLAN REPLAYER CAPTURE'

metadata-lock.md
fix error message of 8028 in metadata lock from "Error 8028: Information schema is changed" to "ERROR 8028 (HY000): public column a has changed"
=> fix error message of 8028 in metadata lock

migrate-with-more-columns-downstream.md
Fix https://asktug.com/t/topic/1028156
=> dm: fix the command for querying migration status

develop/dev-guide-choose-driver-or-orm.md
=> feat: updated suggest jdbc to 8.x

sql-statements/sql-statement-create-index.md, system-variables.md
1. The default value of `tidb_allow_function_for_expression_index` was incorrect as it was formatted not a single string, but as a set of strings.
2. Link from the variable to the expression index doc
3. Link to the functions from the expression index doc
- This PR is translated from: https://github.com/pingcap/docs/pull/17690
- Other …
=> Update docs for tidb_allow_function_for_expression_index

_index.md
=> v8.1: fix the link to roadmap

pd-control.md
Add a description for `scheduler config evict-leader-scheduler` in the PD control doc.
- Other reference link(s): https://github.com/tikv/pd/pull/2206
=> pd-control: add description for `scheduler config evict-leader-scheduler`

develop/dev-guide-choose-driver-or-orm.md, develop/dev-guide-transaction-restraints.md
=> feat: adjust description of hibernate

cached-tables.md
- This PR is translated from: https://github.com/pingcap/docs/pull/18000
=> cached table: add links

hardware-and-software-requirements.md
Add descriptions about CentOS 7 EOL and CentOS Stream 8 EOL
**Note:** "CentOS 7" also exists in many other documents, which will be updated as needed later in another PR.
=> Add CentOS 7 EOL to OS descriptions

system-variables.md
ref https://github.com/pingcap/docs/pull/17892
=> change the default value of `tidb_enable_historical_stats` to `OFF`

system-variables.md
ref https://github.com/pingcap/docs/pull/17894
=> *: adaptive analyze scan concurrency

grafana-tikv-dashboard.md, performance-tuning-methods.md
- Fix several typos
- Update wording and format
- Update punctuation in Grafana TiKV dashboard for consistency
Note: Some issues don't exist in the English version [Performance Analysis and Tuning | PingCAP Docs](https://docs.pingcap.com/tidb/stable/performance-tuning-methods).
- [Performance Analysis and …
=> Fix several typos and update wording for perf tuning

resources/cdnfresh.txt
=> cdnfresh.txt: add v8.2 PDF

grafana-tikv-dashboard.md
- Other reference link(s): https://github.com/tikv/tikv/issues/16837
=> tikv-grafana: add compaction job size(files) metric

ticdc/ticdc-behavior-change.md
=> ticdc: add more description about how cdc split update kv entries 

develop/dev-guide-build-cluster-in-cloud.md, develop/dev-guide-proxysql-integration.md
Update outdated links
- This PR is translated from: https://github.com/pingcap/docs/pull/18096
=> Update outdated https://en.pingcap.com/ links

upgrade-tidb-using-tiup.md
- This PR is translated from:https://github.com/pingcap/docs/pull/17952
=> tiup: add a ref to limitation on users operation during upgrade using tiup 

br/br-pitr-guide.md
Add link to BR monitoring and alert
=> br: link to BR monitoring and alert

TOC.md
Update wording for collation in `TOC.md` to make it consistent with that in [字符集和排序规则 | PingCAP 文档中心](https://docs.pingcap.com/zh/tidb/stable/character-set-and-collation). It seems that "规则" was mistakenly removed in https://github.com/pingcap/docs-cn/pull/8101. …
=> toc: update wording for collation

sql-statements/sql-statement-show-builtins.md
- This PR is translated from: https://github.com/pingcap/docs/pull/18084
=> Update builtins output

optimizer-hints.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/17119
=> *: improve INL_HASH_JOIN document about collation incompatibility

sql-statements/sql-statement-admin-cancel-ddl.md, sql-statements/sql-statement-admin-check-table-index.md, sql-statements/sql-statement-admin-checksum-table.md, sql-statements/sql-statement-admin-pause-ddl.md, sql-statements/sql-statement-admin-recover.md, sql-statements/sql-statement-admin-resume-ddl.md, sql-statements/sql-statement-admin-show-ddl.md, sql-statements/sql-statement-admin.md, sql-statements/sql-statement-import-into.md, temp.md
1. Some pages about specific admin statements also had EBNF for other admin statements.
2. Added some info to the page about `ADMIN CHECKSUM TABLE` about what checksum can be expected the same.
Closes #15468 
3. Formatted the `AdminStmt` EBNF to be more readable.
- This PR is translated from: https://github.com/pingcap/docs/pull/17617
- …
=> Update EBNF for admin statements and add checksum details

tidb-lightning/troubleshoot-tidb-lightning.md
=> fix 8025 solution

basic-features.md
=> basic-features.md: add a column for v8.2.0

TOC.md
=> *: fix a typo in toc

sql-statements/sql-statement-analyze-table.md
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/16647
=> sql: fix a synopsis error

sql-statements/sql-statement-admin-show-ddl.md
The EBNF didn't correctly indicate that `ADMIN SHOW DDL` is a valid statement
- This PR is translated from: https://github.com/pingcap/docs/pull/18153
=> admin show ddl: Fix EBNF

develop/dev-guide-sample-application-nodejs-prisma.md, temp.md
Fix https://github.com/pingcap/docs-cn/issues/14740
- This PR is translated from: https://github.com/pingcap/docs/pull/15552
=> update the MySQL version to 8.0 for `server-version`

clinic/clinic-data-instruction-for-tiup.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/17911
=> Clinic: Various fixes

functions-and-operators/functions-and-operators-overview.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/17712
=> Update function and operator overview

partitioned-table.md
=> removed an English sentence in partitioned-table.md

functions-and-operators/expressions-pushed-down.md, functions-and-operators/window-functions.md, keywords.md, system-variables.md
- This PR is translated from:https://github.com/pingcap/docs/pull/17694
=> Update window function docs

releases/release-8.2.0.md
=> Add missing release note for issue tidb#53540

migration-overview.md
Redirect `https://docs.pingcap.com/tidb/stable/migrate-full-data-from-mysql` to `https://docs.pingcap.com/tidb/stable/migration-overview`.
=> add aliases for migrate-full-data-from-mysql

explain-joins.md
Keep the description of column name to be consistent with the command.
=> fix incorrect column name in Index Join

releases/release-7.4.0.md
Fix a broken Github link from `https://github.com/ZhuohaoHe` to `https://github.com/ZzzhHe`. ref: https://github.com/tikv/pd/pull/6996#issuecomment-1696575707
=> release (contributors): fix a broken GitHub link

dm/task-configuration-file-full.md
Fix the outdated link [https://docs.pingcap.com/zh/tidb/dev/dm-key-features#table-routing](https://docs.pingcap.com/zh/tidb/dev/dm-key-features#table-routing) to [https://docs.pingcap.com/zh/tidb/dev/dm-table-routing](https://docs.pingcap.com/zh/tidb/dev/dm-table-routing)
Note: The outdated link exists in v6.5 and later versions. And the corresponding link is correct in the English docs. …
=> Fix an outdated DM table routing link

dm/dm-worker-intro.md
Add the missing `;` to one SQL statement
=> dm: fix SQL statement syntax

migration-tools.md
Improve descriptions to avoid confusion. Because the example uses `dumpling` but `dumpling` doesn't show in the preceding command output.
- This PR is translated from: https://github.com/pingcap/docs/pull/18328
=> Improve step description for installing tools using TiUP

system-variables.md
Document that txn-total-size-limit won't affect pipelined dml
=> Document that txn-total-size-limit won't affect pipelined dml

functions-and-operators/string-functions.md, temp.md
- MySQL 8.0 is a LTS release
- MySQL 8.3 is an older innovation release
This link was causing a HTTP 302 redirect to the 8.4 page.
- This PR is translated from: https://github.com/pingcap/docs/pull/18243
=> string-functions: Use MySQL 8.0 url instead of 8.3

privilege-management.md, sql-statements/sql-statement-alter-user.md, user-account-management.md
- Add links where appropriate 
- Minor corrections
- This PR is translated from: https://github.com/pingcap/docs/pull/18283
=> Add more links and corrections to user account management

clinic/clinic-user-guide-for-tiup.md, temp.md
Add `--metricsfilter`.
See also: https://github.com/pingcap/diag/blob/master/docs/manual/Diagnosis%20data%20collection%20guide%20in%20TiUP%20environment.md#collect-specific-metrics
- This PR is translated from: https://github.com/pingcap/docs/pull/17978
=> Add metricsfilter option

TOC.md, basic-sql-operations.md, develop/dev-guide-create-table.md, develop/dev-guide-tidb-crud-sql.md, expression-syntax.md, mysql-compatibility.md, sql-statements/sql-statement-overview.md, temp.md
Closes #17467 
- This PR is translated from: https://github.com/pingcap/docs/pull/17468
=> Replace sqlgram links

smooth-upgrade-tidb.md, upgrade-tidb-using-tiup.md
Improve descriptions of upgrading limitations to make it more clear
=> Improve upgrade limitations

releases/release-notes.md
fix the release date of v7.5.2
=> fix the release date of v7.5.2

tiflash/tiflash-configuration.md
This is a follow-up to https://github.com/pingcap/docs-cn/pull/18099
=> tiflash: update TiKV to TiFlash Proxy in config

ticdc/ticdc-sink-to-mysql.md
add notice about data initialize.
=> Add a note to ticdc-sink-to-mysql.md

ticdc/ticdc-faq.md
=> ticdc-faq: fix typo for commitTS

tune-region-performance.md
=> fix the recommended range for region-split-size

tidb-configuration-file.md
- "Control+C" is supported since `v7.3.0`. As there is already description about "Control+C" in [`[KILL]`](https://docs.pingcap.com/zh/tidb/v7.5/sql-statement-kill), just simple remove the redundant words.
=> tidb: Remove description about "Control+C" for `compactible-kill-query`

TOC.md, faq/manage-cluster-faq.md, mysql-schema/mysql-schema-user.md, mysql-schema/mysql-schema.md, privilege-management.md, releases/release-7.6.0.md, statistics.md, tidb-resource-control.md, user-account-management.md
* add explanation for the fields in `mysql.user`
* put `mysql-schema*.md` in a unique dir
- This PR is translated from: https://github.com/pingcap/docs/pull/18318
=> tidb: add explanation for the fields in mysql.user

mysql-schema/mysql-schema-user.md
Fix website build fauilre:
```
error "gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:
end of the stream or a document separator is expected at line 2, column 8:
title: `mysql.user`
^/home/runner/work/website-docs/website-docs/docs/markdown-pages/en/tidb/master/mysql-schema/mysql-schema-user.md: end of the stream or a document separator is expected at line 2, column 8:
title: `mysql.user`
^
YAMLException:end of the stream or a document separator is expected at line 2  , column 8:
title: `mysql.user`
^/home/runner/work/website-docs/website-docs/docs/markdown-pages/en  /tidb/master/mysql-schema/mysql-schema-user.md: end of the stream or a documen  t separator is expected at line 2, column 8:
title: `mysql.user`
^
``` …
=> fix: remove backticks from front matter

identify-expensive-queries.md, information-schema/information-schema-processlist.md, releases/release-8.2.0.md
=> doc: add `session_alias` to `information_schema.processlist` and expensive queries

tidb-lightning/tidb-lightning-configuration.md
Fix  https://asktug.com/t/topic/1029587.  The TiKV-importer component has been deprecated since v7.5.0 as stated in [TiDB 7.5.0 Release Notes](https://docs.pingcap.com/zh/tidb/dev/release-7.5.0).
English PR is not needed because the change had been done in https://github.com/pingcap/docs/pull/14343 already, 
- Other reference …
=> tidb lightning: remove the addr for the importer backend

alert-rules.md
Since https://github.com/pingcap/tidb/pull/40142, we did not have `Keep Alive OPM` metric anymore. But we forget to update the doc.
- Other reference link(s): https://asktug.com/t/topic/1029698
=> alert: remove keep_alive_total metric

sql-logical-optimization.md
=> sql-logical-optimization: add an entry for derive topN and limit

upgrade-tidb-using-tiup.md
Updates DDL descriptions when using smooth upgrade. This PR is a follow-up to https://github.com/pingcap/docs-cn/pull/18076.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/18076
=> Update DDL descriptions in cluster upgrade

information-schema/information-schema-keywords.md
v7.5.3: add information_schema.keywords
=> v7.5.3: add information_schema.keywords

pd-recover.md
=> pd: add an example for pd-recover

releases/release-7.5.3.md
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/18078
=> tidb: add a bugfix about issue https://github.com/pingcap/tidb/issues/54652

tune-region-performance.md
=> update the maximum region size for TiFlash

partitioned-table.md, sql-statements/sql-statement-create-table.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/18483
=> partitioned tables: add some restrictions 

releases/release-8.2.0.md
=> add ticdc pulsar sink related release note

ticdc/ticdc-changefeed-config.md
=> cdc: update output-raw-change-event comment link

system-variables.md
=> sys var: add more contents to `tidb_remove_orderby_in_subquery`

releases/release-7.4.0.md
=> cdc: deprecate the enable-old-value to the previous v7.4 release-note

tiproxy/tiproxy-configuration.md
Use `""` to represent empty string.
Close https://github.com/pingcap/docs/issues/16511
=> fix: use `""` to represent empty string

sql-statements/sql-statement-split-region.md
Clarify that PRE_SPLIT_REGIONS is also recommended for tables with AUTO_RANDOM attribute
=> update pre_split_regions usage scenario

system-variables.md
Related to the tidb issue https://github.com/pingcap/tidb/issues/54999, expaning the system variable scope to `GLOBAL` for the `tidb_low_resolution_tso`.
=> sys var: add global scope for `tidb_low_resolution_tso`

sql-statements/sql-statement-admin-bdr-role.md, ticdc/ticdc-bidirectional-replication.md
=> make bdr ddl replicate GA

system-variables.md
Update scope for system variable `ddl_reorg_batch_size` and `ddl_reorg_worker_cnt`.
- Other reference link(s): https://github.com/pingcap/tidb/pull/55334
=> sys-var: add SESSION scope for `ddl_reorg_batch_size` and `ddl_reorg_worker_cnt`

ticdc/ticdc-canal-json.md, ticdc/ticdc-sink-to-kafka.md
=> cdc: canal-json dml event commit-ts should be tso

glossary.md
- The current TTL in glossary the specifically refers to the row-level time-to-live feature
- Removal prevents confusion with other TTL concepts in documentation
=> remove ambiguous TTL from glossary

releases/release-6.5.7.md, releases/release-6.5.8.md, releases/release-6.5.9.md
=> move issue #36004 to v6.5.7 release notes

configure-memory-usage.md
=> Add doc for TopN spill

system-variables.md
=> system-variables: add tiflash_hashagg_preaggregation_mode

explain-aggregation.md, functions-and-operators/group-by-modifier.md
=> add the root type expand impl for rollup syntax.

identify-expensive-queries.md, information-schema/information-schema-processlist.md, releases/release-8.2.0.md
Update the columns in information_schema.processlist.
This PR is for v8.3 and later releases. For v8.2, there is another PR https://github.com/pingcap/docs-cn/pull/18181.
- Other reference link(s): https://github.com/pingcap/tidb/issues/54486
=> doc: session_alias and rows_affected in information_schema.processlist

tidb-configuration-file.md
Add description of newly added config `batch-policy`.
=> tidb: add doc for `batch-policy` config

pd-control.md
Add a new config item: batch in evict-leader-scheduler from v8.3.0, so add the instructions for use.
=> PD: add description of batch in evict-leader-scheduler config

resources/cdnfresh.txt
=> Update cdnfresh.txt for v8.3

.github/pull_request_template.md
pull_request_template: add v8.4
=> pull_request_template: add v8.4

TOC.md
=> TOC: add v8.3 release notes

tiflash/create-tiflash-replicas.md
The config `raftstore-proxy.server.snap-max-write-bytes-per-sec` has been changed to `raftstore-proxy.server.snap-io-max-bytes-per-sec` since v7.1. Ref https://github.com/pingcap/docs-cn/pull/13336
- Other reference link(s): https://github.com/pingcap/docs/pull/18590
=> *: Rename snap-max-write-bytes-per-sec (tiflash)

README.md
=> *: add 8.2 and 8.3 to README.md

system-variables.md
=> Update system-variable ‘tidb_ddl_reorg_batch_size’

ticdc/ticdc-split-update-behavior.md
=> dev, v8.2, and v8.3: add v8.1.1 to ticdc split behavior for update events

ticdc/ticdc-split-update-behavior.md
=> v8.1.1: update ticdc split behavior for update events

releases/release-8.3.0.md
=> release-8.3.0.md: refine the description of #54565

dashboard/dashboard-monitoring.md, grafana-overview-dashboard.md, grafana-performance-overview-dashboard.md, grafana-tidb-dashboard.md
=> Revise TSO related Grafana monitoring metrics description

sql-statements/sql-statement-select.md, temp.md
Update EBNF for:
- Partition selection: `SELECT * FROM t1 PARTITION (p0);` 
- Joins
Use https://kennytm.github.io/website-docs/dist/ for previewing the EBNF
- This PR is translated from: https://github.com/pingcap/docs/pull/17985
=> SELECT: Update EBNF for partitioning

.github/pull_request_template.md, README.md
Remove v5.2/v8.0 from the PR template because v5.2/v8.0 docs have been archived at https://docs-archive.pingcap.com/zh/tidb and will no longer receive new updates.
=> chore: remove v5.2/v8.0 from PR template

character-set-and-collation.md, faq/sql-faq.md
This PR updates outdated character set descriptions in SQL FAQ, but doesn't introduce new content.
=> faq: update character set description

generated-columns.md
=> *: add a limitation about not supporting `NULLIF()` and supporting `CASE`

releases/release-8.3.0.md, system-variables.md
=> system-variables: change the default value of `tidb_schema_cache_size`

sql-statements/sql-statement-import-into.md
=> sql: change the thread value from 16 to 8

pd-control.md
These schedulers are mainly used in testing and they should not be exposed to the users.
=> pd: remove shuffle schedulers

dashboard/dashboard-access.md
- This PR is translated from:https://github.com/pingcap/docs/pull/18831
=> dashboard: add SSO for dashboard access

information-schema/information-schema-inspection-result.md
Corrected "tikv_critical_error_total_coun" to "tikv_critical_error_total_count"
=> fix typo in information-schema-inspection-result.md

pd-configuration-file.md
- This PR is translated from: None, just optimize some descriptions.
=> PD: optimize the description of label-property

develop/dev-guide-gui-mysql-workbench.md, develop/dev-guide-gui-navicat.md, develop/dev-guide-sample-application-golang-gorm.md, develop/dev-guide-sample-application-golang-sql-driver.md, develop/dev-guide-sample-application-java-hibernate.md, develop/dev-guide-sample-application-java-jdbc.md, develop/dev-guide-sample-application-java-mybatis.md, develop/dev-guide-sample-application-java-spring-boot.md, develop/dev-guide-sample-application-nodejs-mysql2.md, develop/dev-guide-sample-application-nodejs-mysqljs.md, develop/dev-guide-sample-application-nodejs-prisma.md, develop/dev-guide-sample-application-nodejs-sequelize.md, develop/dev-guide-sample-application-nodejs-typeorm.md, develop/dev-guide-sample-application-python-django.md, develop/dev-guide-sample-application-python-mysql-connector.md, develop/dev-guide-sample-application-python-mysqlclient.md, develop/dev-guide-sample-application-python-peewee.md, develop/dev-guide-sample-application-python-pymysql.md, develop/dev-guide-sample-application-python-sqlalchemy.md, develop/dev-guide-sample-application-ruby-mysql2.md, develop/dev-guide-sample-application-ruby-rails.md
This PR updates more files that are missed in https://github.com/pingcap/docs-cn/pull/18520.
=> develop: unify product names

_docHome.md
Update title for all home pages (Home, TiDB Cloud and TiDB Self-Managed) to make them more consistent.
=> Update homepage titles

_docHome.md
This PR redesigns the global home doc.
- Other reference link(s): https://github.com/pingcap/docs/pull/18880
=> refactor(doc): redesign the global home doc

.github/pull_request_template.md
This is a follow-up to https://github.com/pingcap/docs-cn/pull/18497, to fix the format.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/18497
=> Remove an extra bracket in PR template

temp.md, tidb-lightning/tidb-lightning-data-source.md
Update the link <https://docs.pingcap.com/zh/tidb/v6.6/backup-and-restore-storages#uri-%E6%A0%BC%E5%BC%8F> to that of the corresponding TiDB version.
- This PR is translated from: https://github.com/pingcap/docs/pull/18927
=> Update a link in TiDB Lightning data sources

faq/sql-faq.md
=> faq: update the description of "Information schema is out of date"

dr-secondary-cluster.md
Deleted: Removed all binlog-related content from the TiCDC documentation as binlog is completely deprecated.
This PR is translated from: https://github.com/pingcap/docs/pull/18949
Other reference link(s):
=> Remove All Binlog References from CDC Documentation

releases/release-6.5.0.md, releases/release-6.5.1.md, temp.md, tikv-configuration-file.md
Fix the default value of `cdc.min-ts-interval` for v6.5.1 and later versions.
- This PR is translated from: https://github.com/pingcap/docs/pull/18966
- Other reference link(s): https://github.com/tikv/tikv/issues/14092
=> *: fix the default value of cdc.min-ts-interval

TOC.md, information-schema/information-schema-check-constraints.md, information-schema/information-schema-tidb-check-constraints.md
Add description about `TIDB_CHECK_CONSTRAINTS`
- This PR is translated from: https://github.com/pingcap/docs/pull/18753
=> tidb: add description about `TIDB_CHECK_CONSTRAINTS`

sql-statements/sql-statement-change-drainer.md, sql-statements/sql-statement-change-pump.md, sql-statements/sql-statement-show-drainer-status.md, sql-statements/sql-statement-show-pump-status.md, tidb-binlog-deployment-topology.md, tidb-binlog/bidirectional-replication-between-tidb-clusters.md, tidb-binlog/binlog-consumer-client.md, tidb-binlog/binlog-control.md, tidb-binlog/deploy-tidb-binlog.md, tidb-binlog/get-started-with-tidb-binlog.md, tidb-binlog/handle-tidb-binlog-errors.md, tidb-binlog/maintain-tidb-binlog-cluster.md, tidb-binlog/monitor-tidb-binlog-cluster.md, tidb-binlog/tidb-binlog-configuration-file.md, tidb-binlog/tidb-binlog-faq.md, tidb-binlog/tidb-binlog-glossary.md, tidb-binlog/tidb-binlog-overview.md, tidb-binlog/tidb-binlog-relay-log.md, tidb-binlog/tidb-binlog-reparo.md, tidb-binlog/troubleshoot-tidb-binlog.md, tidb-binlog/upgrade-tidb-binlog.md
This PR adds aliases for 21 TiDB Binlog document files deleted from the master branch via https://github.com/pingcap/docs-cn/pull/18576. This is for the release of v8.4.0.
Note: The content in the `aliases` section comes from that in the files of the master branch. In addition to that, I add the alias for the URL of the current dev version.
- This PR is …
=> *: add aliases for 21 deleted TiDB Binlog docs from dev

tidb-lightning/tidb-lightning-physical-import-mode.md
=> tidb-lightning: refine the PITR support info

non-transactional-dml.md
=> non-transactional-dml: update t3. to t3.id

br/br-snapshot-guide.md, mysql-schema/mysql-schema.md
This table has been removed since `v8.0.0` (and it's basically not functional from the very beginning).
It should be removed from document.
=> system tables: remove table `schema_index_usage`

character-set-and-collation.md
=> character-set-and-collation: fix an error

releases/release-6.1.4.md, releases/release-6.5.1.md
=> fix transaction_atomicity in release notes

system-variables.md
We have defined the correct range for tidb_analyze_partition_concurrency in [this pull request](https://github.com/pingcap/tidb/pull/55409).
- This PR is translated from: https://github.com/pingcap/docs/pull/18586
=> statistics: set the right range for tidb_analyze_partition_concurrency

TOC.md
Adds [TiDB Release Support Policy](https://www.pingcap.com/tidb-release-support-policy/) to `TOC.md` according to @likidu's suggestion.
- This PR is translated from: https://github.com/pingcap/docs/pull/19119
=> toc: add TiDB release support policy

functions-and-operators/string-functions.md
- This PR is translated from:https://github.com/pingcap/docs/pull/19117
=> string-functions: Explain binary-as-hex behavior

optimizer-fix-controls.md
add doc for the new fix control 52592
=> add-doc-fix52592

system-variables.md
- This PR is translated from:https://github.com/pingcap/docs/pull/18876
=> planner: change default of tidb_opt_prefer_range_scan

system-variables.md
https://github.com/pingcap/tidb/pull/56316
=> sys-variables: update `tidb_schema_cache_size` default value

partition-pruning.md, partitioned-table.md
- This PR is translated from:https://github.com/pingcap/docs/pull/18456
=> Added EXTRACT(<time unit> FROM <date/datetime/time col) as partition pruning function

dynamic-config.md
- This PR is translated from: https://github.com/pingcap/docs/pull/18814
=> tikv: add new dynamic configure for flow-control

enable-tls-between-components.md
=> pd: support multi cn after 8.4

develop/dev-guide-choose-driver-or-orm.md
=> fix: typo of jdbc v8.0.32

glossary.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/19120
=> glossary: link TSO to the TSO doc

_index.md
update the links in the index page to v8.4
=> update the links in the index page to v8.4

information-schema/information-schema-slow-query.md, system-variables.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/19160
- https://github.com/pingcap/tidb/pull/20200
- https://github.com/pingcap/tidb/issues/56707
=> Update docs around slow_query tables

ddl-introduction.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/19158
=> ddl-introduction: switch the tab of pre-v6.2 info and post-v6.2 info 

ticdc/ticdc-sink-to-kafka.md
=> cdc: add more detail about the authorization

ticdc/ticdc-avro-protocol.md, ticdc/ticdc-sink-to-kafka.md
=> cdc: make mq encoding protocol related more clear

releases/release-8.3.0.md
Remove a duplicate release note from release-8.3.0.md that was previously published in v8.2.0.
=> br: remove duplicated release notes from release-8.3.0.md

.github/pull_request_template.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/19337
=> pull_request_template: add the option for v8.5

system-variables.md
=> sys-var: add `2` for `mpp_version`

tiup/tiup-cluster-topology-reference.md
Fix the errors made in the cherry-pick PR https://github.com/pingcap/docs-cn/pull/19010/files
=> release-8.1: fix kvcdc parameters

resources/cdnfresh.txt
=> cdnfresh.txt: add v8.4 PDF

releases/release-timeline.md
=> fix: correct release link from 7.5.3 to 7.5.4

sql-prepared-plan-cache.md
=> planner: update sql-prepared-plan-cache.md

information-schema/information-schema-data-lock-waits.md, mysql-schema/mysql-schema.md, temp.md, troubleshoot-lock-conflicts.md
- This PR is translated from: https://github.com/pingcap/docs/pull/19248
=> Update docs related to locking

TOC.md, quick-start-with-tidb.md, tidb-in-kubernetes.md
- Updates the topic level in `TOC.md`
- Updates the title of K8s related doc for consistency
- Improves description for the relationship between TiDB and TiDB Operator
- This PR is translated from: not all changes in https://github.com/pingcap/docs/pull/19353 are included in this PR because of language specific considerations.
=> *: update TOC and title wording for on-boarding docs

binary-package.md, production-deployment-using-tiup.md
=> fix: update broken TiDB binary download link

README.md
=> readme: update the display of active contributors

hardware-and-software-requirements.md
TiDB ends support for CentOS 7 from v8.4
=> update description about CentOS 7 EOL

releases/release-8.2.0.md
Fix `INFOMATION_SCHEMA.TABLES` to `INFORMATION_SCHEMA.TABLES`
=> releases: fix a typo in v8.2 release notes

TOC.md, temp.md
- Moves TiCDC docs from **TiDB 工具** > [**TiCDC**](https://docs.pingcap.com/tidb/dev/ticdc-overview) to the first level in left navigation, to make it easier to find
- Renames TiCDC to **数据同步** in the left navigation
- Combines the exiting first-level [**数据集成**](https://docs.pingcap.com/zh/tidb/dev/integration-overview) with the TiCDC docs …
=> toc: reorganize TiCDC docs in left navigation

sync-diff-inspector/sync-diff-inspector-overview.md
=> sync-diff-inspector: add limitations

encryption-at-rest.md
=> encryption: remove experimental for GCP KMS

system-variables.md
Fix incorrect messages for set_var()
- `tidb_read_consistency` is supported conditionally
- `tidb_read_staleness` is not support
- This PR is translated from: https://github.com/pingcap/docs/pull/19451
=> fix incorrect message for set_var()

system-variables.md
add description for var `tidb_ddl_reorg_max_write_speed`
- Other reference link(s): https://github.com/pingcap/tidb/pull/57145
=> tidb: add description for var `tidb_ddl_reorg_max_write_speed`

releases/release-6.2.0.md
=> add the removal reason for `tidb_enable_change_multi_schema`

br/br-pitr-manual.md
=> br-pitr-manual: remove an unnecessary quotation mark

sql-statements/sql-statement-change-drainer.md, sql-statements/sql-statement-change-pump.md, sql-statements/sql-statement-show-drainer-status.md, sql-statements/sql-statement-show-pump-status.md, tidb-binlog-deployment-topology.md, tidb-binlog/bidirectional-replication-between-tidb-clusters.md, tidb-binlog/binlog-consumer-client.md, tidb-binlog/binlog-control.md, tidb-binlog/deploy-tidb-binlog.md, tidb-binlog/handle-tidb-binlog-errors.md, tidb-binlog/maintain-tidb-binlog-cluster.md, tidb-binlog/monitor-tidb-binlog-cluster.md, tidb-binlog/tidb-binlog-configuration-file.md, tidb-binlog/tidb-binlog-faq.md, tidb-binlog/tidb-binlog-glossary.md, tidb-binlog/tidb-binlog-overview.md, tidb-binlog/tidb-binlog-relay-log.md, tidb-binlog/tidb-binlog-reparo.md, tidb-binlog/troubleshoot-tidb-binlog.md, tidb-binlog/upgrade-tidb-binlog.md
TiDB ends the support of Binlog starting from v8.4.0. This PR adds aliases for Binlog docs for stable doc links.
=> add aliases for Binlog docs

resources/cdnfresh.txt
=> update cdnfresh.txt for v8.1 and v8.5

releases/release-8.3.0.md
=> remove https://github.com/apps/renovate from release notes

pd-configuration-file.md, pd-control.md, releases/release-7.1.0.md
=> store limit v2: remove experimental description

.github/workflows/dispatch.yml, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/19560
=> release-8.5: add release-8.5 to dispatch.yml

upgrade-tidb-using-tiup.md
=> tiup: restriction about DXF

br/br-snapshot-manual.md, br/use-br-command-line-tool.md
=> br: change the default value of table-level checksum to false

ticdc/ticdc-simple-protocol.md
=> cdc: add release version for the simple protocol

sql-statements/sql-statement-revoke-privileges.md
sql: fix the synopsis of `REVOKE <privileges>`
Close #19269 
=> sql: fix the synopsis of `REVOKE <privileges>`

quick-start-with-tidb.md, tiup/tiup-playground.md
- This PR is translated from:https://github.com/pingcap/docs/pull/19669
=> tiup: refine description about `tiup playground --tag`

optimizer-fix-controls.md
planner: update the default value of 46177. Its default value changes from OFF to ON starting from v8.5.0.
=> planner: update the default value of 46177

releases/release-8.0.0.md, storage-engine/titan-configuration.md, tikv-configuration-file.md
=> fix version-mark format for shared-blob-cache

basic-features.md
=> update basic-features.md for v8.5

check-before-deployment.md, dm/quick-start-with-dm.md
- This PR is translated from:https://github.com/pingcap/docs/pull/19703
=> check-before-deployment: add selinux 

hardware-and-software-requirements.md, releases/release-8.4.0.md, releases/release-8.5.0.md, upgrade-tidb-using-tiup.md
Highlight the info that CentOS 7 is no long supported 
=> add warnings for CentOS 7 usage

dm/quick-start-with-dm.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/19760
=> dm: update the example version to 8.5.0

.github/pull_request_template.md
- This PR is translated from:https://github.com/pingcap/docs/pull/19767
=> add v9.0 in pull_request_template.md

tiup/tiup-playground.md
=> tiup-playground: add info about TiProxy

releases/release-8.5.0.md
=> release-8.5.0.md: add the performance test section

sql-statements/sql-statement-flashback-cluster.md
=> sql: Update sql-statement-flashback-cluster.md

README.md
=> README.md: add release-8.5

information-schema/information-schema-tidb-index-usage.md
Previously, the table schema for `cluster_tidb_index_usage` is wrong :facepalm: . It's caused by a careless copy-paste. Now it's modified to the correct table schema.
=> fix the table schema for cluster_tidb_index_usage

sql-statements/sql-statement-show-builtins.md
- This PR is translated from:https://github.com/pingcap/docs/pull/19735
=> Update output of SHOW BUILTINS

dynamic-config.md
v8.1.2: dynamic config add `import.num-threads`
- Other reference link(s): https://github.com/tikv/tikv/issues/17807
=> v8.1.2: dynamic config add `import.num-threads`

sql-statements/sql-statement-create-index.md, system-variables.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/52780
=> add `json_schema_valid` into `tidb_allow_function_for_expression_index`

pd-control.md
=> pd-control: update the section level of service-middleware configurations

pd-configuration-file.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/19825
=> configuration-file: correct the initial capitalization of certain configuration items

ecosystem-tool-user-guide.md, migration-tools.md, tidb-lightning/tidb-lightning-data-source.md, tidb-lightning/tidb-lightning-faq.md, tidb-lightning/tidb-lightning-overview.md
Add lightning import support for parquet format files exported by Snowflake.
- This PR is translated from: https://github.com/pingcap/docs/pull/15281
=> Add lightning import support for parquet format files exported by Snowflake

partitioned-table.md
Update the limitation of the Global index
=> Update the limitation of the Global index

sql-statements/sql-statement-admin-alter-ddl.md, system-variables.md
v7.5.5: introduce tidb_ddl_reorg_max_write_speed
=> v7.5.5: introduce tidb_ddl_reorg_max_write_speed

hardware-and-software-requirements.md
=> v7.5.5: support Kylin SP3 (master branch)

hardware-and-software-requirements.md
=> v7.5.5: support Kylin SP3

check-before-deployment.md
- This PR is translated from: https://github.com/pingcap/docs/pull/14480/commits/0d0374843688f13fe6f875236fb15afbf6a148e1
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/14662
=> Clarify swap descriptions

TOC.md, system-variable-reference.md, temp.md
Added system variables references doc to list where each variable is referenced in documentation.
- This PR is translated from: https://github.com/pingcap/docs/pull/19892
=> Add system variable reference

sql-statements/sql-statement-explain-analyze.md
In https://github.com/pingcap/tidb/pull/53335, cop tasks' rpc info execution summary was updated, while the documentation is not.
=> Update cop rpc execution info

partitioned-table.md
- This PR is translated from: https://github.com/pingcap/docs/pull/19977
=> partitioned-table: remove incorrect limitation

character-set-and-collation.md, character-set-gbk.md, migrate-from-mariadb.md, sql-statements/sql-statement-show-collation.md
- Update output of `SHOW COLLATION`
- Add collation nameing details
- Update `utf8/utf8mb3` info
- This PR is translated from:https://github.com/pingcap/docs/pull/19976
=> Character set and collation updates

releases/release-7.5.0.md, releases/release-8.1.0.md, releases/release-8.5.0.md
update the link of release notes PDFs from "https://download.pingcap.org/" to "https://docs-download.pingcap.com/pdf".
=> update the link of release notes PDFs

releases/release-7.1.0.md, releases/release-7.2.0.md
Moves [#41048](https://github.com/pingcap/tidb/issues/41048) bug fix from v7.1.0 to v7.2.0, confirmed by @bb7133 
=> releases: move #41048 bug fix from v7.1.0 to v7.2.0

functions-and-operators/information-functions.md
- This PR is translated from:https://github.com/pingcap/docs/pull/19831
=> Update docs for LAST_INSERT_ID()

sql-statements/sql-statement-drop-column.md, statement-summary-tables.md
Fixes a typo and removes an extra space between words
=> Fix a typo and format

hardware-and-software-requirements.md, upgrade-tidb-using-tiup.md
=> release-8.4: update centos 7 support

dr-solution-introduction.md
=> remove unnecessary white space

dumpling-overview.md
- This PR is translated from:https://github.com/pingcap/docs/pull/19890
=> dumpling: merge userguide into docs

tiflash/tiflash-configuration.md
Add more tiflash config to doc
=> tiflash: add two more TiFlash config items

system-variables.md
As in title
- Other reference link(s): https://github.com/pingcap/docs/pull/15920
=> tidb_cloud_storage_uri: remove limitation info about TiDB Cloud

ticdc/ticdc-changefeed-config.md
=> ticdc: add a deprecate warning to user doc

mysql-compatibility.md, temp.md
The `session_connect_attrs` table is not empty and the `pd%`, `tidb%` and `tikv%` tables are also not empty.
```
mysql-8.0.11-TiDB-v8.5.0> SELECT * FROM performance_schema.session_connect_attrs;
+----------------+-----------------+------------+------------------+
| PROCESSLIST_ID | ATTR_NAME       | ATTR_VALUE | ORDINAL_POSITION |
+----------------+-----------------+------------+------------------+
|     2376073220 | _client_name    | libmysql   |                0 |
|     2376073220 | _client_version | 9.1.0      |                1 |
|     2376073220 | _os             | Linux      |                2 |
|     2376073220 | _pid            | 2987910    |                3 |
|     2376073220 | _platform       | x86_64     |                4 |
|     2376073220 | os_user         | dvaneeden  | …
```
=> mysql-compatibility: correct performance_schema statement

dm/dm-source-configuration-file.md
- This PR is translated from:https://github.com/pingcap/docs/pull/18781
=> dm: enable-relay is undeprecated since v5.4.0

faq/deploy-and-maintain-faq.md
- This PR is translated from:https://github.com/pingcap/docs/pull/20111
=> faq: remove ansible related things

TOC.md, dm/quick-start-with-dm.md, temp.md
This PR updates the TiDB Data Migration Quick Start guide. Changes include:
* Replacing binary-based deployment instructions with TiUP Playground to simplify setup.
* Adding detailed steps for preparing source databases on Docker, macOS, CentOS, and Ubuntu.
* Simplifying and clarifying the steps for DM configuration and task creation.
* Adding explicit cleanup instructions and actionable examples to improve usability.
These changes aim to make the guide more accurate, complete, and easier to follow for users setting up a local data migration environment.
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, …
=> dm: update DM quick start using TiUP Playground

check-before-deployment.md, tiup/tiup-component-cluster-check.md, tune-operating-system.md
- This PR is translated from:https://github.com/pingcap/docs/pull/20070
=> tiup: Update THP docs

tidb-limitations.md
- This PR is translated from:https://github.com/pingcap/docs/pull/20118
=> tidb-limitations: add index length limitation

temp.md, tiup/tiup-component-cluster-check.md
- The status about CentOS 7 is not true (anymore)
- For SELinux it is not just a recommendation, it is required.
- This PR is translated from: https://github.com/pingcap/docs/pull/20021
=> tiup-component-cluster-check: Update

sql-plan-replayer.md
=> Fix keywords orders

pd-configuration-file.md
Updates the default value of `read-base-cost` from 0.25 to 0.125 for v7.5 and later versions
- Other reference link(s): https://github.com/tikv/pd/blob/17f3ae3609fc50bae07e8783c0a373419b7daf9b/client/resource_group/controller/config.go#L66
=> pd: update the default value of read-base-cost

system-variables.md, temp.md
Fix https://github.com/pingcap/docs/issues/19778
- This PR is translated from: https://github.com/pingcap/docs/pull/20156
=> system-variables: add the experimental info for tidb_evolve_plan_baselines

ticdc/ticdc-ddl.md
- Other reference link(s): https://github.com/pingcap/tiflow/issues/11946
=> ticdc: update doc about event filter of renaming table

tidb-lightning/tidb-lightning-configuration.md
lighting: reorder tidb.session-vars
Move the `tidb.session-vars` section after `[tidb.security]` for better organization
=> lighting: reorder tidb.session-vars

sql-statements/sql-statement-create-table.md
Add syntax and description about `ENGINE_ATTRIBUTE` table option, to be consistent with TiDB. The `ENGINE_ATTRIBUTE` is added to TiDB by https://github.com/pingcap/tidb/pull/59201.
- This PR is translated from: https://github.com/pingcap/docs/pull/20148
- Other reference link(s): https://github.com/pingcap/tidb/pull/59201
=> tidb: Add ENGINE_ATTRIBUTE table option

tidb-resource-control-ru-groups.md
Add URL aliases to handle redirects after `tidb-resource-control.md` was removed. Users who visit the old URL (`.../tidb-resource-control/`) will now be automatically redirected to the new location (`.../tidb-resource-control-ru-groups/`), preventing 404 errors.
=> fix: add doc aliases to prevent 404 errors on tidb-resource-control page

tidb-resource-control-ru-groups.md
Add URL aliases to handle redirects after `tidb-resource-control.md` was removed. Users who visit the old URL (`.../tidb-resource-control/`) will now be automatically redirected to the new location (`.../tidb-resource-control-ru-groups/`), preventing 404 errors.
=> v8.5: add doc aliases to prevent 404 errors on tidb-resource-control page

releases/release-6.5.0.md, releases/release-6.6.0.md
Update `tidb_enable_plan_replayer_capture` in v6.5.0 and v6.6.0 release notes:
- Add variable description in v6.5.0
- Fix default value description in v6.6.0
=> fix the default value of tidb_enable_plan_replayer_capture in release notes

check-before-deployment.md
- This PR is translated from:https://github.com/pingcap/docs/pull/20078
=> tiup: update sysctl settings

tiproxy/tiproxy-overview.md
close https://github.com/pingcap/docs/issues/20084
Add tiproxy topology definition to the usage section
- This PR is translated from: https://github.com/pingcap/docs/pull/20141
=> tiproxy: add tiproxy topology definition to the usage section

releases/release-7.0.0.md, system-variables.md
- Other reference link(s): https://github.com/pingcap/tidb/issues/41863
=> variable: tidb_slow_txn_log_threshold

configure-store-limit.md
- This PR is translated from:https://github.com/pingcap/docs/pull/20144
=> pd: store limit updates

functions-and-operators/aggregate-group-by-functions.md
=> Add doc for `APPROX_DISTINCT_COUNT` aggregate function

ticdc/ticdc-faq.md
Make the explanation of `safe-mode` more understandable.
- This PR is translated from: https://github.com/pingcap/docs/pull/20252
=> ticdc: update "safe-mode" description

.github/workflows/media.yml
=> ci: sync media to cos

command-line-flags-for-tidb-configuration.md, dm/dm-overview.md, dumpling-overview.md, explore-htap.md, faq/manage-cluster-faq.md, overview.md, quick-start-with-tidb.md, ticdc/ticdc-overview.md, tidb-architecture.md, tidb-binlog/tidb-binlog-overview.md, tidb-lightning/tidb-lightning-overview.md, tidb-monitoring-framework.md, user-account-management.md
=> v5.4-v6.1: update video resource links to point to new locations

command-line-flags-for-tidb-configuration.md, dm/dm-overview.md, dumpling-overview.md, explore-htap.md, faq/manage-cluster-faq.md, overview.md, quick-start-with-tidb.md, tidb-architecture.md, tidb-binlog/tidb-binlog-overview.md, tidb-lightning/tidb-lightning-overview.md, tidb-monitoring-framework.md, user-account-management.md
=> v6.5-v8.3: update video resource links to point to new locations

command-line-flags-for-tidb-configuration.md, dm/dm-overview.md, dumpling-overview.md, explore-htap.md, faq/manage-cluster-faq.md, overview.md, quick-start-with-tidb.md, tidb-architecture.md, tidb-lightning/tidb-lightning-overview.md, tidb-monitoring-framework.md, user-account-management.md
=> v8.4-dev: update video resource links to point to new locations

subquery-optimization.md, temp.md
The correct symbol should be `>` instead of `<`.
- This PR is translated from: https://github.com/pingcap/docs/pull/20274
=> doc: correct subquery optimization examples for clarity

support.md, temp.md
internals.tidb.io is now inaccessible.  The alternative option is https://github.com/orgs/pingcap/discussions. 
- This PR is translated from: https://github.com/pingcap/docs/pull/20294
=> support: replace internals.tidb.io with discussions on GitHub

check-before-deployment.md, temp.md, tiup/tiup-component-cluster-check.md
Extend the SELinux recommendations:
- The config is in `/etc/selinux/config`.
- On RedHat based systems there is `/etc/sysconfig/selinux`, which is a symlink to `/etc/selinux/config`. This symlink is not present on Ubuntu/Debian based systems.
- On Ubuntu/Debian based systems SELinux tools are not installed by default, so `getenforce` and the config are not available until extra tools are installed.
- On Ubuntu/Debian SELinux is not enabled by default, so no action is needed. Note that `apparmor` is used instead, but this isn't causing issues for TiDB/TiUP.
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility …
=> tiup: give a more clear recommendation about SELinux

temp.md, ticdc/ticdc-open-api-v2.md
There's a typo on the API intro. https://docs.pingcap.com/tidb/stable/ticdc-open-api-v2#examples 
- This PR is translated from: https://github.com/pingcap/docs/pull/20218
=> Document bug: API command for changefeed (/api/v2/changefeed/test1/synced)

information-schema/information-schema-slow-query.md
=> Fix incorrect slow query table desc row count

tidb-scheduling.md
=> pd: add note for tombstone store gc

releases/release-8.2.0.md, system-variables.md
https://github.com/pingcap/docs/pull/19817
=> *: upgrade tidb_auto_analyze_partition_batch_size default value

temp.md, tidb-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs/pull/20289
=> tidb-configuration-file: Add like to Coprocessor Cache docs

mysql-compatibility.md
- This PR is translated from:https://github.com/pingcap/docs/pull/20309
=> mysql-compatibility.md: Add note about JOIN on subquery

sql-statements/sql-statement-admin-pause-ddl.md, sql-statements/sql-statement-admin-resume-ddl.md, sql-statements/sql-statement-admin-show-ddl.md
=> refine admin related docs

generated-columns.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/19701
=> generated columns: list disallowed functions 

develop/dev-guide-unstable-result-set.md
=> fix: vague order by description

releases/release-8.2.0.md, temp.md, tidb-configuration-file.md
1. The default value of `concurrently-init-stats` is true. See: https://github.com/pingcap/tidb/blob/397b0f228a93d4b7323baa6f02a4c895449017f4/pkg/config/config.go#L1002
2. We don't load the full stats for the PK.
- This PR is translated from: https://github.com/pingcap/docs/pull/20254
=> docs: update description and default value for `concurrently-init-stats` in configuration file

sql-statements/sql-statement-overview.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/20392
=> sql-statement-overview.md: add four SQL statements 

tiflash/tiflash-configuration.md
=> tiflash: update config max_threads and task_scheduler_active_set_soft_limit

hardware-and-software-requirements.md
=> v6.5.12: support openEuler 22.03 LTS SP4

releases/release-7.5.5.md, releases/release-8.5.0.md, sql-statements/sql-statement-admin-alter-ddl.md, system-variable-reference.md, system-variables.md
=> tidb_ddl_reorg_max_write_speed: add the support info of v6.5.12

faq/migration-tidb-faq.md, optimizer-fix-controls.md, releases/release-8.4.0.md, temp.md
Fix https://github.com/pingcap/docs/issues/20378
- This PR is translated from: https://github.com/pingcap/docs/pull/20411
=> update "DB2" to "Db2"

tidb-monitoring-api.md, tiproxy/tiproxy-load-balance.md, tiproxy/tiproxy-overview.md, tiproxy/tiproxy-traffic-replay.md
=> update media resource links to point to new locations

migration-tools.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/20410
=> migration-tools: update the descriptions for Dumpling

hardware-and-software-requirements.md
- This PR is translated from:https://github.com/pingcap/docs/pull/20281
=> hardware-and-software-requirements: Update for EOLs

sql-statements/sql-statement-create-table.md
- This PR is translated from:https://github.com/pingcap/docs/pull/20468
=> sql-statements: expand DefaultValueExpr defination

statistics.md
=> statistics.md: correct the default value of stats-load-concurrency

benchmark/benchmark-sysbench-v6.0.0-vs-v5.4.0.md, benchmark/benchmark-sysbench-v6.1.0-vs-v6.0.0.md, benchmark/v6.0-performance-benchmarking-with-tpcc.md, benchmark/v6.0-performance-benchmarking-with-tpch.md, benchmark/v6.1-performance-benchmarking-with-tpcc.md, benchmark/v6.1-performance-benchmarking-with-tpch.md, temp.md
This PR adds aliases for the following stale benchmark docs removed in https://github.com/pingcap/docs/pull/20462.
- ./benchmark/benchmark-sysbench-v6.0.0-vs-v5.4.0.md
- ./benchmark/benchmark-sysbench-v6.1.0-vs-v6.0.0.md
- ./benchmark/v6.0-performance-benchmarking-with-tpcc.md
- ./benchmark/v6.0-performance-benchmarking-with-tpch.md
- ./benchmark/v6.1-performance-benchmarking-with-tpcc.md
- ./benchmark/v6.1-performance-benchmarking-with-tpch.md
For details, see [tips for choosing the affected …
=> v6.1: add aliases for stale benchmark docs

benchmark/benchmark-sysbench-v2.md, benchmark/benchmark-sysbench-v3.md, benchmark/benchmark-sysbench-v4-vs-v3.md, benchmark/benchmark-sysbench-v5-vs-v4.md, benchmark/benchmark-sysbench-v5.1.0-vs-v5.0.2.md, benchmark/benchmark-sysbench-v5.2.0-vs-v5.1.1.md, benchmark/benchmark-sysbench-v5.3.0-vs-v5.2.2.md, benchmark/benchmark-sysbench-v5.4.0-vs-v5.3.0.md, benchmark/benchmark-tpch.md, benchmark/v3.0-performance-benchmarking-with-sysbench.md, benchmark/v3.0-performance-benchmarking-with-tpcc.md, benchmark/v4.0-performance-benchmarking-with-tpcc.md, benchmark/v4.0-performance-benchmarking-with-tpch.md, benchmark/v5.0-performance-benchmarking-with-tpcc.md, benchmark/v5.1-performance-benchmarking-with-tpcc.md, benchmark/v5.2-performance-benchmarking-with-tpcc.md, benchmark/v5.3-performance-benchmarking-with-tpcc.md, benchmark/v5.4-performance-benchmarking-with-tpcc.md, benchmark/v5.4-performance-benchmarking-with-tpch.md, temp.md
This PR adds aliases for the following stale benchmark docs removed in https://github.com/pingcap/docs/pull/20462.
- ./benchmark/benchmark-sysbench-v2.md
- ./benchmark/benchmark-sysbench-v3.md
- ./benchmark/benchmark-sysbench-v4-vs-v3.md
- ./benchmark/benchmark-sysbench-v5-vs-v4.md
- ./benchmark/benchmark-sysbench-v5.1.0-vs-v5.0.2.md
- ./benchmark/benchmark-sysbench-v5.2.0-vs-v5.1.1.md
- ./benchmark/benchmark-sysbench-v5.3.0-vs-v5.2.2.md
- ./benchmark/benchmark-sysbench-v5.4.0-vs-v5.3.0.md
- ./benchmark/benchmark-tpch.md
- ./benchmark/v3.0-performance-benchmarking-with-sysbench.md
- ./benchmark/v3.0-performance-benchmarking-with-tpcc.md
- ./benchmark/v4.0-performance-benchmarking-with-tpcc.md
- ./benchmark/v4.0-performance-benchmarking-with-tpch.md
- …
=> v5.4: add aliases for stale benchmark docs

tiup/tiup-cluster-no-sudo-mode.md
- This PR is translated from:https://github.com/pingcap/docs/pull/20437
=> tiup: Update/fix no sudo mode docs

hardware-and-software-requirements.md
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/19962
=> add openEuler 22.03 LTS SP3/SP4

temp.md, tidb-lightning/tidb-lightning-distributed-import.md, tidb-lightning/tidb-lightning-physical-import-mode.md
Updates following wording about parallel import in two documents:
- [Do not use multiple TiDB Lightning instances to import data to the same TiDB cluster by default. Use Parallel Import instead.](https://docs.pingcap.com/tidb/stable/tidb-lightning-physical-import-mode#limitations:~:text=Do%20not%20use%20multiple%20TiDB%20Lightning%20instances%20to%20import%20data%20to%20the%20same%20TiDB%20cluster%20by%20default.%20Use%20Parallel%20Import%20instead.)
- [By simultaneously running multiple TiDB Lightning instances, you can import data in parallel from different single tables or multiple tables.](https://docs.pingcap.com/tidb/stable/tidb-lightning-distributed-import#:~:text=By%20simultaneously%20running%20multiple%20TiDB%20Lightning%20instances%2C%20you%20can%20import%20data%20in%20parallel%2 …
=> tidb-lightning: update wording about parallel import

transaction-isolation-levels.md
Add a section to change isolation level in transaction-isolation-levels.md
=> Add a section to change isolation level in transaction-isolation-levels.md

system-variables.md
=> sys var: clarify the description of tidb_ddl_reorg_max_write_speed

mysql-schema/mysql-schema.md
Add a description about the `cluster_id` row in the `mysql.tidb` table.
- This PR is translated from: https://github.com/pingcap/docs/pull/20280
- https://github.com/pingcap/tidb/pull/59511
=> Add docs about `cluster_id` row in `mysql.tidb`

tiflash/tiflash-supported-pushdown-calculations.md
=> Support pushdown to tiflash for some aggregation functions

tiflash/tiflash-configuration.md
We found that the tiflash-learner config param "raftstore.store-batch-retry-recv-timeout" has been removed during the code refactor since v5.4. But the doc is not updated.
tiflash-proxy for release-5.3
https://github.com/pingcap/tidb-engine-ext/blob/a80f64730d66da71f98e1f83534ce79ea6779ea4/components/raftstore/src/store/config.rs#L203-L204
tiflash-proxy for release-5.4
https://github.com/pingcap/tidb-engine-ext/blob/c15322fd615c518b0fa2d2204dbdf32dd0b4cfdf/components/raftstore/src/store/config.rs
For …
=> Remove deleted tiflash param "raftstore.store-batch-retry-recv-timeout"

tikv-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs/pull/17976
=> Small updates to TiKV config docs

ticdc/ticdc-faq.md
=> ticdc: refine faq doc

tikv-configuration-file.md
Add missing TiKV configuration.
- This PR is translated from:  N/A
=> tikv: add missing tikv configs

ticdc/ticdc-faq.md
=> ticdc: add duplicate entry faq

sql-statements/sql-statement-import-into.md
=> import into: remove restriction thread >= 8 for import into with global-sort

information-schema/information-schema-slow-query.md
=> Add network traffic related stats in slow query table

sql-statements/sql-statement-explain-analyze.md
=> Modify hash join explain analyze description

system-variables.md, temp.md
Example entry with `log.format="json"`, and the general log and redaction enabled:
```json
{
"level": "INFO",
"time": "2025/03/14 08:19:41.635 +01:00",
"caller": "session.go:4137",
"message": "GENERAL_LOG",
"conn": 2436890632,
"session_alias": "",
"user": "root@127.0.0.1",
"schemaVersion": 54,
"txnStartTS": 0,
"forUpdateTS": 0,
"isReadConsistency": false,
"currentDB": "",
"isPessimistic": false,
"sessionTxnMode": "PESSIMISTIC",
"sql": "select password ( ? )"
}
```
For details, see [tips for choosing …
=> system-variables: Update/extend tidb_general_log docs

encryption-at-rest.md
Clarify outdated TiKV SM4 encryption descriptions
=> Clarify TiKV SM4 encryption descriptions

br/br-pitr-guide.md
=> log-backup: added an explaination to the log status

TOC.md, ddl-introduction.md, metadata-lock.md, mysql-schema/mysql-schema-tidb-mdl-view.md, mysql-schema/mysql-schema.md
- This PR is translated from: https://github.com/pingcap/docs/pull/20329, https://github.com/pingcap/docs/pull/20714
=> Extend DDL/MDL info

stale-read.md
- This PR is translated from: https://github.com/pingcap/docs/pull/20667
=> stale read: update the description of tidb_external_ts

information-schema/information-schema-statistics.md
- This PR is translated from:https://github.com/pingcap/docs/pull/20717
=> information_schema: Update IS_VISIBLE description

optimizer-fix-controls.md
- This PR is translated from:https://github.com/pingcap/docs/pull/20744
=> update release for fix control 54337 to 8.3

ticdc/ticdc-manage-changefeed.md
=> ticdc: use `cdc cli changefeed list` to check `checkpoint-ts`

releases/release-6.0.0-dmr.md
=> v6.0.0 release notes: update the description of "setting incorrect values for system variables"

TOC.md, _index.md, deploy-monitoring-services.md, tidb-monitoring-framework.md
close https://github.com/pingcap/docs-cn/issues/20206
=> tidb-monitoring-framework: add TiDB Dashboard

keywords.md
v6.5: update keywords according to parser.y
=> v6.5: update keywords according to parser.y

temp.md, vector-search/vector-search-index.md
- This PR is translated from: https://github.com/pingcap/docs/pull/20809
=> docs: add attribution for KNN vector search description

character-set-and-collation.md, character-set-gbk.md, sql-statements/sql-statement-show-character-set.md
update the default collation of GBK from gbk_bin to gbk_chinese_ci
=> update the default collation of GBK from gbk_bin to gbk_chinese_ci

develop/dev-guide-optimize-sql.md
=> 修改错别字"更据"为"根据"

pd-configuration-file.md
=> pd configuration: add dashboard.disable-custom-prom-addr

releases/release-8.1.2.md
=> releases: add one br entry to v8.1.2

hardware-and-software-requirements.md
This PR updates "麒麟欧拉版" to "银河麒麟", because "银河麒麟" is more specific. 
=> hardware-and-software-requirements: update "麒麟欧拉版"  to "银河麒麟"

faq/sql-faq.md
This PR updates `defaultfetchsize` to `defaultFetchSize`.
=> JDBC URL: update the letter case for defaultFetchSize

character-set-and-collation.md, information-schema/information-schema-collations.md, sql-statements/sql-statement-show-collation.md, temp.md
Adds the `Pad_attribute` column to collations table descriptions
- This PR is translated from: https://github.com/pingcap/docs/pull/20823
- Other reference link(s): https://github.com/pingcap/tidb/issues/54250
=> Update pad attribute where needed

ticdc/ticdc-ddl.md
=> ticdc: add [[filter.event-filters]] to the toml example

develop/dev-guide-timeouts-in-tidb.md
=> dev guide: fix broken link

basic-features.md
=> basic-features: fix table formatting issue

auto-random.md
- This PR is translated from:https://github.com/pingcap/docs/pull/20734
=> docs: clarify AUTO_RANDOM_BASE usage and explicit insert behavior

tiproxy/tiproxy-overview.md, tiproxy/tiproxy-performance-test.md
The current performance description sounds scarier than it is. I need to make users comfortable.
=> tiproxy: rephrase TiProxy performance to make it comfortable

sql-statements/sql-statement-alter-table.md
Removes one confusing sentence from the `ALTER TABLE` document
=> sql: remove confusing description

quick-start-with-tidb.md
=> quick-start: add a note about minimum resource requirement

develop/dev-guide-bookshop-schema-design.md
This PR updates a step for data import according to the latest TiDB Cloud console UI.
- This PR is translated from: https://github.com/pingcap/docs/pull/20989
=> dev-guide-bookshop-schema-design: update a step for data import

best-practices/haproxy-best-practices.md
close #18858
HAProxy 2.6 is released every a few days to months and each version fixes lots of bugs, so it's hard to say which one is stable. Refer to https://git.haproxy.org/?p=haproxy-2.6.git;a=blob_plain;f=CHANGELOG.
Moreover, the doc claimed `推荐使用最新稳定版的 HAProxy，详情见[已发布的 HAProxy 版本](http://www.haproxy.org/)`, so it should be fine.
Among all the versions, only 2.6.9 fixed a critical bug. The current version is 2.6.22, but it didn't fix a major bug, so I chose 2.6.21 in the example.
For details, see …
=> replay haproxy 2.6.2 with 2.6.21

releases/release-8.5.0.md, tikv-configuration-file.md
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/19118
=> add `in-memory-engine` config items

mysql-schema/mysql-schema.md
Adding a doc about the internal BR table stored in mysql DB.
The table has been there for a while but the doc is not updated
- https://github.com/pingcap/docs/pull/21040
=> br: sys table pitr id map

dm/dm-best-practices.md
=> dm-best-practices: update the example for the auto random column

statement-summary-tables.md
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/18527
=> Add avg_tidb_cpu_time avg_tikv_cpu_time for statements summary doc

keywords.md
- https://github.com/pingcap/docs-cn/pull/13028  
- https://github.com/pingcap/docs-cn/pull/18285  
- https://github.com/pingcap/tidb/commit/c307c0dab5165976ce4694f303dc0851976a7f14#diff-28c98b105c2d87f58bd43aa5f34279eab9b450e359ccf41d50df9713a6a03540
- https://github.com/pingcap/parser/pull/1322
=> delete description about special non-reserved keywords that might still require special treatment

releases/release-7.4.0.md, tiflash/tiflash-configuration.md
=> tiflash: correct the default value of `task_scheduler_active_set_soft_limit`

releases/release-8.5.2.md
=> remove loong64 arch in release notes v8.5.2

tiproxy/tiproxy-configuration.md
Now that a cluster supports multiple virtual IPs, the original description `虚拟 IP 和所有 TiProxy 实例的 IP 必须处于同一个 CIDR 范围内` is confusing.
=> tiproxy: update vip description about CIDR

tiproxy/tiproxy-load-balance.md
=> tiproxy: fix image link in tiproxy-load-balance.md

tiproxy/tiproxy-load-balance.md
=> Revert "tiproxy: fix image link in tiproxy-load-balance.md"

develop/dev-guide-timeouts-in-tidb.md
=> feat: jdbc set query timeout

tiproxy/tiproxy-overview.md
Users may mistakenly think that upgrading tiproxy won't upgrade the cluster.
=> add notice about upgrading tiproxy

explain-walkthrough.md, temp.md
Fix wording in the explain walkthrough, the current working seems to imply that the initial performance is good (which it is not).  The rest of the walkthrough is to improve the performance, so the changed wording seems more correct.
This PR is translated from:  https://github.com/pingcap/docs/pull/20840
=> Fix wording to reflect poor performance of initial query before optimization

br/br-log-architecture.md
=> br: `{checkpoint_ts}-{uuid}.meta` should be `{resolved_ts}-{uuid}.meta`

ticdc/ticdc-changefeed-config.md
=> ticdc: fix wrong config value of `region-threshold`

clinic/clinic-data-instruction-for-tiup.md, temp.md
- This PR is translated from: https://github.com/pingcap/docs/pull/21129
=> clinic: list audit logs as included in diag

temp.md, tiflash/tiflash-compatibility.md, tiflash/use-fastscan.md
- This PR is translated from: https://github.com/pingcap/docs/pull/20461
=> TiFlash: small fixes and added links

pd-control.md
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/20641
=> pd-ctl: add notice for `member delete`

br/backup-storage-S3.md
A notice was added at the top of the S3 backup storage guide to direct users to the TiDB v7.5 backup and restore use cases documentation.
=> v6.1-br: add tip linking to v7.5 BR doc

br/backup-and-restore-use-cases.md
=> Revert "v6.5 br: add an v6.1 alias to br use cases"

tidb-configuration-file.md
=> overload-threshold: update the description of its effective scope

ticdc/ticdc-sink-to-mysql.md
close https://github.com/pingcap/docs/issues/21480
=> ticdc: add param `multi-stmt-enable` description in mysql sink

_docHome.md
Replaces template variable references with explicit 'TiDB Cloud' text in card labels and descriptions for improved clarity on the documentation home page.
- This PR is translated from: https://github.com/pingcap/docs/pull/21486
=> Update TiDB Cloud references on doc home

placement-rules-in-sql.md
=> sql: fix displayed result of `SHOW PLACEMENT LABELS`

ticdc/ticdc-filter.md
This PR adds a note to the TiCDC event filter documentation to clarify how the `matcher` parameter works with database-level DDLs.
When a `matcher` is configured (e.g., `matcher = ["test.t1"]`), it matches against the database name (`test`) as well. This can cause a broad rule like `ignore-sql = ["^drop"]` to unexpectedly filter `DROP DATABASE test` in addition to `DROP TABLE test.t1`.
This change adds an explicit note explaining this behavior and recommends using a more precise filter, such as `ignore-sql = ["drop table"]`, if the goal is to only ignore DDLs for the specific table.
This clarification helps prevent users from unintentionally filtering important database-level DDLs when they only mean to filter table-level events. It improves the predictability and safety of the event …
=> ticdc: clarify event filter matcher behavior for DB-level DDLs

maintain-tidb-using-tiup.md
=> Revert "v8.5: remove VictoriaMetrics guide"

tidb-troubleshooting-map.md
- Other reference link(s):https://github.com/pingcap/tidb/pull/12223
=> troubleshooting: remove outdated `max-txn-time-use`

system-variables.md
- This PR is translated from: https://github.com/pingcap/docs/pull/21551
=> v7.5.7: change the default value of tidb_enable_historical_stats

tiflash/tiflash-configuration.md
=> tiflash: add the default value of `enable_resource_control`

temp.md, tiproxy/tiproxy-deployment-topology.md, tiproxy/tiproxy-overview.md
Updated to: https://github.com/pingcap/tiproxy/releases/tag/v1.3.2
- This PR is translated from: https://github.com/pingcap/docs/pull/21780
=> Update TiProxy version to v1.3.2

sql-statements/sql-statement-load-data.md
- This PR is translated from:https://github.com/pingcap/docs/pull/21806
=> sql-statement-load-data: add DuplicateOpt 

best-practices-for-security-configuration.md, command-line-flags-for-tidb-configuration.md, temp.md
See also: https://github.com/pingcap/tidb/blob/master/docs/design/2021-09-29-secure-bootstrap.md
- This PR is translated from: https://github.com/pingcap/docs/pull/21738
=> Add details to the `--initialize-secure` option

tikv-configuration-file.md
=> tikv: clarify the description of config 'in-memory-engine.capacity'

tidb-configuration-file.md
This configuration was deprecated in https://github.com/pingcap/tidb/pull/60408.
- This PR is translated from: https://github.com/pingcap/docs/pull/20758
=> tidb: mark the concurrently-init-stats config as deprecated

best-practices/java-app-best-practices.md, develop/dev-guide-connection-parameters.md, dm/dm-glossary.md, migrate-from-mariadb.md
close https://github.com/pingcap/docs-cn/issues/20964
The MariaDB Knowledge Base has been migrated to a new documentation platform (`mariadb.com/docs/`). Many links using the old `kb/` path structure are now broken (returning 404 errors) or being redirected, which impacts user experience and documentation reliability.
- This PR is …
=> update MariaDB documentation links from `kb/` to `docs/`
