pingcap/docs-cn

- dev/how-to/monitor/monitor-a-cluster.md
- v2.1/how-to/monitor/monitor-a-cluster.md
- v3.0/how-to/monitor/monitor-a-cluster.md
- v3.1/how-to/monitor/monitor-a-cluster.md
> how-to: fix a typo

- dev/reference/configuration/tidb-server/tidb-specific-variables.md
- v3.0/reference/configuration/tidb-server/tidb-specific-variables.md
- v3.1/reference/configuration/tidb-server/tidb-specific-variables.md
Fix a TiDB parameter name.
N/A
> reference: fix a tidb parameter name

- dev/reference/tools/data-migration/dm-upgrade.md
- dev/reference/tools/data-migration/releases/1.0.3.md
- v2.1/reference/tools/data-migration/dm-upgrade.md
- v2.1/reference/tools/data-migration/releases/1.0.3.md
- v3.0/reference/tools/data-migration/dm-upgrade.md
- v3.0/reference/tools/data-migration/releases/1.0.3.md
- v3.1/reference/tools/data-migration/dm-upgrade.md
- v3.1/reference/tools/data-migration/releases/1.0.3.md
Add DM v1.0.3 release notes and update DM upgrade doc
dev/v3.0/v3.1/v2.0
> DM: Add v1.0.3 release notes and update DM upgrade doc

- dev/TOC.md
- v2.1/TOC.md
- v3.0/TOC.md
- v3.1/TOC.md
Add DM v1.0.3 in TOC
https://github.com/pingcap/docs-cn/pull/2118 
dev/v3.1/v3.0/v2.1
> DM: add dm v1.0.3 in TOC

- dev/how-to/maintain/backup-and-restore/mydumper-loader.md
- Add the missing character `\` in `wget http://download.pingcap.org/tidb-enterprise-tools-latest-linux-amd64.tar.gz &&`
- #2122 (closed)
- https://github.com/pingcap/docs-cn/pull/1838
- https://github.com/pingcap/docs/pull/1694
dev
> how-to/maintain: add the missing backslash character

- dev/how-to/deploy/orchestrated/ansible.md
- v2.1/how-to/deploy/orchestrated/ansible.md
- v3.0/how-to/deploy/orchestrated/ansible.md
- v3.1/how-to/deploy/orchestrated/ansible.md
- Correct the colon in `注意：` to support website demonstration
N/A
dev, v3.0, v3.1, v2.1
> how-to/deploy: fix the punctuation of Ansible Deployment doc

- dev/how-to/deploy/orchestrated/ansible.md
- dev/how-to/upgrade/from-previous-version.md
- v3.1/how-to/deploy/orchestrated/ansible.md
Update 3.1 version info in the Ansible deployment and upgrade docs
#2101 
dev, v3.1
> *: update version info related to v3.1

- dev/reference/tools/mydumper.md
- v2.1/reference/tools/mydumper.md
- v3.0/reference/tools/mydumper.md
- v3.1/reference/tools/mydumper.md
Add concurrent dump chapter in the Mydumper document.
NA
> tools: add concurrent dump chapter in mydumper document

- dev/tidb-in-kubernetes/deploy/tidb-operator.md
- v3.0/tidb-in-kubernetes/deploy/tidb-operator.md
- v3.1/tidb-in-kubernetes/deploy/tidb-operator.md
fix a typo
https://github.com/pingcap/docs-cn/pull/2105
dev/3.0/3.1
> tidb-operator: fix a typo

- dev/releases/3.1.0-beta.md
- v3.1/releases/3.1.0-beta.md
fix a release date
https://github.com/pingcap/docs-cn/pull/2101/
dev, 3.1
> releases: fix a release date

- dev/how-to/deploy/orchestrated/docker.md
- v2.1/how-to/deploy/orchestrated/docker.md
- v3.0/how-to/deploy/orchestrated/docker.md
- v3.1/how-to/deploy/orchestrated/docker.md
This PR updates the Docker Hub address.
https://github.com/pingcap/docs/pull/1713/
> how-to/deploy: update Docker Hub address

- v3.1/reference/tools/download.md
add br download introduction after v3.1.0beta published
v.3.1
> v3.1/reference/tools/download: add br download introduction

- dev/how-to/monitor/monitor-a-cluster.md
- v3.0/how-to/monitor/monitor-a-cluster.md
- v3.1/how-to/monitor/monitor-a-cluster.md
update prometheus config wrong format
N/A
> how-to/monitor: update prometheus config wrong format

- v3.1/how-to/maintain/backup-and-restore/br.md
add down link in br document
https://github.com/pingcap/docs-cn/pull/2143
v3.1
> /v3.1/how-to/maintain/backup-and-restore/br: add br download link

- dev/how-to/maintain/backup-and-restore/br.md
- v3.1/how-to/maintain/backup-and-restore/br.md
This PR refines `br.md`.
N/A
v3.1, dev
> maintain/backup-and-restore: refine br doc

- dev/reference/security/cert-based-authentication.md
- v3.0/reference/security/cert-based-authentication.md
Improve the usability of the certificate-based authentication document.
https://github.com/pingcap/docs/pull/1740
dev, v3.0
> reference: improve usability of certificate-based authentication doc

- dev/how-to/scale/with-ansible.md
- v3.0/how-to/scale/with-ansible.md
- v3.1/how-to/scale/with-ansible.md
This PR updates a note in `with-ansible.md`.
https://github.com/pingcap/docs-cn/pull/2126/
> how-to/scale/with-ansible: add a note

- dev/reference/tools/mydumper.md
- v2.1/reference/tools/mydumper.md
- v3.0/reference/tools/mydumper.md
- v3.1/reference/tools/mydumper.md
- Update the description: "加上 `--skip-tz-utc` 参数忽略这种转化" -> "加上 `--skip-tz-utc` 参数禁止这种转化"
N/A
> reference/tools: improve the wording of mydumper doc

- dev/tidb-in-kubernetes/troubleshoot.md
- v3.0/tidb-in-kubernetes/troubleshoot.md
- v3.1/tidb-in-kubernetes/troubleshoot.md
Refine the language of k8s troubleshoot document.
N/A
> tidb-in-kubernetes: refine the language of k8s troubleshoot doc

- v2.1/reference/mysql-compatibility.md
- Update supported character sets in v2.1
https://github.com/pingcap/docs-cn/pull/1907
v2.1
> reference: update supported character sets

- dev/reference/best-practices/grafana-monitor.md
- v2.1/reference/best-practices/grafana-monitor.md
- v3.0/reference/best-practices/grafana-monitor.md
- v3.1/reference/best-practices/grafana-monitor.md
update grafana best practice
3.0, 3.1, dev, 2.1
> reference: update grafana best practice

- CONTRIBUTING.md
> CONTRIBUTING: fix a broken link

- dev/TOC.md
- dev/releases/3.1.0-beta.1.md
- dev/releases/rn.md
- v3.1/TOC.md
- v3.1/releases/3.1.0-beta.1.md
- v3.1/releases/rn.md
add 3.1.0-beta.1 release notes
https://github.com/pingcap/docs/pull/1763
dev, v3.1
> dev, v3.1: add 3.1.0-beta.1 release notes

- dev/reference/tidb-binlog/upgrade.md
- v2.1/reference/tidb-binlog/upgrade.md
- v3.0/reference/tidb-binlog/upgrade.md
- v3.1/reference/tidb-binlog/upgrade.md
The original document only introduce how to upgrade from kafka/local version to the cluster version.
This PR adds introduction to cover how to upgrade from one version to another in the cluster version.
> tidb-binlog: introduce how to upgrade binlog

- v3.1/TOC.md
- v3.1/reference/security/cert-based-authentication.md
Add the certificate-based authentication document for v3.1.
https://github.com/pingcap/docs-cn/pull/2153
https://github.com/pingcap/docs-cn/pull/2162
https://github.com/pingcap/docs/pull/1770
v3.1
> reference/security: add cert-based authentication doc for v3.1

- dev/releases/3.0.9.md
- v3.0/releases/3.0.9.md
- v3.1/releases/3.0.9.md
Add a note to the TiDB 3.0.9 Release Notes.
https://github.com/pingcap/docs/pull/1771
> release: add a note to 3.0.9 release notes

- dev/TOC.md
- dev/releases/4.0.0-beta.md
- dev/releases/rn.md
> releases, toc: add 4.0.0-beta release notes

- dev/releases/4.0.0-beta.md
Improve the format of 4.0.0-beta Release Notes.
> releases: improve format of 4.0.0-beta release notes

- v2.1/TOC.md
- v2.1/reference/tools/data-migration/glossary.md
> tools: add a glossary for dm in v2.1

- v3.1/reference/performance/optimizer-hints.md
delete two inapplicable optimizer hints
> v3.1: delete inapplicable optimizer hints

- dev/reference/sql/statements/admin.md
remove statement repetition in dev/reference/sql/statements/admin.md
> reference/sql/statements/admin: remove statement repetition for admin doc

- dev/reference/supported-clients.md
- v1.0/sql/connection-and-APIs.md
- v2.0/sql/connection-and-APIs.md
- v2.1-legacy/sql/connection-and-APIs.md
- v2.1/reference/supported-clients.md
- v3.0/reference/supported-clients.md
- v3.1/reference/supported-clients.md
Remove the MyDB API link, because the original link is invalid. 
> *: remove MyDB

- dev/tidb-in-kubernetes/deploy/alibaba-cloud.md
- v3.0/tidb-in-kubernetes/deploy/alibaba-cloud.md
- v3.1/tidb-in-kubernetes/deploy/alibaba-cloud.md
Signed-off-by: Yecheng Fu <fuyecheng@pingcap.com>
> tidb-in-kubernetes/deploy: required terraform must be 0.12.*

- dev/tidb-in-kubernetes/deploy/aws-eks.md
- v3.0/tidb-in-kubernetes/deploy/aws-eks.md
- v3.1/tidb-in-kubernetes/deploy/aws-eks.md
Fix `Error: Error parsing /Users/ruby/work/test/tidb-operator/deploy/aws/clusters.tf: At 2:24: unexpected token while parsing list: IDENT` for Terraform v0.11.8
> kubernetes: terraform must be >= v0.12

- dev/reference/performance/optimizer-hints.md
- v3.1/reference/performance/optimizer-hints.md
move description before the example
> optimizer-hints: move description before the example

- CONTRIBUTING.md
Update version description in `CONTRIBUTING.md`
> contributing: update version description

- dev/TOC.md
- dev/reference/tools/tidb-lightning/glossary.md
- v2.1/TOC.md
- v2.1/reference/tools/tidb-lightning/glossary.md
- v3.0/TOC.md
- v3.0/reference/tools/tidb-lightning/glossary.md
- v3.1/TOC.md
- v3.1/reference/tools/tidb-lightning/glossary.md
This PR adds a glossary for TiDB-lightning.
>  tidb-lightning: add glossary

- dev/reference/tools/br/use-cases.md
- v3.1/reference/tools/br/use-cases.md
Add a missing alias to the BR Use Case document.
> reference/tools: add br aliases

- dev/reference/tools/br/use-cases.md
- v3.1/reference/tools/br/use-cases.md
Refine the format of the BR Scenario Demonstration document.
> reference/tools: refine format

- README.md
make some minor edits to test cherry-pick
> readme: make some minor edits to test cherry-pick

- .github/pull_request_template.md
> .github: update pr template

- scripts/markdown-link-check.tpl
- scripts/verify-links.sh
> scripts: update verify links to fit current layout

- TOC.md
- reference/best-practices/high-concurrency.md
- reference/configuration/tidb-server/configuration-file.md
- reference/sql/attributes/auto-random.md
- reference/sql/language-structure/comment-syntax.md
- reference/sql/language-structure/keywords-and-reserved-words.md
- reference/sql/statements/create-table.md
Cherry-pick #2209.
- Reference link(s): #2209
> reference: add user documentation for auto_random feature (#2209)

- scripts/verify-links.sh
update error messages in link check CI report 
> scripts/verify-links: update link check error messages

- reference/tools/download.md
some users use latest version, but the latest version is built from our develop branch, is unstable and may incompatible with the release version, we don't suggest users use the latest version.
> tools: remove latest in download document

- reference/tools/download.md
some users use latest version, but the latest version is built from our develop branch, is unstable and may incompatible with the release version, we don't suggest users use the latest version.
- Reference link(s): cherry-pick https://github.com/pingcap/docs-cn/pull/2296
> tools: remove latest in download document 

- reference/tools/download.md
remove a `latest` replacement suggestion in tools download doc (forget to remove it in https://github.com/pingcap/docs-cn/pull/2301/files)
- Reference link(s): 
> tools: remove `latest` replacement suggestion

- how-to/get-started/tispark.md
Change the download address of the TiSpark sample data.
- Reference link(s): 
- This PR is to align with: https://github.com/pingcap/docs/pull/1861 https://github.com/pingcap/docs/pull/1780
> how-to/get-started: change tispark-sample-data download address

- how-to/get-started/tispark.md
Change the download address of the TiSpark sample data.
- Reference link(s): https://github.com/pingcap/docs/pull/1861, https://github.com/pingcap/docs-cn/pull/2316
- This PR is to align with: https://github.com/pingcap/docs/pull/1877 
> how-to/get-started: change tispark-sample-data download address for v2.1

- TOC.md
- releases/4.0.0-beta.1.md
- releases/rn.md
Adds TiDB 4.0 Beta.1 Release Notes.
> releases: add TiDB 4.0.0-beta.1 Release Notes

- reference/configuration/tidb-server/configuration-file.md
- reference/configuration/tidb-server/tidb-specific-variables.md
https://github.com/pingcap/tidb/pull/12491
> config: update the default value of `query-log-max-len` from 2048 to 4096

- how-to/maintain/identify-abnormal-queries/identify-slow-queries.md
Add `backoff` information into the slow-log doc.
https://github.com/pingcap/tidb/pull/13770
> sql: add `backoff` information into the slow-log doc

- reference/tidb-binlog/monitor.md
Remove unnecessary aliases for the TiDB Binlog monitor doc in v3.0.
> how-to/tidb-binlog: remove unnecessary aliases

- how-to/scale/with-ansible.md
add Install the NTP service on the target machines
add Configure the SSH mutual trust and sudo rules on the Control Machine
> how-to/scale: add necessary actions on the target machines

- reference/best-practices/high-concurrency.md
Fix a typo.
- Other reference link(s):https://github.com/pingcap/docs-cn/issues/2373
> best-practices: fix a typo

- tidb-in-kubernetes/maintain/backup-and-restore/backup-gcs.md
- tidb-in-kubernetes/maintain/backup-and-restore/backup-s3.md
- tidb-in-kubernetes/maintain/backup-and-restore/charts.md
- tidb-in-kubernetes/maintain/backup-and-restore/restore-gcs.md
- tidb-in-kubernetes/maintain/backup-and-restore/restore-s3.md
Refine the wording and usability of K8s backup and restoration docs.
> tidb-in-kubernetes: refine backup and restore docs

- releases/4.0.0-beta.md
Fix a typo in TiDB 4.0.0-beta Release Notes: 解藕->解藕  to close https://github.com/pingcap/docs-cn/issues/2381
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/2381
> releases:fix a typo

- faq/tidb.md
Fix sysbench links
- This PR is translated from:https://github.com/pingcap/docs/pull/1963
> faq: fix sysbench links

- reference/transactions/transaction-optimistic.md
Change the code block type from `sql` to `toml`.
> reference/transactions: fix code block style

- reference/tools/br/br.md
> reference/tools: refine format of a default value in br document

- how-to/secure/enable-tls-clients.md
> how-to/secure: fix TLS client typo

- releases/3.1.0-beta.2.md
Change the format of 3.1.0-beta.2 release notes.
> releases: change the format of 3.1.0-beta.2 release notes

- reference/configuration/tidb-server/configuration-file.md
update the tidb-server oom-action to `cancel`
https://github.com/pingcap/tidb/issues/15224
> configuration: change tidb-server oom-action configuration to cancel

- CONTRIBUTING.md
Fix a typo in markdownlint rules No.11
v2.0
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/2017
> contributing: fix a typo

- tidb-in-kubernetes/maintain/backup-and-restore/charts.md
Fix an alias in the k8s backup and restore document.
> tidb-in-kubernetes: fix an alias

- how-to/deploy/data-migration-with-ansible.md
don't suggest user to use latest version in dm-ansible, remove it
> how-to/deploy: do not suggest user to use latest version in dm-ansible

- TOC.md
- reference/tools/data-migration/releases/1.0.4.md
add release notes for DM v1.0.4.
> data migration: add release notes for v1.0.4

- overview.md
> Overview: fixed some typos

- how-to/deploy/orchestrated/ansible.md
> Add arm for deployment by tidb-ansible

- TOC.md
add v4.0 doc links in TOC.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/2251, https://github.com/pingcap/docs-cn/pull/2264
> TOC: add v4.0 doc links

- how-to/deploy/orchestrated/ansible.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/2501
> Update the ansible deployment documentation

- reference/tidb-binlog/monitor.md
This PR fixes the format of Drainer table
> reference/tidb-binlog: fix the format of Drainer table

- reference/tools/data-migration/troubleshoot/error-handling.md
add handling suggestions about GTID, when setting the parameter enable_gtid to true
> dm: update error handling guide

- reference/tools/data-migration/troubleshoot/error-handling.md
Add handling suggestions about GTID, when setting the parameter enable_gtid to true.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/2528
> dm: update error handling for 3.0

- reference/best-practices/pd-scheduling.md
Updates the master changes in https://github.com/pingcap/docs-cn/pull/2215.
The v3.1 changes are made in https://github.com/pingcap/docs-cn/pull/2507
> best-practice: re-fix namespace-classifier value

- reference/tools/data-migration/dm-portal.md
Editing the configuration file is not supported in DM-Portal, so remove this content.
**Note:** Changes for 3.1, 3.0, 2.1 are already covered in #2480.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/2480
> tools: remove edit config file in dm-portal for dev

- reference/tools/data-migration/dm-portal.md
- Fix some error in DM Portal doc.
- Add brief introduction between headings.
- Add a summary.
- Other reference link(s): https://github.com/pingcap/docs/pull/2044
> DM: fix error in dm portal

- tidb-in-kubernetes/deploy/aws-eks.md
Fix inconsistency with other versions
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/1984
> tidb-in-kubernetes: fix inconsistency with other versions

- _index.md
- faq/tidb.md
- how-to/deploy/data-migration-with-ansible.md
- how-to/deploy/geographic-redundancy/location-awareness.md
- how-to/deploy/orchestrated/ansible.md
- how-to/deploy/orchestrated/docker.md
- how-to/deploy/orchestrated/offline-ansible.md
- how-to/get-started/deploy-tidb-from-docker-compose.md
- how-to/scale/horizontally.md
- how-to/troubleshoot/tidb-lightning.md
- how-to/upgrade/from-previous-version.md
- overview.md
- reference/best-practices/grafana-monitor.md
- reference/key-monitoring-metrics/overview-dashboard.md
- reference/key-monitoring-metrics/pd-dashboard.md
- reference/key-monitoring-metrics/tidb-dashboard.md
- reference/key-monitoring-metrics/tikv-dashboard.md
- reference/tidb-binlog/deploy.md
- reference/tidb-binlog/monitor.md
- reference/tidb-binlog/tidb-binlog-kafka.md
- reference/tidb-binlog/tidb-binlog-local.md
- reference/tidb-binlog/upgrade.md
- reference/tools/data-migration/cluster-operations.md
- reference/tools/data-migration/faq.md
- reference/tools/tidb-lightning/deployment.md
- reference/tools/tikv-control.md
Change `Ansible` to `TiDB Ansible` or `DM-Ansible` in proper places.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/2575
> *: unify ansible names for v2.1

- _index.md
- benchmark/how-to-run-tpcc.md
- faq/tidb.md
- how-to/deploy/data-migration-with-ansible.md
- how-to/deploy/geographic-redundancy/location-awareness.md
- how-to/deploy/orchestrated/ansible.md
- how-to/deploy/orchestrated/docker.md
- how-to/deploy/orchestrated/offline-ansible.md
- how-to/get-started/deploy-tidb-from-docker-compose.md
- how-to/scale/horizontally.md
- how-to/troubleshoot/tidb-lightning.md
- how-to/upgrade/from-previous-version.md
- overview.md
- reference/best-practices/grafana-monitor.md
- reference/key-monitoring-metrics/overview-dashboard.md
- reference/key-monitoring-metrics/pd-dashboard.md
- reference/key-monitoring-metrics/tidb-dashboard.md
- reference/key-monitoring-metrics/tikv-dashboard.md
- reference/tidb-binlog/deploy.md
- reference/tidb-binlog/monitor.md
- reference/tidb-binlog/tidb-binlog-kafka.md
- reference/tidb-binlog/tidb-binlog-local.md
- reference/tidb-binlog/upgrade.md
- reference/tools/data-migration/cluster-operations.md
- reference/tools/data-migration/faq.md
- reference/tools/tidb-lightning/deployment.md
- reference/tools/tidb-lightning/tidb-backend.md
Change `Ansible` to `TiDB Ansible` or `DM-Ansible` in proper places.
v2.1 is updated in [#2576](https://github.com/pingcap/docs-cn/pull/2576) to avoid excessive conflicts.
> *: unify ansible names

- reference/tools/tidb-control.md
add description of the `keyrange` subcommand.
https://github.com/pingcap/tidb-ctl/pull/29
> tools: update tidb-ctl doc

- reference/performance/optimizer-hints.md
Add "ignore_plan_cache" hint for prepare statements to ignore plan cache.
optimizer-hints.md is changed.
- Other reference link(s): issue [issue 15587](https://github.com/pingcap/tidb/issues/15587)
> reference/performance: update optimizer-hints

- TOC.md
> TOC: fix dead links

- reference/error-codes.md
- reference/transactions/transaction-pessimistic.md
Update some error code changes and transaction-related documents.
> reference: update transaction related master docs

- reference/configuration/tidb-server/mysql-variables.md
add a mysql system variable [windowing_use_high_precision](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_windowing_use_high_precision)
-  master (the latest development version, including v4.0 changes for now)
https://github.com/pingcap/tidb/pull/15606
https://github.com/pingcap/tidb/pull/14887
> reference: add a mysql var windowing_use_high_precision

- TOC.md
fix a TOC link
- Other reference link(s): http://github.com/pingcap/docs-cn/pull/2603
> TiFlash: fix a TOC link

- reference/tiflash/tune-performance.md
> reference: update TiFlash tune doc

- how-to/deploy/orchestrated/ansible.md
- how-to/upgrade/from-previous-version.md
Update Ansible deployment and upgrade documents for v4.0 (only apply to 4.0, does not apply to master).
The changes in this PR is migrated from https://github.com/pingcap/docs-cn/pull/2583.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/2583
> how-to: update ansible document for v4.0

- reference/tiflash/upgrade.md
update tiflash 3.1 upgrade document, according to https://pingcap.com/docs-cn/stable/how-to/upgrade/from-previous-version/
> update tiflash 3.1 upgrade document

- how-to/upgrade/from-previous-version.md
Fix a typo in title and remove aliases in 4.0 ansible upgrade doc.
To close https://github.com/pingcap/docs-cn/issues/2665.
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/2633
> how-to/upgrade: fix typo in title and remove aliases in 4.0 ansible upgrade doc

- reference/tiflash/maintain.md
- reference/tiflash/scale.md
- releases/2.1.17.md
fix a typo: tomestone -> tombstone
> typo: tomestone -> tombstone

- TOC.md
- how-to/scale/with-tiup.md
预期输出 Scaled cluster `<cluster-name>` out successfully 信息，表示扩容操作成功。
预期输出 Scaled cluster `<cluster-name>` in successfully 信息，表示缩容操作成功。
打开浏览器访问监控平台 <http://10.0.1.5:3200>，监控整个集群的状态。
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/2645
> how-to/scale: fix typo and add TOC link

- how-to/maintain/backup-and-restore/mydumper-lightning.md
- how-to/maintain/identify-abnormal-queries/identify-expensive-queries.md
- how-to/maintain/identify-abnormal-queries/identify-slow-queries.md
- how-to/migrate/from-mysql-aurora.md
- reference/best-practices/java-app.md
- reference/tidb-binlog/binlog-slave-client.md
- reference/tidb-binlog/deploy.md
- reference/tidb-binlog/faq.md
- reference/tidb-binlog/maintain.md
- reference/tidb-binlog/monitor.md
- reference/tidb-binlog/overview.md
- reference/tidb-binlog/relay-log.md
- reference/tidb-binlog/reparo.md
- reference/tidb-binlog/tidb-binlog-kafka.md
- reference/tidb-binlog/tidb-binlog-local.md
- reference/tidb-binlog/troubleshoot/binlog.md
- reference/tidb-binlog/upgrade.md
- reference/tools/br/br.md
- reference/tools/br/use-cases.md
- reference/tools/tidb-control.md
- reference/tools/user-guide.md
- reference/transactions/transaction-optimistic.md
- roadmap.md
> *: remove aliases

- releases/3.0.10.md
- releases/3.0.11.md
- releases/3.0.12.md
- releases/3.0.9.md
- releases/3.1.0-beta.2.md
- releases/4.0.0-beta.1.md
- releases/4.0.0-beta.2.md
- releases/4.0.0-beta.md
- releases/4.0.0-rc.md
Unify the format in release notes.
- This PR is translated from: https://github.com/pingcap/docs/pull/2262
> releases: unify release notes format

- how-to/upgrade/using-tiup.md
fix the config path
- [*] master (the latest development version)
- [*] v4.0 (TiDB 4.0 versions)
> fix the config path in using-tiup.md

- how-to/upgrade/using-tiup.md
> tiup: fix the config path in using-tiup.md

- reference/error-codes.md
Change error code format. Nearly no content changes.
> reference: change error code format to list

- reference/tiflash/configuration.md
> Modify tiflash proxy config explanation

- reference/tiflash/upgrade.md
add warning to upgrade pre-rc version of tiflash
> tiflash: add warning to upgrade from pre-rc version

- reference/configuration/tikv-server/configuration-file.md
Signed-off-by: Yilin Chen <sticnarf@gmail.com>
Add more descriptions to the unified read pool. It would help users understand better.
> reference: add more descriptions to readpool.unified

- reference/tiflash/deploy.md
> tiflash: remove tiflash tar

- reference/configuration/tidb-server/configuration-file.md
unify the configuration name style by replacing `temp` into `tmp`
https://github.com/pingcap/tidb/pull/16431
> references/configuration: unify the configuration name style 

- _index.md
- overview.md
remove ansible deployment method and update notes in ansible deployment doc
- This PR is translated from: https://github.com/pingcap/docs/pull/2317
> *: remove ansible deployment method and update notes in ansible deployment doc

- README.md
- benchmark/how-to-run-sysbench.md
- faq/tidb.md
- how-to/deploy/orchestrated/ansible.md
update ansible deployment description to tiup deployment description
> *: update ansible deployment description to tiup deployment description

- reference/tidb-binlog/reparo.md
> tidb-binlog: remove useless config of reparo

- quick-start-with-tidb.md
The `copyable` code snippet misses a `{`.
- This PR is translated from:https://github.com/pingcap/docs/pull/2348
> quick-start-with-tidb: fix typo

- quick-start-with-tidb.md
remove the playground installation part
- This PR is translated from:https://github.com/pingcap/docs/pull/2356
> TiUP: remove playground installation

- TOC.md
- how-to/maintain/tiup-operations.md
Signed-off-by: lucklove <gnu.crazier@gmail.com>
> tiup: ducument how to maintain a TiDB cluster using tiup

- how-to/maintain/tiup-operations.md
> tiup: fix an indentation issue

- how-to/maintain/identify-abnormal-queries/identify-slow-queries.md
> how-to: fix the Mem_max field name

- how-to/deploy/orchestrated/tiup.md
- quick-start-with-tidb.md
update the default value for unified
> tiup: update the default value for `readpool.storage.use-unified-pool`

- how-to/deploy/orchestrated/tiup.md
> how-to/deploy: update format for tiflash

- reference/tiflash/use-tiflash.md
Add description about behavior under tidb CBO mode.
> tiflash: Update behavior under CBO mode

- how-to/deploy/orchestrated/tiup.md
Signed-off-by: lucklove <gnu.crazier@gmail.com>
> tiup: simplify topology example

- how-to/deploy/orchestrated/tiup.md
- how-to/upgrade/using-tiup.md
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>
Fix tiup example yaml link.
- This PR is translated from: https://github.com/pingcap-incubator/tiup-cluster/pull/343
> fix tiup example yaml link

- how-to/maintain/tiup-operations.md
> how-to/maintain: fix the TiUP parameter link

- how-to/monitor/key-visualizer.md
Refine the image size in the Key Visualizer document.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/2432
> how-to/monitor: refine the image size of key visualizer

- how-to/maintain/tiup-operations.md
Update the TiUP parameter link
https://github.com/pingcap/docs-cn/pull/2930
> how-to/maintain: update the TiUP parameter link

- TOC.md
- releases/3.1.1.md
- releases/rn.md
> releases, toc: add 3.1.1 release notes

- CONTRIBUTING.md
Add the link to join Slack #sig-docs channel to track source
- This PR is translated from: https://github.com/pingcap/docs/pull/2449
> contributing: add a link to join #sig-docs Slack channel

- .github/workflows/media.yml
As the title.
Related PR: https://github.com/pingcap/docs/pull/2464
> ci: add GitHub action to upload media files

- CONTRIBUTING.md
Add the link of #sig-docs slack channel with referral.
> contributing: add link of #sig-docs slack channel with referral

- reference/tidb-binlog/monitor.md
> tools: fix typo of binlog's minitor

- how-to/deploy/orchestrated/tiup.md
> tiup: modify user login description

- reference/performance/tune-tikv.md
> reference/performance: reorder tikv tuning log parameters

- how-to/scale/with-tiup.md
- reference/tools/ticdc/deploy.md
fix two titles in scale/with-tiup.md
- This PR is translated from: https://github.com/pingcap/docs/pull/2463
- Other reference link(s): to fix small issues In https://github.com/pingcap/docs-cn/pull/2938
> tiup: fix two titles in scale/with-tiup.md

- reference/tools/tiup/playground.md
refine expressions in playground.md
- Other reference link(s): https://github.com/pingcap/docs/pull/2480/
> tiup: refine expressions in playground.md

- reference/tools/tiup/cluster.md
> tiup: add -p flag on deploy incluster.md

- reference/tools/tiup/mirrors.md
- reference/tools/tiup/package-component.md
- This PR is translated in: https://github.com/pingcap/docs/pull/2481
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/2878
> TiUP: improve expressions in mirrors.md and package-component.md

- how-to/monitor/key-visualizer.md
Change the image format for better doc maintenance.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/2929
> how-to/monitor: change the image format for better doc maintenance

- reference/performance/tune-tikv.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/2948
> reference/performance: reorder tikv tuning log parameters #2948

- releases/3.0.14.md
Add a note to TiDB 3.0.14 release notes.
> releases: add a note to tidb 3.0.14 release notes

- reference/sql/data-types/json.md
已有的写法并没有创建索引，需要在 create table 时指定 index index_name (index_column)
> reference/sql: create index in json strings

- how-to/deploy/orchestrated/tiup.md
Fix a typo.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/3070
> how-to/deploy: fix a typo

- follower-read.md
- transaction-overview.md
Some descriptions of transaction isolation are out of date.
> reference: fix some mistakes about transaction isolation

- coprocessor-cache.md
> reference/performance: fix an anchor

- production-deployment-using-tiup.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/3113
> how-to/deploy: fix typos

- TOC.md
- releases/release-4.0.0-rc.2.md
- releases/release-notes.md
> releases: add 4.0.0-rc.2 release notes

- releases/release-4.0.0-rc.2.md
Fix typos in TiDB 4.0.0-rc.2 release notes.
> releases: fix typos in 4.0.0-rc.2

- releases/release-4.0.0-rc.2.md
Fix the confusing description of the transaction size limit.
> releases: fix an unclear note in 4.0.0-rc.2

- TOC.md
Remove tiflash section in old TOC (commented out) to prevent lint error
> Remove tiflash section in old TOC (commented out) to prevent lint error

- resources/figma-quick-start-guide.md
Update the Figma design template link
> resources: update the Figma link

- TOC.md
> Fix TOC.md

- deploy-monitoring-services.md
- geo-distributed-deployment-topology.md
- hybrid-deployment-topology.md
- minimal-deployment-topology.md
- ticdc-deployment-topology.md
- tidb-binlog-deployment-topology.md
- tidb-monitoring-api.md
- tiflash-deployment-topology.md
> change aliases

- best-practices/tidb-best-practices.md
- dashboard/dashboard-statement-detail.md
- dashboard/dashboard-statement-list.md
- faq/sql-faq.md
- releases/release-2.1.17.md
- releases/release-2.1.18.md
- ticdc-deployment-topology.md
- ticdc/manage-ticdc.md
- ticdc/ticdc-open-protocol.md
- tidb-best-practices.md
- tidb-configuration-file.md
- tispark-overview.md
- troubleshoot-hot-spot-issues.md
- upgrade-tidb-using-tiup.md
> change absolute path to relative path of docs-cn repo files

- sql-statements/sql-statement-revoke-privileges.md
- sql-statements/sql-statement-set-variable.md
- tikv-configuration-file.md
Fix build issues in release-3.1
> fix build issues in release-3.1

- TOC.md
- Update the position for several topics
- Remove 开发指南
- Move TiUP topics temporarily to 参考指南; will have its own docs repo soon @scsldb FYI.
> toc: udpate position and wording for new toc

- TOC.md
- quick-start-with-tidb.md
- test-deployment-using-docker.md
- Remove `test-deployment-using-docker.md` from `TOC.md`
- Add `draft: true` to the metadata of `test-deployment-using-docker.md`
> *: remove testing deployment using Docker

- TOC.md
- benchmark/v4.0-performance-benchmarking-with-tpch.md
Remove 4.0 vs 3.0 TPC-H test report from TOC.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/3392
> remove 4.0 TPC-H from TOC

- post-installation-check.md
- production-deployment-using-tiup.md
- production-offline-deployment-using-tiup.md
- ticdc/troubleshoot-ticdc.md
> update deploy document to v4.0.0

- TOC.md
Add Coprocessor Cache to TOC, which might have been removed.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/2857
> toc: add coprocessor cache to toc

- statement-summary-tables.md
- add descriptions about new params introduced in https://github.com/pingcap/tidb/pull/16476
- fix https://github.com/pingcap/tidb/issues/16217
> add descriptions about new params for plan cache

- benchmark/benchmark-sysbench-v4-vs-v3.md
> Fix typos in 4.0 test report

- quick-start-with-tidb.md
The incorrect indent blocks docs website building
> style: format indent

- TOC.md
The code tag on folder level does not parse well on new doc website 
> remove code tag from folder level

- tidb-troubleshooting-map.md
There are typos in the sentence that "调大改参数" and "优化改机制"， it should be changed to "该"。
> troubleshooting: fix two typos in tidb-troubleshooting-map.md

- production-deployment-using-tiup.md
> correct heading levels

- TOC.md
Remove links at the folder level in TOC.
> toc: remove links at folder level

- releases/release-3.0.13.md
- releases/release-3.0.14.md
Remove TiUP version in release notes.
- This PR is translated from: https://github.com/pingcap/docs/pull/2682
> releases: remove tiup version

- tiflash/tune-tiflash-performance.md
Modify "distince" to "dintinct"
The word "distince" should be "distinct";
- [] v3.1 (TiDB 3.1 versions)
> fix one typo in tune-tiflash-performance.md

- faq/tidb-faq.md
> zh: improve description for public cloud

- TOC.md
fix TOC introduced in https://github.com/pingcap/docs-cn/pull/3526#discussion_r435858797.
#3526
> *: fix TOC

- whats-new-in-tidb-4.0.md
Fix typos in what's new in TiDB 4.0.
> Fix typos in what's new in TiDB 4.0

- ticdc/ticdc-overview.md
Remove `暂不支持同步分区表。` since this scenario is supported now
- This PR is translated in: https://github.com/pingcap/docs/pull/2694
> TiCDC: Update unsupported scenarios in ticdc-overview.md

- dashboard/dashboard-overview.md
Fix pic and typos in dashboard-overview.md.
> dashboard: fix pic and typos in dashboard-overview.md

- TOC.md
3.1/3.0: https://github.com/pingcap/docs/pull/2808/files
2.1: https://github.com/pingcap/docs-cn/pull/3583
> add migrate-from-mysql-mydumper-files.md to TOC

- basic-features.md
modify some wrong word
changed
> modify some wrong word

- basic-features.md
- releases/release-2.1.15.md
- releases/release-3.0-ga.md
- releases/release-3.0.1.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/3639
> change a typo

- configure-placement-rules.md
> update warning for placement rules

- TOC.md
- _index.md
- migration-overview.md
- quick-start-with-tidb.md
change `data-migration-route.md` to `migration-overview.md`
- This PR is translated in: https://github.com/pingcap/docs/pull/2774
> data migration: rename `data-migration-route.md`

- .markdownlint.yaml
- deploy-test-cluster-using-docker-compose.md
- quick-start-with-tidb.md
- schedule-replicas-by-topology-labels.md
- test-deployment-using-docker.md
> add deprecated warnings for outdated deployment methods

- tidb-configuration-file.md
add explaination about a new system variable `nested-loop-join-cache-capacity` to tidb-configuration-file.md
- https://github.com/pingcap/tidb/pull/17039
> add explaination about `nested-loop-join-cache-capacity`

- tikv-configuration-file.md
> Fix titan compression type

- sql-statements/sql-statement-admin.md
- This PR is translated from: https://github.com/pingcap/docs/pull/2928/
> sql-statement-admin.md: fix heading levels

- data-type-json.md
- functions-and-operators/json-functions.md
- generated-columns.md
- tidb-configuration-file.md
> *: add warnings

- user-defined-variables.md
> *: add warnings for user variables

- .github/assign-by-files.yml
- .github/workflows/auto-assign.yml
> Fix auto assign config

- tiflash/use-tiflash.md
> update tiflash expr pushdown list

- CONTRIBUTING.md
- README.md
- TOC.md
- _index.md
- architecture.md
- dashboard/dashboard-ops-deploy.md
- download-ecosystem-tools.md
- ecosystem-tool-user-case.md
- ecosystem-tool-user-guide.md
- faq/tidb-faq.md
- migrate-from-aurora-mysql-database.md
- overview.md
- quick-start-with-tidb.md
- syncer-overview.md
- tidb-troubleshooting-map.md
- Update links: `stable` to `v4.0` for tidb, `v1.1` for tidb-operator, `v1.0` for dm
- Updata old links to new links with `docs.pingcap.com`
- Update wording: Cloud TiDB > TiDB Cloud
> *: update links from stable to v4.0 and new docs urls

- telemetry.md
> update for operator deployment

- daily-check.md
add aliases (new website)
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/3535
> daily.check.md: add aliases

- user-defined-variables.md
> fix typo in user-defined-variable.md

- configure-store-limit.md
Update the store limit configuration to the latest master.
> Update store limit configuration

- keywords.md
update letter id to match anchor link
- This PR is translated from: https://github.com/pingcap/docs/pull/3088
> chore: update letter id

- tidb-lightning/tidb-lightning-overview.md
> tidb-lightning: add an alias

- loader-overview.md
> loader-overview: add an alias

- configure-store-limit.md
Add store limit guide for release 3.0 branch
> Add store limit guide

- garbage-collection-configuration.md
cherry-pick from https://github.com/pingcap/docs-cn/pull/3807
> remove duplicate note in garbage-collection-configuration.md (#3807)

- literal-values.md
Fix typo in literal values
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/3236
> Fix typo in literal values

- production-deployment-using-tiup.md
`deploy-tiflash.md` is reorganized as part of `production-deployment-using-tiup.md`.
This PR adds an alias for TiFlash deployment in `production-deployment-using-tiup.md`.
> deploy: add aliases for tiflash deployment

- dashboard/dashboard-ops-reverse-proxy.md
> dev/dashboard: fix a broken link

- TOC.md
Forgot to add this file to TOC in this PR https://github.com/pingcap/docs-cn/pull/3834
> toc: add store limit to toc

- README.md
> Readme: change 4.0 branch description

- br/backup-and-restore-use-cases.md
Signed-off-by: Neil Shen <overvenus@gmail.com>
Update TiDB version in BR page.
> br: update version

- dumpling-overview.md
Fix unclosed tag
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/3800
> chore: fix unclosed tag

- loader-overview.md
- tidb-binlog/get-started-with-tidb-binlog.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/3655
> Add missing aliases for binlog docs

- max-min-eliminate.md
fix typo in max-min-eliminate.md
[link](https://docs.pingcap.com/zh/tidb/v4.0/max-min-eliminate#%E5%AD%98%E5%9C%A8%E5%A4%9A%E4%B8%AA-maxmin-%E5%87%BD%E6%95%B0%E6%97%B6%E7%9A%84%E4%BC%98%E5%8C%96%E8%A7%84%E5%88%99)
> docs: fix typo

- tikv-configuration-file.md
Correct the default value of `hibernate_regions`.
N/A
> tikv-configuration-file: correct the default value of `hibernate_regions`

- troubleshoot-cpu-issues.md
> Remove 2 broken links

- .github/workflows/assign-to-project.yml
- .github/workflows/auto-assign.yml
- .github/workflows/auto-label.yml
- This PR is translated from: https://github.com/pingcap/docs/pull/3344
> .github: disable 3 github actions

- tiflash/use-tiflash.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/18458
> Update use tiflash for v4.0.3

- faq/tidb-faq.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/4005
> faq: update descriptions about deploying TiDB on cloud

- optimistic-transaction.md
- Remove reference to being "default". 
- Translate the updated part according to English file. > [TiDB Optimistic Transaction Model](https://docs.pingcap.com/tidb/stable/optimistic-transaction#tidb-optimistic-transaction-model)
- This PR is translated from: https://github.com/pingcap/docs/pull/3146
> Update optimistic-transaction: remove reference to being "default"

- sync-diff-inspector/sync-diff-inspector-overview.md
- tidb-binlog/tidb-binlog-faq.md
update some description about tidb-binlog and sync-diff-inspector
> tools: update some description about tidb-binlog and sync-diff-inspector

- system-variables.md
- Other reference link(s): Fix this comment https://github.com/pingcap/docs-cn/pull/4001#discussion_r459961008
> fix aliases in system-variables.md

- query-execution-plan.md
Add aliases
- Other reference link(s): [pingcap/docs-cn#3201](https://github.com/pingcap/docs-cn/pull/3201)
> Add index-merge.md aliases to query-execution-plan.md

- functions-and-operators/json-functions.md
Remove "syntactic sugar" from the heading names, and refers to the shortcuts as "aliases" instead. 
Update according to [JSON Functions](https://docs.pingcap.com/tidb/stable/json-functions#json-functions).
- This PR is translated from: https://github.com/pingcap/docs/pull/3154
> functions-and-operators: Update JSON functions

- sql-statements/sql-statement-create-index.md
从 [配置文件] 调整到 [ TiDB 配置文件]，并赋予链接地址，细化参数配置方式
超链接如果不符合要求需要帮忙修正，感谢
> Add a link in `CREATE INDEX` sql document

- pd-configuration-file.md
- telemetry.md
Update docs about the `TiDB Dashboard` in TiDB v4.0.3.
- [PD#2651](https://github.com/pingcap/pd/pull/2651)
> Update Dashboard Doc

- tikv-configuration-file.md
Document the new TiKV configuration `backup.num-threads` introduced in tikv/tikv#8193.
> tikv: document backup.num-threads config

- optimizer-hints.md
- This PR is translated from: https://github.com/pingcap/docs/pull/2573#pullrequestreview-452945454
> Align updates from en to optimizer-hints.md

- system-tables/system-table-information-schema.md
- system-tables/system-table-sql-diagnostics.md
Fixes https://github.com/pingcap/docs-cn/pull/3503/files#diff-345ad3d131a6268bda0656454cd78346R910, https://github.com/pingcap/docs-cn/pull/3981/files#diff-8074a2a28071d696bf7725dbeba1c742R5
> Fix some issues: add alias; fix wrong content

- TOC.md
- _index.md
- Add deployment in K8s link to `TOC.md`
- Update a K8s link in `_index.md`
- This PR is translated from: https://github.com/pingcap/docs/pull/3461
> toc, index: add K8s deployment

- tidb-lightning/tidb-lightning-tidb-backend.md
This PR is manually cherry-picked from https://github.com/pingcap/docs-cn/pull/3704.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/3704
> Fix typos in TiDB back-end doc

- benchmark/benchmark-tidb-using-sysbench.md
This PR is manually cherry-picked from https://github.com/pingcap/docs-cn/pull/3419.
> Clarify an ambiguous sentence in sysbench report

- .github/pull_request_template.md
Add options in PR template to facilitate addressing the potential issues in cherry-picked PRs.
> .github: add cherry-pick checklist to pr template

- TOC.md
Aligns dev and release-4.0 TOC.md
> Add all releases to TOC

- releases/release-3.0.17.md
Add a description for config item
>  add a description for configuration item query-feedback-limit

- tiflash/troubleshoot-tiflash.md
Manually cherry-picked from https://github.com/pingcap/docs-cn/pull/3418.
> Update related description in troubleshoot-tiflash

- ticdc/manage-ticdc.md
- ticdc/ticdc-overview.md
> add tiup deployment prompt in ticdc docs

- releases/release-2.1.17.md
tomestone -> tombstone: to close https://github.com/pingcap/docs-cn/issues/2669
> Fix a typo in 2.1.17 release notes

- sql-statements/sql-statement-modify-column.md
Add an alias in sql-statements/sql-statement-modify-column.md to fix a dead link.
> Add an alias to fix dead link

- experimental-features-4.0.md
Add auto-scaling doc link in 4.0 experimental feature.
> Add auto-scaling doc link in 4.0 experimental feature

- ticdc/ticdc-open-protocol.md
> ticdc: update the note about a bug

- troubleshoot-hot-spot-issues.md
Removed spurious backslash from troubleshoot-hot-spot-issues.md.
- This PR is translated from: https://github.com/pingcap/docs/pull/3283
> Removed spurious backslash from troubleshoot-hot-spot-issues.md

- tidb-scheduling.md
> fix typo: tidb-scheduling

- br/backup-and-restore-tool.md
Update out-date limitation of br
> br: update limitation

- character-set-and-collation.md
> remove duplicate table

- tiup/tiup-cluster.md
Add migrate control node in tiup-cluster
fix https://github.com/pingcap/tiup/issues/681
> Add migrate control node in tiup-cluster

- ticdc/manage-ticdc.md
Change the code block format of manage-ticdc.md.
> Change the code block format of manage-ticdc.md

- maintain-tidb-using-tiup.md
Signed-off-by: lucklove <gnu.crazier@gmail.com>
> Add document for tiup cluster rename

- _index.md
Add *What's New in TiDB 4.0* to `_index.md`
Note: We do not maintain the `adopters.md` file in docs-cn.
- This PR is translated from: https://github.com/pingcap/docs/pull/3679
> Add what's new in TiDB 4.0 to index

- information-schema/information-schema-cluster-systeminfo.md
- quick-start-with-tidb.md
- storage-engine/titan-configuration.md
Add 3 aliases to fix dead links
> Add 3 aliases to fix dead links

- TOC.md
The current file order of BR in TOC is not logical.
- This PR is translated from: https://github.com/pingcap/docs/pull/3681
> toc: update the file order of br

- best-practices/pd-scheduling-best-practices.md
Delete a hyphen in the syntax.
- This PR is translated from: https://github.com/pingcap/docs/pull/3687
> Fixed evict-leader-scheduler syntax

- sql-statements/sql-statement-show-create-sequence.md
fix an error in example sql statement
> fix an error in `create sequence`

- mydumper-overview.md
The way the current warning is written, it is a bit ambiguous as to which maintainers have stopped development. Let's be more careful not to throw mydumper developers under a bus and imply their project is end of life :-)
- This PR is translated from: https://github.com/pingcap/docs/pull/3719
> mydumper: Improve clarity of mydumper warning

- information-schema/information-schema-cluster-log.md
- information-schema/information-schema-ddl-jobs.md
- information-schema/information-schema-inspection-rules.md
- information-schema/information-schema-key-column-usage.md
- information-schema/information-schema-schemata.md
- information-schema/information-schema-table-constraints.md
- information-schema/information-schema-tikv-region-status.md
- mysql-schema.md
> Fix dead links

- functions-and-operators/string-functions.md
> Fix a dead link

- br/backup-and-restore-tool.md
This PR is manually cherry-picked from https://github.com/pingcap/docs-cn/pull/4339.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/4339
> Clarify wording in BR tool doc

- experimental-features-4.0.md
- ticdc-deployment-topology.md
- ticdc/ticdc-overview.md
- whats-new-in-tidb-4.0.md
> ticdc: add ga version, remove experiment warning

- ticdc/manage-ticdc.md
- whats-new-in-tidb-4.0.md
fix some unprecise description
- timezone is configured in server level
- add pulsar
> ticdc: fix some unprecise docs

- ticdc/manage-ticdc.md
> Fix typos in manage-ticdc.md

- experimental-features-4.0.md
- ticdc-deployment-topology.md
- ticdc/ticdc-overview.md
- whats-new-in-tidb-4.0.md
revert 1b01988b9e2f81edf96f83c33ff09f5f68b89823, cdc ga is delayed two weeks
> ticdc: revert cdc ga

- tikv-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs/pull/3589
> Update default value for RocksDB max-subcompactions

- tikv-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs/pull/3588
> Update default value for RocksDB max-subcompactions 

- tidb-troubleshooting-map.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/4324
> Correct a description

- sql-statements/sql-statement-create-role.md
- sql-statements/sql-statement-drop-role.md
- sql-statements/sql-statement-grant-privileges.md
- sql-statements/sql-statement-grant-role.md
- sql-statements/sql-statement-revoke-role.md
- sql-statements/sql-statement-set-default-role.md
- sql-statements/sql-statement-set-role.md
> Wrap all <role> in back ticks

- sql-statements/sql-statement-start-transaction.md
Revert the changes made in https://github.com/pingcap/docs-cn/pull/4400/commits/fa93edd94c8598fc2d5ba119d1d2286c5ef7a2cf by @Joyinqin 
> Revert the inappropriate changes

- ticdc/ticdc-open-protocol.md
> ticdc: fix a typo

- identify-expensive-queries.md
- information-schema/information-schema-statistics.md
- loader-overview.md
- query-execution-plan.md
Add 4 aliases to fix dead links. Each alias might apply to different versions. I'll make version-specific changes in each cp PRs.
> Add 4 aliases to fix dead links

- sync-diff-inspector/sync-diff-inspector-overview.md
update download link for sync-diff-inspector
> tools: update download link for sync-diff-inspector

- mydumper-overview.md
Fix a typo in mydumper-overview.md.
> Fix a typo in mydumper-overview.md

- tidb-binlog/maintain-tidb-binlog-cluster.md
Manually cherry-picked from https://github.com/pingcap/docs-cn/pull/4431.
> Change the returned value of log-binlog from on/off to 1/0

- system-variables.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/18896
> Fix the incorrect version for allow_auto_random_explicit_insert

- dumpling-overview.md
- This PR is translated from: https://github.com/pingcap/docs/pull/3718
> dumpling: add unit to -F

- functions-and-operators/json-functions.md
- get-started-with-tidb-lightning.md
- mysql-compatibility.md
- pd-configuration-file.md
- releases/release-1.1-alpha.md
- releases/release-3.1.0-beta.2.md
- sql-statements/sql-statement-show-databases.md
- ticdc/manage-ticdc.md
Add 8 aliases to fix dead links。
> Add 8 aliases to fix dead links

- enable-tls-between-components.md
> Fix a typo

- experimental-features-4.0.md
- ticdc-deployment-topology.md
- ticdc/ticdc-overview.md
- whats-new-in-tidb-4.0.md
CDC is GA since v4.0.6, update related docs
> ticdc: cdc is GA since v4.0.6

- br/backup-and-restore-faq.md
BR has fixed a bug, and we should update the out-dated docs.
> br: update br faq

- character-set-and-collation.md
Fixes https://github.com/pingcap/tidb/issues/17801.
- This PR is translated from: https://github.com/pingcap/docs/pull/3730
> character set: include useful warning

- ticdc/manage-ticdc.md
After test, the minimum Kafka version that CDC supports is `0.11.0.2`
> ticdc: update kafka minumum version

- mysql-compatibility.md
add the issue link after TEMPORARY TABLE feature, and remove the syntax line
- This PR is translated from: https://github.com/pingcap/docs/pull/3796; https://github.com/pingcap/docs/commit/6078be93bebd7b847b1a46cf2e7df4bb31408287
- Other reference link(s):  https://github.com/pingcap/docs-cn/pull/4150
> mysql-compatibility: update docs

- mysql-compatibility.md
Add a missing item in mysql-compatibility.md.
- This PR is translated from: https://github.com/pingcap/docs/pull/3893
> Add a missing item in mysql-compatibility.md

- character-set-and-collation.md
Fix a description in character-and-collation.md.
- Other reference link(s): https://github.com/pingcap/docs/pull/3880
> Fix a description in character-and-collation.md

- ticdc/manage-ticdc.md
Signed-off-by: Neil Shen <overvenus@gmail.com>
Add TiCDC upgrading section.
> cdc: add upgrading section

- best-practices/pd-scheduling-best-practices.md
close https://github.com/pingcap/docs-cn/issues/4354
> best-practices: improve wording in pd-scheduling

- ticdc/ticdc-open-protocol.md
Add ticdc open protocol parsing demo link.
> ticdc: add open protocol parser demo link

- system-variables.md
Fix wording for clustered index item.
> Fix wording for clustered index item

- ticdc/manage-ticdc.md
Fix a typo in manage-ticdc-md.
> Fix a typo in manage-ticdc-md

- functions-and-operators/aggregate-group-by-functions.md
- Other reference link(s): https://github.com/pingcap/tidb/pull/19810
> functions-and-operators: function VAR_SAMP()/STDDEV_SAMP() is supported

- storage-engine/titan-configuration.md
Fix titan blob-run-mode options' name.
> Fix titan blob-run-mode options

- tidb-configuration-file.md
添加了 5.0 新增特性 async commit 的配置文件参数说明。用户可参考文档使用最新的 nightly 版本尝试 async commit 特性。
> Add async commit configuration

- tikv-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs/pull/3935
> Remove sync-log config in TiKV config template

- configure-placement-rules.md
- add the usage of the new add bundle API
- remove the old load/save method
- Other reference link(s): https://github.com/tikv/pd/pull/2927 https://github.com/tikv/pd/issues/2865
> pd: update placement rules

- benchmark/v4.0-performance-benchmarking-with-tpcc.md
benchmarking with tpcc should use `TPC-C` in the configuration instead of `Sysbench`
> fix typo in benchmark result

- system-variables.md
Add system variable: tidb_union_concurrency
> system_variables: add tidb_union_concurrency

- TOC.md
- roadmap.md
> update TiDB roadmap.md

- information-schema/information-schema-tidb-indexes.md
> Add 1 alias to fix dead link

- releases/release-4.0.6.md
- ticdc/manage-ticdc.md
update the docs about create changefeed
> ticdc: update the docs about create changefeed

- br/backup-and-restore-tool.md
update br document about manually set the gc life time.
br can do it automatically after v4.0.3.
> br: update docs for gc life time

- tiup/tiup-cluster.md
Fix the description issues brought in https://github.com/pingcap/docs-cn/pull/4390
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/4390
> tiup: optimize descriptions about config

- system-variables.md
These variables do not take any effect, are deprecated in current version, and will be removed in the next major release.
So I remove them from the documentation now.
- This PR is translated from: https://github.com/pingcap/docs/pull/3947
> system-variables: remove the useless memory quota variables

- system-variables.md
- This PR is translated from: https://github.com/pingcap/docs/pull/3897
> sysvars: update tidb_dml_batch_size

- releases/release-4.0.2.md
Add missing release note.
- This PR is translated from: https://github.com/pingcap/docs/pull/3107
> releases: add missing release note for v4.0.2 #

- constraints.md
- sql-statements/sql-statement-alter-database.md
- sql-statements/sql-statement-begin.md
- sql-statements/sql-statement-commit.md
- sql-statements/sql-statement-explain-analyze.md
- sql-statements/sql-statement-flush-tables.md
- sql-statements/sql-statement-kill.md
- sql-statements/sql-statement-load-data.md
- sql-statements/sql-statement-load-stats.md
- sql-statements/sql-statement-recover-table.md
- sql-statements/sql-statement-rollback.md
- sql-statements/sql-statement-show-analyze-status.md
- sql-statements/sql-statement-show-character-set.md
- sql-statements/sql-statement-show-collation.md
- sql-statements/sql-statement-show-variables.md
- sql-statements/sql-statement-split-region.md
- sql-statements/sql-statement-use.md
- tidb-specific-system-variables.md
This is a cherry pick of https://github.com/pingcap/docs-cn/pull/4263 for release-3.1.
It still requires a version-specific change for 2.1 because the default is optimistic concurrency control.
- This PR is translated from: https://github.com/pingcap/docs/pull/3663
> sql-stmt: improve consistency, fix small errors

- user-defined-variables.md
Update SQL keywords to upper case, to improve readability.
- Other reference link(s): #2826
> user-defined-variables: Update SQL keywords to capital

- br/backup-and-restore-tool.md
Change a note format to fix a display issue.
> br: change a note format to fix a display issue

- information-schema/information-schema-engines.md
- scale-tidb-using-tiup.md
- storage-engine/rocksdb-overview.md
- tiflash/troubleshoot-tiflash.md
- tiup/tiup-mirror.md
Add 5 aliases to fix dead links
> Add 5 aliases to fix dead links

- tiflash/maintain-tiflash.md
- This PR is translated from: https://github.com/pingcap/docs/pull/4054
- Other reference link(s): #4681
> Fix TiFlash critical logs

- information-schema/information-schema-cluster-config.md
- information-schema/information-schema-processlist.md
Add 2 aliases to fix dead links.
> Add 2 aliases to fix dead links

- tiflash/use-tiflash.md
Fix wording in `use-tiflash.md`.
> Fix wording in use-tiflash.md

- pd-configuration-file.md
Fix typo in pd-configuration-file.md
> Fix typo in pd-configuration-file.md

- explain-overview.md
- identify-slow-queries.md
- information-schema/information-schema-cluster-load.md
- releases/release-2.1.1.md
- releases/release-3.0.4.md
- sql-statements/sql-statement-drop-sequence.md
- sql-statements/sql-statement-rename-table.md
- tidb-binlog/tidb-binlog-reparo.md
Add 9 aliases to fix dead links.
> Add 9 aliases to fix dead links

- sql-statements/sql-statement-show-variables.md
- system-variables.md
- tidb-configuration-file.md
`enable-streaming` is not well maintained because we are focusing on optimizing the non-streaming coprocessor API for its performance and resource usage and don’t have time to optimize streaming's currently, I propose to deprecate it temporarily until somebody has time to pick it up again and prove it could be GA in the future.
- Other reference link(s): https://github.com/pingcap/tidb/pull/20760
> config: hide & deprecate enable-streaming

- auto-increment.md
Capitalize sql keywords
- This PR is translated from: https://github.com/pingcap/docs/pull/4116
> AUTO_INCREMENT: Capitalize sql keywords

- roadmap.md
Update roadmap for tidb operator
> update roadmap for tidb operator

- pd-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs/pull/4155
> Fix a typo in pd-configuration-file.md

- ticdc/manage-ticdc.md
Add `cdc cli` command introduction
> ticdc: add cdc cli command introduction

- TOC.md
- ticdc/integrate-confluent-using-ticdc.md
- ticdc/manage-ticdc.md
- Add how to create an Avro changefeed.
- Add a quick start guide for integrating with Confluent Platform.
- This PR is translated from: https://github.com/pingcap/docs/pull/4102
> ticdc: add documentation on integration with Confluent

- .github/workflows/link-check.yaml
- connectors-and-apis.md
> Filter several external links to pass ci check

- tikv-configuration-file.md
change the value `0` into `0s`.  https://github.com/tikv/tikv/pull/8283
- This PR is translated from: https://github.com/pingcap/docs/pull/4175
- Other reference link(s): https://github.com/tikv/tikv/pull/8283
> Update a value in tikv-configuration-file.md

- faq/tidb-faq.md
- functions-and-operators/expressions-pushed-down.md
- releases/release-2.1.2.md
- tidb-binlog/deploy-tidb-binlog.md
- tidb-monitoring-framework.md
- upgrade-tidb-using-ansible.md
Add 8 aliases to fix broken links
> Fix 8 broken links

- quick-start-with-tidb.md
Remove TiDB-Wasm from `quick-start-with-tidb.md`.
- This PR is translated from: https://github.com/pingcap/docs/pull/4185
> quick-start-with-tidb: remove Wasm-related content

- tikv-configuration-file.md
Update config to include max-background-flushes.
- This PR is translated from: https://github.com/pingcap/docs/pull/4111
> Update config to include max-background-flushes

- sql-statements/sql-statement-admin.md
Fix two display errors by adding the escape characters.
- This PR is translated from: https://github.com/pingcap/docs/pull/4215
> sql: fix display errors 

- br/backup-and-restore-use-cases.md
> br: update backup-and-restore-use-cases.md

- sync-diff-inspector/sync-diff-inspector-overview.md
Add a command for downloading the Docker image of tidb-enterprise-tools (containing sync-diff-inspector).
> sync-diff-inspector: add a command to download docker image

- sql-statements/sql-statement-admin.md
Replace backticks with `<code>` for the inline code. This fixes a display error.
> sql: replace backticks with <code> for the inline code

- TOC.md
Remove three duplicate TiCDC doc links to avoid confusion when reading them on the PingCAP website
- Other reference link(s): #4873
> toc: remove duplicate ticdc doc links

- tikv-configuration-file.md
Fix a typo in tikv-configuration-file.md.
> tikv config file: fix a typo

- tiflash/use-tiflash.md
Add `round without fraction` to TiFlash's push down expression list.
> tiflash: update TiFlash's pushdown expression list

- partitioned-table.md
`INFORMATION_SCHEMA.PARTITION` has already been supported since v4.0.8.
> Support INFORMATION_SCHEMA.PARTITION since 4.0.8

- backup-and-restore-using-mydumper-lightning.md
- geo-distributed-deployment-topology.md
- multi-data-centers-in-one-city-deployment.md
- releases/release-2.0.4.md
- releases/release-3.0.1.md
- tiflash/tiflash-overview.md
Add 5 aliases to fix broken links.
> Add 5 aliases to fix broken links

- character-set-and-collation.md
- sql-statements/sql-statement-show-collation.md
Add 2 anchor links in collation-related docs.
> Add 2 links in collation-related docs

- analyze-slow-queries.md
there -> where
Fix a typo in analyze-slow-queries.md:
`there -> where`
> Fix a typo in analyze-slow-queries.md

- character-set-and-collation.md
Fix a typo in character-set-and-collation.md:
update the charset name from ut8mb4 to utf8mb4.
> Fix a typo in character-set-and-collation.md

- sql-plan-management.md
> Update initial capitalization

- ticdc/integrate-confluent-using-ticdc.md
Add "Apache" before "Kafka" (only for the first appearance of "Kafka").
- This PR is translated from: https://github.com/pingcap/docs/pull/4297
> ticdc: add "apache" before "kafka"

- dumpling-overview.md
add system database detail description.
add system database detail.
> dumpling: add system database detail

- tidb-configuration-file.md
+ 指定日志输出级别, 可选项为 [debug, info, warn, error, fatal]
+ 默认值: "info"
> Add log.level description

- resources/figma-quick-start-guide.md
update a Figma template link
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/4998#pullrequestreview-542493134
> resources: update a Figma template link

- tidb-control.md
> tidb-control: modify --port to status port

- sql-statements/sql-statement-backup.md
add some parameters in backup sql example.
> statements: put access-key & secret-key in backup example

- tikv-overview.md
fix some typos in tikv-overview.md
> Fix typos in tikv-overview.md

- tidb-binlog/tidb-binlog-configuration-file.md
add an example for `ignore-txn-commit-ts`
> binlog: add an example for `ignore-txn-commit-ts`

- dynamic-config.md
This PR makes the dynamic config of TiKV more clear.
- This PR is translated from: https://github.com/pingcap/docs/pull/4353
> Make the dynamic config of TiKV more clear

- ticdc/troubleshoot-ticdc.md
> ticdc: fix typos

- tiflash/tiflash-configuration.md
Add description of `delta_index_cache_size` configuration for TiFlash.
- This PR is translated from: [https://github.com/pingcap/docs/pull/4403](https://github.com/pingcap/docs/pull/4403)
> TiFlash config: Add description for delta_index_cache_size

- functions-and-operators/date-and-time-functions.md
- grafana-tikv-dashboard.md
- sql-statements/sql-statement-rename-index.md
- tidb-binlog/maintain-tidb-binlog-cluster.md
- tidb-binlog/monitor-tidb-binlog-cluster.md
- tidb-binlog/tidb-binlog-overview.md
- transaction-overview.md
Add 7 aliases to fix broken links.
> Add 7 aliases to fix broken links

- system-variables.md
- Update format of `tidb_enable_amend_pessimistic_txn` description.
- Replace English colon with Chinese colon.
- Other reference link(s): https://github.com/pingcap/docs/pull/4411#discussion_r543184324
> update format and refine punctuation

- configure-memory-usage.md
- system-variables.md
- tidb-configuration-file.md
> Added introduction version description

- releases/release-4.0.9.md
releases: correct the release date
> releases: correct the release date

- tidb-configuration-file.md
see https://github.com/pingcap/tidb/blob/master/config/config.toml.example#L244
- This PR is translated from: https://github.com/pingcap/docs/pull/4413
> fix the default value of tcp-keep-alive

- garbage-collection-configuration.md
GC: unify TiKV and TiDB --> TiDB
> GC: unify TiKV and TiDB --> TiDB

- error-codes.md
Add errorcodes TiFlashServerBusy and TiFlashServerTimeout.
- This PR is translated from: need translate to English
- Other reference link(s): https://github.com/pingcap/tidb/pull/21926
> errorcode: Add TiFlashServerBusy and TiFlashServerTimeout.

- system-variables.md
Introduce variable `tidb_track_aggregate_memory_usage` by https://github.com/pingcap/tidb/pull/21597
> add variable item `tidb_track_aggregate_memory_usage`

- garbage-collection-configuration.md
- tikv-configuration-file.md
Signed-off-by: qupeng <qupeng@pingcap.com>
Set gc in compaction filter by default.
> disable gc in compaction filter by default

- .github/pull_request_template.md
Add a v5.0 tick box in the PR template.
- This PR is translated from: https://github.com/pingcap/docs/pull/4517
> Update PR template for v5.0

- TOC.md
Remove What's New in TiDB 4.0 from TOC, according to @scsldb's discretion.
> Remove 4.0-specific docs from TOC

- tikv-configuration-file.md
- tikv-control.md
Add note about the side effect of auto-tuned limiter and how to turn it off.
- This PR is translated from: https://github.com/pingcap/docs/pull/4497
> Add description related to compaction rate limit

- .circleci/config.yml
> chore: update release-5.0 PDF

- log-redaction.md
- pd-configuration-file.md
- system-variables.md
- tidb-configuration-file.md
- tikv-configuration-file.md
Comment out v5.0 version marks before it is officially released.
> Comment out v5.0 version marks

- pd-control.md
Fix a display error caused by wrong format.
> Fix a display error caused by wrong format

- benchmark/v4.0-performance-benchmarking-with-tpch.md
Fix a typo in 4.0 benchmark report, as requested and confirmed by @shuke987.
> Fix a typo in 4.0 benchmark report

- dashboard/dashboard-ops-deploy.md
- deploy-test-cluster-using-docker-compose.md
- ecosystem-tool-user-guide.md
- overview.md
- quick-start-with-tidb.md
- test-deployment-using-docker.md
Update some links to stable versions.
- This PR is translated from: https://github.com/pingcap/docs/pull/4454
> update link versions

- tikv-configuration-file.md
Fix a wrong tikv config value.
> Fix a wrong tikv config value

- partitioned-table.md
- system-variables.md
> *: reviert list partition doc since it doesn't release in 5.0-rc

- .github/workflows/dispatch.yml
> chore: update dispatch branch

- tidb-limitations.md
Update max column count in tidb-limitations.md.
- This PR is translated from: https://github.com/pingcap/docs/pull/4580
> Update max column count in tidb-limitations.md

- .github/workflows/stale.yml
Uses the latest version of this action. It includes a fix so that the action will remove `lifecycle/stale` automatically once the issue is updated.
- Other reference link(s): https://github.com/actions/stale/pull/220
> .github: use the latest stale action

- .github/workflows/stale.yml
The action returns an error this morning: `Error: input days-before-issue-stale did not parse to a valid integer`
It might be related to incompatibility caused by version change (#5320) 
> .github: Update stale.yml

- hybrid-deployment-topology.md
The configuration is not consistent with the description text.
> Fix an inconsistency between description and config

- tiup/tiup-documentation-guide.md
> Fix a broken external link

- ticdc/manage-ticdc.md
> Update `kafka-version` description

- ecosystem-tool-user-guide.md
- This PR is translated from: https://github.com/pingcap/docs/pull/4627
> Refine ecosystem tool guide document 

- comment-syntax.md
- functions-and-operators/cast-functions-and-operators.md
- geo-distributed-deployment-topology.md
- information-schema/information-schema-inspection-result.md
- pd-recover.md
- sql-statements/sql-statement-show-create-sequence.md
- support.md
- tiflash/tiflash-alert-rules.md
- upgrade-tidb-using-ansible.md
Add 9 aliases to fix broken links
> Add 9 aliases to fix broken links

- mysql-compatibility.md
- This PR is translated from: https://github.com/pingcap/docs/pull/4590
> Add incompatibility caused by deprecated features in mysql-compatibility.md

- .github/workflows/media.yml
Refresh CDN cache when modify existing images.
> chore: update CDN refresh

- check-before-deployment.md
> Fix a typo in check-before-deployment.md

- sql-statements/sql-statement-kill.md
- tidb-configuration-file.md
add SQL & config docs for global kill
- This PR is translated from: https://github.com/pingcap/docs/pull/4565
> tidb: add doc for global kill

- production-offline-deployment-using-tiup.md
- tiup/tiup-mirror.md
Change an unordered list to an ordered list.
- This PR is translated from: https://github.com/pingcap/docs/pull/4706
> tiup: change unordered list to ordered list

- system-variables.md
Fix an invalid character, which broke PDF generation.
> chore: fix an invalid character

- tiflash/use-tiflash.md
TiDB internal code names `Time` as `Duration`, but we shouldn't expose it to users in documents.
- Other reference link(s): https://github.com/pingcap/parser/blob/master/mysql/type.go#L29-L30
> Rename `Duration` to `Time`.

- ticdc/manage-ticdc.md
TiCDC supports Kafka up to 2.7.0
> ticdc: update max support kafka version

- best-practices/tidb-best-practices.md
- data-type-numeric.md
- tidb-best-practices.md
> Fix 2 external broken links

- grafana-tidb-dashboard.md
Update the  part of tidb doc metrics - transaction, please help to check whether the description is accurate, thank you.
Add or remove metrics are updated based on the current situation of grafana.
> metrics: update metrics guide transaction

- .github/ISSUE_TEMPLATE/change-request.md
- .github/ISSUE_TEMPLATE/error-report.md
- .github/ISSUE_TEMPLATE/question.md
Add the AskTUG link in issue templates
> .github: add asktug link in issue template

- sql-plan-management.md
Fix a typo in a statement example.
> Fix a typo in a statement example

- tiflash/tiflash-configuration.md
Add config of TiFlash coprocessor thread pool.
- Other reference link(s): https://github.com/pingcap/tics/pull/1280/
> Add config of TiFlash coprocessor thread pool

- _index.md
- br/backup-and-restore-faq.md
- overview.md
- ticdc-deployment-topology.md
- tidb-architecture.md
- tidb-binlog-deployment-topology.md
- tidb-scheduling.md
- tidb-storage.md
- tiflash-deployment-topology.md
- tispark-deployment-topology.md
- Add multiple docs links to several files, to make it easier for users to learn the architecture of components or tools
- Remove `credits.md` from `_index.md` because it's outdated for a while (later we can directly use https://developer.tidb.io/ for **master** and **5.0**, but we can keep it for the `release-4.0` branch for now because that's a list till 4.0 GA)
- Optimize one link: http://asktug.com/ -> https://asktug.com/
> *: add multiple interrelated links and update description

- .github/workflows/link-check.yaml
Filter 7 external links to pass ci check
> Filter 7 external links to pass ci check

- TOC.md
- ticdc/monitor-ticdc.md
- ticdc/ticdc-grafana-dashboard.md
Fix a typo in `ticdc-grafana-dashboard.md`
- This PR is translated from: https://github.com/pingcap/docs/pull/4711
> fix a typo in ticdc-grafana-dashboard.md

- sql-statements/sql-statement-show-columns-from.md
Distinguish `explain <table_name>` and `explain table <table_name>`.
> Distinguish `explain <table_name>` and `explain table <table_name>`.

- tidb-limitations.md
> Correct the max column count in tidb-limitations.md

- best-practices/pd-scheduling-best-practices.md
Refine a description for PD scheduling best practices.
> Refine a description for PD scheduling best practices

- get-started-with-tidb-lightning.md
The configuration file adds filtering parameters and their descriptions, so that users can understand the role of the parameters 
> tidb-lightning: add filtering parameters and their descriptions

- privilege-management.md
Delete Grant privilege in privilege-management.md.
- Other reference link(s): https://github.com/pingcap/docs/issues/4791
> Delete Grant privilege in privilege-management.md

- tidb-lightning/tidb-lightning-faq.md
Dead links found in https://github.com/pingcap/docs-tidb-operator/pull/1102#issuecomment-781218533
> tidb-lightning: fix wrong aliases in faq

- system-variables.md
- This PR is translated from: https://github.com/pingcap/docs/pull/4821
> doc: fix ddl reorg priority scope problem

- tikv-configuration-file.md
Update the default value of `use-unified-pool` from `false` to `true`.
- This PR is translated from: https://github.com/pingcap/docs/pull/4707
> tikv-config-file: update the default value of use-unified-pool

- tiup/tiup-faq.md
> Fix a typo in tiup-faq.md

- tidb-lightning/tidb-lightning-overview.md
Change "在导数据之前" to "在导入数据之前". 
> fix a typo in tidb-lightning-overview.md

- scale-tidb-using-tiup.md
- This PR is translated from: https://github.com/pingcap/docs/pull/4880
> tiup: update version info in scale-tidb-using-tiup.md

- best-practices/massive-regions-best-practices.md
- garbage-collection-configuration.md
- tikv-configuration-file.md
Fix a wrong tikv config name: raftstore.hibernate-regions --> hibernate-regions
- This PR is translated from: https://github.com/pingcap/docs/pull/4890
> Fix a wrong tikv config name

- maintain-tidb-using-tiup.md
- production-deployment-using-tiup.md
- production-offline-deployment-using-tiup.md
- tiup/tiup-cluster.md
- upgrade-tidb-using-tiup.md
Fix a broken link of TiUP 配置参数模版.
> tiup: fix a broken link

- pd-recover.md
Fix the typo `bootsrap` in `pd-recover.md`.
> fix typo `bootsrap` in pd-recover.md

- tidb-troubleshooting-map.md
> Correct the default memory threshold for a single SQL statement

- log-redaction.md
- pd-configuration-file.md
- tiflash/tiflash-configuration.md
TiFlash and PD have picked the feature "redact-log" to the release-4.0 branch(released in 4.0.10), but forgot to add documents to the release-4.0 branch.
Add redact log configurations for TiFlash and PD.
- Other reference link(s): https://github.com/tikv/pd/pull/3266, https://github.com/pingcap/tics/pull/1333, https://github.com/pingcap/docs-cn/pull/5186
> Log redact on TiFlash and PD (4.0)

- br/use-br-command-line-tool.md
> br: correct command line usage

- benchmark/v4.0-performance-benchmarking-with-tpch.md
Add a description to clarity that tables in the benchmark test have no index created.
> benchmark: add description to explain the non-index test result

- dashboard/dashboard-key-visualizer.md
Update the title level of "Y 轴明暗交替：需要关注产生的热点聚集程度" from the 2nd to the 3rd.
Updated the title level of "Y 轴明暗交替：需要关注产生的热点聚集程度" from the 2nd to the 3rd, because it is a subsection under the 2nd level title "常见热力图解读"
> Correct the title level of "Y 轴明暗交替：需要关注产生的热点聚集程度"

- sql-statements/sql-statement-create-table.md
Update compatibility for temporary tables for dev and v5.0.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/5673
> Update compatibility for temporary tables

- garbage-collection-configuration.md
Signed-off-by: qupeng <qupeng@pingcap.com>
- https://github.com/tikv/tikv/pull/9833
> enable compaction filter by default

- sql-plan-management.md
- Other reference link(s): https://github.com/pingcap/tidb/pulls?q=is%3Apr+is%3Aclosed+label%3Aepic%2Fsql-plan-management
> update SPM documentation for DML SQL Bind and baseline capture

- configure-load-base-split.md
- dynamic-config.md
Signed-off-by: lhy1024 <admin@liudos.us>
> update load base split config

- tiup/tiup-bench.md
- tiup/tiup-cluster.md
> Remove private info in TiUP document

- system-variables.md
As title.
- Other reference link(s): https://github.com/pingcap/tidb/pull/18193, the introduction of this variable
> sysvars: add tidb_skip_ascii_check

- .circleci/config.yml
- .github/workflows/dispatch.yml
Stop triggering website build temporary.
> chore: stop building release-5.0

- pd-configuration-file.md
- [] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.
Update the default value of enable-joint-consensus from false to true for 5.0GA according to the confirmation from Jay
> Update the default value of joint consensus

- tiup/tiup-mirror-reference.md
Fix two typos in `tiup-mirror-reference.md`.
- Other reference link(s): https://github.com/pingcap/docs/pull/5040#discussion_r595758085
> fix two typos in tiup-mirror-reference.md

- .github/workflows/dispatch.yml
> chore: trigger preview build

- get-started-with-tidb-lightning.md
- Other reference link(s): N/À
> lightning: update config in get started

- system-variables.md
- tiflash/use-tiflash.md
> write document for mpp

- .github/workflows/rebase.yml
Use [this action](https://github.com/cirrus-actions/rebase) to enable manual rebase for PRs.
> .github: add an action to enable manual rebase

- character-set-and-collation.md
> doc: fix doc typo

- pd-control.md
> pd-ctl: add more jq examples

- ticdc/manage-ticdc.md
Refine the confusing expression `该选项默认开启默认选项` in the description of unified sorter.
> refine expression of unified sorter

- tidb-binlog/tidb-binlog-overview.md
Increase the restriction of using binlog in version 5.0
- [] master (the latest development version)
- [] v5.0 (TiDB 5.0 versions)
https://github.com/pingcap/docs-cn/pull/5832
- Other reference link(s): 
- Async Commit: https://github.com/pingcap/docs-cn/pull/5607/files
- Clustered Index: https://github.com/pingcap/docs-cn/pull/5771/files
> add  V4.0 tidb binlog restriction

- roadmap.md
alias to https://github.com/pingcap/docs-cn/pull/5868/files
- This PR is translated in: https://github.com/pingcap/docs/pull/5147
> Add an alias in roadmap.md

- troubleshoot-hot-spot-issues.md
The document is for v5.0 but the description is for v4.0, so I updated the related v4.0 informationion to adapt to v5.0 after confirming with the R&D. 
> Remove the TiDB 4.0 specific information from the Hot Spot issues doc

- tikv-configuration-file.md
Signed-off-by: gengliqi <gengliqiii@gmail.com>
- This PR is translated from:  https://github.com/pingcap/docs/pull/5168
> tikv: change default store/apply max-batch-size

- clustered-indexes.md
- system-variables.md
udpate the scope of system variable 'tidb_enable_clustered_index'
- This PR is translated from: NA
- Other reference link(s): https://github.com/pingcap/tidb/pull/23711
> udpate the scope of system variable 'tidb_enable_clustered_index'

- config-templates/complex-cdc.yaml
- ticdc/deploy-ticdc.md
> ticdc: add cdc server config

- br/backup-and-restore-use-cases.md
> br: update cluster version

- tune-tikv-thread-performance.md
The default thread pool setting of TiKV read requests is changed for v5.0.
> Update the thread pool description of TiKV read requests for v5.0

- tikv-configuration-file.md
- hibernate region is disabled on release branch.
- unified thread pool is no longer experimental long time ago.
> fixes statements about experimental features

- system-variables.md
> add apply-cache

- production-deployment-using-tiup.md
- upgrade-tidb-using-tiup.md
Align doc changes in https://github.com/pingcap/docs/pull/5099.
- Other reference link(s): https://github.com/pingcap/docs/pull/5099 https://github.com/pingcap/docs-cn/pull/5728
> tiup: align changes in docs#5099

- tiflash/tiflash-configuration.md
update tiflash config: add proxy log level.
> update tiflash config: add proxy log level

- TOC.md
- releases/release-notes.md
Revert 4.0.12 release notes (only deletes TOC and release-notes.md)
> revert 4.0.12 release notes

- tiflash/use-tiflash.md
> Fix a typo in use-tiflash.md

- quick-start-with-tidb.md
update use tiup client access database
- This PR is translated from: https://github.com/pingcap/docs/pull/5028
> update use tiup client access database

- tidb-configuration-file.md
Added the description for a new configuration entry for the 'tidb-configuration-file'.
https://github.com/pingcap/tidb/pull/19109
> update configuration page for `enable-enum-length-limit`

- .github/workflows/link-check.yaml
> link-check.yaml: disables external link check

- tikv-configuration-file.md
> tikv: update CDC config

- tiflash/tiflash-configuration.md
> Update the way of config`location-labels` if tiflash enable

- clustered-indexes.md
Signed-off-by: zyguan <zhongyangguan@gmail.com>
Fix a typo in clustered-indexes.md, also remove some trailing spaces.
> fix a typo in clustered-indexes.md

- pd-configuration-file.md
Signed-off-by: HunDunDM <hundundm@gmail.com>
* pd: remove the experimental flag for the enable-joint-consensus config
> pd: remove the experimental flag for the enable-joint-consensus config

- partitioned-table.md
- This PR is translated from: https://github.com/pingcap/docs/pull/5227
> partitioned-table: Correct the variable name for list partitioning

- check-before-deployment.md
- tiflash/use-tiflash.md
- tikv-configuration-file.md
> fix typos in multiple docs

- .circleci/config.yml
Update 4.0 PDF version tag. Leave this pr until the version of documents updated. 
> chore: update PDF version tag

- pessimistic-transaction.md
Signed-off-by: you06 <you1474600@gmail.com>
Pipelined lock in pessimistic is enabled by default in latest version and release-5.0.
> update pipelined lock default value

- releases/release-5.0.0.md
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/5991
> Fix a typo in release notes 5.0

- tidb-configuration-file.md
> update default oom action

- backup-and-restore-using-mydumper-lightning.md
- experimental-features-4.0.md
- loader-overview.md
- maintain-tidb-using-ansible.md
- mydumper-overview.md
- offline-deployment-using-ansible.md
- online-deployment-using-ansible.md
- production-offline-deployment-using-tiup.md
- scale-tidb-using-ansible.md
- syncer-overview.md
- upgrade-tidb-using-ansible.md
- upgrade-tidb-using-tiup-offline.md
- This PR is translated from: https://github.com/pingcap/docs/pull/5264
> add stable aliases for deleted docs in dev

- syncer-overview.md
remove a duplicate alias.
- This PR is translated from: https://github.com/pingcap/docs/pull/5275
> remove a duplicate alias

- system-variables.md
Signed-off-by: crazycs520 <crazycs520@gmail.com>
update system-variable for statements-summary
- N/A
> update system-variable for statements-summary

- alert-rules.md
Signed-off-by: qupeng <qupeng@pingcap.com>
Update the rule for GC can't work alert. Close https://github.com/pingcap/docs/issues/5269.
> update the rule for gc can't work alert

- releases/release-5.0.0.md
- system-variables.md
- 为三个 5.0 新引入的系统变量补全 New in v5.0 标识 `tidb_opt_prefer_range_scan`、`tidb_skip_ascii_check`、`tidb_skip_ascii_check`
- 调整变量顺序
- This PR is translated from: https://github.com/pingcap/docs/pull/5276
> Add the New in v5.0 mark in system-variables.md

- tidb-binlog/deploy-tidb-binlog.md
Fix a display error in tidb-binlog/deploy-tidb-binlog.md
> Fix a display error

- best-practices/pd-scheduling-best-practices.md
- explain-overview.md
- geo-distributed-deployment-topology.md
- hybrid-deployment-topology.md
- information-schema/information-schema-cluster-info.md
- minimal-deployment-topology.md
- pd-configuration-file.md
- production-deployment-using-tiup.md
- sync-diff-inspector/sync-diff-inspector-overview.md
- ticdc-deployment-topology.md
- ticdc/ticdc-open-protocol.md
- tidb-binlog-deployment-topology.md
- tidb-binlog/binlog-consumer-client.md
- tidb-binlog/tidb-binlog-configuration-file.md
- tidb-binlog/tidb-binlog-overview.md
- tidb-configuration-file.md
- tidb-scheduling.md
- tiflash/tiflash-configuration.md
- tikv-configuration-file.md
- tispark-deployment-topology.md
- tiup/tiup-faq.md
- tiup/tiup-playground.md
- troubleshoot-lock-conflicts.md
Update the external GitHub links that contain `/master/` and `/release-3.0/` to `/release-5.0/`.
> update the external links that contains master to release-5.0

- best-practices/pd-scheduling-best-practices.md
- explain-overview.md
- information-schema/information-schema-cluster-info.md
- pd-configuration-file.md
- production-deployment-using-tiup.md
- sync-diff-inspector/sync-diff-inspector-overview.md
- ticdc/ticdc-open-protocol.md
- tidb-binlog/binlog-consumer-client.md
- tidb-binlog/tidb-binlog-configuration-file.md
- tidb-binlog/tidb-binlog-overview.md
- tidb-configuration-file.md
- tidb-scheduling.md
- tikv-configuration-file.md
- tispark-deployment-topology.md
- tiup/tiup-faq.md
- tiup/tiup-playground.md
- troubleshoot-lock-conflicts.md
Update the external GitHub links that contain `/master/` and `/release-3.0/` to `/release-4.0/`.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/6054
> update the external links that contains master to release-4.0

- mysql-compatibility.md
Chinese part of https://github.com/pingcap/docs/issues/5137
> mention mysql replication

- statement-summary-tables.md
The statement summary doc is not very clear: users are always confused why the data of the history table is becoming less.
I added tips for it to clarify why it may become less and how to solve this problem.
> Add tips for the limitation of statements summary history table

- explain-overview.md
- sql-statements/sql-statement-explain.md
Add a hint to the `EXPLAIN` documentation about how to use `less -S` to view large explain output without line wrapping.
- This PR is translated from: https://github.com/pingcap/docs/pull/5349; https://github.com/pingcap/docs/pull/5407
> explain: add hint about disabling line wrapping with less

- TOC.md
- sql-statements/sql-statement-table.md
Add initial documentation for the `TABLE` statement.
- This PR is translated from: https://github.com/pingcap/docs/pull/5281
> Document the TABLE statement

- information-schema/information-schema-cluster-config.md
- information-schema/information-schema-cluster-hardware.md
- information-schema/information-schema-cluster-info.md
- information-schema/information-schema-cluster-load.md
- information-schema/information-schema-cluster-log.md
- information-schema/information-schema-cluster-systeminfo.md
- information-schema/information-schema-inspection-result.md
- information-schema/information-schema-inspection-summary.md
- information-schema/information-schema-metrics-summary.md
- information-schema/information-schema-metrics-tables.md
- information-schema/information-schema-sql-diagnostics.md
- information-schema/information-schema.md
- metrics-schema.md
- mysql-schema.md
- sql-statements/sql-statement-set-names.md
- system-variables.md
- table-filter.md
- tidb-binlog/binlog-consumer-client.md
- tidb-lightning/tidb-lightning-backends.md
Batch add missing v4.0 aliases.
- This PR is translated from: https://github.com/pingcap/docs/pull/5404
> batch add v4.0 aliases

- tikv-control.md
Add more information for compact and remove-fail-stores command
- Improve https://github.com/tikv/tikv/issues/10040
> tikv-ctl: Add more information for compact and remove-fail-stores

- benchmark/v5.0-performance-benchmarking-with-tpcc.md
> no server.request-batch-enable-cross-command in v5.0

- dynamic-config.md
Remove the backticks of the parameter
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/5274
> Remove the backticks of the parameter

- sql-statements/sql-statement-backup.md
- sql-statements/sql-statement-restore.md
Fix a miswording in sql-statement-backup.md
> Fix a miswording in sql-statement-backup.md

- tiup/tiup-cluster.md
- This PR is translated from: https://github.com/pingcap/docs/pull/5202
> Fix typos in tiup-cluster.md

- character-set-and-collation.md
Fix a typo in Update character-set-and-collation.md
- This PR is translated from: https://github.com/pingcap/docs/pull/5448
> Fix a typo in Update character-set-and-collation.md

- releases/release-5.0.1.md
> Update a wrong URL in release-5.0.1.md

- releases/release-5.0.1.md
releases: add a lighting note to br in 5.0.1
> releases: add a lighting note to br in 5.0.1

- user-defined-variables.md
add a note translation about MySQL compatibility.
- This PR is translated from:https://github.com/pingcap/docs/pull/5268
> add MySQL compatibility in user-defined-variables.md

- faq/deploy-and-maintain-faq.md
Signed-off-by: Yilin Chen <sticnarf@gmail.com>
Add an FAQ about why async commit or 1PC does not take effect.
> Add an faq about async commit or 1PC not working

- quick-start-with-tidb.md
Update oudated description in quick-start-with-tidb.md
- This PR is translated from: https://github.com/pingcap/docs/pull/5495
- Other reference link(s): https://github.com/pingcap/docs/issues/5485
> Update oudated description in quick-start-with-tidb.md

- quick-start-with-tidb.md
Add a note that TiUP Playground doesn't support Apple M1 so far.
> Add a note that TiUP Playground doesn't support M1

- tikv-configuration-file.md
Signed-off-by: gengliqi <gengliqiii@gmail.com>
update tikv 2 config default value `leader-transfer-max-log-lag`(https://github.com/tikv/tikv/pull/9592) and `merge-check-tick-interval`(https://github.com/tikv/tikv/pull/9675)
- This PR is translated from: https://github.com/pingcap/docs/pull/4853
> update tikv config default value

- pd-configuration-file.md
Add the value range and type for `store-balance-rate` in the PD Configuration File document.
- This PR is translated from: https://github.com/pingcap/docs/pull/5530
> pd-config: add value range and type for store-balance-rate

- grafana-tikv-dashboard.md
- This PR is translated from: https://github.com/pingcap/docs/pull/5324
> update grafana panels for TiKV GC

- sql-mode.md
Remove the description of --sql-mode
> Remove the description of --sql-mode

- explain-mpp.md
> Fix wrong table name

- system-variables.md
Add documentation for pingcap/tidb#23818
This affects master only.
- This PR is translated from: https://github.com/pingcap/docs/pull/5351
> Add read only to noop functions

- scale-tidb-using-tiup.md
+ To update the confusing `tiup ctl pd` usage.
+ To add PD information for the command.
> tiup: clarify the pd-ctl command usage

- tiup/tiup-mirror.md
Adding info about how to use the mirror created with `tiup mirror clone`.
- This PR is translated from: https://github.com/pingcap/docs/pull/5336
> tiup-mirror: Add a hint about how to use a tiup mirror

- tidb-lightning/tidb-lightning-backends.md
tidb-lightning: fix a display failure
> tidb-lightning: fix a display failure

- dumpling-overview.md
Currently we point users to: https://docs.pingcap.com/tidb/stable/download-ecosystem-tools#dumpling
However for this the user needs to:
- Figure out what version he/she wants to download
- Then based on that construct the URL
- Download the file
- Extract/install dumpling
TiUP is making this easier, so best to use that instead. This is also
more consistent with other tools.
- This PR is translated from: https://github.com/pingcap/docs/pull/5350
> dumpling-overview: Add info about how to install with TiUP

- tiflash/use-tiflash.md
explain how to check if mpp takes effect.
> add detailes about whether mpp takes effect.

- mysql-compatibility.md
- sql-statements/sql-statement-load-data.md
Added information about LOAD DATA...REPLACE compatibility.
- This PR is translated from: https://github.com/pingcap/docs/pull/5595
- Other reference link(s): pingcap/tidb#24515
> Added information about LOAD DATA...REPLACE compatibility

- ticdc/deploy-ticdc.md
Add a link to the CDC configurable field.
> Add a link to the CDC configurable field.

- tidb-computing.md
update SQL statement
fix Error DDL
> Fix a typo in tidb-computing.md

- br/backup-and-restore-faq.md
> br: add br faq NotFound description

- ticdc/manage-ticdc.md
> add --sort-engine default values

- tidb-lightning/tidb-lightning-backends.md
> Update status-port description

- certificate-authentication.md
Fix a display failure of copyable snippt
- This PR is translated from: https://github.com/pingcap/docs/pull/5635
- Other reference link(s): https://github.com/pingcap/docs/issues/5633
> Fix a display failure of copyable snippt

- dumpling-overview.md
Update dumpling document about threads and some other stuff.
> dumpling: update dumpling doc

- system-variables.md
Signed-off-by: Yilin Chen <sticnarf@gmail.com>
> Add some more docs about async commit not used

- sql-statements/sql-statement-explain.md
Signed-off-by: crazycs <chen.two.cs@gmail.com>
update doc for explain for connection.
https://github.com/pingcap/tidb/pull/19183
> *: update doc for explain for connection

- config-templates/complex-cdc.yaml
> cdc: fix config typo

- tidb-binlog/upgrade-tidb-binlog.md
> binlog: fix typo

- tikv-configuration-file.md
Add the value range and type for stack-size in the TiKV Configuration File document.
- This PR is translated from: https://github.com/pingcap/docs/pull/5681
> tikv-config: add value range and type for stack-size

- config-templates/complex-tidb-binlog.yaml
Fix typos in complex-tidb-binlog.yaml.
> Fix typos in complex-tidb-binlog.yaml

- .github/pull_request_template.md
Add v5.1 in pull_request_template.md.
> Add v5.1 in pull_request_template.md

- TOC.md
The BR docs are linked from the 'TiDB Ecosystem Tools' as well as from
the 'Maintain' section.
This fixes:
- Wrong link for command-line info
- Make the titles and list on both places identical
- This PR is translated from: https://github.com/pingcap/docs/pull/5454
> TOC: Fix BR related issues in the TOC

- dashboard/dashboard-ops-deploy.md
- quick-start-with-tidb.md
Most of the content is not changed.
Follow-up: Follow up on @dveeden's comments.
Main change:
- I used shortcodes for tab panels to create two panels "Mac" and "Linux" to reorganize the page structure. 
- I bumped version to v5.0.1, the latest stable version of v5.0. And in future releases, we'll bump the version in this page to the latest stable one. This will be written in our docs release checklist. FYI @morgo
- I rewrote the beginning according to Morgan's suggestions: 1) removed the warning on the top 2) introduce what TiUP is
- This PR is translated from: https://github.com/pingcap/docs/pull/5613
> Add tab panels to TiDB Quick Start page and optimize content and structure

- sql-statements/sql-statement-split-region.md
Enhance descriptions of the Split Region section according to the feedbacks from the user support issues
> Enhance descriptions of the Split Region section

- dashboard/dashboard-access.md
- post-installation-check.md
1. Added a sentence to show that the IP address used to log in to TiDB is the tidb_server address configured in the cluster topology file. 
2. Added a sentence to show that the default password of the root user for the TiDB Dashboard login is empty. 
> Enhance TiDB login descriptions

- system-variables.md
Typo
`UPDATA` CHANGE TO `UPDATE`
> Fix a typo in system-variables.md

- tispark-overview.md
- [x ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.
add a missing '.' in  tispark-overview.md
> Fix typo: tispark-overview.md

- mysql-compatibility.md
Update SQL Keywords and Reserved Words to CAPS
https://github.com/pingcap/docs-cn/issues/2825
https://github.com/pingcap/docs-cn/blob/master/mysql-compatibility.md
> Update SQL Keywords and Reserved Words to CAPS

- tiflash/use-tiflash.md
update tiflash documents about cartesian join
> update tiflash documents about cartesian join support

- tiflash/use-tiflash.md
> mpp support new ops

- releases/release-4.0.13.md
Fix typos in 4.0.13 release notes
> Fix typos in 4.0.13 release notes

- clustered-indexes.md
- tidb-binlog/tidb-binlog-overview.md
- upgrade-tidb-using-tiup.md
https://github.com/pingcap/tidb/issues/24133
https://github.com/pingcap/tidb/pull/24135
https://github.com/pingcap/tidb-binlog/pull/1040
> tidb-binlog: support binlog for clustered index

- releases/release-5.0.2.md
Clarify a note in 5.0.2 release notes
> Clarify a note in 5.0.2 release notes

- best-practices/massive-regions-best-practices.md
- experimental-features.md
- system-variables.md
- ticdc/ticdc-overview.md
- tikv-configuration-file.md
Signed-off-by: Yi Wu <yiwu@pingcap.com>
Hibernate region is turned on by default on 5.0.2. Remove experimental warning for hibernate region, and update default value.
- Other reference link(s): https://github.com/tikv/tikv/pull/10199
> tikv config: hibernate region GA

- statistics.md
We've updated the analyze behavior when setting `tidb_analyze_version=2` and change its default value to 2.
This pr is to make the doc compatible with it.
> optimizer: modify docs for analyze behavior

- quick-start-with-tidb.md
Add a note to clarify the purpose of the quick start guide
- Other reference link(s): https://asktug.com/t/topic/93604/3
> Add a note to clarify the purpose of the quick start guide

- mysql-compatibility.md
- sql-statements/sql-statement-change-column.md
- sql-statements/sql-statement-modify-column.md
Signed-off-by: AilinKid <314806019@qq.com>
modify some lines about the column type change
> modify the column type change doc

- roadmap.md
update tidb roadmap
Follow up: After this PR is merged, @IANTHEREAL will create a separate PR to tick the box.
> Update the tools part in roadmap.md

- tikv-configuration-file.md
Signed-off-by: linning <linningde25@gmail.com>
> resolevd-ts: add resolved-ts related config doc

- experimental-features.md
- ticdc/ticdc-open-protocol.md
remove a experimental feature of ticdc
> ticdc: remove a experimental feature

- tikv-configuration-file.md
TiKV config: add abort-on-panic. The option is new in v5.0.2.
- Other reference link(s): https://github.com/tikv/tikv/pull/10164
> TiKV config: add abort-on-panic

- clustered-indexes.md
correct a typo in clustered-indexes.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/6405
> tidb-binlog: correct a typo

- tidb-lightning/deploy-tidb-lightning.md
- tidb-lightning/tidb-lightning-backends.md
Clarify tidb lightning backend description
> Clarify tidb lightning backend description

- migrate-from-aurora-using-lightning.md
> lightning: fix a lightning config bug

- tune-operating-system.md
Fix a typo in tune-operating-system.md
> Fix a typo in tune-os-

- sql-statements/sql-statement-with.md
> Fix ebnf display

- .circleci/config.yml
- .github/workflows/dispatch.yml
> change docs-cn configs to release-5.1

- benchmark/v5.0-performance-benchmarking-with-tpch.md
Add alias for `/benchmark/v5.0-performance-benchmarking-with-tpch.md` deleted in https://github.com/pingcap/docs-cn/pull/6510.
> Add alias for 5.0 mpp test report in dev

- download-ecosystem-tools.md
> Bump missing version

- releases/release-5.1.0.md
> Removed an unneeded line break from 5.1 release note

- scale-tidb-using-tiup.md
Signed-off-by: HunDunDM <hundundm@gmail.com>
Remove the content related to setting Tombstone, they are no longer supported.
- This PR is translated from: [pd#3407](https://github.com/tikv/pd/pull/3407)
> Not support to set Tombstone

- as-of-timestamp.md
Add workaround about using Stale Read with TiFlash.
- This PR is translated from: https://github.com/pingcap/docs/pull/5875
> Add workaround about using Stale Read with TiFlash

- roadmap.md
https://github.com/pingcap/tidb/issues/17526 is finished, so update the roadmap.
> *: update roadmap

- partitioned-table.md
Signed-off-by: crazycs <crazycs520@gmail.com>
fix partition table doc error 
- N/A
> fix partition table doc error

- sql-statements/sql-statement-with.md
Remove a blank line that causes display failure
> Remove a blank line that causes display failure

- pd-configuration-file.md
update pd-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs/pull/5726
> pd-configuration-file: add hot-region information

- system-variables.md
This adds basic docs for a mysql-compatible feature. It has been present in TiDB for a long time.
- This PR is translated from: https://github.com/pingcap/docs/pull/5756
> system-variables: add warning count

- as-of-timestamp.md
> Fix link to optimizer-hints.md

- tikv-configuration-file.md
- Other reference link(s): https://github.com/pingcap/tidb/issues/25419
> Add a note about grpc-compression-type.

- pd-configuration-file.md
- tiflash/tiflash-configuration.md
removed some useless configurations
- Other reference link(s): https://github.com/pingcap/docs/pull/5558
> removed some useless configurations

- ticdc/troubleshoot-ticdc.md
- Fix ticdc canal json related doc
- This PR is translated from: https://github.com/pingcap/docs/pull/5774
> Fix ticdc canal json related doc

- faq/migration-tidb-faq.md
- Before this PR: The FAQs of the migration related tools are in the corresponding tool documents, so it is hard to locate them easily in the FAQ category. 
- In this PR: Add the FAQ links of the migration related tools to the Migration FAQs. 
> Migration FAQs: add the FAQ links of the migration related tools

- pd-configuration-file.md
Make description of `max-replcias` more specific.
- Other reference link(s): https://github.com/pingcap/docs/issues/5866
> update max-replicas description

- config-templates/complex-cdc.yaml
- tiup/tiup-cluster-topology-reference.md
CDC support data dir for cluster version >= `v4.0.13`
> TiUP: CDC support Data dir .

- system-variables.md
- This PR is translated from: https://github.com/pingcap/docs/pull/5998
> sysvar: change the default value of tidb_multi_statement_mode in v4.0.14

- benchmark/v5.0-performance-benchmarking-with-tpch.md
same as https://github.com/pingcap/docs-cn/pull/6703
because this file has a different name than the master/5.1 's, so I can't cherry-pick.
> remove useless variable. (for 5.0)

- tidb-binlog/deploy-tidb-binlog.md
make the expression on deployment clearer to close https://github.com/pingcap/docs-cn/issues/6684.
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/6684
> deploy-tidb-binlog: make the expression on deployment clearer

- .circleci/config.yml
- .zhlint.yaml
- experimental-features.md
- explore-htap.md
- mysql-compatibility.md
- pd-control.md
- quick-start-with-htap.md
- sql-statements/sql-statement-explain-analyze.md
- storage-engine/rocksdb-overview.md
- storage-engine/titan-configuration.md
- storage-engine/titan-overview.md
- sync-diff-inspector/sync-diff-inspector-overview.md
- system-variables.md
- table-filter.md
- tidb-configuration-file.md
- tidb-troubleshooting-map.md
- troubleshoot-cpu-issues.md
- troubleshoot-lock-conflicts.md
> add zhmd to ci

- system-variables.md
added charset documentation in system-variables document
- This PR is translated from: [#5867](https://github.com/pingcap/docs/pull/5867)
> system variables: add charset documentation

- download-ecosystem-tools.md
- pd-recover.md
- production-deployment-using-tiup.md
- production-offline-deployment-using-tiup.md
- quick-start-with-tidb.md
- scale-tidb-using-tiup.md
- ticdc/manage-ticdc.md
- tiup/tiup-component-cluster-deploy.md
- upgrade-tidb-using-tiup.md
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.  
For details, see [tips for choosing the affected versions (in Chinese)](/CONTRIBUTING.md#版本选择指南).
- This PR is translated from: https://github.com/pingcap/docs/pull/6040
> Bump version for v4.0.14

- sync-diff-inspector/sync-diff-inspector-overview.md
> fix a typo for sync_diff_inspector

- ticdc/ticdc-open-protocol.md
> update golang demo link

- README.md
Add v5.1.0 / release-5.1 where it is missing
- This PR is translated from: https://github.com/pingcap/docs/pull/5893
> Add v5.1.0 / release-5.1 where it is missing

- ticdc/manage-ticdc.md
- ticdc/ticdc-open-protocol.md
* fix outdated cdc golang demo link
* fix outdated recommand disk information.
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.  
> ticdc: Fix cdc doc outdate link and info

- br/backup-and-restore-faq.md
update br FAQ
- This PR is translated from: https://github.com/pingcap/docs/pull/6060
> update br faq

- grafana-overview-dashboard.md
Fixed the issue reported in https://asktug.com/t/topic/95634
> grafana-overview-dashboard: update the monitoring item for CPS

- scripts/verify-link-anchors.sh
> chore: fix lint

- mysql-compatibility.md
> Wording correction

- system-variables.md
- tikv-configuration-file.md
- fixed some default configurations for RocksDB
- This PR is translated from:https://github.com/pingcap/docs/pull/5969
> TiKV configuration: fixed some default configurations

- functions-and-operators/string-functions.md
To add doc for new feature, supporting Oracle translate function
- This PR is translated from: https://github.com/pingcap/docs/pull/6053
- Other reference link(s): https://github.com/pingcap/tidb/pull/26408
> update doc for Oracle translate function

- tiflash/tune-tiflash-performance.md
remove a tiflash tuning advise. Right now we have supported tidb_enforce_mpp = ON, so we don't need other way to enforce mpp functions.
Additionally, this tune advise will not take effect any more.
> mpp: remove outdated tune advise

- security-compatibility-with-mysql.md
- system-variables.md
updated security compatibility with MySQL in "security compatibility with MySQL" and "system variable".
- This PR is translated from: [#5921](https://github.com/pingcap/docs/pull/5921)
> security compatibility: update security compatibility with MySQL

- tiflash/use-tiflash.md
MPP has fully support for collator, so delete the mpp restriction when new collation is on.
> mpp fully support collator

- tidb-configuration-file.md
Add documentation for `auto-tls`.
- This PR is translated from: [#6125](https://github.com/pingcap/docs/pull/6125)
> TiDB configuration: add docs for auto-tls setting

- tikv-configuration-file.md
Add the document about storage flow control 
- Other reference link(s): https://github.com/tikv/tikv/pull/10249
> tikv: add storage flow control doc

- grafana-pd-dashboard.md
> update pd monitor description

- .circleci/config.yml
> chore: update version tag

- best-practices/high-concurrency-best-practices.md
>  high-concurrency-best-practices: fix the support info of follower read

- tidb-configuration-file.md
Update the default value of `max-stmt-count`.
Notice: the value in `statement-summary-tables.md` has already been changed.
> update the default value of stmt_max_count

- tiflash/use-tiflash.md
Add function list pushed down to tiflash.
master, 5.2
> Update function list pushed down to tiflash

- dumpling-overview.md
Now visiting the table `cluster_info` and `tidb_servers_info` requires `PROCESS` privilege in TiDB, and the Dumpling accesses these tables.
- Other reference link(s): https://github.com/pingcap/tidb/pull/26220
> Require process privilege for dumpling

- minimal-deployment-topology.md
- This PR is translated from: https://github.com/pingcap/docs/pull/6178
> Make IP address of Monitoring & Grafana for Minimal Topology consistent

- tiflash/use-tiflash.md
1. Remove the description about expr_blacklist in use_tiflash.md.
we don't want users to open them.
2. remove the functions with bug.
> tiflash: Remove the description about expr_blacklist in use_tiflash.md

- ticdc/ticdc-open-api.md
> Fix typo in ticdc open api

- sql-plan-management.md
This change does not affect correctness, it just makes the SQL simpler.
> spm: fix typo

- tikv-configuration-file.md
peer-stale-state-check-interval or  rafrstore.peer-stale-state-check-interval ？
> Remove redundant instructions

- alert-rules.md
https://github.com/tikv/tikv/pull/10792
> fix wrong coprocessor alert rules

- config-templates/complex-tidb-binlog.yaml
> add checkpoint info

- error-codes.md
- support.md
fix broken links in "error codes.md" and "support.md".
- This PR is translated from: https://github.com/pingcap/docs/pull/6196
> error codes, support: fix broken links

- tune-tikv-memory-performance.md
After v5.0, sync-log will be forced to set to be true and can not be modified，so 、the document should not direct the user to close sync-log
5.0 and later
> tune-tikv-memory-performance: remove description for sync-log

- system-variables.md
- tiflash/use-tiflash.md
> Revert "update bcj threshold"

- ticdc/manage-ticdc.md
- ticdc/ticdc-open-api.md
- ticdc/ticdc-overview.md
ticdc: fix wording
Open API --> OpenAPI
- This PR is translated from: https://github.com/pingcap/docs/pull/6231
> ticdc: fix wording

- information-schema/information-schema-tidb-trx.md
There's a missing paragraph in  https://github.com/pingcap/docs-cn/pull/6824 which is expect to explain a query result of TIDB_TRX table. This PR added the missing paragraph.
> Fix missing paragraph in document of TIDB_TRX table

- alert-rules.md
TiKV_coprocessor_request_lock_error
TiKV_coprocessor_request_error
reversed
https://github.com/tikv/tikv/pull/10792/files
> Update some desc

- ticdc/ticdc-open-api.md
> ticdc-open-api: correct some error

- ticdc/ticdc-open-api.md
> ticdc-open-api: correct error

- .github/workflows/dispatch.yml
> chore: stop building temporary

- ticdc/manage-ticdc.md
- tiup/tiup-component-dm-edit-config.md
> fix typo: relaod -> reload

- releases/release-5.2.0.md
> release note: update feature description 

- tidb-configuration-file.md
> add release notes information

- releases/release-5.0.0.md
- releases/release-5.1.0.md
> release note: add a check item for feedback-probability

- tikv-configuration-file.md
Signed-off-by: ekexium <ekexium@gmail.com>
Complement the descriptions of `wal-recovery-mode` and `use-direct-io-for-flush-and-compaction`.
Previous descriptions are vague.
> update doc on wal-recovery-mode and use-direct-io-for-flush-and-compaction

- tidb-configuration-file.md
> correct the default value

- sql-statements/sql-statement-alter-table.md
Fix the broken link.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/6522
> sql-statements: fix broken link

- alert-rules.md
https://github.com/tikv/tikv/pull/10807
> Update alert rule for low space

- tidb-binlog/tidb-binlog-configuration-file.md
There is a problem with the `type` level. It is at the same level as the schema.
Optimize the document structure to make it easier to read
> update syncer.to.checkpoint info

- grafana-tikv-dashboard.md
https://asktug.com/t/topic/123305
Add counter type description for TiKV "Ready handled" panel
- For v2.1, "v3.0.0 后废弃" can be removed
> Add description for TiKV Ready handled panel

- production-offline-deployment-using-tiup.md
- upgrade-tidb-using-tiup.md
Fix 2 broken links of tiup config files
> Fix 2 broken links of tiup config files

- configure-memory-usage.md
- tiup/tiup-cluster-topology-reference.md
revised the `log_dir` description, which should be the log directory, not data one.
- This PR is translated from: https://github.com/pingcap/docs/pull/6168
> TiUP cluster: revise the log directory

- system-variables.md
- This PR is translated from: https://github.com/pingcap/docs/pull/6298
> add warning messages

- tiup/tiup-component-cluster-import.md
> tiup-component-cluster-import.md: fix a typo

- incremental-replication-between-clusters.md
Fix typos in incremental-replication-between-clusters.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/6278/files#diff-712ba3906236931d00e233f4d0679ffe935d8f8aedba81bd6a8d31b3e8624b46R33
> Fix typos in incremental-replication-between-clusters.md

- tiflash/use-tiflash.md
Add label schedule doc for TiFlash.
https://github.com/pingcap/tidb/issues/21217
> tiflash: Add label schedule for TiFlash.

- sql-statements/sql-statement-kill.md
> kill: update kill's description

- configure-placement-rules.md
fix the wrong placement command, since the usage like that：
```bash
Usage:
pd-ctl config placement-rules rule-bundle save [flags]
Flags:
-h, --help        help for save
--in string   the file contains all group configs and all rules (default "rules.json")
--partial     do not drop all old configurations, partial update
unknown shorthand flag: 'i' in -in=rules.json
```
For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本 …
> tidb: fix placement doc

- explore-htap.md
> explore-htap: Update the HTAP blog address 

- TOC.md
- sql-statements/sql-statement-admin-show-telemetry.md
added a reference page "sql-statements/sql-statement-admin-show-telemetry.md" for the statement `ADMIN SHOW TELEMETRY`.
- This PR is translated from: https://github.com/pingcap/docs/pull/6138
> SQL statement: add a doc "ADMIN SHOW TELEMETRY"

- .circleci/config.yml
Temporarilty disable zh.md to avoid jenkins error-reporting
> Temporarilty disable zh.md to avoid jenkins error-reporting

- system-variables.md
Update the "warning" part of `tidb_enable_noop_functions` in "system-variables.md".
- This PR is translated from: https://github.com/pingcap/docs/pull/6374
> system-variables: improve noop functions warning

- TOC.md
Revised the format of `ADMIN SHOW TELEMETRY` in "TOC.md" file
> revise the format of `ADMIN SHOW TELEMETRY` in TOC file

- mysql-compatibility.md
> reword some descriptions in MySQL Compatibility

- mysql-compatibility.md
This PR is cherry-picked from https://github.com/pingcap/docs-cn/pull/7153.
> reword some descriptions in MySQL Compatibility (#7153)

- faq/sql-faq.md
Correct description about DELETE space release
- Other reference link(s): https://asktug.com/t/topic/153432/2
> Correct description about DELETE space release

- statement-summary-tables.md
Stress that TiDB provides system tables in information_schema, not in performance_schema
- This PR is translated from: https://github.com/pingcap/docs/pull/6418
> performance_schema -> information_schema

- dynamic-config.md
add dynamic online change cdc configuration docs.
> For 4.0.15:  tikv(cdc): dynamic online change cdc configuration
