pingcap/docs-cn

- op-guide/docker-deployment.md
@siddontang @andelf @thinxer @shenli 
PTAL
> op-guide: update docker deployment

- op-guide/monitor-overview.md
@siddontang @qiuyesuifeng PTAL
> some small changes

- op-guide/mysql-compatibility.md
> some small change

- op-guide/migration.md
- tools/loader.md
@siddontang @zhangjinpeng1987 @cwen0 
PTAL
> *: add loader document

- op-guide/monitor.md
> op-guite: add grafana download address

- op-guide/binary-deployment.md
> op-guide: Add config file description

- faq.md
> faq: Add a few questions and answers

- circle.yml
- op-guide/migration.md
- scripts/generate_pdf.sh
- scripts/merge_by_toc.py
- templates/template.tex
* CircleCI Support
* Add scripts/templates
TODO: an API key for auto upload docs.
> Add circle CI support

- op-guide/tune-TiKV.md
> tune for load data

- faq.md
> faq: add "TiKV cluster is not bootstrapped"

- op-guide/migration.md
> op-guide: update migration

- op-guide/binary-deployment.md
> link trouble shooting when use nohup

- faq.md
PTAL @siddontang @huachaohuang @andelf 
Close pingcap/pd#477
> faq: update PD command line arguments

- op-guide/migration.md
@andelf @shenli @siddontang PTAL
> op-guide: add skip-tz-tsc flag to mydumper

- op-guide/monitor.md
PTAL @tennix @shenli @siddontang
> op-guide: update monitor

- README.md
> README.md - fix wrong link to PingCAP tech blog

- FAQ.md
- op-guide/binary-deployment.md
> add --log-file in binary deployment command

- sql/tidb-specific.md
@shenli @hanfei1991 @coocood PTAL
> sql: update comment for index nested loop join

- op-guide/mysql-compatibility.md
PTAL @shenli @coocood @tiancaiamao
> op-guide: Add description about add or drop primary key

- op-guide/migration.md
The migration  document  before doesn't care about the realistic scenario. 
@iamxy  @shenli  @ngaut   PTAL
> op-guide/migration: update doc for syncer

- op-guide/migration.md
@GregoryIan  @liubo0127   PTAL
> op-guide: remove unsupported argument

- op-guide/mysql-compatibility.md
> add doc for alter table lock clause

- op-guide/mysql-compatibility.md
Refer to pingcap/tidb#3215, we support these keywords now.
> update doc for first/after in modify/change column

- op-guide/ansible-deployment.md
fix ansible deployment,  add uncomment `ansible_become = true`
> fix-ansible-deployment

- op-guide/migration.md
- tools/loader.md
@GregoryIan @holys @shenli @siddontang PTAL
> *: add tidb-enterprise-tools download links

- op-guide/migration.md
> migration: change mydumper downlink

- op-guide/mysql-compatibility.md
PTAL @shenli @iamxy 
/cc @queenypingcap
> op-guide: Add 'load data' detail

- tools/loader.md
> loader: update command line explanation

- op-guide/mysql-compatibility.md
> op-guide: update mysql compatibility about alter enum column

- FAQ.md
- op-guide/configuration.md
> explain TiDB skip-grant-table and update FAQ

- tools/syncer.md
> add deploy suggestion

- op-guide/tune-tikv.md
@zhangjinpeng1987 @andelf PTAL
> tune-tikv: update config

- op-guide/ansible-deployment.md
> add ansible rolling update

- README.md
- op-guide/overview-dashboard-info.md
1.change the name of “overview dashboard 说明”
2.fix typo
> change the name of “overview dashboard 说明” && fix typo

- newfaqtmp.md
> add new format faq

- op-guide/try-tidb.md
> add try tidb content

- op-guide/ansible-deployment.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/docs-cn/175)
> add ssh_args guide

- README.md
> Revert "Add quick start guide to toc"

- sql/README.md
- sql/privilege/README.md
- sql/privilege/create-user.md
- sql/privilege/grant.md
- sql/privilege/revoke.md
- sql/privilege/user-account-name.md
> User privilege

- sql/dml/README.md
- sql/dml/insert.md
As title says.
@queenypingcap PTAL
> dml: Add insert statement document

- op-guide/tispark-quick-start-guide.md
> fix a link and update format

- sql/README.md
- sql/information-functions.md
> sql: add doc for information functions

- sql/README.md
> add more links to TOC

- sql/dml.md
Document for `Delete` and `Update` statements.
`Replace` statement will be in the next PR.
> sql: Add `Delete` and `Update` in DML doc

- sql/ddl.md
> sql: add ddl section `create index`

- sql/README.md
- sql/transaction.md
All things about transaction in TiDB.
> sql: Add transaction statement

- sql/README.md
- sql/privilege.md
- sql/user-account-management.md
用户管理相关的文档部分。类似于MySQL
@sunhao2017 @shenli
> sql: user account management document

- sql/bit-functions-and-operators.md
> Fix format

- sql/README.md
- sql/tidb-server.md
Add document for tidb-server.
@sunhao2017
> Add document for tidb-server

- sql/dml.md
Add document for Replace statement syntax.
> sql: Add document for Replace statement

- sql/README.md
- sql/time-zone.md
> sql: add document about time zone support

- sql/system-database.md
> sql: update system-databases.md add inforschema database description

- sql/README.md
- sql/error.md
> sql: Add error doc

- sql/ddl.md
> Fix typo, update format and wording

- sql/README.md
> sql: add user-define-variable link and scheme-object-names link in Readme

- sql/README.md
- sql/prepare.md
Document for prepared statement.
> sql: Add document for prepared statement

- sql/README.md
- sql/functions-and-operators-reference.md
> 1. add link to info-func 2. add doc for function reference

- sql/README.md
- sql/admin.md
> sql: Add admin document

- sql/datatype.md
> sql: Add doc for set and enum

- sql/README.md
- sql/connection-and-APIs.md
> add connection and APIs to document

- op-guide/ansible-deployment.md
> ansible port and dir variable

- FAQ.md
> Fix wrong link for PD Control

- op-guide/offline-ansible-deployment.md
- op-guide/op-guide.md
add offline ansible deployment document
> add offline ansible deployment document

- circle.yml
update:
with new version of packages,  static ip/host binding.
> ci: update build docker image

- sql/system-database.md
> Update format and fix wording

- trouble-shooting.md
TiKV OOM related touble-shooting
> TiKV OOM related touble-shooting

- op-guide/ansible-deployment.md
- op-guide/offline-ansible-deployment.md
Add multiple tikv instance deployment
@LinuxGit @zhengwanbo @buggithubs @sunhao2017  PTAL
> update ansible deployment

- benchmark/sysbench.md
Benchmark for TiDB 1.0.0 with Sysbench.
> benchmark: Add Sysbench result for v1.0.0

- FAQ.md
PTAL @coocood @shenli @sunhao2017 
cc @queenypingcap
> faq: Add details to run DDL

- op-guide/tispark-quick-start-guide.md
- op-guide/tispark-user-guide.md
> update tispark docs

- tools/loader.md
> loader support mysql

- op-guide/tispark-user-guide.md
@queenypingcap @birdstorm PTAL
> chore: update tispark-user-guide

- op-guide/configuration.md
> Update the order of configuration parameters

- op-guide/offline-ansible-deployment.md
old tispark jar address in ansible document should be updated.
@queenypingcap PTAL.
> update tispark jar address

- op-guide/recommendation.md
Ubuntu 16.04 supports systemd and ntpstat
> recommend ubuntu version

- op-guide/ansible-deployment.md
> Fix the display format

- README.md
add headlink for transaction isolation
> add headlink for transaction isolation

- README.md
- tools/tidb-binlog-kafka.md
Via https://github.com/pingcap/docs-cn/pull/455. @sunhao2017
> Update Kafka binlog in README

- README.md
> add new article：IFENG

- README.md
- op-guide/docker-compose.md
This PR add document to uses [tidb-docker-compose](https://github.com/pingcap/tidb-docker-compose) project for docker-compose deployment.
PTAL @sunhao2017 @lilin90 @iamxy
> use tidb-docker-compose project

- tools/tidb-binlog-kafka.md
> binlog-tools: add download url

- op-guide/offline-ansible-deployment.md
> Fix the format display error at PingCAP website

- op-guide/offline-ansible-deployment.md
update offline ansible deployment
@LinuxGit PTAL
> update offline ansible deployment

- tools/syncer.md
@buggithubs  @GregoryIan  @WangXiangUSTC  PTAL
> syncer:  add skip-dmls document

- releases/11alpha.md
- releases/README.md
> Add release notes for 1.1 alpha

- README.md
> add new customer case

- README.md
update user cases
@sunhao2017 @meyu44 PTAL
> update user cases

- README.md
- overview.md
> fix description

- op-guide/tune-tikv.md
Format chaos on PingCAP website. PTAL @sunhao2017 @CaitinChen
> Fix format display error

- FAQ.md
> Fix list display format

- sql/precision-math.md
Fix the broken link @XuHuaiyu  PTAL
> Fix broken link

- op-guide/ansible-deployment.md
> Fix display format, update wording and punctuation

- FAQ.md
Also delete repetitive content. @dbaoutdo PTAL
> Fix typo, links and punctuation in FAQ

- FAQ.md
> Fix word spelling

- sql/ddl.md
@shenli @zimulala @queenypingcap @lilin90 PTAL
> ddl: add column limit declaration.

- tools/syncer.md
> tools: update Syncer guide

- FAQ.md
PTAL @shenli @winkyao @queenypingcap @lilin90
> faq: update kill DDL

- tools/tidb-binlog-kafka.md
> tools: update Kafka wording and format

- tools/syncer.md
> tools: fix display error

- tools/loader.md
> tools: fix loader display format

- releases/11beta.md
- releases/README.md
> Add the release notes for 1.1 beta

- sql/dml.md
> Fix a broken link

- tools/syncer.md
> fix: fixed indent in syncer code block

- tools/syncer.md
> tools: update syncer content and format

- tools/syncer.md
> tools: fix syncer code indent

- README.md
@lilin90 @liubo0127 @sunhao2017 @dbaoutdo 
PTAL
> add post link

- releases/2.0rc1.md
- releases/README.md
> releases: add 2.0 RC1 Release Notes

- tispark/tispark-quick-start-guide.md
> tispark: fix a broken link and punctuation

- QUICKSTART.md
- tools/tidb-binlog-kafka.md
> QUICKSTART: Fix a typo

- sql/ddl.md
Support RESTRICT and CASCADE in `drop table`.
> ddl: Support RESTRICT and CASCADE in drop table

- README.md
add user case
@sunhao2017 @meyu44 PTAL
> add user case

- sql/json-functions-generated-column.md
> sql: add unquote in json doc

- op-guide/docker-compose.md
> op-guide: update wording and fix a link

- releases/2.0rc3.md
- releases/README.md
> releases: add the release notes for 2.0 RC3

- README.md
add FUNYOURS JAPAN case
@sunhao2017 @meyu44 @jinsheng1995  PTAL
> add FUNYOURS JAPAN case

- op-guide/tune-tikv.md
> op-guide: fix wording and update format

- op-guide/ansible-deployment.md
- tools/tidb-binlog-kafka.md
change zk url example in ansible and tool doc
> change zk url example

- tools/loader.md
> tools: fix loader description

- FAQ.md
- op-guide/configuration.md
- sql/admin.md
- sql/ddl.md
> sql: update admin and ddl doc

- op-guide/configuration.md
> op-guide: fix configuration typo and wording

- sql/statistics.md
> stats: update statistic docs

- op-guide/ansible-deployment.md
- tools/tidb-binlog-kafka.md
> op-guide/tools: fix wording and punctuation

- op-guide/ansible-deployment.md
- op-guide/offline-ansible-deployment.md
Update the download example for ansible deployment
@sunhao2017 @lilin90 PTAL
> Update the download example for ansible deployment

- sql/comment-syntax.md
- sql/dml.md
> sql: add `STRAIGHT_JOIN` and fix `comment_syntax.md`.

- sql/transaction-isolation.md
> sql: update transaction behavior in transaction-isolation.md

- QUICKSTART.md
- README.md
- overview.md
@queenypingcap @CaitinChen PTAL
Via: https://github.com/pingcap/docs/pull/411
> *: update TiDB feature description

- op-guide/binary-deployment.md
> Command relative path error

- op-guide/binary-deployment.md
> op-guide: fix the file name

- scripts/generate_pdf.sh
- scripts/merge_by_toc.py
- templates/template.tex
> fix: update template latex and script for merging and generating pdf

- README.md
- releases/2.0ga.md
- releases/rn.md
> releases/readme: add the release notes for TiDB 2.0

- op-guide/tidb-v2-upgrade-guide.md
> op-guide: update link, wording, punctuation and format

- op-guide/ansible-deployment.md
> op-guide: delete extra whitespace and update format

- op-guide/tidb-v2-upgrade-guide.md
> op-guide: fix code block format at website

- README.md
@CaitinChen PTAL 
Via: https://github.com/pingcap/docs/pull/459
> readme: simplify document structure

- FAQ.md
> faq: update list format and version description

- sql/tidb-specific.md
> sql: fix scope of some tidb variables

- sql/ddl.md
update ddl doc about `alter table comment`.
> sql: update ddl doc

- sql/system-database.md
> sql: fix typo about COLUMN_PRIVILEGES

- op-guide/ansible-deployment.md
ansible-deployment:  add tikv topology note
> ansible-deployment: add tikv topology note

- op-guide/docker-compose.md
@tennix @CaitinChen PTAL
Via: https://github.com/pingcap/docs/pull/496
> op-guide: update docker compose deployment

- op-guide/ansible-deployment.md
- op-guide/offline-ansible-deployment.md
deployment: 
- add font and sshpass offline package installation
- add ansible_user note
>  deployment: add font and sshpass offline package installation

- op-guide/horizontal-scale.md
via https://github.com/pingcap/docs-cn/issues/773
@lilin90  PTAL
> op-guide: fix a typo

- op-guide/ansible-deployment-rolling-update.md
> op-guide: fix format

- FAQ.md
> faq: fix typo and update wording

- op-guide/ansible-deployment-rolling-update.md
- op-guide/ansible-deployment-scale.md
- op-guide/tidb-v2-upgrade-guide.md
> op-guide: fix links, format, and heading level

- README.md
- releases/21beta.md
- releases/rn.md
> releases, readme: add the release notes for 2.1 beta

- sql/transaction-isolation.md
> sql: fix format and update wording

- README.md
> README: remove a user case

- op-guide/ansible-deployment.md
op-guide: add CPUfreq governor note
> op-guide: add CPUfreq governor note

- FAQ.md
@zhexuany @CaitinChen PTAL 
Via: https://github.com/pingcap/docs/pull/539
> FAQ: update gc duration error message

- tools/tikv-control.md
Via: https://github.com/pingcap/docs/pull/541
> tools: improve content organization

- op-guide/docker-compose.md
@CaitinChen @tennix PTAL
Via: https://github.com/pingcap/tidb-docker-compose/pull/27, https://github.com/pingcap/docs/pull/546
> op-guide: add accessing Spark with Python or R

- tools/pd-control.md
Introduce the cluster version.
> tools: add cluster version command in pd-control

- overview.md
> overview: delete extra whitespaces

- op-guide/ansible-deployment.md
> op-guide: update IPs of target machines

- QUICKSTART.md
> quickstart: fix Ansible link

- sql/datatype.md
> sql: fix typo in datatype

- op-guide/configuration.md
from https://github.com/pingcap/docs/pull/543
> op-guide: add advertise-address to configuration.md

- README.md
- releases/206.md
- releases/rn.md
@CaitinChen @yikeke PTAL
Via: https://github.com/pingcap/docs/pull/562
> releases, readme: add TiDB 2.0.6 release notes

- op-guide/ansible-deployment.md
By default, `useradd` will not create home dir for new user automatically, and `useradd` is a low level utility for adding users. Set -m and -d will create tidb dir.
> op-guide: Update ansible-deployment.md `useradd` command

- tools/pd-control.md
related PR: https://github.com/pingcap/pd/pull/1201
> tools/pd-control: add option of disable-namespace-relocation

- tools/loader.md
> tools: replace some words that are not used properly

- FAQ.md
> FAQ: address term issue

- ROADMAP.md
@tennix PTAL Via: https://github.com/pingcap/docs/pull/574
> roadmap: update state of K8s based integration

- README.md
- releases/21rc1.md
- releases/rn.md
> releases, readme: add the release notes for 2.1 rc1

- sql/understanding-the-query-execution-plan.md
@CaitinChen PTAL Via: https://github.com/pingcap/docs/pull/578
> sql: update `EXPLAIN` format

- releases/21rc1.md
> releases: fix a broken link

- sql/character-set-configuration.md
- sql/mysql-compatibility.md
Via: https://github.com/pingcap/docs/pull/591 
Comment addressed. PTAL again. @lilin90
> sql: add default differences between TiDB and MySQL

- FAQ.md
- sql/slow-query.md
Via https://github.com/pingcap/docs/pull/595
@coocood @lilin90 PTAL
> faq, sql: update wording

- README.md
- releases/207.md
- releases/rn.md
> readme, releases: add 2.0.7 release notes

- sql/character-set-configuration.md
@CaitinChen PTAL Via: https://github.com/pingcap/docs/pull/609
> sql: clarify default character-set is utf8

- sql/mysql-compatibility.md
@CaitinChen PTAL Via: https://github.com/pingcap/docs/pull/601
> sql: add support for IGNORE n LINES

- sql/tidb-specific.md
Via: https://github.com/pingcap/docs/pull/610
> sql: update tidb_ddl_reorg_priority and format

- tools/pd-control.md
related pr: [#616](https://github.com/pingcap/docs/pull/616)
> pd ctl: change the `remove` to `add`

- sql/information-functions.md
just add parenthesis
Related PR: https://github.com/pingcap/docs-cn/pull/883
> sql: add parenthesis

- overview.md
This PR solves the 404 issue if you click the link (relative path) directly on the https://www.pingcap.com/docs-cn/ page.
> overview: update a link

- tools/tikv-control.md
Via: https://github.com/pingcap/docs/pull/581/. PTAL. @lilin90
> tools: add two commands in tikv-ctl

- tools/pd-control.md
[#1254](https://github.com/pingcap/pd/pull/1254)
[default region limit](https://github.com/pingcap/pd/blob/master/server/api/region.go#L245)
> pd-ctl: add topsize command and change the default number of limit

- README.md
- releases/21rc3.md
- releases/rn.md
Via: https://github.com/pingcap/docs/pull/639
> releases, readme: add 2.1 RC3 releases notes

- op-guide/ansible-deployment-rolling-update.md
> op-guide: fix website display error

- sql/mysql-compatibility.md
@CaitinChen PTAL 
Via: https://github.com/pingcap/docs-cn/issues/910
> sql: fix display format error

- ROADMAP.md
Signed-off-by: Huachao Huang <huachao.huang@gmail.com>
> roadmap: update TiKV

- sql/character-set-support.md
Via: https://github.com/pingcap/docs-cn/issues/916
> sql: fix a typo

- op-guide/ansible-deployment.md
> op-guide: update one link path

- ROADMAP.md
> roadmap: fix a typo and make format consistent

- sql/mysql-compatibility.md
Via: https://github.com/pingcap/docs/pull/661
> sql: add X Protocol to MySQL compatibility

- overview.md
> overview: remove K8s related description

- sql/admin.md
Add some description about show master status
@zz-jason @lilin90
> sql: update admin.md about `show master status`

- op-guide/tidb-config-file.md
It's introduced in https://github.com/pingcap/tidb/pull/7192
@lilin90 @winkyao
> op-guide: add document about `compatible-kill-query` in config

- FAQ.md
> faq: update fio command

- FAQ.md
- sql/connection-and-APIs.md
- sql/precision-math.md
- sql/tidb-server.md
Via: https://github.com/pingcap/docs/pull/687
> faq, sql: fix several broken links

- tools/binlog-slave-client.md
- tools/tidb-binlog-cluster.md
you can preview at https://github.com/WangXiangUSTC/docs-cn/blob/xiang/binlog_slave/tools/binlog-slave-client.md
> binlog: add slave client user guide document

- FAQ.md
Via: https://github.com/pingcap/docs/pull/688
> faq: fix typos and update format

- sql/aggregate-group-by-functions.md
@zz-jason @CaitinChen PTAL
Via: https://github.com/pingcap/docs/pull/657
> sql: update aggregation functions

- tools/pd-control.md
> pd-ctl: update the usage of region key

- tools/tidb-binlog-kafka.md
> tools/tidb-binlog-kafka.md: update download link

- sql/system-database.md
@zz-jason PTAL
Via: https://github.com/pingcap/docs/pull/691
> sql: improve description of infoschema engines

- README.md
- tools/tidb-binlog-cluster.md
1. update some download link for binlog
2. update the tidb-binlog's link in readme
> binlog: update some link

- tools/tidb-binlog-cluster.md
- tools/tidb-binlog-monitor.md
you can preview at: https://github.com/WangXiangUSTC/docs-cn/blob/xiang/monitor/tools/tidb-binlog-monitor.md
> tools: add monitor user guide document for tidb-binlog

- tools/mydumper.md
@kennytm @CaitinChen PTAL
Via: https://github.com/pingcap/docs/pull/693
> tools: update mydumper default tidb_snapshot

- sql/statistics.md
- Update the syntax for `analyze` statement
- Add description for auto analyze start and end time.
- Update output info for show stats.
> sql: update document for stats

- tools/tidb-binlog-cluster.md
> tools: update Binlog wording

- FAQ.md
> faq: fix fio command

- tools/tidb-binlog-monitor.md
> tools: update wording for TiDB-Binlog monitoring metrics

- FAQ.md
- sql/user-manual.md
- tools/binlog-slave-client.md
- tools/tidb-binlog-kafka.md
Found by tool: https://github.com/rleungx/dlmd
> FAQ, sql, tools: Fix link errors

- sql/mysql-compatibility.md
via https://github.com/pingcap/docs/pull/714
@lilin90 @kennytm PTAL
> sql: add the description of small transactions

- tools/reparo.md
- tools/tidb-binlog-cluster.md
can preview at https://github.com/WangXiangUSTC/docs-cn/blob/xiang/reparo/tools/reparo.md
> tools: add user guide for reparo

- tools/lightning-deployment.md
- tools/lightning-faq.md
> lightning: increase the required version from 2.0.4 to 2.0.9

- ROADMAP.md
> roadmap: update Tools

- tools/tidb-binlog-cluster.md
> Add release-2.1 in tools/tidb-binlog-cluster.md

- op-guide/ansible-deployment.md
> op-guide: add Ansible release-2.1 to Ansible deployment

- op-guide/horizontal-scale.md
should be "member delete name pd4"
> op-guide: fix pd-ctl command error

- tools/pd-control.md
cherry-pick #957 to 2.0 branch.
> tools: update the usage of region key

- FAQ.md
Add the EOF error in the log files for FAQ.
PTAL @lilin90 @CaitinChen
> faq: add eof error from the log

- op-guide/tidb-v2.1-upgrade-guide.md
> Update v2.1 upgrade guide

- op-guide/tidb-dashboard-info.md
This PR adds part of tidb metrics info.
> op-guide: add metrics info for tidb

- op-guide/tidb-dashboard-info.md
> op-guide: replace tab with space

- tools/pd-control.md
- tools/pd-recover.md
> tools: update pdctl document

- tools/tidb-binlog-cluster.md
> tools: fix format

- sql/mysql-compatibility.md
Via https://github.com/pingcap/docs/pull/761
@lilin90 @zz-jason PTAL. Thanks.
> sql: update description of the transaction model part

- sql/mysql-compatibility.md
Via https://github.com/pingcap/docs/pull/728
@lilin90 @zz-jason PTAL
> sql: add SQL mode details

- sql/json-functions.md
@zz-jason PTAL
Via: https://github.com/pingcap/docs/pull/770
> sql: add JSON_DEPTH

- tools/loader.md
- tools/reparo.md
- tools/syncer.md
- tools/tidb-binlog-cluster.md
- tools/tidb-binlog-kafka.md
- tools/tidb-binlog.md
- tools/tidb-controller.md
Via https://github.com/pingcap/docs/pull/762
@lilin90 PTAL 
`data-migration-deployment.md` does not exist in the docs-cn repo, so I ignore it.
> tools: highlight snippets missing the INI, TOML etc tags

- README.md
> readme: add TiDB, PD, TiKV monitoring metrics

- op-guide/dashboard-overview-info.md
> op-guide: update the title

- op-guide/tidb-v2.1-upgrade-guide.md
- tools/tidb-binlog-cluster.md
> New upgrade compatibility note

- sql/tidb-specific.md
- tools/mydumper.md
- tools/sync-diff-inspector.md
- tools/tidb-binlog-cluster.md
Via: https://github.com/pingcap/docs/pull/744#issuecomment-443713806
This PR removes all "_tidb_rowid" related content except that in Release Notes.
@GregoryIan @CaitinChen PTAL
> sql, tools: remove "_tidb_rowid"

- op-guide/horizontal-scale.md
Via https://github.com/pingcap/docs/pull/798
@disksing  @lilin90 PTAL
> op-guide: clarify offline behavior

- README.md
- releases/2.1.1.md
- releases/rn.md
Via: https://github.com/pingcap/docs/pull/809
> releases, readme: add TiDB 2.1.1 Releases Notes

- sql/dml.md
- v1.0/sql/dml.md
- v2.0/sql/dml.md
Should I apply the changes to v1.0 and v2.0?
> sql: fix example of `insert into set`

- README.md
- releases/2.0.10.md
- releases/rn.md
> releases, readme: add TiDB 2.0.10 Release Notes

- v1.0/sql/character-set-support.md
- v2.0/sql/character-set-support.md
The previous list format leads to format confusion.
> v1.0/sql, v2.0/sql: fix list format

- op-guide/monitor.md
> op-guide: update tidb http api doc

- tools/tikv-control.md
Update for latest change for tikv-ctl unsafe-recover.
> tools: update doc for tikv-ctl unsafe-recover

- op-guide/tune-tikv.md
> op-guide: fix the format

- tools/tidb-binlog-cluster.md
need set run_ddl = false if don't enable binlog.
> tools: add tip about enable binlog

- sql/connection-and-APIs.md
> sql: fix a broken link of MySQL for D

- tools/tidb-binlog-cluster.md
> tools: fix invalid characters in binlog cluster

- README.md
- releases/2.0.11.md
- releases/rn.md
> README, releases: add the release notes for 2.0.11

- op-guide/ansible-deployment.md
@rleungx @LinuxGit @lilin90 PTAL
> New status port for tikv, update multi-instance deployment documentation

- FAQ.md
I found a broken link. PTAL @lilin90
> FAQ: fix a broken link

- op-guide/ansible-deployment.md
> op-guide: update ansible deployment for tikv status-addr

- sql/admin.md
admin: add doc for admin show ddl jobs
> sql: add doc for admin show ddl jobs

- ROADMAP.md
Update the TiDB roadmap, @shenli @lilin90 PTAL
> ROADMAP: update the tidb roadmap

- sql/user-account-management.md
Via https://github.com/pingcap/docs/pull/835
@lilin90 @lonng PTAL when https://github.com/pingcap/docs/pull/835 is merged.
> sql: add `FLUSH PRIVILEGES` hint

- sql/mysql-compatibility.md
> sql: fix the typo

- FAQ.md
- op-guide/migration-overview.md
remove introduction about `checker` because it is obsolete.
> tools: remove checker

- README.md
- releases/2.1.3.md
- releases/rn.md
Via https://github.com/pingcap/docs/pull/875
@lilian90 PTAL
> releases, README: add TiDB 2.1.3 release notes

- sql/mysql-compatibility.md
Via: https://github.com/pingcap/docs/pull/830 PTAL @lilin90
> sql: add three unsupported features to imcompatible

- try-tidb.md
> try-tidb: fix the index syntax

- tools/tidb-binlog-cluster.md
@CaitinChen @WangXiangUSTC PTAL
> tools: remove invalid characters causing CI failure

- sql/json-functions.md
Via: https://github.com/pingcap/docs/pull/864/ Comment addressed. @lilin90 @zz-jason PTAL.
> sql: Add JSON_MERGE_PRESERVE

- tispark/tispark-quick-start-guide_v1.x.md
- tispark/tispark-user-guide.md
- tispark/tispark-user-guide_v1.x.md
Update for TiSpark version 2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/docs-cn/1053)
> tispark: update for spark v2

- benchmark/sysbench-v3.md
- v2.1/benchmark/sysbench-v3.md
> benchmark, v2.1/benchmark: fix table format

- benchmark/sysbench-v2.md
- v2.1/benchmark/sysbench-v2.md
> v2.1/benchmark, benchmark: fix table format

- benchmark/sysbench.md
- v1.0/benchmark/sysbench.md
- v2.0/benchmark/sysbench.md
- v2.1/benchmark/sysbench.md
> *: fix table format of 4 sysbench files

- README.md
- releases/2.1.4.md
- releases/rn.md
DO NOT MERGE this PR until https://github.com/pingcap/docs/pull/902 is merged.
> releases, readme: add TiDB 2.1.4 Release Notes

- sql/json-functions.md
Via: https://github.com/pingcap/docs/pull/894/ PTAL @lilin90 
Note: I saw a mistranslation about JSON UNQUOTE so I fixed it as well.
> sql: add JSON QUOTE and fix JSON UNQUOTE

- tools/sync-diff-inspector.md
1. add config `tidb-instance-id`
2. add config `table-rule`
3. update download urls
> sync-diff-inspector: update config file

- FAQ.md
- tools/tidb-binlog-cluster.md
> TiDB-Binlog: add start pump step

- README.md
- tools/download.md
@GregoryIan @CaitinChen PTAL
Via: https://github.com/pingcap/docs/pull/855
> readme, tools: add tools download page

- op-guide/try-tidb.md
- v1.0/QUICKSTART.md
- v1.0/op-guide/try-tidb.md
- v2.0/QUICKSTART.md
- v2.0/op-guide/try-tidb.md
- v2.1/op-guide/try-tidb.md
- v2.1/try-tidb.md
> *: fix alter add unique syntax

- sql/dml.md
update document about "SQL_NO_CACHE"
> sql/dml: update SQL_NO_CACHE definition

- tools/dm/relay-log.md
The English version: https://github.com/pingcap/docs/blob/master/tools/dm/relay-log.md
The original Chinese version: https://github.com/pingcap/tidb-tools/blob/docs/docs/dm/zh_CN/features/relay-log.md
> tools: add DM relay log 

- tools/dm/dm-worker-intro.md
Related PR: https://github.com/pingcap/docs/pull/915
English file:
https://github.com/pingcap/docs/blob/master/tools/dm/dm-worker-intro.md
@lilin90 @GregoryIan  @csuzhangxc PTAL
> tools/dm: add DM-worker intro

- tools/dm/dm-worker-intro.md
- tools/dm/overview.md
- tools/dm/relay-log.md
> tools/dm: update format

- README.md
@lilin90 PTAL
Related PR: https://github.com/pingcap/docs-cn/pull/1131
> README: add practice.md

- sql/tidb-specific.md
- v2.1/sql/tidb-specific.md
update `tidb_ddl_reorg_worker_cnt` and `tidb_ddl_reorg_batch_size` parameter definition。
> sql/tidb-specific: update ddl reorg parameter

- tools/dm/deployment.md
> tools/dm: fix links

- README.md
- releases/2.1.5.md
- releases/rn.md
> README, releases: add 2.1.5 release notes

- tools/dm/manage-task.md
- tools/dm/precheck.md
- tools/tools/dm/manage-task.md
Via docs: https://github.com/pingcap/docs/blob/master/tools/dm/manage-task.md
docs-cn reference: 
https://github.com/pingcap/tidb-tools/blob/docs/docs/dm/zh_CN/task-handling/dmctl-manual.md
https://github.com/pingcap/tidb-tools/blob/docs/docs/dm/zh_CN/task-handling/task-commands.md
PTAL. @lilin90 @GregoryIan @csuzhangxc
> tools/dm: add manage-task.md and precheck.md

- tools/dm/manually-handling-sharding-ddl-locks.md
@GregoryIan @csuzhangxc @amyangfei @CaitinChen PTAL
- [English doc](https://github.com/pingcap/docs/blob/master/tools/dm/manually-handling-sharding-ddl-locks.md)
- [Original Chinese doc](https://github.com/pingcap/tidb-tools/blob/docs/docs/dm/zh_CN/shard-table/handle-DDL-lock.md)
> tools/dm: add Handling Sharding DDL Locks Manually

- tools/dm/dm-configuration-file-overview.md
@GregoryIan @csuzhangxc @CaitinChen PTAL
Via: https://github.com/pingcap/docs/blob/master/tools/dm/dm-configuration-file-overview.md
> tools/dm: add dm config intro

- tools/dm/simple-synchronization-scenario.md
Via docs: https://github.com/pingcap/docs/blob/master/tools/dm/simple-synchronization-scenario.md
PTAL. @GregoryIan @csuzhangxc @lilin90
> tools/dm: add simple-synchronization-scenario.md

- README.md
- tools/dm/task-configuration-file-intro.md
English doc: https://github.com/pingcap/docs/blob/master/tools/dm/task-configuration-file-intro.md
@csuzhangxc @lilin90 @GregoryIan PTAL
> README, tools/dm: add DM task config file intro

- tools/dm/troubleshooting.md
Via: https://github.com/pingcap/docs/blob/master/tools/dm/troubleshooting.md
PTAL. @lilin90 @csuzhangxc @GregoryIan 
PTAL again. @amyangfei
> tools/dm: add troubleshooting.md

- tools/dm/query-status.md
Added doc for DM Query Status
Translated from: https://github.com/pingcap/docs/blob/master/tools/dm/query-status.md
> tools/dm: add doc for query status

- tools/dm/manually-handling-sharding-ddl-locks.md
> toos/dm: add link to query status

- tools/dm/troubleshooting.md
> tools/dm: update links in troubleshooting.md

- tools/dm/task-configuration-file-intro.md
> tools/dm: remove Tab spaces

- tools/loader.md
- tools/tidb-binlog-cluster.md
- tools/tidb-binlog-kafka.md
- tools/tidb-binlog.md
Via: https://github.com/pingcap/docs/pull/901/ PTAL @lilin90 @amyangfei
> tools: fix incorrect category

- TOC.md
added cluster-operations.md in TOC
> TOC: update TOC with cluster operation entry

- sql/tidb-specific.md
- v2.1/sql/tidb-specific.md
> v2.1/sql, sql: fix links

- TOC.md
> TOC: add DM troubleshooting

- op-guide/offline-ansible-deployment.md
- tools/dm/cluster-operations.md
- tools/dm/dm-configuration-file-overview.md
- tools/dm/troubleshooting.md
- v2.1/op-guide/offline-ansible-deployment.md
This PR fixes some links that cannot jump to the correct position at the PingCAP website. This update affects the link jumping at GitHub, but we'll first guarantee the usability of the PingCAP website.
@YiniXu9506 PTAL
> *: fix links for website display

- tools/loader.md
- tools/mydumper.md
- tools/syncer.md
- tools/tidb-binlog.md
Via: https://github.com/pingcap/docs/pull/919/ PTAL @lilin90 @GregoryIan
> tools: harmonize download links

- TOC.md
- releases/2.1.6.md
- releases/rn.md
release note updates for 2.1.6
> TOC, releases: publish release notes for 2.1.6

- sql/transaction.md
PTAL @tiancaiamao @lilin90 @CaitinChen
> sql: add lazy check for transaction

- tools/tikv-control.md
- v2.1/tools/tikv-control.md
Since most of the user will compact a single TiKV in online mode, This PR makes it more clear.
> tools: make compacting a single node more clear

- sql/understanding-the-query-execution-plan.md
- v1.0/sql/understanding-the-query-execution-plan.md
- v2.0/sql/understanding-the-query-execution-plan.md
- v2.1/sql/understanding-the-query-execution-plan.md
Via https://github.com/pingcap/docs/pull/850
@lilin90 @zz-jason PTAL @_@
> sql: explain cop capabilities

- TOC.md
- tools/dm/dm-upgrade.md
> TOC, tools/dm: add the DM upgrade doc

- sql/mysql-compatibility.md
- v2.0/sql/mysql-compatibility.md
- v2.1/sql/mysql-compatibility.md
Via https://github.com/pingcap/docs/pull/917
@lilin90 @jackysp @zimulala PTAL
> *: update explicit defaults for timestamps

- architecture.md
Via https://github.com/pingcap/docs/pull/852
@lilin90 @kennytm @disksing PTAL
> architecture: update PD description

- op-guide/tidb-config-file.md
- sql/statistics.md
- v2.1/op-guide/tidb-config-file.md
- v2.1/sql/statistics.md
use `0` for `feedback-probability` can not start, need use `0.0`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/docs-cn/1163)
> sql: statistics `feedback-probability` need use float `0.0`

- TOC.md
- releases/3.0.0-beta.1.md
- releases/rn.md
Related PR: https://github.com/pingcap/docs/pull/978
@shenli PTAL
> releases, TOC: add 3.0.0 Beta.1 Release Notes

- TOC.md
- releases/2.1.7.md
- releases/rn.md
Via: https://github.com/pingcap/docs/pull/984
> releases, toc: add 2.1.7 Releases Notes

- sql/mysql-compatibility.md
via: [pingcap/docs #849](https://github.com/pingcap/docs/pull/849)
PTAL @lilin90 @CaitinChen
> sql: add latency sensitivity specifically

- op-guide/ansible-deployment.md
- op-guide/offline-ansible-deployment.md
> op-guide: update tidb-ansible deployment

- tools/tidb-controller.md
tools: add doc for tidb-ctl base64decode
releated PR: https://github.com/pingcap/tidb-ctl/pull/20
> tools: add doc for tidb-ctl base64decode

- README.md
- sql/user-manual.md
> sql, README: adjust doc display on the website

- TOC.md
> toc: delete user-case-eleme

- op-guide/ansible-deployment.md
> op-guide: add parameter description in ansible deployment

- FAQ.md
- sql/transaction-isolation.md
@dcalvin PTAL
Via: https://github.com/pingcap/docs/pull/936, https://github.com/pingcap/docs/pull/938
> faq, sql: update isolation level and FAQ description

- tools/syncer.md
add more arguments description in syncer docs
> tools: add more syncer argument description

- op-guide/tidb-config-file.md
Via docs changed by kolbe: https://github.com/pingcap/docs/pull/969 PTAL @lilin90
> op-guide: clarify compatible-kill-query

- contribute.md
- report-issue.md
- support.md
Via: https://github.com/pingcap/docs/pull/974 PTAL @lilin90
> contribute, support, report-issue: add three files

- sql/mysql-compatibility.md
- sql/statistics.md
Via https://github.com/pingcap/docs/pull/970
@lilin90 @jackysp PTAL
> sql: add additional information about ANALYZE TABLE in TiDB

- sql/admin.md
This PR aims to add `ADMIN CHECK TABLE` syntax description to current docs
> sql: add `ADMIN CHECK TABLE` command

- TOC.md
- sql/tidb-server.md
via issue https://github.com/pingcap/docs-cn/issues/1216
> **TiDB用户文档-TiDB数据库管理-TiDB服务和TiDB用户文档-TiDB数据库管理-数据目录**
内容重复
> TOC, sql: update TOC and header to clear confusion

- tools/dm/deployment.md
> tools/dm: add description for `{version}`

- op-guide/tidb-config-file.md
Original English doc: https://github.com/pingcap/docs/pull/969
Reference to PR: https://github.com/pingcap/docs-cn/pull/1214
PTAL @lilin90
> op-guide: add a missing paragraph in tidb-config-file.md

- releases/21rc1.md
- tools/pd-control.md
- v1.0/FAQ.md
- v1.0/trouble-shooting.md
- v2.0/FAQ.md
- v2.0/trouble-shooting.md
- v2.1/releases/21rc1.md
- v2.1/tools/pd-control.md
Via: https://github.com/pingcap/docs/pull/1021
@dcalvin PTAL
> *: fix multiple typos

- sql/mysql-compatibility.md
- sql/understanding-the-query-execution-plan.md
Related PR: https://github.com/pingcap/tidb/pull/10030
> sql: update EXPLAIN related document

- tispark/tispark-quick-start-guide.md
- tispark/tispark-quick-start-guide_v1.x.md
- v1.0/tispark/tispark-quick-start-guide.md
- v2.0/tispark/tispark-quick-start-guide.md
- v2.1/tispark/tispark-quick-start-guide.md
Related issue: https://github.com/pingcap/docs/issues/1019
Via https://github.com/pingcap/docs/pull/1020
@ilovesoup @birdstorm @lilin90 PTAL
> tispark: update an example

- support.md
via: https://github.com/pingcap/docs/pull/1028 @CaitinChen PTAL
> support: add slack channel

- sql/privilege.md
Please review this PR after https://github.com/pingcap/tidb/pull/9872 merged.
Add more infomation about privilege.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/docs-cn/1192)
> sql: add more privileges info

- tools/pd-control.md
- v2.1/tools/pd-control.md
> tools, v2.1: fix a typo

- op-guide/ansible-deployment.md
> op-guide: fix deployment about tidb-ansible version introduction

- releases/3.0beta.md
> releases: clarify meaning

- op-guide/migration-overview.md
Via: https://github.com/pingcap/docs/pull/1038
@dcalvin PTAL
> op-guide: reorganize and update migration overview

- benchmark/sysbench-v4.md
> benchmark: fix format

- ROADMAP.md
add a plan about the invisible index, it will be supported in version v3.1.
@shenli @lilin90 PTAL
> ROADMAP: add supporting invisible index

- v2.1/tools/tidb-binlog-cluster.md
- v2.1/tools/tidb-binlog-monitor.md
Related PR: https://github.com/pingcap/docs-cn/pull/1236
@WangXiangUSTC @lilin90  PTAL
> v2.1/tools: update TiDB-Binlog

- TOC.md
> TOC: update the QUICKSTART link

- op-guide/recommendation.md
via: https://github.com/pingcap/docs/pull/1029 @CaitinChen PTAL
> op-guide: modify the translation: requirements vs recommendations

- tools/dm/monitor.md
- refine the description for task's dashboard
- add a description for instances' dashboard
> tools/dm: refine dashboard description

- sql/privilege.md
- sql/user-account-management.md
I hope this change would make it better here https://www.pingcap.com/docs-cn/sql/privilege/ 
and here https://www.pingcap.com/docs-cn/sql/user-account-management/
@CaitinChen
> sql: remove redundant content

- tools/lightning/deployment.md
> tools: update a lightning download link

- TOC.md
- sql/system-database.md
> sql, TOC: update doc title

- benchmark/sysbench-v2.md
- v2.1/benchmark/sysbench-v2.md
> benchmark, v2.1/benchmark: remove an invalid link

- sql/transaction-isolation.md
Via issue:
https://github.com/pingcap/docs-cn/issues/1237
> sql: update condition

- sql/slow-query.md
> sql/slow_query: add pt-digest-query version

- tools/dm/monitor.md
> tools: clarify meaning of "N/A"

- releases/3.0.0-beta.1.md
Via https://github.com/pingcap/docs/pull/1084
@lilin90 PTAL
> releases: correct the TiDB-Ansible version

- TOC.md
- dev/how-to/get-started/explore-sql.md
- dev/how-to/get-started/local-cluster/install-from-docker-compose.md
- dev/how-to/get-started/read-historical-data.md
This PR renames the documents in the `dev/how-to/get-started` directory. 
Related PR: https://github.com/pingcap/docs/pull/1046
@dcalvin @scsldb @YiniXu9506 PTAL
> *: rename how-to get started

- TOC.md
> TOC: update a doc title

- tools/lightning/deployment.md
Related issue: https://github.com/pingcap/docs-cn/issues/1282
@lilin90 PTAL
> tools/lightning: fix a broken link

- sql/dml.md
- v1.0/sql/dml.md
- v2.0/sql/dml.md
- v2.1/sql/dml.md
Add explanation for `select for update` statement.
> sql: explain select for update statement

- sql/generated-columns.md
Currently only generated `stored` column index take effective, create index on generated `virtual` column is useless for plan-optimizer.
Below is example, there is 2 tables: `persone`, `persone1`. The only differented between `persone` and `persone1` is the column `city` virtual or stored generated column.
```sql
tidb:test> show create table person
+--------+----------------------------------------------------------------------------------------------------------+
| Table  | Create Table                                                                                             |
+--------+----------------------------------------------------------------------------------------------------------+
| person | CREATE TABLE `person` ( …
```
> sql: update generated columns docs

- tools/syncer.md
we have updated default batch size to 100 in syncer, synchronize update to docs
> tools: update syncer batch size

- circle.yml
> circle.yml: [WIP] comment publish pdf cmd

- tools/loader.md
- tools/syncer.md
pprof-addr is deprected, use status-addr instead
> tools: update loader status addr

- circle.yml
> circle.yml: remove IP address

- sql/generated-columns.md
> sql: fix format

- sql/generated-columns.md
> sql: update format

- sql/user-account-management.md
> sql: replace "jeffrey" with "test"

- op-guide/monitor.md
- v1.0/op-guide/monitor.md
- v2.0/op-guide/monitor.md
- v2.1/op-guide/monitor.md
> op-guide/monitor: update the PD API DOC link

- benchmark/sysbench-v4.md
Via: https://github.com/pingcap/docs/pull/1096 
@lilin90  PTAL
> benchmark/sysbench-v4: update a link

- circle.yml
> circle.yml: add a new IP for qiniu

- sql/user-account-management.md
> sql: fix typo

- op-guide/ansible-deployment.md
> op-guide: delete useless instruction

- TOC.md
- releases/3.0.0-rc.1.md
- releases/rn.md
> TOC, releases: add TiDB 3.0.0 RC1 release notes

- TOC.md
- op-guide/tidb-v3.0-upgrade-guide.md
> op-guide, toc: fix upgrade wording and update TOC

- TOC.md
- support.md
- Update the docs-cn TOC based on #1279 and discussion with @scsldb 
- Update a support link that is no longer active
> toc, support: reorganize TOC and update a link

- tools/binlog/overview.md
> tools/binlog: add `db-type` value description

- TOC.md
- dev/how-to/maintain/ansible-operations.md
- dev/how-to/maintain/backup-and-restore.md
- dev/how-to/maintain/identify-slow-queries.md
- dev/how-to/migrate/from-mysql.md
- dev/how-to/migrate/incrementally-from-mysql.md
- dev/how-to/migrate/overview.md
- dev/how-to/scale/horizontally.md
- dev/how-to/scale/with-ansible.md
- dev/how-to/troubleshoot/cluster-setup.md
- dev/how-to/upgrade/rolling-updates-with-ansible.md
- dev/how-to/upgrade/to-tidb-2.1.md
- dev/how-to/upgrade/to-tidb-3.0.md
- tools/binlog/overview.md
> *: rename remaining how-to files

- TOC.md
@CaitinChen @dcalvin PTAL
This PR removes the horizontal scaling file from TOC, requested by @tshqin.
> toc: hide the horizontal scale file

- tools/dm/shard-merge-scenario.md
> tools/dm: update a comma

- tools/pd-control.md
> tools/pd-control.md: add back slash before angle bracket

- tools/pd-control.md
> tools: update pd-control.md

- releases/2.1.10.md
Via https://github.com/pingcap/docs/pull/1162
@lilin90 PTAL
> releases: update release date

- tools/dm/task-configuration-file-intro.md
> tools/dm: update indentation

- tools/dm/shard-merge-scenario.md
> tools/dm: remove spaces

- sql/util.md
via: https://github.com/pingcap/docs/pull/1155
@jackysp @lilin90 PTAL
> sql/util: update sql/util

- dev/reference/tools/tidb-binlog/overview.md
> dev/reference/tools/tidb-binlog: add note for the `db-type` value

- TOC.md
- releases/3.0.0-rc.2.md
- releases/rn.md
> TOC, releases: add release notes for 3.0.0-rc.2

- dev/reference/tools/data-migration/usage-scenarios/shard-merge.md
> dev/reference/dm/usage-scenarios: fix typo

- dev/how-to/deploy/orchestrated/ansible.md
- dev/reference/configuration/tidb-server/tidb-specific-variables.md
- dev/reference/performance/understanding-the-query-execution-plan.md
- dev/reference/tools/data-migration/overview.md
Involve the following fixes:
- bad links 
- incorrect formatting 
- incorrect command line
> dev/how-to, dev/reference: fix bad links and other formatting issues

- FAQ.md
Via https://github.com/pingcap/docs/pull/1174
@dcalvin PTAL
> FAQ: update the link for `SHARD_ROW_ID_BITS`

- FAQ.md
Reverts pingcap/docs-cn#1370
@dcalvin PTAL
> FAQ: update link format

- dev/how-to/scale/with-ansible.md
@liubo0127  @lilin90  PTAL
Related PR: https://github.com/pingcap/docs-cn/pull/1328
> dev/how-to: update scale with ansible steps

- dev/how-to/upgrade/rolling-updates-with-ansible.md
Via https://github.com/pingcap/docs/pull/1180
@dcalvin PTAL
> dev/how-to/upgrade: update upgrade info

- dev/how-to/get-started/tidb-binlog.md
> dev/how-to/reference: update binlog

- dev/reference/tools/data-migration/overview.md
> dev/reference/tools: fix a ddl broken link

- dev/reference/configuration/tidb-server/mysql-variables.md
- dev/reference/sql/statements/ddl.md
- dev/reference/system-databases/information-schema.md
> dev/reference/*: fix 3 links

- dev/reference/sql/statements/dml.md
> dml: update the select for update notes for jepsen

- releases/2.1.11.md
> releases: add a TiKV PR

- dev/reference/sql/statements/admin.md
> dev/reference/sql/statements: fix a link

- FAQ.md
- dev/reference/configuration/tidb-server/tidb-specific-variables.md
> dev: update the descriptions of batch dmls

- dev/reference/tools/tidb-lightning/faq.md
- v2.1/tools/lightning/faq.md
Via: https://github.com/pingcap/docs/pull/1175
> dev/reference, v2.1/tools: fix a no-schema typo

- dev/how-to/migrate/from-mysql.md
Address some format mistakes.
PTAL @lilin90 @CaitinChen
> dev/how-to/migrate: update from-mysql

- dev/reference/mysql-compatibility.md
Via: https://github.com/pingcap/docs/pull/1130
@lilin90  PTAL
> dev/reference/mysql-compatibility: correct the name of `mysql-compatibility`

- TOC.md
- dev/reference/tools/data-migration/monitor.md
Related PR: https://github.com/pingcap/docs-cn/pull/1408
> toc, dev/reference/*: fix DM deployment links

- TOC.md
> TOC: update support file name

- faq/tidb.md
> faq: update the default value of `tidb_auto_analyze_ratio`

- TOC.md
Related PR: https://github.com/pingcap/docs-cn/pull/1427
@lilin90 PTAL
> TOC: update the roadmap file name

- dev/reference/tools/tidb-lightning/table-filter.md
- roadmap.md
- support-resources.md
> *: add alias for 3 files

- dev/reference/tools/syncer.md
Via: https://github.com/pingcap/docs/pull/1170
@CaitinChen  PTAL
>  dev/reference/tools: update MySQL settings in Syncer

- dev/reference/tools/tidb-control.md
Signed-off-by: Lonng <heng@lonng.org>
> tools/tidb-ctl: add some subcommands docs

- dev/reference/tools/sync-diff-inspector.md
Fix a mistake in line 29.
PTAL @lilin90
> dev\reference\tools: fix a mistake in sync-diff-inspector.md

- dev/reference/mysql-compatibility.md
- dev/reference/sql/character-set.md
- dev/reference/sql/statements/ddl.md
- dev/reference/system-databases/information-schema.md
updated docs about `CHARACTER SET` and `COLLATION` in TiDB, this is for the release of 3.0
> dev/reference: update CHARSET and COLLATION infos

- .github/pull_request_template.md
> .github: add a pr template

- .github/pull_request_template.md
Improve the PR template.
https://github.com/pingcap/docs-cn/pull/1453
No
> .github: update the pr template

- tidb-in-kubernetes/local-pv-management.md
- tidb-in-kubernetes/manage-local-pv.md
https://github.com/cofyc/docs-cn/blob/local-pv-management/tidb-in-kubernetes/manage-local-pv.md
> tidb-in-kubernetes: local-pv-management

- dev/reference/tools/sync-diff-inspector.md
This PR updates the inline code format, to fix the PR info build failure on the PingCAP website.
That failure was caused by https://github.com/pingcap/docs-cn/pull/1440.
> dev/reference/tools: update format

- dev/how-to/maintain/identify-slow-queries.md
> dev/how-to/maintain: update wording

- TOC.md
- dev/reference/sql/constraints.md
- dev/reference/transactions/overview.md
Via https://github.com/pingcap/docs/pull/1218
@lilin90 PTAL
> dev/reference/transactions, TOC: update transaction overview directory

- dev/reference/error-codes.md
- dev/reference/tools/tidb-lightning/deployment.md
This PR fixes several FAQ links caused by refactoring.
Related PR: https://github.com/pingcap/docs-cn/pull/1458
v3.0
> dev/reference: fix FAQ links

- .github/pull_request_template.md
This PR updates the list format of the PR template.
https://github.com/pingcap/docs/pull/1225
No.
> .github: update pr template list

- tidb-in-kubernetes/gcp-gke-tutorial.md
Related PR: https://github.com/pingcap/docs/pull/1236
Preview: https://github.com/DanielZhangQD/docs-cn/blob/gke-cn/tidb-in-kubernetes/gcp-gke-tutorial.md
> tidb-in-kubernetes: migrate gke terraform deployment doc to docs-cn repo

- tidb-in-kubernetes/aws-eks-tutorial.md
Preview: https://github.com/DanielZhangQD/docs-cn/blob/aws-cn/tidb-in-kubernetes/aws-eks-tutorial.md
Related PR: https://github.com/pingcap/docs/pull/1235
> tidb-in-kubernetes: migrate aws terraform deployment doc to docs-cn repo

- TOC.md
- dev/reference/performance/execution-plan-bind.md
- dev/reference/tools/syncer.md
Add document for execution plan bind.
> dev/reference: add document for execution plan bind

- tidb-in-kubernetes/maintain-node.md
> tidb-in-kubernates/maintain-node.md: remove '\t'

- dev/key-features.md
> dev: remove TiDB Binlog part from key-features

- tidb-in-kubernetes/expose-servics.md
https://github.com/cofyc/docs-cn/blob/expose-service/tidb-in-kubernetes/expose-servics.md
> tidb-in-kubernetes: expose services

- TOC.md
> TOC: remove redundant content in TOC

- dev/reference/sql/statements/split-region.md
To fix issues from https://github.com/pingcap/docs-cn/pull/1441
PTAL @CaitinChen
> dev/reference: fix format issues

- TOC.md
- dev/releases/2.1.13.md
- dev/releases/rn.md
> TOC, dev/releases: add TiDB 2.1.13 release notes

- TOC.md
- dev/releases/3.0.0-rc.3.md
- dev/releases/rn.md
Via: https://github.com/pingcap/docs/pull/1248
> TOC, dev/releases: add TiDB 3.0.0-rc.3 Release Notes

- tidb-in-kubernetes/google-kubernetes-tutorial.md
> tidb-in-kubernetes: migrate google trial doc to docs-cn repo

- tidb-in-kubernetes/local-dind-tutorial.md
> tidb-in-kubernetes: add local dind deployment doc

- tidb-in-kubernetes/minikube-tutorial.md
> tidb-in-kubernetes: add minikube deployment doc

- dev/how-to/get-started/local-cluster/install-from-kubernetes-dind.md
- dev/how-to/get-started/local-cluster/install-from-kubernetes-gke.md
Update the format of a code block that has bulleted list symbols in it. The list format will cause a display error at the PingCAP website, so this PR removes them.
https://github.com/pingcap/docs-cn/pull/1492
v3.0
> dev/how-to: update K8s doc format

- dev/_index.md
- dev/faq/tidb.md
- dev/how-to/get-started/local-cluster/install-from-kubernetes-gke.md
- dev/overview.md
- dev/reference/tispark.md
- v2.1/_index.md
- v2.1/faq/tidb.md
- v2.1/how-to/get-started/local-cluster/install-from-kubernetes-gke.md
- v2.1/overview.md
- v2.1/reference/tispark.md
- v3.0/_index.md
- v3.0/faq/tidb.md
- v3.0/how-to/get-started/local-cluster/install-from-kubernetes-gke.md
- v3.0/overview.md
- v3.0/reference/tispark.md
This PR fixes some links and format caused by the reorganization.
https://github.com/pingcap/docs-cn/pull/1496
> *: fix links and format related to reorganization

- _index.md
Fix deployment links in `_index.md`.
https://github.com/pingcap/docs-cn/pull/1500
> index: fix deployment links

- dev/reference/tools/data-migration/configure/overview.md
- v2.1/reference/tools/data-migration/configure/overview.md
- v3.0/reference/tools/data-migration/configure/overview.md
add source-id restriction in DM
ref: https://github.com/pingcap/dm/pull/164
> tools: add dm source-id restriction

- tidb-in-kubernetes/tidb-backup-configuration.md
Preview: https://github.com/aylei/docs-cn/blob/tidb-backup-config/tidb-in-kubernetes/tidb-backup-configuration.md
This documentation has a English version which is not properly organized, I'll commit that to pingcap/docs later, namely, this documentation do not need translation😜
@weekface @cofyc @lilin90 @dcalvin PTAL
> tidb-in-kubernetes: add tidb-backup configuration reference

- tidb-in-kubernetes/auto-failover.md
https://github.com/weekface/docs-cn/blob/auto-failover/tidb-in-kubernetes/auto-failover.md
> tidb-in-kubernetes: auto failover

- dev/how-to/troubleshoot/tidb-in-kubernetes.md
- tidb-in-kubernetes/recovery-after-accidental-deletion.md
Preview: https://github.com/weekface/docs-cn/blob/recovery-after-accidental-deletion/tidb-in-kubernetes/recovery-after-accidental-deletion.md
> tidb-in-kubernetes: recovery after accidental deletion

- tidb-in-kubernetes/tidb-operator-setup.md
- Related PR: https://github.com/pingcap/docs/pull/1240
- Preview: https://github.com/DanielZhangQD/docs-cn/blob/setup-cn/tidb-in-kubernetes/tidb-operator-setup.md
> tidb-in-kubernetes: migrate tidb operator setup guide

- dev/faq/tidb.md
- v3.0/faq/tidb.md
> v3.0, dev/faq: update sysbench link

- v2.1/faq/tidb.md
Fix 2 sysbench links
https://github.com/pingcap/docs-cn/pull/1499/
@jackysp PTAL I'm not sure what link is correct.
@lilin90 FYI.
> v2.1/faq: update v2.1 sysbench link

- .github/pull_request_template.md
Update PR template to make it clearer on versions.
N/A
> .github: update PR template description

- dev/benchmark/how-to-run-tpcc.md
- v3.0/benchmark/how-to-run-tpcc.md
> v3.0, dev/benchmark: add how to run tpcc

- dev/reference/security/role-based-access-control.md
Document of role-based access control system has some mistakes, This pr fixed them.
https://github.com/pingcap/docs-cn/pull/1362
dev/3.0
> dev: fix rbac doc mistake

- dev/reference/sql/functions-and-operators/window-functions.md
- v3.0/reference/sql/functions-and-operators/window-functions.md
Update window feature description
v3.0, dev
@lamxtyler @lilin90 PTAL
> dev, v3.0: update format

- dev/how-to/maintain/identify-slow-queries.md
- v2.1/how-to/maintain/identify-slow-queries.md
- v3.0/how-to/maintain/identify-slow-queries.md
This PR fixed a dead link for Identify Slow Query
TiDB 2.1/3.0/Dev
> */maintain: fix dead link in slow query

- dev/reference/sql/functions-and-operators/window-functions.md
- v3.0/reference/sql/functions-and-operators/window-functions.md
Clarify the MySQL version.
https://github.com/pingcap/docs/pull/1274
dev, v3.0
@lamxtyler PTAL
> dev, v3.0: clarify the MySQL version

- dev/reference/sql/statements/create-table-like.md
- dev/reference/sql/statements/create-table.md
- v2.1/reference/sql/statements/create-table-like.md
- v2.1/reference/sql/statements/create-table.md
- v3.0/reference/sql/statements/create-table-like.md
- v3.0/reference/sql/statements/create-table.md
fix an inconsistent word usage
> dev, v3.0, v2.1: fix inconsistent word usage

- dev/TOC.md
- v2.1/TOC.md
- v3.0/TOC.md
- Update inappropriate description in TOC
- Remove SQL diagrams link because they already exist in another directory
No.
> dev, v3.0, v2.1: remove inappropriate description in TOC

- dev/reference/security/role-based-access-control.md
- v3.0/reference/security/role-based-access-control.md
Update wording
https://github.com/pingcap/docs/pull/1270
dev, v3.0
@imtbkcat PTAL
> dev, v3.0: update wording

- dev/reference/sql/statements/split-region.md
- v3.0/reference/sql/statements/split-region.md
fix split region doc
https://github.com/pingcap/docs-cn/pull/1441
> dev: fix split region doc problem

- dev/releases/3.0-ga.md
- v3.0/releases/3.0-ga.md
Update description in 3.0 GA release notes.
dev, v3.0
> dev, v3.0: update 3.0 GA release notes

- v2.1/TOC.md
- v2.1/releases/3.0-ga.md
- v2.1/releases/rn.md
Forgot to add the 3.0 RN to the 2.1 manual. This PR updated it.
https://github.com/pingcap/docs/pull/1290
2.1 (other versions already handled)
> v2.1/releases: add 3.0 GA release notes

- _index.md
Fix 4 broken links.
Just _index.md
@dcalvin @lilin90 PTAL
> index: fix 4 links

- dev/faq/tidb.md
- v2.1/faq/tidb.md
- v3.0/faq/tidb.md
Update the sysbench test report link.
https://github.com/pingcap/docs/pull/1285
@lilin90 @jackysp PTAL
> dev, v2.1, v3.0: update sysbench link

- dev/_index.md
- dev/faq/tidb.md
- dev/how-to/deploy/hardware-recommendations.md
- dev/how-to/deploy/orchestrated/ansible.md
- dev/overview.md
- v3.0/_index.md
- v3.0/faq/tidb.md
- v3.0/how-to/deploy/hardware-recommendations.md
- v3.0/how-to/deploy/orchestrated/ansible.md
- v3.0/overview.md
Update links as a follow-up step of K8s related document changes.
#1542 
dev, v3.0
> dev, v3.0: update docker compose links

- dev/how-to/migrate/incrementally-from-mysql.md
- v2.1/how-to/migrate/incrementally-from-mysql.md
- v3.0/how-to/migrate/incrementally-from-mysql.md
> dev, v3.0, v2.1: update the Syncer link

- dev/how-to/deploy/tidb-operator.md
- dev/how-to/get-started/deploy-tidb-from-kubernetes-gke.md
- dev/how-to/get-started/deploy-tidb-from-kubernetes-minikube.md
- v3.0/how-to/deploy/tidb-operator.md
- v3.0/how-to/get-started/deploy-tidb-from-kubernetes-gke.md
- v3.0/how-to/get-started/deploy-tidb-from-kubernetes-minikube.md
Update links related to TiDB in K8s document changes
https://github.com/pingcap/docs-cn/pull/1542
dev, v3.0
> dev, v3.0: update K8s related doc links

- dev/TOC.md
- dev/faq/data-migration.md
- v3.0/TOC.md
- v3.0/faq/data-migration.md
add a simple FAQ page for DM, including:
- how to handle `invalid connection`
- how to handle `driver: bad connection`
> tools: add a simple FAQ for DM to cover `invalid connection` and `driver: bad connection`

- dev/how-to/maintain/tidb-in-kubernetes/tidb-cluster.md
- v3.0/how-to/maintain/tidb-in-kubernetes/tidb-cluster.md
remove broken links
https://github.com/pingcap/docs-cn/pull/1542 
PTAL @lilin90 
dev, v3.0
> dev, v3.0: remove broken links

- dev/reference/sql/partitioning.md
- v3.0/reference/sql/partitioning.md
1. fix typos and format
2. update code blocks
To align with: https://github.com/pingcap/docs/pull/1300
PTAL @CaitinChen 
dev, v3.0
> dev, v3.0: fix typos and format, and update code blocks

- dev/reference/mysql-compatibility.md
- v3.0/reference/mysql-compatibility.md
Update the descriptions of compability.
dev and v3.0
> reference: update the descriptions of compability in v3.0.0

- dev/faq/tidb.md
- v2.1/faq/tidb.md
- v3.0/faq/tidb.md
Seems that there's a mistyped `q`, so delete it.
https://pingcap.com/docs-cn/v3.0/faq/tidb/
v3.0
> remove redundant character

- dev/how-to/migrate/overview.md
- v2.1/how-to/migrate/overview.md
- v3.0/how-to/migrate/overview.md
Fix migration links related to refactoring.
N/A
> dev, v3.0, v2.1: fix migration links

- dev/how-to/migrate/overview.md
- v2.1/how-to/migrate/overview.md
- v3.0/how-to/migrate/overview.md
Related PR: https://github.com/pingcap/docs-cn/pull/1563
> dev, v3.0, v2.1: fix DM and Lightning links

- dev/how-to/maintain/tidb-in-kubernetes/tidb-node.md
- v3.0/how-to/maintain/tidb-in-kubernetes/tidb-node.md
Fix broken links
@lilin90 PTAL
> dev, v3.0: fix broken links

- README.md
- _index.md
- dev/_index.md
- dev/how-to/get-started/deploy-tidb-from-docker-compose.md
- dev/how-to/get-started/explore-sql.md
- dev/overview.md
- dev/tispark/tispark-quick-start-guide_v1.x.md
- v2.1-legacy/op-guide/docker-compose.md
- v2.1-legacy/overview.md
- v2.1-legacy/sql/aggregate-group-by-functions.md
- v2.1-legacy/sql/character-set-configuration.md
- v2.1-legacy/sql/dml.md
- v2.1-legacy/tispark/tispark-quick-start-guide.md
- v2.1/_index.md
- v2.1/how-to/get-started/explore-sql.md
- v2.1/how-to/get-started/local-cluster/install-from-docker-compose.md
- v2.1/overview.md
- v2.1/tispark/tispark-quick-start-guide_v1.x.md
- v3.0/_index.md
- v3.0/how-to/get-started/deploy-tidb-from-docker-compose.md
- v3.0/how-to/get-started/explore-sql.md
- v3.0/overview.md
- v3.0/tispark/tispark-quick-start-guide_v1.x.md
Fix broken links.
@lilin90 PTAL
> dev, v2.1, v3.0: fix broken links

- dev/how-to/maintain/tidb-in-kubernetes/tidb-cluster.md
- v3.0/how-to/maintain/tidb-in-kubernetes/tidb-cluster.md
https://github.com/DanielZhangQD/docs-cn/blob/force-upgrade/dev/how-to/maintain/tidb-in-kubernetes/tidb-cluster.md
https://github.com/DanielZhangQD/docs-cn/blob/force-upgrade/v3.0/how-to/maintain/tidb-in-kubernetes/tidb-cluster.md
> tidb-in-kubernetes: add force upgrade feature usage

- dev/faq/tidb-in-kubernetes.md
Fix the lint errors found in master branch
`dev`
> dev/faq: fix lint in tidb-in-kubernetes FAQ

- dev/TOC.md
- v3.0/TOC.md
Remove useless prefix in a relative path
The current relative path cause page not found
dev and v3.0
> dev, v3.0: update relative path in TOC.md

- dev/how-to/monitor/monitor-a-cluster.md
- v3.0/how-to/monitor/monitor-a-cluster.md
> dev, v3.0: fix a dead link

- dev/reference/configuration/tidb-server/server-command-option.md
- v1.0/sql/server-command-option.md
- v2.0/sql/server-command-option.md
- v2.1-legacy/sql/server-command-option.md
- v2.1/reference/configuration/tidb-server/server-command-option.md
- v3.0/reference/configuration/tidb-server/server-command-option.md
fix a typo and resolve lint issues
to close https://github.com/pingcap/docs-cn/pull/1380/
all versions
> all versions: fix typo and resolve lint issues

- dev/how-to/deploy/tidb-operator.md
- v3.0/how-to/deploy/tidb-operator.md
Fix the K8s setup link
dev, v3.0
@lilin90 PTAL
> dev, v3.0: fix the K8s setup link

- dev/reference/transactions/transaction-model.md
- v2.1/reference/transactions/transaction-model.md
- v3.0/reference/transactions/transaction-model.md
修改了事务模型相关描述
https://github.com/pingcap/docs-cn/issues/1615
修改涉及的路径：
参考手册-事务-事务模型
https://pingcap.com/docs-cn/dev/reference/transactions/transaction-model/
涉及到的版本：dev/2.1/3.0
> v2.1, v3.0, dev: remove redundant description about transaction model file

- dev/TOC.md
- dev/how-to/monitor/tidb-in-kubernetes.md
- v3.0/TOC.md
- v3.0/how-to/monitor/tidb-in-kubernetes.md
- Add two new TiDB in K8s files to TOC.md
- Update one title
#1552 
dev, v3.0
> dev, v3.0: add log collection and monitoring docs to toc

- dev/TOC.md
- v2.1/TOC.md
- v3.0/TOC.md
Remove a relative path of a folder in TOC.md of dev/v3.0/v2.1
> dev/v3.0/v2.1: remove relative path in a folder

- v2.1/reference/mysql-compatibility.md
Remove duplicate alter table description
N/A
v2.1
> v2.1/reference: remove duplicate alter table description

- dev/TOC.md
- dev/reference/sql/statements/create-database.md
- v2.1/TOC.md
- v2.1/reference/sql/statements/create-database.md
- v3.0/TOC.md
- v3.0/reference/sql/statements/create-database.md
1. fix dead links in https://github.com/pingcap/docs-cn/pull/1535
2. fix pdf generation issues
> dev, v3.0, v2.1: fix dead links and pdf generation issues

- .circleci/config.yml
circleci/config.yml: remove branch filters in job 'build' to generate PDFs
dev, v3.0 and v2.0
> add job build to workflow

- dev/reference/garbage-collection/configuration.md
- v3.0/reference/garbage-collection/configuration.md
* Add the example of `mysql.tidb`'s content back to make it easier for reader to understand how the configurations are represented.
* Use `tikv_gc_life_time` as the example of updating configurations, which is more frequently used.
dev, v3.0
> dev, 3.0: Refine document of GC

- dev/TOC.md
- dev/releases/3.0.1.md
- dev/releases/rn.md
- v3.0/TOC.md
- v3.0/releases/3.0.1.md
- v3.0/releases/rn.md
add TiDB 3.0.1 release notes
https://github.com/pingcap/docs/pull/1346
dev, v3.0
> dev, v3.0: add TiDB 3.0.1 release notes

- dev/how-to/deploy/orchestrated/tidb-in-kubernetes/alibaba-cloud.md
- v3.0/how-to/deploy/orchestrated/tidb-in-kubernetes/alibaba-cloud.md
update alibaba cloud deployment document
https://github.com/pingcap/tidb-operator/pull/658
`dev`, `3.0`
> dev,3.0:update alibaba cloud deployment document

- dev/how-to/deploy/orchestrated/tidb-in-kubernetes/alibaba-cloud.md
- v3.0/how-to/deploy/orchestrated/tidb-in-kubernetes/alibaba-cloud.md
Update the brackets of shortcode in file `alibaba-cloud.md`
Related PR #1630
dev and v3.0
> how-to/deploy: fix shortcode brackets

- dev/support-resources.md
- v2.1/support-resources.md
- v3.0/support-resources.md
This PR updated wording in Support Resouces page.   
TiDB Dev/2.1/3.0
> */support-resources: update wording in support

- dev/how-to/get-started/deploy-tidb-from-kubernetes-gke.md
- v3.0/how-to/get-started/deploy-tidb-from-kubernetes-gke.md
Fix file suffix typo in gke tutorial
> dev,3.0: fix file suffix for gke tutorial

- dev/TOC.md
- v2.1/TOC.md
- v3.0/TOC.md
add benchmark docs to the website
> dev, v3.0, v2.1: add benchmark docs to the website

- dev/how-to/get-started/read-historical-data.md
- v3.0/how-to/get-started/read-historical-data.md
Update two links in `read-historical-data`
dev, v3.0
> update two links

- v3.0/how-to/deploy/orchestrated/ansible.md
> Fix attention content about deploy of ansible.

- dev/reference/tools/tidb-lightning/deployment.md
- v2.1/reference/tools/tidb-lightning/deployment.md
- v3.0/reference/tools/tidb-lightning/deployment.md
Update table indentation in file `/reference/tools/tidb-lightning/deployment/` 
dev, v3.0 and v2.0
> update table indentation

- dev/how-to/deploy/tidb-in-kubernetes-prerequisites.md
- v3.0/how-to/deploy/tidb-in-kubernetes-prerequisites.md
fix typos and improve wording and format
https://github.com/pingcap/docs/pull/1366
dev, v3.0
> dev, v3.0: fix typos and improve wording

- dev/reference/configuration/tidb-in-kubernetes/cluster-configuration.md
- v3.0/reference/configuration/tidb-in-kubernetes/cluster-configuration.md
This PR adds a missing period.
v3.0, dev
> v3.0, dev/reference/configuration: fix a typo

- dev/TOC.md
- dev/how-to/maintain/tidb-in-kubernetes/backup-and-restore.md
- v3.0/TOC.md
- v3.0/how-to/maintain/tidb-in-kubernetes/backup-and-restore.md
Add backup and restore documentation.
EN: https://github.com/pingcap/docs/pull/1368
`3.0`,`dev`
> dev, 3.0: Add backup and restore documentation

- dev/reference/configuration/tidb-in-kubernetes/local-pv-configuration.md
Add best practices for local PV configuration
https://github.com/cofyc/docs-cn/blob/cloud-560/dev/reference/configuration/tidb-in-kubernetes/local-pv-configuration.md
> Add data security and best practices sections for local PV configuration

- v3.0/reference/configuration/tidb-in-kubernetes/local-pv-configuration.md
The change in #1646 affects v3.0 too.
https://github.com/pingcap/docs-cn/pull/1646
3.0
> v3.0/reference/configuration: sync local pv dev doc to v3.0

- dev/how-to/deploy/orchestrated/tidb-in-kubernetes/alibaba-cloud.md
- v3.0/how-to/deploy/orchestrated/tidb-in-kubernetes/alibaba-cloud.md
Fix errors in alibaba cloud deployment doc
`3.0`,`dev`
> dev, 3.0: Fix errors in alibaba cloud deployment doc

- dev/faq/tidb-in-kubernetes.md
- dev/reference/configuration/tidb-in-kubernetes/cluster-configuration.md
- v3.0/faq/tidb-in-kubernetes.md
- v3.0/reference/configuration/tidb-in-kubernetes/cluster-configuration.md
add way how to view tidb configuration file in kubernetes.
> faq: add way how to view tidb configuration file in kubernetes

- dev/TOC.md
- dev/how-to/deploy/orchestrated/tidb-in-kubernetes/general-kubernetes.md
- dev/how-to/deploy/tidb-operator.md
- dev/reference/tools/tools-in-kubernetes.md
- v3.0/TOC.md
- v3.0/how-to/deploy/orchestrated/tidb-in-kubernetes/general-kubernetes.md
- v3.0/how-to/deploy/tidb-operator.md
- v3.0/reference/tools/tools-in-kubernetes.md
Add cloud related tools documentation
@DanielZhangQD @xiaojingchen @lilin90 @tennix PTAL
> 3.0,dev: Add cloud related tools documentation

- dev/TOC.md
- dev/faq/tidb-in-kubernetes.md
- dev/how-to/configure/initialize-cluster.md
- dev/how-to/deploy/tidb-in-kubernetes/tidb-operator.md
- dev/how-to/get-started/deploy-tidb-from-kubernetes-dind.md
- dev/how-to/get-started/deploy-tidb-from-kubernetes-gke.md
- dev/how-to/get-started/deploy-tidb-from-kubernetes-minikube.md
- dev/how-to/scale/tidb-in-kubernetes.md
- dev/how-to/troubleshoot/tidb-in-kubernetes.md
- dev/how-to/upgrade/tidb-in-kubernetes.md
- dev/reference/tidb-operator-overview.md
- dev/reference/tools/tools-in-kubernetes.md
- v3.0/TOC.md
- v3.0/faq/tidb-in-kubernetes.md
- v3.0/how-to/configure/initialize-cluster.md
- v3.0/how-to/deploy/tidb-in-kubernetes/tidb-operator.md
- v3.0/how-to/get-started/deploy-tidb-from-kubernetes-dind.md
- v3.0/how-to/get-started/deploy-tidb-from-kubernetes-gke.md
- v3.0/how-to/get-started/deploy-tidb-from-kubernetes-minikube.md
- v3.0/how-to/scale/tidb-in-kubernetes.md
- v3.0/how-to/troubleshoot/tidb-in-kubernetes.md
- v3.0/how-to/upgrade/tidb-in-kubernetes.md
- v3.0/reference/tidb-operator-overview.md
- v3.0/reference/tools/tools-in-kubernetes.md
Fix dead link, coordinate helm link, replace hard-coded chart version
`dev` `3.0`
> dev, 3.0: Fix dead link, coordinate helm link, replace hard-coded chart version

- dev/how-to/maintain/tidb-in-kubernetes/backup-and-restore.md
- v3.0/how-to/maintain/tidb-in-kubernetes/backup-and-restore.md
> maintain: fix dead links

- dev/how-to/troubleshoot/tidb-in-kubernetes.md
- dev/reference/tidb-operator-overview.md
- v3.0/how-to/troubleshoot/tidb-in-kubernetes.md
- v3.0/reference/tidb-operator-overview.md
Update links and format for TiDB in K8s documents
N/A
dev, v3.0
> dev, v3.0: update TiDB in K8s related format and links

- dev/TOC.md
- dev/how-to/deploy/orchestrated/docker.md
- dev/how-to/deploy/tidb-in-kubernetes/gcp-gke.md
- dev/how-to/get-started/deploy-tidb-from-docker-compose.md
- dev/how-to/get-started/deploy-tidb-from-kubernetes-dind.md
- dev/how-to/get-started/deploy-tidb-from-kubernetes-gke.md
- dev/how-to/get-started/deploy-tidb-from-kubernetes-minikube.md
- dev/overview.md
- v2.1/overview.md
- v3.0/TOC.md
- v3.0/how-to/deploy/orchestrated/docker.md
- v3.0/how-to/deploy/tidb-in-kubernetes/gcp-gke.md
- v3.0/how-to/get-started/deploy-tidb-from-docker-compose.md
- v3.0/how-to/get-started/deploy-tidb-from-kubernetes-dind.md
- v3.0/how-to/get-started/deploy-tidb-from-kubernetes-gke.md
- v3.0/how-to/get-started/deploy-tidb-from-kubernetes-minikube.md
- v3.0/overview.md
add warning messages
Related PR: https://github.com/pingcap/docs/pull/1396
> deploy: add warning messages

- v3.0/releases/3.0.1.md
Add release note
This feature is included in 3.0.1 but not reflect in the release note
https://github.com/pingcap/tidb/pull/11026
https://github.com/pingcap/docs/pull/1349
3.0.1
> v3.0/releases: update the 3.0.1 release-note

- dev/releases/3.0.1.md
- v2.1/releases/3.0.1.md
Add one new item to 3.0.1 release notes
https://github.com/pingcap/docs-cn/pull/1640
dev, v2.1
> dev, v2.1/releases: add one new item to 3.0.1 release notes

- dev/how-to/deploy/tidb-in-kubernetes/aws-eks.md
- dev/reference/tools/tools-in-kubernetes.md
- v3.0/how-to/deploy/tidb-in-kubernetes/aws-eks.md
- v3.0/reference/tools/tools-in-kubernetes.md
Update TiDB operator version info to v1.0.0 after 1.0 GA release
https://github.com/pingcap/docs/pull/1395
@lilin90
> dev, v3.0: update TiDB operator version info to v1.0.0

- dev/reference/tidb-operator-overview.md
- v3.0/reference/tidb-operator-overview.md
Change link name and order according to content
`dev` `3.0`
> dev,3.0: Change link name and order according to content

- dev/how-to/upgrade/from-previous-version.md
- v3.0/how-to/upgrade/from-previous-version.md
docs-cn/v3.0/how-to/upgrade/from-previous-version.md
v3.0.0
> how-to/upgrade: Fix upgrade of v3.0.0 some errors attention.

- dev/how-to/deploy/tidb-in-kubernetes/aws-eks.md
- dev/how-to/deploy/tidb-in-kubernetes/general-kubernetes.md
- dev/overview.md
- v3.0/how-to/deploy/tidb-in-kubernetes/aws-eks.md
- v3.0/how-to/deploy/tidb-in-kubernetes/general-kubernetes.md
- v3.0/overview.md
This PR fixes a broken link to the `tidb-operator.md` document.
N/A
`v3.0`, `dev`
> dev, v3.0/how-to/deploy, */overview: fix a broken link 

- dev/how-to/get-started/deploy-tidb-from-kubernetes-gke.md
- dev/overview.md
- v3.0/how-to/get-started/deploy-tidb-from-kubernetes-gke.md
- v3.0/overview.md
This PR fixes a broken link to the `gcp-gke.md` document.
N/A
`dev`, `v3.0`
> v3.0, dev/how-to/get-started, */overvew: fix a broken link

- dev/overview.md
- v3.0/overview.md
This PR fixes two broken links in the `overvew.md`.
N/A
`v.3.0` `dev`
> v3.0, dev/overview: fix two broken links

- dev/tidb-in-kubernetes/deploy/aws-eks.md
- dev/tidb-in-kubernetes/deploy/gcp-gke.md
- dev/tidb-in-kubernetes/deploy/prerequisites.md
- dev/tidb-in-kubernetes/deploy/tidb-operator.md
- dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-dind.md
- dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md
- dev/tidb-in-kubernetes/reference/tools/in-kubernetes.md
- dev/tidb-in-kubernetes/tidb-operator-overview.md
- v3.0/tidb-in-kubernetes/deploy/aws-eks.md
- v3.0/tidb-in-kubernetes/deploy/gcp-gke.md
- v3.0/tidb-in-kubernetes/deploy/prerequisites.md
- v3.0/tidb-in-kubernetes/deploy/tidb-operator.md
- v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-dind.md
- v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md
- v3.0/tidb-in-kubernetes/reference/tools/in-kubernetes.md
- v3.0/tidb-in-kubernetes/tidb-operator-overview.md
- Update TiDB in K8s documentation links related to the reorganization
- Update format
#1695 
dev, v3.0
> dev, v3.0: update TiDB in K8s links and format

- dev/tidb-in-kubernetes/deploy/gcp-gke.md
- dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md
- dev/tidb-in-kubernetes/tidb-operator-overview.md
- v3.0/tidb-in-kubernetes/deploy/gcp-gke.md
- v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md
- v3.0/tidb-in-kubernetes/tidb-operator-overview.md
This PR fixed a wrong link.
TiDB Dev/3.0
> tidb-in-kubernetes: fixed a wrong link

- dev/reference/tools/data-migration/dm-portal.md
- v2.1/reference/tools/data-migration/dm-portal.md
- v3.0/reference/tools/data-migration/dm-portal.md
Fix the an order issue in DM Portal doc
https://github.com/pingcap/docs-cn/pull/1679. 
> dev/reference, v3.0/reference, v2.1/reference: fix the dm-portal order issue

- .circleci/config.yml
- dev/architecture.md
- dev/faq/tidb.md
- dev/how-to/deploy/orchestrated/ansible.md
- dev/overview.md
- dev/reference/garbage-collection/configuration.md
- dev/reference/sql/statements/load-data.md
- dev/reference/sql/statements/recover-table.md
- dev/tidb-in-kubernetes/deploy/tidb-operator.md
- dev/tidb-in-kubernetes/maintain/kubernetes-node.md
- scripts/markdown-link-check.tpl
- scripts/verify-links.sh
- v3.0/TOC.md
- v3.0/faq/tidb.md
- v3.0/how-to/deploy/orchestrated/ansible.md
- v3.0/overview.md
- v3.0/reference/garbage-collection/configuration.md
- v3.0/reference/sql/statements/load-data.md
- v3.0/reference/tidb-operator-overview.md
- v3.0/tidb-in-kubernetes/deploy/tidb-operator.md
- v3.0/tidb-in-kubernetes/maintain/kubernetes-node.md
Add a script to verify internal links and fix some broken links under dev and v3.0 directories.
Why: Avoid broken links in CI phrase.
dev
v3.0
> scripts: add verify links check and fix some broken links

- v2.1/TOC.md
- v3.0/TOC.md
Update the Docker Compose link
v3.0, v2.1
@lilin90 PTAL @YiniXu9506 FYI.
> v3.0, v2.1: update the Docker Compose link

- dev/reference/tools/data-migration/dm-portal.md
- v2.1/reference/tools/data-migration/dm-portal.md
- v3.0/reference/tools/data-migration/dm-portal.md
Update the download links of DM Portal. 
https://github.com/pingcap/docs-cn/pull/1705 
> dev/reference, v3.0/reference, v2/1/reference: update dm-portal download links

- dev/reference/key-monitoring-metrics/tidb-dashboard.md
- v3.0/reference/key-monitoring-metrics/tidb-dashboard.md
Signed-off-by: Lonng <heng@lonng.org>
Update the TiDB metrics docs.
> reference: update the TiDB metrics docs

- dev/how-to/maintain/tidb-binlog.md
add a tip for binlogctl
dev, v3.0 and v2.1
- [] Add a new file to `TOC.md`
- [ x] No Tab spaces anywhere 
- [ x] Leave a blank line both before and after a code block
- [x ] Keep the first level heading consistent with `title` in metadata
- [ x] Use *four* spaces for each level of indentation except that in `TOC.md`
> tools: add  a tip for binlogctl's usage

- scripts/verify-links.sh
Enable the colorful output always.
> scripts: enable colorful output always

- v2.1/how-to/maintain/tidb-binlog.md
- v3.0/how-to/maintain/tidb-binlog.md
add a tip for binlogctl for v2.1 and v3
#1663 
dev, v3.0 and v2.1
> tools: add binlogctl tip for v2.1 and v3

- dev/TOC.md
- dev/releases/3.0.2.md
- dev/releases/rn.md
- v3.0/TOC.md
- v3.0/releases/3.0.2.md
- v3.0/releases/rn.md
Add TiDB 3.0.2 Release Notes
https://github.com/pingcap/docs/pull/1423
dev, v3.0
> dev, v3.0: add TiDB 3.0.2 Release Notes

- dev/releases/3.0.2.md
- v3.0/releases/3.0.2.md
Add a space
dev, v3.0: add a space
> dev, v3.0: add a space

- v3.0/reference/tispark.md
Signed-off-by: wangjun <277372664@qq.com>
add tispark faq
> update tispark faq

- dev/reference/key-monitoring-metrics/overview-dashboard.md
- v2.1-legacy/op-guide/dashboard-overview-info.md
- v2.1/reference/key-monitoring-metrics/overview-dashboard.md
- v3.0/reference/key-monitoring-metrics/overview-dashboard.md
Signed-off-by: Lonng <heng@lonng.org>
Update  the PD metrics documents.
> metrics: correct the LowSpace Stores docs

- dev/reference/sql/functions-and-operators/bit-functions-and-operators.md
- dev/reference/sql/functions-and-operators/cast-functions-and-operators.md
- dev/reference/sql/functions-and-operators/control-flow-functions.md
- dev/reference/sql/functions-and-operators/date-and-time-functions.md
- dev/reference/sql/functions-and-operators/encryption-and-compression-functions.md
- dev/reference/sql/functions-and-operators/information-functions.md
- dev/reference/sql/functions-and-operators/miscellaneous-functions.md
- dev/reference/sql/functions-and-operators/numeric-functions-and-operators.md
- dev/reference/sql/functions-and-operators/string-functions.md
- v3.0/reference/sql/functions-and-operators/bit-functions-and-operators.md
- v3.0/reference/sql/functions-and-operators/cast-functions-and-operators.md
- v3.0/reference/sql/functions-and-operators/control-flow-functions.md
- v3.0/reference/sql/functions-and-operators/date-and-time-functions.md
- v3.0/reference/sql/functions-and-operators/encryption-and-compression-functions.md
- v3.0/reference/sql/functions-and-operators/information-functions.md
- v3.0/reference/sql/functions-and-operators/miscellaneous-functions.md
- v3.0/reference/sql/functions-and-operators/numeric-functions-and-operators.md
- v3.0/reference/sql/functions-and-operators/string-functions.md
update functions and operators in 9 files
https://github.com/pingcap/docs/pull/1262/
dev, v3.0
> reference/sql: update functions and operators

- dev/reference/sql/statements/recover-table.md
- v3.0/reference/sql/statements/recover-table.md
This PR updated some wording for clarity and consistency.
TiDB V3.0/Dev
> reference*/recover-table: update wording

- dev/reference/tools/tidb-binlog/tidb-binlog-local.md
- v2.1/reference/tools/tidb-binlog/tidb-binlog-local.md
- v3.0/reference/tools/tidb-binlog/tidb-binlog-local.md
This PR modifies the link of the dashboard configuration file.
> dev/reference/tools: modify the link of dashboard config file

- dev/tidb-in-kubernetes/deploy/aws-eks.md
- v3.0/tidb-in-kubernetes/deploy/aws-eks.md
- Update bastion username EKS deploy document to avoid ssh failure
https://github.com/pingcap/docs/pull/1426
dev, v3.0
> dev/3.0: Update bastion username EKS deploy document to avoid ssh failure

- .github/pull_request_template.md
- Make version description a required item
- Remove the unnecessary checklist because most items have been covered in the markdownlint check
https://github.com/pingcap/docs/pull/1461
N/A
> .github: refine the pr template

- dev/tidb-in-kubernetes/monitor/tidb-in-kubernetes.md
- dev/tidb-in-kubernetes/reference/tools/in-kubernetes.md
- v3.0/tidb-in-kubernetes/reference/tools/in-kubernetes.md
Run port-forward in background to not blocking users
`dev` `3.0`
> dev,3.0: run port-forward in background to not blocking users

- scripts/verify-links.sh
- v2.1/faq/tidb.md
- v2.1/how-to/deploy/orchestrated/ansible.md
- v2.1/reference/sql/statements/drop-table.md
- v2.1/reference/sql/statements/load-data.md
Enable link check for v2.1 directory and fix some broken links.
https://github.com/pingcap/docs/pull/1459
> scripts: enable link check for v2.1

- dev/contribute.md
- v2.1/contribute.md
- v3.0/contribute.md
- Update `CONTRIBUTING.md` url because it is outdated in repo `community`
https://github.com/pingcap/docs/pull/1196
> dev/v2.1/v3.0: update CONTRIBUTING.md url

- scripts/check_requirement.sh
- Append a command `export PATH=...` to profile settings: 
to let the developers know that they need to update env variables if they don't have Rust or Go installed before
https://github.com/pingcap/docs/pull/1194
> scripts: append go/bin to $PATH

- dev/reference/tools/tidb-lightning/deployment.md
- v3.0/reference/tools/tidb-lightning/deployment.md
Update Lightning config to latest.
Update Lightning configure file to latest version.
v3.0
> dev, v3.0/reference/tools: update TiDB Lightning deployment document

- dev/reference/system-databases/information-schema.md
- v2.1/reference/system-databases/information-schema.md
- v3.0/reference/system-databases/information-schema.md
The schema of the current slow-query table is outdated, this PR updates it.
v3.0
> reference: update the schema information of slow-query table

- scripts/verify-links.sh
verify-links.sh takes [4~5 minutes](https://circleci.com/gh/pingcap/docs-cn/6815), try to speed it up.
NONE
> scripts: speed up verify links

- CONTRIBUTING.md
Add PR filing process to `CONTRIBUTING.md`
N/A
N/A
> contributing: add PR filing process

- dev/tidb-in-kubernetes/deploy/tidb-operator.md
- v3.0/tidb-in-kubernetes/deploy/tidb-operator.md
This PR adds the missing image name for custom kube-scheduler image.
*Note:* This only affects Chinese document.
> dev,v3.0/tidb-in-kubernetes/deploy: fix kube-scheduler image

- dev/releases/21rc5.md
- v2.1/releases/21rc5.md
- v3.0/releases/2.1.2.md
- v3.0/releases/21rc5.md
> dev, v2.1, v3.0: fix 4 broken links

- dev/reference/configuration/tidb-server/tidb-specific-variables.md
- v2.1-legacy/sql/tidb-specific.md
- v2.1/reference/configuration/tidb-server/tidb-specific-variables.md
- v3.0/reference/configuration/tidb-server/tidb-specific-variables.md
1. correct the scope of a tidb_opt_insubquery_unfold for release-2.1
2. remove tidb_opt_insubquery_unfold since master and 3.0 do not support it
N/A
dev, v3.0, v2.1, v2.1-legacy
> correct the scope of a tidb_opt_insubquery_unfold

- dev/reference/configuration/tidb-server/mysql-variables.md
- dev/reference/performance/optimizer-hints.md
- v2.1/reference/configuration/tidb-server/mysql-variables.md
- v2.1/reference/performance/optimizer-hints.md
- v3.0/reference/configuration/tidb-server/mysql-variables.md
- v3.0/reference/performance/optimizer-hints.md
Tiny update the document.
https://github.com/pingcap/docs/pull/1430
> dev/reference: add some description about max_execution_time

- dev/tidb-in-kubernetes/reference/configuration/storage-class.md
- v3.0/tidb-in-kubernetes/reference/configuration/storage-class.md
Add `aliases` for the previous local PV file to support redirection and avoid 404
#1770 
dev, v3.0
> tidb-in-kubernetes: add aliases about local PV

- dev/how-to/maintain/backup-and-restore.md
- v2.1/how-to/maintain/backup-and-restore.md
- v3.0/how-to/maintain/backup-and-restore.md
- Fix the description of backup and restore document
- Add a comma at the end of an SQL statement
https://github.com/pingcap/docs/pull/1416
https://github.com/pingcap/docs/pull/1443
> how-to/maintain: fix backup and restore description

- dev/TOC.md
- dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-gke.md
- v2.1/TOC.md
- v3.0/TOC.md
- v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-gke.md
- Update TOC structure by moving Tools upward
- Remove unnecessary 3.0 releases from `v2.1`
https://github.com/pingcap/docs/pull/1473
> *: update toc and link format

- dev/how-to/upgrade/from-previous-version.md
- v2.1/how-to/upgrade/from-previous-version.md
- v3.0/how-to/upgrade/from-previous-version.md
This PR adds aliases in the TiDB 3.0 upgrade guide.
`N/A`
`dev`, `v3.0`, `v2.1`
> how-to/upgrade: add aliases in TiDB 3.0 upgrade guide

- dev/tidb-in-kubernetes/deploy/prerequisites.md
- v3.0/tidb-in-kubernetes/deploy/prerequisites.md
Add config for net.ipv4.conf.all.rp_filter
https://github.com/pingcap/docs/pull/1480
dev, v3.0
> tidb-in-kubernetes: add config for rp_filter

- v2.1/reference/mysql-compatibility.md
- v3.0/faq/tidb.md
Update doc and add faq for ddl.
No PR.
V2.1, V3.0
> ddl: update ddl doc

- dev/benchmark/sysbench.md
- v1.0/benchmark/sysbench.md
- v2.0/benchmark/sysbench.md
- v2.1-legacy/benchmark/sysbench.md
- v2.1/benchmark/sysbench.md
- v3.0/benchmark/sysbench.md
Update insecure links in `sysbench.md` to relative image links.
N/A
dev, v3.0, v2.1, v2.1-legacy, v2.0, v1.0
> benchmark: fix inappropriate sysbench links

- v1.0/FAQ.md
- v2.0/FAQ.md
Remove useless `www` from PingCAP URLs
N/A
v1.0, v2.0
> faq: remove extra www characters from links

- scripts/verify-links.sh
> scripts: quite mode by default

- dev/reference/transactions/transaction-pessimistic.md
The `transaction-pessimistic.md` is changed.
https://github.com/pingcap/tidb/pull/12041
master
> reference/transactions: update pessimistic doc

- dev/how-to/maintain/tidb-binlog.md
- v2.1/how-to/maintain/tidb-binlog.md
- v3.0/how-to/maintain/tidb-binlog.md
Remove extra punctuation from code
N/A
> how-to: remove extra punctuation from code

- dev/reference/tools/data-migration/dm-upgrade.md
- v2.1/reference/tools/data-migration/dm-upgrade.md
- v3.0/reference/tools/data-migration/dm-upgrade.md
DM 1.0 GA released today. Update the DM upgrade doc to introduce how to upgrade to DA 1.0 GA version and the limitation. 
dev/v3.0/v2.1
Will commit to v3.0 and v2.1 when dev part review pass.
> dev/how-to: Add DM 1.0 GA upgrade 

- dev/releases/2.1.2.md
> dev/releases: fix 1 broken link

- dev/reference/sql/statements/show-variables.md
- v2.1/reference/sql/statements/show-variables.md
- v3.0/reference/sql/statements/show-variables.md
Update the result of `show global variables like 'tidb%'`.
v2.1, v3.0 and dev
> reference/sql: update show-variables example

- dev/how-to/migrate/overview.md
- dev/how-to/troubleshoot/tidb-lightning.md
- v2.1/how-to/migrate/overview.md
- v2.1/how-to/troubleshoot/tidb-lightning.md
- v3.0/how-to/migrate/overview.md
- v3.0/how-to/troubleshoot/tidb-lightning.md
`lightning` mistyped `lighting` somewhere
*
> [*]: fix typo for lightning

- dev/reference/tispark.md
- v2.1/reference/tispark.md
- v3.0/reference/tispark.md
Fix 3 broken links
N/A
3.0/2.1/dev
> reference: fix 3 broken links

- v1.0/tispark/tispark-user-guide.md
- v2.0/tispark/tispark-user-guide.md
- v2.1/tispark/tispark-user-guide_v1.x.md
Fix typos and broken links
N/A
1.0/2.0/2.1
> tispark: fix typos and broken links

- dev/reference/tools/tidb-lightning/checkpoints.md
- v2.1/reference/tools/tidb-lightning/checkpoints.md
- v3.0/reference/tools/tidb-lightning/checkpoints.md
unify checkpoint type in example config file.
[JIRA](https://internal.pingcap.net/jira/browse/TOOL-1570)
pingcap/docs: TBD
v2.1/v3.0/dev
> checkpoints: Update checkpoints.md

- dev/reference/tools/data-migration/manage-tasks.md
- v2.1/reference/tools/data-migration/manage-tasks.md
- v3.0/reference/tools/data-migration/manage-tasks.md
Add missing master port in dm manage-tasks.md
> Add missing master port in dmctl example

- v3.0/how-to/scale/horizontally.md
> how-to/scale: update table format

- dev/benchmark/dm-v1.0-ga.md
- v3.0/benchmark/dm-v1.0-ga.md
some format fix in DM benchmark
#1859 
3.0, dev
> 3.0, dev: some format fix in DM benchmark report

- v2.1/reference/tools/data-migration/cluster-operations.md
- v3.0/reference/tools/data-migration/cluster-operations.md
refine the doc for
1. 替换 DM-master 实例
2. 替换 DM-worker 实例
https://github.com/pingcap/docs-cn/pull/1853
v3.0/v2.1
> v3.0, v2.1: refine components migration of DM

- v2.1/TOC.md
- v2.1/reference/tools/data-migration/cluster-operations.md
- v2.1/reference/tools/data-migration/overview.md
- v2.1/reference/tools/data-migration/usage-scenarios/master-slave-switch.md
- v3.0/TOC.md
- v3.0/reference/tools/data-migration/cluster-operations.md
- v3.0/reference/tools/data-migration/overview.md
- v3.0/reference/tools/data-migration/usage-scenarios/master-slave-switch.md
update the doc about master-slave switch support in DM
https://github.com/pingcap/docs-cn/pull/1852
v3.0/v2.1
> v3.0, v2.1: update master-slave switch support in DM

- scripts/merge_by_toc.py
Update a relative path in a script for pdf generation.
> update a relative path in script

- dev/reference/sql/statements/show-table-regions.md
- dev/reference/tools/data-migration/overview.md
- scripts/markdown-link-check.tpl
- scripts/verify-links.sh
- v2.1/reference/sql/statements/show-table-regions.md
- v2.1/reference/tools/data-migration/overview.md
- v3.0/reference/sql/statements/show-table-regions.md
- v3.0/reference/tools/data-migration/overview.md
- Links must be absolute and start from repo root
- Only files in current directory and /media are allowed
> scripts: support new link convention

- dev/reference/sql/view.md
- v3.0/reference/sql/view.md
This PR fixes a typo in `view.md`
https://github.com/pingcap/docs-cn/issues/1887
`dev`, `v3.0`
> reference/sql: fix a typo

- dev/reference/tools/data-migration/manage-tasks.md
- v2.1/reference/tools/data-migration/manage-tasks.md
- v3.0/reference/tools/data-migration/manage-tasks.md
fix command sample introduced in https://github.com/pingcap/docs-cn/pull/1878.
https://github.com/pingcap/docs-cn/pull/1878
dev/v3.0/v2.1
> references: fix DM command sample

- dev/reference/mysql-compatibility.md
- v2.1/reference/mysql-compatibility.md
- v3.0/reference/mysql-compatibility.md
Fix inconsistent names in #1858.
N/A
> reference: fix inconsistent names in #1858

- dev/how-to/upgrade/from-previous-version.md
A note was added
https://github.com/pingcap/docs-cn/pull/1893
dev
> update previous version for dev

- dev/faq/tidb.md
- v2.1/faq/tidb.md
- v3.0/faq/tidb.md
The answer is wrong
* dev
* v3.0
* v2.1
> faq/tidb: Fix TiDB FAQ answer 3.4.12

- dev/reference/tools/data-migration/features/overview.md
- v2.1/reference/tools/data-migration/features/overview.md
- v3.0/reference/tools/data-migration/features/overview.md
refine docs of DM Black & white table lists.
- add some explanation about Black & white table lists
- add some link to MySQL Replication Filtering Rules
dev/v3.0/v2.1
> references: refine MySQL Replication Filtering Rules in DM Black & white table lists

- dev/reference/tispark.md
- v2.1/reference/tispark.md
- v3.0/reference/tispark.md
Signed-off-by: King-Dylan <702299521@qq.com>
This PR updates the TiSpark FAQ.
https://github.com/pingcap/docs-cn/pull/1877
`dev`, `v3.0`, `v2.1`
> reference: update Tispark FAQ

- dev/reference/tispark.md
- v3.0/reference/tispark.md
Add TiSpark FAQ for dev and 3.0
null
Dev and 3.0
> update TiSpark FAQ for dev and 3.0

- dev/releases/3.0.4.md
- v3.0/releases/3.0.4.md
Update the description of 12049 in 3.0.4 release notes. 
dev/v3.0
> Releases: update the description of 12049

- dev/reference/tispark.md
- v3.0/reference/tispark.md
update FAQ for TiSpark
dev and 3.0
> update FAQ for TiSpark (dev and 3.0)

- v3.0/reference/tispark.md
> update FAQ for TiSpark (3.0)

- dev/how-to/deploy/geographic-redundancy/location-awareness.md
- dev/how-to/deploy/orchestrated/ansible.md
- v2.1/how-to/deploy/geographic-redundancy/location-awareness.md
- v2.1/how-to/deploy/orchestrated/ansible.md
Add usage precautions for `labels`
https://github.com/pingcap/docs-cn/pull/1919
dev, v2.1, v3.0 (#1919)
> how-to/deploy: add usage precautions for labels

- dev/releases/3.0.4.md
- v3.0/releases/3.0.4.md
Fix a typo 
https://github.com/pingcap/docs/pull/1581
dev, v3.0
> releases: fix a typo

- dev/releases/3.0.4.md
- v3.0/releases/3.0.4.md
Update format
https://github.com/pingcap/docs/pull/1583
dev, v3.0
> releases: update format

- dev/tidb-in-kubernetes/deploy/aws-eks.md
- dev/tidb-in-kubernetes/deploy/gcp-gke.md
- v3.0/tidb-in-kubernetes/deploy/aws-eks.md
- v3.0/tidb-in-kubernetes/deploy/gcp-gke.md
Update the Note formats
N/A
dev, v3.0
> tidb-in-kubernetes/deploy: update the Note formats

- dev/reference/sql/constraints.md
- dev/tidb-in-kubernetes/troubleshoot.md
- v2.1/reference/sql/constraints.md
- v3.0/reference/sql/constraints.md
- v3.0/tidb-in-kubernetes/troubleshoot.md
This PR fixes typos in `troubleshoot.md` and `constraints.md`.
https://github.com/pingcap/docs-cn/pull/1861
https://github.com/pingcap/docs-cn/pull/1819
> *: fix typos

- dev/reference/best-practices/grafana-monitor.md
- v2.1/reference/best-practices/grafana-monitor.md
- v3.0/reference/best-practices/grafana-monitor.md
- Update wording of `Prometheus 集群`
- Update some UI content to make it consistent with that in screenshots
- Update format
#1952
> reference/best-practices: refine Grafana wording

- dev/reference/tools/data-migration/manage-tasks.md
- v2.1/reference/tools/data-migration/manage-tasks.md
- v3.0/reference/tools/data-migration/manage-tasks.md
This PR changes `config_file` to `config-file` in DM `manage-tasks.md`.
https://github.com/pingcap/docs/pull/1556#discussion_r335945797
> data-migration: change config_file to config-file

- dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md
- v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md
Fix a grep error on macOS
https://github.com/pingcap/docs/pull/1582
dev, v3.0
> tidb-in-kubernetes/get-started: fix a grep error on macOS

- dev/reference/security/user-account-management.md
- v2.1/reference/security/user-account-management.md
- v3.0/reference/security/user-account-management.md
This PR fixes the code block format in the user account management document.
N/A
> reference/security: fix format in user account management doc

- dev/how-to/monitor/monitor-a-cluster.md
- v3.0/how-to/monitor/monitor-a-cluster.md
Update the dashboard file for manual deploy monitor. In master or 3.0, some file does not exist.
https://github.com/pingcap/tidb-ansible/issues/999
#1962
Affects TiDB master and 3.0.
> how-to/monitor: update manual deploy monitor

- dev/TOC.md
- v3.0/TOC.md
Add 3.0.5 Release Notes to TOC
#1982
https://github.com/pingcap/docs/pull/1611
dev, v3.0
> toc: add 3.0.5 Release Notes

- dev/how-to/deploy/orchestrated/ansible.md
- v2.1/how-to/deploy/orchestrated/ansible.md
- v3.0/how-to/deploy/orchestrated/ansible.md
Update disk formatting document.
To close https://github.com/pingcap/docs-cn/issues/1358
dev / v3.0 / v2.1
> Update disk formatting document

- dev/reference/best-practices/java-app.md
- v2.1/reference/best-practices/java-app.md
- v3.0/reference/best-practices/java-app.md
Add rewriting suggestion for `insert on duplicate key update`.
#1884
> best-practices: add rewriting suggestion for insert on duplicate key update

- dev/TOC.md
- dev/reference/tools/data-migration/releases/1.0.2.md
- v2.1/TOC.md
- v2.1/reference/tools/data-migration/releases/1.0.2.md
- v3.0/TOC.md
- v3.0/reference/tools/data-migration/releases/1.0.2.md
add DM v1.0.2 release notes
dev, v3.0 and v2.1
> references: add DM v1.0.2 release notes

- v2.1/TOC.md
- v3.0/TOC.md
Added TOC entry for PD scheduling best practices for v2.1 and v3.0
N/A
TiDB V2.1, V3.0
> TOC: update TOC for PD scheduling best practice

- dev/reference/best-practices/pd-scheduling.md
- v2.1/reference/best-practices/pd-scheduling.md
- v3.0/reference/best-practices/pd-scheduling.md
This PR replaces the current general glossary reference with specific ones.
#1990
#2003 
TiDB 2.1/3.0/Dev
> reference/best-practices: update PD term references

- dev/reference/configuration/tidb-server/tidb-specific-variables.md
- v2.1/reference/configuration/tidb-server/tidb-specific-variables.md
TiDB from v2.1.18 supports `tidb_allow_remove_auto_inc` variable, so change `v2.1.8` to `v2.1.18`
[TiDB disallow dropping auto_increment column attribute](https://github.com/pingcap/tidb/pull/12146)
TiDB v2.1, dev
> reference/configuration: fix-feature-introduce-version

- dev/reference/tools/data-migration/configure/task-configuration-file.md
- v2.1/reference/tools/data-migration/configure/task-configuration-file.md
- v3.0/reference/tools/data-migration/configure/task-configuration-file.md
fix link for dm's config
v2.1, v3.0 and dev
> tools: fix link for dm's config

- dev/releases/2.1.18.md
- dev/tidb-in-kubernetes/deploy/alibaba-cloud.md
- dev/tidb-in-kubernetes/deploy/aws-eks.md
- dev/tidb-in-kubernetes/deploy/gcp-gke.md
- dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-dind.md
- v2.1/releases/2.1.18.md
- v3.0/releases/2.1.18.md
- v3.0/tidb-in-kubernetes/deploy/alibaba-cloud.md
- v3.0/tidb-in-kubernetes/deploy/aws-eks.md
- v3.0/tidb-in-kubernetes/deploy/gcp-gke.md
- v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-dind.md
Fix 11 broken links
https://github.com/pingcap/docs/pull/1638
v3.0/v2.1/dev
> *: fix 11 broken links

- scripts/generate_pdf.sh
- scripts/merge_by_toc.py
> generate v3.1 PDF

- .github/pull_request_template.md
Update version description in PR template: add v3.1
https://github.com/pingcap/docs/pull/1642
N/A
> .github: update version description in PR template

- v3.1/reference/performance/optimizer-hints.md
Update optimizer hints for TiDB v3.1
#1979 
v3.1
> v3.1/reference: update optimizer hints

- dev/how-to/deploy/data-migration-with-ansible.md
- v2.1/how-to/deploy/data-migration-with-ansible.md
- v3.0/how-to/deploy/data-migration-with-ansible.md
- v3.1/how-to/deploy/data-migration-with-ansible.md
The PR fixed some ill formatting caused by inconsistent indent. Also for V2.1, some code copyable tags are added. 
V2.1/3.0/3.1/Dev
> how-to: fix indent and update some code copying tags (2.1)

- dev/how-to/deploy/orchestrated/offline-ansible.md
- v2.1/how-to/deploy/orchestrated/offline-ansible.md
- v3.0/how-to/deploy/orchestrated/offline-ansible.md
- v3.1/how-to/deploy/orchestrated/offline-ansible.md
> *: update offline deployment

- dev/tidb-in-kubernetes/deploy/gcp-gke.md
- v3.0/tidb-in-kubernetes/deploy/gcp-gke.md
- v3.1/tidb-in-kubernetes/deploy/gcp-gke.md
- Add warning that scaling in TiKV count might cause data loss
- Add a Fluent Bit vs Fluentd section for "Customize logging"
- Fix list format that causes chaos at the PingCAP website
- Improve organization such as splitting a para into clearer steps
- https://github.com/pingcap/docs/pull/1493
- https://github.com/pingcap/docs/pull/1500
- https://github.com/pingcap/docs/pull/1651
dev, v3.1, v3.0
> tidb-in-kubernetes: add customizing logging and update organization

- dev/reference/tools/data-migration/overview.md
- v2.1/reference/tools/data-migration/overview.md
- v3.0/reference/tools/data-migration/overview.md
- v3.1/reference/tools/data-migration/overview.md
This PR adds a reference in the DM overview doc.
N/A
> data-migration: add reference in dm overview

- dev/reference/system-databases/information-schema.md
- v3.0/reference/system-databases/information-schema.md
Add introduced version information for the `MEM` column in the `PROCESSLIST` table
Fix this issue: https://github.com/pingcap/docs-cn/issues/2049
v3.0
> reference: add version info for the MEM column

- v2.1/reference/tools/download.md
- v3.0/reference/tools/download.md
- v3.1/reference/tools/download.md
users don't know how to download tools by version, need update document
copy from https://github.com/pingcap/docs-cn/pull/2050
v2.1, v3.0 and v3.1
> tools: update download urls

- dev/reference/sql/language-structure/keywords-and-reserved-words.md
- v2.1/reference/sql/language-structure/keywords-and-reserved-words.md
- v3.0/reference/sql/language-structure/keywords-and-reserved-words.md
- v3.1/reference/sql/language-structure/keywords-and-reserved-words.md
Add missing attribute to <a> tag
> add attribute 'href' to "a" tag

- dev/reference/performance/statistics.md
- v2.1/reference/performance/statistics.md
- v3.0/reference/performance/statistics.md
- v3.1/reference/performance/statistics.md
Update `column_name` description to make it clearer
N/A
dev, v3.1, v3.0, v2.1
> *: update column_name description

- dev/reference/best-practices/massive-regions.md
- v2.1/reference/best-practices/massive-regions.md
- v3.0/reference/best-practices/massive-regions.md
- v3.1/reference/best-practices/massive-regions.md
Fix a few typos in the massive Region best practices document.
N/A
> best-practices: fix typos in massive region best practices

- dev/reference/tispark.md
- v2.1-legacy/tispark/tispark-user-guide.md
- v2.1/reference/tispark.md
- v2.1/tispark/tispark-user-guide_v1.x.md
- v3.0/reference/tispark.md
- v3.1/reference/tispark.md
fix spark cluster config settings
dev, 2.1, 3.0, 3.1
> fix spark cluster config

- dev/how-to/get-started/data-migration.md
- v2.1/how-to/get-started/data-migration.md
- v3.0/how-to/get-started/data-migration.md
- v3.1/how-to/get-started/data-migration.md
add encrypt password and update download's URL in get started for dm 
dev, v2.1, v3.0 and v3.1
> how-to/get-started: add DM encrypt password and update download url

- dev/releases/3.0.6.md
- v3.0/releases/3.0.6.md
- v3.1/releases/3.0.6.md
Add missed PRs in 3.0.6 release notes 
https://github.com/pingcap/docs-cn/pull/2082
> releases: v3.1, v3.0, dev, add missed PRs in 3.0.6

- dev/releases/3.0.6.md
- v3.0/releases/3.0.6.md
- v3.1/releases/3.0.6.md
Add missed PRs in 3.0.6 release notes, patch 2
https://github.com/pingcap/docs-cn/pull/2085
> v3.0, v3.1, dev: add missed PRs in 3.0.6 patch2

- dev/tidb-in-kubernetes/deploy/tidb-operator.md
- v3.0/tidb-in-kubernetes/deploy/tidb-operator.md
- v3.1/tidb-in-kubernetes/deploy/tidb-operator.md
> tidb-in-kubernetes: fix typo in tidb-operator guide

- dev/reference/tools/pd-control.md
- v2.1/reference/tools/pd-control.md
- v3.0/reference/tools/pd-control.md
- v3.1/reference/tools/pd-control.md
> tools: add pdctl download guide

- dev/reference/performance/follower-read.md
- v3.1/reference/performance/follower-read.md
- Update Follower Read description: `另外两个` > `另外的`
- Make Follower Read capitalization consistent
https://github.com/pingcap/docs/pull/1675#discussion_r353575505
dev, v3.1
> reference: update Follower Read description

- dev/reference/performance/optimizer-hints.md
update optimizer hint doc
https://github.com/pingcap/docs-cn/pull/2093/
aligned in https://github.com/pingcap/docs/pull/1685
dev
> dev: update optimizer hint doc

- dev/how-to/upgrade/from-previous-version.md
- v3.0/how-to/upgrade/from-previous-version.md
- v3.1/how-to/upgrade/from-previous-version.md
- Improve the wording and format of the upgrade document
https://github.com/pingcap/docs/pull/1689
dev, v3.1, v3.0
> how-to/upgrade: improve wording and format of upgrade docs

- dev/faq/tidb.md
- dev/reference/best-practices/pd-scheduling.md
- v2.1-legacy/FAQ.md
- v2.1/faq/tidb.md
- v2.1/reference/best-practices/pd-scheduling.md
- v3.0/faq/tidb.md
- v3.0/reference/best-practices/pd-scheduling.md
- v3.1/faq/tidb.md
- v3.1/reference/best-practices/pd-scheduling.md
> *: remove extra spaces

- dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md
- v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md
- v3.1/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md
- Add a blank line for ordered lists
N/A
> tidb-in-kubernetes: add a blank line for ordered lists

- dev/reference/sql/functions-and-operators/miscellaneous-functions.md
- v2.1/reference/sql/functions-and-operators/miscellaneous-functions.md
- v3.0/reference/sql/functions-and-operators/miscellaneous-functions.md
- v3.1/reference/sql/functions-and-operators/miscellaneous-functions.md
Fix the format of the function table.
N/A
> sql: fix table format of functions
