pingcap/docs-cn

download-ecosystem-tools.md
pd-recover.md
production-deployment-using-tiup.md
production-offline-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tiup/tiup-component-cluster-deploy.md
upgrade-tidb-using-tiup.md

bump version for v4.0.15

---

download-ecosystem-tools.md
pd-recover.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
ticdc/manage-ticdc.md
tiup/tiup-component-cluster-deploy.md
upgrade-tidb-using-tiup.md

bump version for 5.0.4

---

optimizer-hints.md

Add the hint LIMIT_TO_COP()

---

releases/release-4.0.15.md

Move a note in 4.0.15

---

optimizer-hints.md

remove a unnecessary line

---

download-ecosystem-tools.md
pd-control.md
pd-recover.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
ticdc/manage-ticdc.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

bump version for 5.1.2

---

releases/release-5.2.0.md

- This PR is translated from: https://github.com/pingcap/docs/pull/6344

release-5.2.0: Add info about caching_sha2

---

releases/release-5.0.0.md
releases/release-5.0.1.md

https://github.com/pingcap/tidb/pull/23776
https://github.com/pingcap/docs-cn/pull/7142

5.1.0 release notes: add the changes to committer-concurrency

---

tikv-configuration-file.md

Remive a tikv config that should not have existed in 4.0
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/6418

Remove a tikv config that should not have existed in 4.0

---

download-ecosystem-tools.md
pd-control.md
pd-recover.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
ticdc/manage-ticdc.md
tidb-lightning/tidb-lightning-backends.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

Bump version for 5.2.2

---

system-variables.md

Fix the mistaken link of `oom-use-tmp-storage` in ` tidb_enable_rate_limit_action`

Fix a mistaken link

---

sql-mode.md

sql-mode.md: fix a typo 

---

system-variables.md

system-variables: update permitted ranges
- This PR is translated from: https://github.com/pingcap/docs/pull/6665

system-variables: update permitted ranges

---

system-variables.md

Make some corrections for the example of system variable `tidb_opt_insubq_to_join_and_agg`

make some correction for tidb_opt_insubq_to_join_and_agg

---

tiflash/use-tiflash.md

Update the TiFlash supported function list

update functions supported by TiFlash

---

deploy-monitoring-services.md

Update deploy-monitoring-services.md

Update Prometheus version in deploy-monitoring-services.md

---

tidb-lightning/tidb-lightning-configuration.md

Corrected default values of checksum and analyze in Lightning.
- checksum should be "required" by default
- analyze should be "optional" by default

Corrected default values of checksum and analyze in Lightning.

---

.github/pull_request_template.md
README.md

chore: update pr template for v5.3

chore: update pr template for v5.3

---

br/use-br-command-line-tool.md

Signed-off-by: joccau <zak.zhao@pingcap.com>
Add a encrypt-feature for V5.3.0, need to add content for it
V5.3.0
- This PR is translated from:  
[issue#28640](https://github.com/pingcap/tidb/issues/28640)

br: update doc for encrypt

---

system-variables.md

Revised the order of system variables into alphabetical order.

revise the order of system variables into alphabetical order

---

TOC.md
alert-rules.md
ticdc/ticdc-alert-rules.md

Add description of TiCDC alert rules.

Add description of TiCDC alert rules

---

pd-control.md

Remove the store limit scene feature since it isn't maintained and well tested.

Remove store limit scene

---

pd-control.md

Revised ``` into ` that encloses “store [delete | label | weight | remove-tombstone | limit ] <store_id> [--jq="<query string>"]”.

revise the format of store related command

---

tidb-configuration-file.md

Correct a minor error

---

.github/workflows/ci.yaml
.github/workflows/link-check.yaml

+ Add link anchor checks GitHub action, because these checks are too buggy in Jenkins and affect merge. 
+ Add back external link check action

chore: add link check ci

---

tidb-configuration-file.md

Update the value of txn-local-latches from enable to enabled
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/7468

Update the value of txn-local-latches from enable to enabled

---

system-variables.md

Revise a part of unclear description of TSO variables according to comments on https://github.com/pingcap/docs/pull/6770.

revise description of TSO variables

---

ticdc/ticdc-alert-rules.md

- Other reference link(s): https://github.com/pingcap/docs-cn/pull/7354

refine TiCDC alter rules

---

placement-rules-in-sql.md

Update wording in placement rules in sql
- This PR is translated from: https://github.com/pingcap/docs/pull/6818

Update wording in placement rules in sql

---

sql-prepare-plan-cache.md

Optimize description to caching conditions based on review comments of the English version.
- This PR is translated from: https://github.com/pingcap/docs/pull/6726
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/7356

Optimize description to caching conditions

---

tikv-control.md

Add a warning for unsafe recover

Add a warning for unsafe recover

---

ticdc/manage-ticdc.md

ticdc: update max-batch-size

---

temporary-tables.md

The system table `information_schema.INNODB_TEMP_TABLE_INFO` doesn't exist in TiDB.

fix the declaration about `INNODB_TEMP_TABLE_INFO`

---

sync-diff-inspector/sync-diff-inspector-overview.md

change the download link for sync-diff-inspector

---

system-variables.md

Update description to tidb_scatter_region

Update description to tidb_scatter_region

---

faq/deploy-and-maintain-faq.md
tidb-scheduling.md

Revise the status information of a TiKV store in the following docs:
- "deploy-and-maintain-faq.md"
- "tidb-scheduling.md"
This PR is the revised version of https://github.com/pingcap/docs-cn/pull/7177.

Docs: revise the status information of a TiKV store

---

sync-diff-inspector/sync-diff-inspector-overview.md

update the download link for  sync-diff-inspector

---

ticdc/ticdc-open-api.md

Delete the warning note that open api is an experimental feature.

ticdc: GA TiCDC open API

---

benchmark/v5.2-performance-benchmarking-with-tpch.md

Add aliases to v5.2 TPCH report

Add aliases to v5.2 TPCH report

---

information-schema/information-schema-data-lock-waits.md

Add warning about `data_lock_waits` table won't record optimistic transaction blocked by pessimistic transaction (since it is frequently asked).

Add warning about data_lock_waits table won't record optimistic transaction blocked by pessimistic transaction

---

ticdc/ticdc-open-protocol.md

update java example link
- Other reference link(s): cc: https://github.com/pingcap/ticdc/pull/3547
None

ticdc: update java example link

---

production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

Bump versions for tiup related content for 5.3.0

---

sync-diff-inspector/sync-diff-inspector-overview.md

add annontation for option configuration items

sync-diff-inspector: add annontation for option configuration items

---

grafana-tidb-dashboard.md

The monitor setting is modified in https://github.com/pingcap/tidb/pull/25123

Update transaction types panel name

---

sync-diff-inspector/sync-diff-inspector-overview.md

update docker link to `nightly` version
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/7568

sync-diff-inspector: update docker link

---

scale-tidb-using-tiup.md
tiup/tiup-component-cluster-scale-in.md

Add a sub-title for tiup cluster scale-in
- Other reference link(s): https://asktug.com/t/topic/183600

Add-a-sub-title-for-tiup-cluster-scale-in

---

ticdc/ticdc-open-protocol.md

ticdc open protocol: fix a typo

---

table-attributes.md

Change `；` to `;` and make the user docs more readable.

Fix the user docs of table attributes

---

dashboard/dashboard-user.md

Refine the expression about how to create a SQL user when enabling SEM.
- Other reference link(s): #7187

fix the expression about creating sql user when enabling sem

---

ticdc/ticdc-overview.md

update `sort-dir` supported version

---

alert-rules.md
tidb-troubleshooting-map.md

update some alert rules

---

placement-rules-in-sql.md

Signed-off-by: xhe <xw897002528@gmail.com>
- This PR is translated from: pingcap/docs#7017

tidb: warn limitations of placement rules dict syntax

---

tidb-lightning/tidb-lightning-distributed-import.md

lightning: fix lightning distribute import config

---

quick-start-with-tidb.md
table-attributes.md
tiup/tiup-playground.md

- Other reference link(s): https://github.com/pingcap/docs/pull/6918#issuecomment-976214716

change-tiup-related-content

---

releases/release-4.0.9.md

Added an entry [#21290](https://github.com/pingcap/tidb/issues/21290) in the release notes.

Add a missing note to v4.0.9 release notes

---

experimental-features.md

1. Added v5.3 experimental features 
2. Added the missing release info for some existing experimental features 

update experimental features for v5.3

---

quick-start-with-tidb.md

Found [a rendering error](https://docs.pingcap.com/zh/tidb/dev/quick-start-with-tidb#%E6%8E%A2%E7%B4%A2%E6%9B%B4%E5%A4%9A).

fix a note rendering error

---

data-type-date-and-time.md

The description on conversion from `DATETIME`/`TIMESTAMP` to `TIME` is wrong, fix it.
See https://asktug.com/t/topic/273044 and https://dev.mysql.com/doc/refman/8.0/en/date-and-time-type-conversion.html
- Other reference link(s):  https://asktug.com/t/topic/273044  https://dev.mysql.com/doc/refman/8.0/en/date-and-time-type-conversio …

Fix error on conversion between date and time types

---

alert-rules.md

Updated alter rule's promql expression for NODE_node_overload and NODE_cpu_used_more_than_80.
The promeql's syntax is changed because TiDB cluster upgraded prometheus version from 2.2.1 to 2.8.1 in TiDB 3.0.
Reference : https://docs.pingcap.com/zh/tidb/stable/release-3.0-ga#tidb-ansible
Issue: #7638 

alert-rules.md: Updated alter rule's promql expression.

---

.github/workflows/dispatch.yml

chore: update dispatch in release-5.3

chore: update dispatch in release-5.3

---

.github/workflows/dispatch.yml
releases/release-5.3.0.md

Fix rendering failures caused by wrong format

Fix rendering failures caused by wrong format

---

experimental-features.md

experimental-features: add OpenAPI feature

---

best-practices/haproxy-best-practices.md

Update haproxy best practices using haproxy2.5.0
- This PR is translated from: https://github.com/pingcap/docs/pull/7046 https://github.com/pingcap/docs/pull/7082

Update haproxy best practices using haproxy2.5.0

---

ticdc/manage-ticdc.md

Corrected description about RTO and RPO.

Corrected RTO and RPO in manage-ticdc.md

---

maintain-tidb-using-tiup.md

Update the order of tiup startup components

---

overview.md

Added 2 videos

---

best-practices/pd-scheduling-best-practices.md

Updated two commands and the tool info needed for modifying `key-type` regarding the feedback from AskTUG, https://asktug.com/t/topic/213152.

update commands and tool info about `key-type`

---

system-variables.md

Add back a description deleted in https://github.com/pingcap/docs-cn/pull/7466.

Add back a description

---

alert-rules.md

Fix alert item

---

mysql-compatibility.md

Modify the name of the Oracle and PostgreSQL

---

config-templates/simple-file-binlog.yaml

There are 3 directories in TiUP configuration, drainer's data_dir (generated by global config), drainer's config.data-dir, and drainer's config.syncer.to.dir.
The priority of this is drainer_servers.config.syncer.to.dir > drainer_servers.data_dir > drainer.config.data-dir, so the data-dir is adjusted to the higher priority version here. …

update binlog deploy configuration

---

.github/workflows/link.yaml
connectors-and-apis.md

- Update cron and assignee of the external link checker.
- Remove 2 dead links.

.github: change cron and assignee

---

tidb-monitoring-api.md

Fix a typo in tidb-monitoring-api.md
- This PR is translated from: https://github.com/pingcap/docs/pull/6829

Fix a typo in tidb-monitoring-api.md

---

explain-subqueries.md

Fix typo error and refine the description of the plan. 

Fix description error in explain-subqueries.md

---

TOC.md
tidb-lightning/tidb-lightning-prechecks.md

Refined the title of prechecks.

Updated prechecks

---

ticdc/manage-ticdc.md

Revert "cdc: add advice for how to use kafka sink in ticdc (#7570)"

---

ticdc/manage-ticdc.md

Added version info for `partition-num` and `max-message-bytes`.

cdc: add advice for how to use kafka sink in ticdc

---

troubleshoot-tidb-cluster.md

remove duplicate ‘的’ in troubleshoot-tidb-cluster.md

Remove duplicate word

---

tikv-configuration-file.md

Fix #7842
- But no need to translate to v4.0, as the value is correct for docs-v4.0
No

Fix config value for tikv compression-per-level

---

releases/release-5.3.0.md

Add a space
- Other reference link(s): https://github.com/pingcap/docs/pull/7174

Fix format of 5.3.0 release notes

---

tikv-configuration-file.md

Update parameter name of peer-stale-state-check-interval

---

tidb-configuration-file.md

Update the description for Prepare Plan Cache

---

tikv-configuration-file.md

Fix a typo in tikv configuration file

Fix a typo in tikv configuration file

---

garbage-collection-configuration.md

Signed-off-by: linning <linningde25@gmail.com>
Update tikv-ctl modify-tikv-config usage for gc, see https://github.com/pingcap/docs/issues/6867 for more details

Update tikv-ctl modify-tikv-config usage for gc

---

tidb-binlog/tidb-binlog-reparo.md

update description of start-tso

---

tidb-lightning/migrate-from-csv-using-tidb-lightning.md
tidb-lightning/tidb-lightning-configuration.md

- This PR is translated from:  https://github.com/pingcap/docs/pull/6386

tidb-lightning: add line terminator and update other csv settings

---

tidb-configuration-file.md

Remove invalid log format for TiDB.
https://github.com/pingcap/tidb/pull/23534

TiDB: remove invalid log format

---

alert-rules.md

https://github.com/tikv/tikv/pull/11614/files

remove about 'meet_lock' alter

---

alert-rules.md

Fixed a TiDB alert rule for `TiDB_tikvclient_backoff_total`
- This PR is translated from: https://github.com/pingcap/docs/pull/7153

Fix a TiDB alert rule for `TiDB_tikvclient_backoff_total`

---

auto-increment.md

auto-increment: correct the description in 'limit' part

---

TOC.md
quick-start-with-tidb.md

+ Delete Docker Composer deployment from TOC because the linked page is no longer available.
+ Add a document for a quick start with TiDB. This document links to the latest stable version of quick start with TiDB.

Delete docker composer deploy from TOC and direct to the latest stable version

---

statistics.md

Update description in statistics v2

Update description in statistics v2

---

CONTRIBUTING.md

Update the link for how to write a good commit message
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/7961

Update the link for how to write a good commit message

---

check-before-deployment.md

Update the description of disabling swap
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/7443 https://github.com/pingcap/docs/pull/6983

Update the description of disabling swap

---

releases/release-5.0.5.md

delele a wrong info , the grafaba upgrade is not in 5.0.5, and it will be in 5.0.6

Remove a note in release-5.0.5.md

---

maintain-tidb-using-tiup.md

Update component stopping order
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/7403

Update component stopping order

---

br/backup-and-restore-faq.md
releases/release-4.0-ga.md
releases/release-4.0.0-rc.1.md
releases/release-4.0.0-rc.2.md
releases/release-4.0.0-rc.md
releases/release-4.0.10.md
releases/release-4.0.11.md
releases/release-4.0.12.md
releases/release-4.0.13.md
releases/release-4.0.14.md
releases/release-4.0.15.md
releases/release-4.0.2.md
releases/release-4.0.3.md
releases/release-4.0.5.md
releases/release-4.0.6.md
releases/release-4.0.7.md
releases/release-4.0.8.md
releases/release-4.0.9.md
ticdc/ticdc-open-protocol.md
ticdc/ticdc-overview.md

changed github.com/pingcap/ticdc to github.com/pingcap/tiflow

changed github.com/pingcap/ticdc to github.com/pingcap/tiflow

---

download-ecosystem-tools.md
pd-recover.md
production-deployment-using-tiup.md
production-offline-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tiup/tiup-component-cluster-deploy.md
upgrade-tidb-using-tiup.md

Bump version for v4.0.16

---

tidb-configuration-file.md

Delete the Configuration File Parameters about the `nested-loop-join-cache-capacity` .  
It had been delete in PR : https://github.com/pingcap/tidb/pull/20844
pingcap/tidb#20844

Delete the Configuration File Parameters about the nested-loop-join-cache-capacity

---

configure-placement-rules.md

Placement rule is enabled by default after v5.0. Remove information about _experimental_.
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/8049

update placement rule configuration

---

ticdc/ticdc-overview.md

Updated the code repo link of TiCDC 
from https://github.com/pingcap/tiflow
to https://github.com/pingcap/tiflow/tree/master/cdc

Updated the code repo link of TiCDC

---

.github/pull_request_template.md

chore: add v5.4 to pr template
- This PR is translated from: https://github.com/pingcap/docs/pull/7334

chore: add v5.4 to pr template

---

system-variables.md

Update the default value for sysvar `wait_timeout`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8076

fix incorrect default value for sysvar wait_timeout

---

download-ecosystem-tools.md
pd-recover.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tiup/tiup-component-cluster-deploy.md
upgrade-tidb-using-tiup.md

bump version for v5.0.6
- This PR is translated from: https://github.com/pingcap/docs/pull/7365

bump version for v5.0.6

---

tidb-architecture.md

Added a video about TiDB architecture

Added a video about TiDB architecture

---

tidb-architecture.md

Update vedio code

---

sync-diff-inspector/sync-diff-inspector-overview.md

- Other reference link(s): https://github.com/pingcap/docs/issues/7351

sync_diff: update description about tidb collation

---

migrate-large-mysql-to-tidb.md

Remove this symbol from the code block.

Remove sql from copyable snippet

---

tiflash/tiflash-configuration.md

https://github.com/pingcap/tics/pull/3762

update configuration for FD-323

---

.github/workflows/dispatch.yml

Disable build on master

---

migrate-from-csv-files-to-tidb.md

- This PR is translated from: https://github.com/pingcap/docs/pull/7369

fix pdf build

---

system-variables.md

Signed-off-by: you06 <you1474600@gmail.com>
Add a new environment variable which controls coprocessor paging for `IndexLookUp` executor, ref pingcap/tidb#30578.
- This PR is translated from: pingcap/docs#7352

system-variables: add tidb_enable_paging

---

dm/dm-open-api.md

as title
- This PR is translated from: https://github.com/pingcap/tiflow/pull/3836

dm: update openapi config field

---

dm/relay-log.md

align relay log behaviour in v5.4.0

---

releases/release-5.3.0.md

lightning: add missing new config in release-5.3 release note

---

ticdc/ticdc-canal-json.md

Added an example.
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/8040

Added an example in ticdc-canal-json.md

---

dynamic-config.md
releases/release-5.3.0.md
tikv-configuration-file.md

It's a dangerous configuration that breaks correctness.
Check tikv/tikv#10384.

*: remove configuration `allow-remove-leader` and `raft-msg-flush-interval`

---

faq/upgrade-faq.md
sql-statements/sql-statement-add-index.md
upgrade-tidb-using-tiup.md

Update warning for DDL execution before cluster upgrade

Update warning for DDL execution before cluster upgrade

---

br/backup-and-restore-azblob.md

br: remove experimental properties

---

ticdc/manage-ticdc.md

clarify rowid HandleKey meaning

ticdc: clarify rowid HandleKey meaning

---

dm/dm-task-configuration-guide.md
dm/task-configuration-file-full.md

dm: add dm task timezone config

---

sql-statements/sql-statement-alter-table.md

Fix an ebnf display failure

---

sql-statements/sql-statement-show-create-placement-policy.md
sql-statements/sql-statement-with.md

Fix ebnf errors

---

troubleshoot-high-disk-io.md

`[rocksdb] max-sub-compactI/Ons = 2（或者 3）` to `[rocksdb] max-sub-compactions = 2（或者 3）`

fix a typo in a rroubleshoot related doc

---

statistics.md

This PR is to align some changes made in https://github.com/pingcap/docs/pull/7412/files. 
- This PR is translated from: https://github.com/pingcap/docs/pull/7412/files

Add information for the synchronously loading statistics content

---

dm/dm-open-api.md

as title
https://github.com/pingcap/dm/pull/2187
- Other reference link(s): close #8188

fix dm openapi http method

---

ticdc/ticdc-open-protocol.md

Fix a typo in links in ticdc-open-protocol.md

---

benchmark/v5.3-performance-benchmarking-with-tpch.md

Add aliases to v5.3 TPCH report

Add aliases to v5.3 TPCH report

---

tikv-configuration-file.md

Revert "TiKV config: add docs for raft engine configurations"

---

tidb-lightning/tidb-lightning-faq.md

lightning: add clean up metadata schema

---

tikv-configuration-file.md

Revert "Revert "TiKV config: add docs for raft engine configurations""

---

tidb-lightning/tidb-lightning-configuration.md
tidb-lightning/tidb-lightning-error-resolution.md

Added max-error and task-info-schema-name in tidb-lightning-configuration
- This PR is translated from:https://github.com/pingcap/docs/pull/7370

Added max-error and task-info-schema-name in tidb-lightning-configuration

---

br/backup-and-restore-azblob.md

br: fix br azblob typos

---

download-ecosystem-tools.md
ticdc/manage-ticdc.md

Bump version for v5.4.0, including only ecosystem tools. This PR change must be fully tested.

Bump version for v5.4.0 - ecosystem tools

---

configure-memory-usage.md

The session variables have been deprecated.

remove useless description for mem control

---

character-set-and-collation.md
character-set-gbk.md
mysql-compatibility.md

Update execution results affect the number of rows.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/8101/files

*: update character-set-and-collation

---

sql-statements/sql-statement-show-stats-meta.md
statistics.md

update: column header description

---

configure-placement-rules.md

Fixed the version that the Placement Rules was introduced. In 4.0~5.2 branches, the documents say "Placement Rules is...  introduced in v4.0.", but in 5.3 and the master branches, they say "Placement Rules is...  introduced in v5.0.".
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/8236

Placement rules: fix the version that Placement Rules was introduced

---

tidb-limitations.md

Correct the partition number supported by a table

Correct the partition number supported by a table

---

tidb-troubleshooting-map.md

Fix improper "or" between item list
- Other reference link(s): https://asktug.com/t/topic/274001

Fix improper "or" between item lists

---

configure-memory-usage.md
system-variables.md

Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>
Fix typo.
- This PR is translated from: None
- Other reference link(s): None

fix typo of tidb_distsql_scan_concurrency

---

alert-rules.md

Fix GC alert expression

---

tidb-configuration-file.md

Fix a typo about system variables `lower_case_table_names`

Fix a typo about system variables

---

tikv-configuration-file.md

The config item `pessimistic-txn.wake-up-delay-duration` in TiKV config file is mistyped as `wait-up-delay-duration` in all versions of documents since pessimistic transaction is supported. We didn't notice it perhaps because the config item is rarely used. Fix it.

Fix name of config item `wake-up-delay-duration` in TiKV config file

---

releases/release-4.0.0-rc.md

update a typo in 4.0 RC Release Notes

update a typo in 4.0 RC Release Notes

---

explain-indexes.md

revised a number in "explain-indexes.md"

revise a number in "EXPLAIN indexes" doc

---

best-practices/java-app-best-practices.md

Add a note for JDBC streaming result.
Case:
https://github.com/7yyo/jdbc-best-practices/blob/master/src/main/java/example/MysqlIO_41.java

Add a note for JDBC streaming result

---

tiflash/tiflash-configuration.md

Add log redaction to learner toml
- This PR is translated from: https://github.com/pingcap/docs/pull/7438

Add log redaction to learner toml

---

system-variables.md

Add docs for version_compile_* variables
- This PR is translated from: https://github.com/pingcap/docs/pull/6649

Add docs for version_compile_* variables

---

tidb-lightning/tidb-lightning-distributed-import.md

lightning: add usage restriction for tidb-lightning

---

tiup/tiup-bench.md

add link for TPC

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs/pull/7289

system-variables: update from generated source

---

ticdc/manage-ticdc.md
ticdc/troubleshoot-ticdc.md

Remove `canal-json` protocol from v5.3 docs. Because it does not have GA in this branch.
Revert some changes from https://github.com/pingcap/docs-cn/pull/8088

Remove `canal-json` protocol from v5.3 docs

---

keywords-and-reserved-words.md

chore: use TabsPanel

---

config-templates/complex-tiflash.yaml

Fix typos in complex-tiflash.yaml
* Should use ":" instead of "="
* The array-size in `storage.main.capacity` should be the same as `storage.main.dir`
- Other reference link(s): English version: https://github.com/pingcap/docs/pull/7551

Fix typo in complex-tiflash.yaml

---

troubleshoot-hot-spot-issues.md

- Other reference link(s): https://asktug.com/t/topic/274147

Fix image description

---

sql-statements/sql-statement-explain.md

Delete an outdated note

---

tidb-lightning/tidb-lightning-requirements.md

- Other reference link(s): https://github.com/pingcap/docs-cn/pull/8228

Fix border format

---

sql-statements/sql-statement-alter-table.md

Add some table options  about Alter table statement which had been supported

Add some tableoptions  about Alter table

---

sql-statements/sql-statement-create-index.md

- Other reference link(s): [表达式索引](https://docs.pingcap.com/zh/tidb/v5.0/sql-statement-create-index#%E8%A1%A8%E8%BE%BE%E5%BC%8F%E7%B4%A2%E5%BC%95)

sql-statement-create-index.md: fix the example of expression index create by 'create table' 

---

releases/release-5.3.0.md
upgrade-tidb-using-tiup.md

add-prometheuse-change-desc

---

dm/dm-overview.md

Add v5.4 to the DM overview documentation

---

dm/deploy-a-dm-cluster-using-tiup-offline.md

remove - Experimental-label-for- DM-Offline-deployment

---

tidb-lightning/tidb-lightning-distributed-import.md

- Other reference link(s): https://github.com/pingcap/docs-cn/pull/8249

Fix typo in TiDB lightning distributed import

---

glossary.md

Add terms for v5.4. All definitions come from existing published documents.

Add terms for v5.4

---

ticdc/manage-ticdc.md

Follow up https://github.com/pingcap/docs-cn/pull/8090

ticdc: fix wrong max-message-bytes

---

releases/release-timeline.md

Fix a typo in release-timeline

Fix a typo in release-timeline

---

.github/workflows/dispatch.yml

enable build for master

---

production-deployment-using-tiup.md

Fix SimpleTab format for deployment using tiup

---

alert-rules.md

Signed-off-by: tabokie <xy.tao@outlook.com>
Fix #7383

fix ping latency alert solution

---

tidb-binlog/bidirectional-replication-between-tidb-clusters.md

binlog: warn cyclic repication
- This PR is translated from: https://github.com/pingcap/docs/pull/7588

binlog: warn Bidirectional Replication

---

releases/release-5.4.0.md

- This PR is translated from: https://github.com/pingcap/docs/pull/7619

Fix wrong default values

---

production-deployment-using-tiup.md

Fix format in deployment using tiup

---

production-deployment-using-tiup.md

The doc lists 7 scenarios rather than 6. To reduce future maintenance cost, let's use "several" instead of a specific number.

fix a number in tiup prod deployment

---

system-variables.md

https://docs.pingcap.com/zh/tidb/stable/partitioned-table/#list-%E5%88%86%E5%8C%BA

name correspondence

---

migrate-with-more-columns-downstream.md

Fix the PDF table format issue for a table 

---

releases/release-5.4.0.md

Add doc links to rn-5.4 to improve usability.

rn: add document links to rn-5.4

---

best-practices/java-app-best-practices.md

Fix https://github.com/pingcap/docs-cn/issues/8401

fix a typo in java best practices

---

sql-plan-replayer.md

Fix a typo in sql-plan-replayer.md

---

TOC.md
tidb-operator-overview.md

Update TiDB Operator overview to include v1.3.
- Other reference link(s): https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/

update tidb operator version description

---

tune-tikv-memory-performance.md

Signed-off-by: nolouch <nolouch@gmail.com>
fix the config
https://github.com/pingcap/docs-cn/issues/6466

docs: revised the performance documentation

---

faq/migration-tidb-faq.md

Fix format in migration-tidb-faq.md
There is an incorrectly coded blank line causing the page to display incorrectly. 
https://docs.pingcap.com/zh/tidb/stable/migration-tidb-faq
Analyze using Hexdump.
Hexadecimal representation of the original blank line: 0D 0A 20 20 20 20 0D 0A 20 20 20 20
The correct hexadecimal representation of a blank line should be: 0D 0A 0D 0A 20 20 20 20
For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIB …

Fix format in migration tidb faq

---

releases/release-3.0.3.md

fix format in release-3.0.3.md

---

follower-read.md

Signed-off-by: tier-cap <zhengxiaojin@pingcap.com>
tidb_replica_read support global set.
- Other reference 
- https://github.com/pingcap/docs-cn/issues/8109
- https://github.com/pingcap/docs/pull/6451/commits/2d6b5234e68a4a7a1cc6f535976e7afa6712cf48
- https://github.com/pingcap/tidb/pull/27622)

tidb_replica_read support global set

---

tiup/tiup-playground.md

Remove use of v5.4.0 in dev version

---

releases/release-3.0.3.md
two-data-centers-in-one-city-deployment.md

Add description of how to configure placement rules

2dc: add config description

---

tiup/tiup-playground.md

- Other reference link(s): https://github.com/pingcap/docs-cn/pull/8455

Remove version from tiup playground and add two examples

---

TOC.md

fix format in TOC.md

---

.github/pull_request_template.md

add 6.0 option in pr template

---

download-ecosystem-tools.md
pd-control.md
pd-recover.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md

Bump version for 5.1.4

---

tidb-lightning/tidb-lightning-configuration.md

fix https://github.com/pingcap/tidb/issues/31633
fix https://github.com/pingcap/docs/issues/7401#event-5901407658

Add some configs in tidb-lightning-configuration.md

---

pd-control.md

Signed-off-by: IcePigZDB <icepigzdb@gmail.com>

tools: fix region keys typo

---

basic-features.md

The url is used to explain index merge, not index merge join. 

Fix wrong feature name for index merge

---

tidb-binlog/tidb-binlog-overview.md

Fix a dead link in tidb-binlog-overview.md

---

TOC.md

Fix a TOC issue for PDF generation

---

releases/release-3.0.3.md
tidb-lightning/tidb-lightning-distributed-import.md

lightning: add error handler for distributed import

---

tiup/tiup-cluster.md

change-version-for-5.0

---

tiup/tiup-cluster.md

update-version for 5.2

---

tiup/tiup-cluster.md

chang-version-for-5.1

---

tiflash/tiflash-configuration.md

The configuration "tmp_path" in TiFlash config file is required if the user deploy a tiflash instance other than tiup/tidb-operator
master/6.0 are not affected.
5.4/5.3/5.2/5.1/5.0/4.0 are affected.
Note that this PR is base on release-5.4 …

tmp_path is required if user deploy tiflash instance other than tiup/tidb-operator

---

br/use-br-command-line-tool.md

- This PR is translated from: https://github.com/pingcap/docs/pull/7343

Optimize description of restoring system tables

---

tiup/tiup-cluster.md

update audit time for 4.0 tiup cluster.md

---

releases/release-5.1.4.md
releases/release-5.3.1.md

功能增强 --> 提升改进

---

migrate-from-sql-files-to-tidb.md

- Other reference link(s): https://github.com/pingcap/docs-cn/issues/8573

Fix link for Lightning backends

---

tiup/tiup-cluster-topology-reference.md

Fix tiup storage retention

---

information-schema/information-schema.md

Fix a wrong link in info-schema

Fix a wrong link in info-schema

---

benchmark/v5.4-performance-benchmarking-with-tpch.md

Update some descriptions in "benchmark/v5.4-performance-benchmarking-with-tpch.md".
This PR has made the same changes to the PR #7844's [commit b3da841350507d7c38d013ee52f52ae3e4c0e6bd](https://github.com/pingcap/docs-cn/pull/7844/commits/b3da841350507d7c38d013ee52f52ae3e4c0e6bd). Because the doc "benchmark/v5.3-performance-benchmarking-with-tpch.md" in that PR is updated to the v5.4's doc "benchmark/v5.4-performance-benchmarking-with-tpch.md", and the PR's conflict is wrongly fixed, I created this PR to re-revise it.
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE …

update "v5.4 performance benchmarking with tpch"

---

mysql-compatibility.md

Clarified a description about auto-incremental ID

Clarified a description about auto-incremental ID

---

functions-and-operators/miscellaneous-functions.md

- This PR is translated from: https://github.com/pingcap/docs/pull/7816

Update issue number to show GET_LOCK() and RELEASE_LOCK() status

---

.github/workflows/rebase.yml

chore: update rebase secret key

chore: update rebase secret key

---

hardware-and-software-requirements.md

- This PR is translated from: https://github.com/pingcap/docs/pull/7473

List Amazon Linux 2 as supported

---

quick-start-with-tidb.md

- Other reference link(s): https://github.com/pingcap/docs/pull/7859

Add item lists for quick start with tidb

---

configure-placement-rules.md

After running the following command, the terminal reports an error. The reason is that the count field is an integer, while a string is used in the configuration. So we just fixed it by removing the quotes.
```shell
cat > rules.json <<EOF
[{
"group_id": "pd",
"id": "meta",
"index": 1,
"override": true,
"start_key": "6d00000000000000f8",
"end_key": "6e00000000000000f8",
"role": "voter",
"count": "5",
"location_labels": ["zone", "rack", "host"]
}]
EOF
pd-ctl config placement save --in=rules.json
```
```shell
json: cannot unmarshal string into Go struct field RuleOp.count of type int
```
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior …

Fix a problem in configure-placement-rules.md

---

.github/workflows/dispatch.yml

Disable master build to avoid exposing v6.0 docs.
- This PR is translated from: https://github.com/pingcap/docs/pull/7878

disable trigger website building from docs master

---

tidb-lightning/tidb-lightning-error-resolution.md

lightning: add max-err summary output example

---

dm/task-configuration-file-full.md

dm: add new config for lightning

---

choose-index.md
optimizer-hints.md

planner: add explanation about `force_index` and `force index`

---

tiflash/use-tiflash.md

Update function list supported by TiFlash

---

tidb-lightning/tidb-lightning-configuration.md

Lightning supports base64 encoding of password.

lightning: support base64 encoding of password

---

tiflash/monitor-tiflash.md

Signed-off-by: bestwoody <bestwoody@163.com>

update coprocessor of monitor-tiflash.md

---

statistics.md

Add description on how to kill auto analyze
- Other reference link(s): https://github.com/pingcap/tidb/pull/31724

add docs for kill auto analyze

---

sql-plan-management.md
system-variables.md

Add a link to system variable

---

migrate-with-more-columns-downstream.md

dm: remove redundant sentence

---

tiflash/tiflash-command-line-flags.md
tiflash/tiflash-configuration.md

Add dt_compression_method and dt_compression_level config in TiFlash doc.

update tiflash doc add dt_compression_method and dt_compression_level config

---

tiflash/tiflash-configuration.md

Signed-off-by: hehechen <awd123456sss@gmail.com>
Update tiflash-configuration.md, update default value of dt_enable_logical_split

Update tiflash-configuration.md, update default value of dt_enable_logical_split

---

tiflash/use-tiflash.md

refine description about join.
support left semi join.

tiflash: refine description about join push down

---

ticdc/manage-ticdc.md

cdc: add timeout to kafka docs.

---

tiflash/tiflash-configuration.md
tiflash/use-tiflash.md

Version Details of TiFlash Checksum
https://github.com/pingcap/tiflash/pull/4010

doc: update docs for default checksum strategy

---

pd-control.md

Signed-off-by: Cabinfever_B <cabinfeveroier@gmail.com>

Add pdctl balance-leader-scheduler config command

---

tiflash/monitor-tiflash.md

add description for task scheduler, which has been recently added in tiflash_summary.json.

add description for task scheduler

---

explain-mpp.md

- Other reference link(s):https://github.com/pingcap/tidb/pull/31459

tiflash: remove tidb_opt_broadcast_join

---

tikv-configuration-file.md

Changed the default value of `enable` of "raft-engine".
- This PR is translated from: https://github.com/pingcap/docs/pull/7512

enable of "raft-engine": change the default value

---

ticdc/manage-ticdc.md

changed rowid to index-value
- This PR is translated from:https://github.com/pingcap/docs/pull/7904

ticdc: clarify rowid HandleKey meaning 

---

system-variables.md

Signed-off-by: crazycs520 <crazycs520@gmail.com>
update tidb topsql system variable
https://github.com/pingcap/tidb/pull/31599

topsql: update tidb topsql system variable doc

---

ticdc/deploy-ticdc.md

cdc update docs for `cdc server` command.

---

tiflash/tiflash-configuration.md

Signed-off-by: bestwoody <bestwoody@163.com>

update description of TiFlash config: enable_elastic_threadpool

---

TOC.md

- Add table-cache to TOC
- Refine the position of DM WebUI

v6.0: adjust TOC

---

tikv-configuration-file.md

tikv: configuration change 6.0

---

dm/task-configuration-file-full.md

fixed a typo

---

faq/sql-faq.md
mysql-compatibility.md
privilege-management.md
sql-statements/sql-statement-load-data.md
tikv-configuration-file.md

+ Support LOAD DATA REPLACE INTO
+ Refine the wording for 2 TiKV configs
- This PR is translated from: https://github.com/pingcap/docs/pull/7976 https://github.com/pingcap/docs/pull/7426 https://github.com/pingcap/docs/pull/7915

update LOAD DATA ... REPLACE compatibility

---

dashboard/top-sql.md
system-variables.md

Update the default setting of Top SQL

---

releases/release-5.3.0.md

- Fix format
- Change the description of Prometheus v2.27.1 from "2021 年发布的较新版本" to "2021 年 5 月发布的版本" 

Fix format and define Prometheus v2.27.1's release time in release-5.3.0.md

---

tikv-configuration-file.md

modify configuration description for disable-auto-compactions

modify configuration description

---

releases/release-5.2.0.md
tidb-configuration-file.md

Remove stmt-summary config in v6.0

tidb: remove stmt-summary config

---

schedule-replicas-by-topology-labels.md

Updated descriptions of PD's `location-lable`.
- This PR is translated from: https://github.com/pingcap/docs/pull/7432

update PD's `location-lable`

---

dynamic-config.md
tikv-configuration-file.md

tikv: add missing config threshold for some online config

---

tiflash/tiflash-overview.md

Add tiflash repo link to overview

---

tikv-configuration-file.md

- Disable Raft Engine by default
- Add a note to remind users that this feature is an experimental feature
- Other reference link(s): https://github.com/tikv/tikv/pull/12317

Disable Raft Engine by default

---

placement-rules-in-sql.md

- This PR is translated from: https://github.com/pingcap/docs/pull/8011

fix typo in placement rules

---

production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
tiup/tiup-bench.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

tiup-bump-version-6.0

---

dm/dm-overview.md

commented out incorrect links

---

tiup/customized-montior-in-tiup-environment.md

- Other reference link(s): https://github.com/pingcap/docs/pull/8007

Change monitoring_servers to grafana_servers

---

clinic/clinic-user-guide-for-tiup.md

Clinic: Revise a link

---

identify-expensive-queries.md

Fix typo: set pesudo to `pseudo`

Fix typo: set `stats` value to `pseudo`

---

ticdc/integrate-confluent-using-ticdc.md

fix wrong jdbc sqlite url in ticdc confluent integration doc

---

tidb-configuration-file.md

Signed-off-by: Jack Yu <jackysp@gmail.com>
`grpc-compression-type` is missing to add to the documents and it doesn't have some known issues. So add it.

tidb-configuration-file.md: add grpc-compression-type

---

placement-rules-in-sql.md

- This PR is translated from: https://github.com/pingcap/docs/pull/8066

placement-rules-in-sql: add some lightning descriptions

---

pd-control.md

According to Line 768 in "pd-control.md" in [#7998](https://github.com/pingcap/docs/pull/7998), a link for the `store limit` command is added to "pd-control.md".
- Other reference link(s): https://github.com/pingcap/docs/pull/7998

PD Control: add a line about `store limit`

---

clinic/clinic-user-guide-for-tiup.md

This PR is manually created to revise the same contents in [#8841](https://github.com/pingcap/docs-cn/pull/8841).
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/8841

Clinic: Revise a link for 6.0 branch

---

placement-rules-in-sql.md

- EN PR: https://github.com/pingcap/docs/pull/8071

Add alter partition demo in placement in sql

---

blocklist-control-plan.md
explain-overview.md

The titles for explain-overview.md in TOC and in the document are inconsistent. This PR unifies the title.

Unify title for explain-overview

---

tiflash/use-tiflash.md

- Other reference link(s): https://github.com/pingcap/docs/pull/8077

Adjust the structure of replica creation and az setting

---

mysql-compatibility.md
releases/release-5.3.0.md
sql-statements/sql-statement-select.md
system-variables.md

align multiple pr for sql
- This PR is translated from: https://github.com/pingcap/docs/pull/7095 https://github.com/pingcap/docs/pull/6716 https://github.com/pingcap/docs/pull/6838

align multiple pr sql

---

.github/workflows/dispatch.yml

This reverts commit fad79f77da7345749bcfae21a20f78e047788900.

Revert "disable trigger website building from docs master (#8705)"

---

ticdc/deploy-ticdc.md

- Clarify the ambiguous description of `data-dir` free space
- Fix typo and format

Clarify the ambiguous description of `data-dir` free space

---

dm/feature-expression-filter.md

Remove aliases from feature-expression-filter.

Remove aliases from feature-expression-filter

---

releases/release-6.0.0-dmr.md
tiflash/tiflash-configuration.md

refine cn-name of elastic thread pool

---

releases/release-6.0.0-dmr.md

Put `new features` before `compatibility changes`.

releases: change the order of new features and compatibility changes

---

tiflash/use-tiflash.md

add semicolon for sqls
- Other reference link(s): https://github.com/pingcap/docs/pull/8077

Update use-tiflash.md: add semicolon for sqls

---

tiflash/use-tiflash.md

Fix improper title levels of use tiflash

---

releases/release-6.0.0-dmr.md
sql-prepare-plan-cache.md

- `tidb_ignore_clost_stmt_cmd` => `tidb_ignore_prepared_cache_close_stmt`(used in other docs and source codes)
- `Preapre Statement` => `Prepare Statement`
the English documents also need to be fixed.
N/A

fix typo "tidb_ignore_clost_stmt_cmd" in tidb 6.0.0 release notes

---

migration-overview.md
sql-statements/sql-statement-set-names.md

Remove aliases from migration-overview.md and sql-statement-set-names.md.

Remove aliases from migration-overview.md and sql-statement-set-names.md

---

tidb-binlog/binlog-consumer-client.md

Update binlog.proto file link.

update binlog proto URI

---

credits.md

- This PR is translated from: https://github.com/pingcap/docs/pull/8080

Add TiFlash to the credits.md

---

query-execution-plan.md

Remove aliases from query-execution-plan.md.

Remove aliases from query-execution-plan.md

---

query-execution-plan.md
tidb-lightning/tidb-lightning-faq.md

Remove aliases from query-execution-plan.md and tidb-lightning-faq.md.

Remove aliases from query-execution-plan.md and tidb-lightning-faq.md

---

dashboard/dashboard-user.md

- Fix format
- Add RBAC authorize example desc

Add RBAC desc and fix format for Dashboard user management

---

sync-diff-inspector/sync-diff-inspector-overview.md

sync-diff: fix the download link in v3.0

---

sync-diff-inspector/sync-diff-inspector-overview.md

Remove the download link in v3.1，because we don't have the v3.1 version tools. 

sync-diff: remove the download link in v3.1

---

sync-diff-inspector/sync-diff-inspector-overview.md

sync-diff: fix the download link in v5.1

---

system-variables.md

Remove the default value `2` of `idb_analyze_version` in release-5.1.
- This PR is translated from: https://github.com/pingcap/docs/pull/8073

Remove the default value of `idb_analyze_version` in v5.1 and v5.2

---

tidb-troubleshooting-map.md

Clarify the meaning of small transaction for TTL

---

grafana-tidb-dashboard.md

ref https://github.com/pingcap/docs-cn/issues/8947

fix description of OPM

---

system-variables.md

system-variables: document tidb-enable-alter-placement
- This PR is translated from: https://github.com/pingcap/docs/pull/6588

system-variables: document tidb-enable-alter-placement

---

.github/pull_request_template.md
README.md

chore: add 6.1 in pr template

---

dumpling-overview.md

update dumpling eg format

---

exporting-grafana-snapshots.md

Add a warning in exporting-grafana-snapshots.md

---

statement-summary-tables.md
system-variables.md

Revert #8186 in release-5.4

---

upgrade-tidb-using-tiup.md

Revised a wrong part in "upgrade-tidb-using-tiup.md".

TiUP: revise a wrong link

---

exporting-grafana-snapshots.md

Revise the format of a warning in "exporting-grafana-snapshots.md"
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/8927

Revise the format of a warning in exporting-grafana-snapshots.md

---

upgrade-tidb-using-tiup.md

- Other reference link(s): https://asktug.com/t/topic/662840

Add a warning about upgrading tiflash using tiup

---

ticdc/ticdc-overview.md

ticdc: update overview

---

tispark-overview.md

Remove spark-defaults.conf in statistics.
- This PR is translated from: https://github.com/pingcap/docs/pull/8205

Remove spark-defaults.conf in statistics

---

quick-start-with-tidb.md

Modify Mac to macOS in quick-start-with-tidb.md.

Modify Mac to macOS in quick-start-with-tidb.md

---

placement-rules-in-sql.md

- This PR is translated from: https://github.com/pingcap/docs/pull/8278

Fix example errors in placement-rules-in-sql.md

---

TOC.md
br/backup-and-restore-tool.md
table-filter.md

Add backup-and-restore-using-dumpling-lightning.md to TOC of the 4.0 branch

---

sql-statements/sql-statement-modify-column.md

Modify column signed int to unsigned int also raises ERROR 8200
- This PR is translated from: https://github.com/pingcap/docs/pull/7744

Modify column signed int to unsigned int also raises ERROR 8200

---

dashboard/dashboard-key-visualizer.md

Dashboard: fix typo on dashboard-key-visualizer.md

---

tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs/pull/7378

update raft log gc related tikv configurations

---

alert-rules.md

Fixed the rule of TiKV_GC_can_not_work

Fix the rule of TiKV_GC_can_not_work

---

br/backup-and-restore-storages.md

- [ x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.
add aliyun oss example
https://help.aliyun.com/document_detail/185803.html

add aliyun oss example

---

.github/workflows/rebase.yml

- Update cirrus-actions from v1.4 to [v1.6](https://github.com/cirrus-actions/rebase/releases/tag/1.6) to fix the unsafe repository problem when /rebase.
- Since the rebase is running on a Docker container, add `git config --global --add safe.directory /github/workspace` in `rebase.yml` will fail.

Actions: Fix "fatal: unsafe repository" in rebase.yml

---

two-data-centers-in-one-city-deployment.md

Refine the format of JSON and add one more method to change pd config in placement rules

---

tidb-lightning/tidb-lightning-configuration.md
tidb-lightning/tidb-lightning-glossary.md

fix-description-checksum

---

migrate-large-mysql-shards-to-tidb.md
tidb-lightning/tidb-lightning-configuration.md

Replace `route` with `mydumper.files` due to `route` feature not GA yet

---

tikv-configuration-file.md

Updated the values of `compaction-style`.
- This PR is translated from: https://github.com/pingcap/docs/pull/7375

TiKV Config: Update the values of `compaction-style`

---

migrate-large-mysql-shards-to-tidb.md

Change copyable "shell-regular" to copyable "sql"

---

dumpling-overview.md

expand dumpling example parameter 

add dumpling parameter

---

tiup/tiup-faq.md

Fix typo of macOS in tiup-faq.md.

Fix typo of macOS in tiup-faq.md

---

tikv-configuration-file.md

Signed-off-by: Connor1996 <zbk602423539@gmail.com>
Add flow-control config override hint
- Other reference link(s): https://github.com/tikv/tikv/pull/11840

tikv: add flow-control config override hint

---

tiflash-deployment-topology.md

close https://github.com/pingcap/docs-cn/issues/6849

Unify IP addresses in tiflash config doc and the config file

---

benchmark/v5.4-performance-benchmarking-with-tpch.md

- Other reference link(s): https://github.com/pingcap/docs-cn/issues/9137, https://github.com/pingcap/docs-cn/pull/9140

Add hardware configurations and aliases to 5.4 tpch

---

develop/delete-data.md
develop/developer-guide-overview.md
develop/get-data-from-single-table.md
develop/join-tables.md
develop/optimistic-and-pessimistic-transaction.md
develop/paginate-results.md
develop/prepared-statement.md
develop/sample-application-java.md
develop/stale-read.md
develop/temporary-table.md
develop/update-data.md

[Update] add href in SimpleTab to unique URL

---

download-ecosystem-tools.md
pd-control.md
pd-recover.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
sync-diff-inspector/sync-diff-inspector-overview.md
ticdc/manage-ticdc.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

v5.2.4: Bump version for v5.2 docs

---

tikv-configuration-file.md

Updated the value of `wal-recovery-mode`, `rate-limiter-mode`, `compaction-pri`, and `compaction-style`.
- This PR is translated from: https://github.com/pingcap/docs/pull/7376

TiKV Config: Update some optional values of TiKV configuration items

---

develop/bookshop-schema-design.md
develop/build-cluster-in-cloud.md
develop/choose-driver-or-orm.md
develop/connect-to-tidb.md
develop/connection-parameters.md
develop/create-database.md
develop/create-secondary-indexes.md
develop/create-table.md
develop/delete-data.md
develop/developer-guide-overview.md
develop/timeouts-in-tidb.md
develop/update-data.md

add cloud doc url and periods

---

faq/manage-cluster-faq.md

Update an FAQ added in https://github.com/pingcap/docs-cn/pull/8997 according to discussion.

Update an FAQ according to discussion

---

.github/pull_request_template.md

remove legacy versions from pr template because they no longer accept PRs.

remove legacy versions from pr template

---

character-set-and-collation.md
information-schema/information-schema-collations.md
mysql-compatibility.md

- This PR is translated from: https://github.com/pingcap/docs/pull/7920 https://github.com/pingcap/docs/pull/8364

Align 2 PRs from docs about collations

---

quick-start-with-tidb.md

Fix dead link to TiDB Cloud quick start guide

---

CONTRIBUTING.md
README.md
dm/dm-overview.md

- This PR is translated from: https://github.com/pingcap/docs/pull/8389

Update the slack channel to internals

---

ticdc/ticdc-overview.md
tidb-binlog/tidb-binlog-overview.md
tidb-lightning/tidb-lightning-overview.md

- Other reference link(s): https://github.com/pingcap/docs-cn/issues/9226

Correct the video length of tidb binlog, tidb lightning, and ticdc

---

two-data-centers-in-one-city-deployment.md

add rollback step

---

mysql-compatibility.md

- This PR is translated from: https://github.com/pingcap/docs/pull/8381

Document four unsupported mysql syntax and statements

---

TOC.md
migrate-from-tidb-to-tidb.md
replicate-data-to-kafka.md

TiCDC: Update file name to keep bilingual consistency

---

tispark-overview.md

add aliases for a tispark file deleted in https://github.com/pingcap/docs-cn/pull/8985
- This PR is translated from: https://github.com/pingcap/docs/pull/8474

Add aliases to tispark

---

develop/sample-application-spring-boot.md

remove the needless blank space.

Remove a redundant space in sample-application-spring-boot.md

---

ticdc/manage-ticdc.md

fix sinkURI typo. We do not support multi-protocol. So remove `protocol=canal`.

ticdc: fix sinkURI typo

---

two-data-centers-in-one-city-deployment.md

Revise the rollback step in "two-data-centers-in-one-city-deployment.md".
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/9174

revise the rollback step

---

releases/release-6.0.0-dmr.md
sql-statements/sql-statement-show-collation.md

Fix a typo in 6.0 release notes and update collation results
Close https://github.com/pingcap/docs-cn/issues/9266 https://github.com/pingcap/docs-cn/issues/9265

Fix a typo in 6.0 release notes

---

benchmark/v5.4-performance-benchmarking-with-tpch.md

Add back 5.4 tpch report

---

benchmark/v5.4-performance-benchmarking-with-tpch.md

tpch: Correct aliases

---

develop/use-temporary-tables.md

Describe how to drop global temporary tables

dev: update temporary table dev doc

---

whats-new-in-tidb-4.0.md

add missing alias to fix broken link
- This PR is translated from: https://github.com/pingcap/docs/pull/8503

add missing alias to fix broken link

---

config-templates/complex-tiflash.yaml

add [tiflash-learner] configuration

update some topoloy

---

develop/index-best-practice.md
develop/optimize-sql-best-practices.md
develop/optimize-sql.md

Signed-off-by: crazycs520 <crazycs520@gmail.com>

develop: remove todo

---

develop/optimize-sql.md

[Debug] running result can not copyable

---

develop/sample-application-java.md

[Debug] hide real url

---

replicate-between-primary-and-secondary-clusters.md

- Other reference link(s): https://github.com/pingcap/docs/pull/8457

Add missing parameters in creating a changefeed

---

develop/paginate-results.md

- Other reference link(s): close https://github.com/pingcap/docs-cn/issues/9331

develop: use users table as the NONCLUSTERED paginate example

---

TOC.md

Move Glossary after Release Notes.
- This PR is translated from: https://github.com/pingcap/docs/pull/8525

Move Glossary after Release Notes

---

ticdc/manage-ticdc.md

remove unsupported kafka auth type. We do not support plain.

ticdc: remove unsupported kafka auth type

---

releases/release-5.2.4.md
releases/release-6.0.0-dmr.md

Insert a space between Chinese character and English character.

Insert a space between Chinese character and English character

---

production-deployment-using-tiup.md

production deployment using tiup: Replace tiflash config file with config.toml

---

tiup/tiup-cluster-topology-reference.md

update how to config initial-commit-ts on tiup v1.9.2

---

ticdc/manage-ticdc.md
ticdc/troubleshoot-ticdc.md

ticdc: synchronize data in the new collations

---

develop/delete-data.md

fix minor errors

---

explain-subqueries.md

Fix misleading agg function

---

garbage-collection-overview.md

Update gc full process

---

tiflash/tiflash-overview.md

Update tiflash architecture image

---

mysql-compatibility.md
releases/release-5.3.0.md
statistics.md
system-variables.md

- This PR is translated from: https://github.com/pingcap/docs/pull/7163 https://github.com/pingcap/docs/pull/7077 https://github.com/pingcap/docs/pull/7371 https://github.com/pingcap/docs/pull/6769 https://github.com/pingcap/docs/pull/8609

Align 4 PRs

---

alert-rules.md

Update an outdated TiKV alert in v5.3 according to https://github.com/tikv/tikv/blob/v5.3.0/metrics/alertmanager/tikv.rules.yml#L17.

Update an outdated TiKV alert in v5.3

---

releases/release-6.0.0-dmr.md

Add asktug link to 6.0.0 release notes.

add asktug link to 6.0.0 release notes

---

grafana-performance-overview-dashboard.md
performance-tuning-methods.md
performance-tuning-overview.md
performance-tuning-practices.md

chore: add aliases for the removed performance overview docs from v6.0

---

statement-summary-tables.md

statement-summary-tables: fix a broken link

---

auto-random.md

Sync the changes from https://github.com/pingcap/docs/pull/7475.
- This PR is translated from: https://github.com/pingcap/docs/pull/7475

auto-random.md: update docs

---

data-type-string.md

fix length limitations of longtext and longblob

---

.github/workflows/dispatch.yml

Pause website build for master branch.

ci: pause master build

---

tiflash/use-tiflash.md

Add docs about window function push down to tiflash.

tiflash: add docs about window function push down to tiflash

---

hardware-and-software-requirements.md

Bilingual inconsistency is found in the notes part of the [Linux 操作系统版本要求](hardware-and-software-requirements.md#linux-操作系统版本要求): Three notes are deleted by mistake in https://github.com/pingcap/docs-cn/pull/6263. This PR is to add them back.

Linux OS support: add back three notes and change date description

---

tikv-configuration-file.md

tikv: fix some error for tikv config
- This PR is translated from: https://github.com/pingcap/docs/pull/8672

tikv: fix some error for tikv config

---

pd-control.md

Add a new config in pd-ctl
- Other reference link(s): tikv/pd#4640

Add `max-store-preparing-time` in pd-ctl

---

placement-rules-in-sql.md
schedule-replicas-by-topology-labels.md

Refine Placement Rules related docs according to discusstion.

Refine Placement Rules related docs

---

system-variables.md

Add the description for new system variable to control the outer join reorder.

system variable: add the switch control for outer join reorder

---

.github/exclude-links.txt

Exclude 4 links from link checker (https://github.com/pingcap/docs-cn/issues/9478)

ci: exclude 4 links

---

system-variables.md

Add the description for new variable.

system-variables: add the description of `tidb_enable_new_only_full_group_by_check`

---

exporting-grafana-snapshots.md

Add warning for MetricsTool in v6.1

Add warning for MetricsTool

---

non-transactional-dml.md
sql-statements/sql-statement-batch.md

Fix the format of nt-dml docs

---

tikv-configuration-file.md

Signed-off-by: Xintao <hunterlxt@live.com>
Add a new tikv config item `background-error-recovery-window`

tikv: add a new config item `background-error-recovery-window`

---

ticdc/manage-ticdc.md

Add description for Kafka multi-topic feature

---

dm/dm-overview.md
dm/task-configuration-file-full.md

fix aliases

---

production-deployment-using-tiup.md

add toolkit package merge step

---

download-ecosystem-tools.md

download-ecosystem-tools: remove a step

---

tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs/pull/8677

v6.1: enable raft engines by default

---

TOC.md
sql-statements/sql-statement-alter-table-compact.md
sql-statements/sql-statement-alter-table.md
tiflash/tiflash-configuration.md

Signed-off-by: Wish <breezewish@outlook.com>
Add docs for the new `ALTER TABLE ... COMPACT` syntax.
TODO: Update Release Note for this new feature.
- Other reference link(s): 
- This new syntax is introduced by https://github.com/pingcap/tidb/pull/34741

docs: ALTER TABLE COMPACT

---

pd-configuration-file.md

Add `max-store-preparing-time` to pd config file.

Add `max-store-preparing-time` to pd config file

---

sql-statements/sql-statement-kill.md
statistics.md
tidb-configuration-file.md

Update docs about global kill.
- Other reference link(s): https://github.com/pingcap/tidb/issues/8854

update docs about global kill

---

_index.md
overview.md

Add aliases

---

_index.md
overview.md

Remove aliases in release-4.0.

Remove aliases in release-4.0

---

pd-configuration-file.md
pd-control.md

Make the `max-store-preparing-time` more accurate

---

non-transactional-dml.md
system-variables.md

Signed-off-by: ekexium <ekexium@gmail.com>

fix the link in non-transactional-dml.md

---

sql-statements/sql-statement-add-column.md

add-column.md: refine the sqlgram

---

production-deployment-using-tiup.md
quick-start-with-tidb.md

quick start: add summary

---

functions-and-operators/tidb-functions.md

Modify to shard index

---

ticdc/manage-ticdc.md

Add Kafka authentication and authorization description in TiCDC

---

join-reorder.md

- Other reference link(s): https://github.com/pingcap/docs-cn/pull/9558

v6.1: update join reorder according to the new feature

---

alert-rules.md

Change rockdb.defaultcf to rocksdb.defaultcf

fix a typo: change rockdb.defaultcf to rocksdb.defaultcf

---

auto-increment.md
mysql-compatibility.md

suggest using auto_random instead of auto_increment

---

releases/release-6.0.0-dmr.md

tiem: rename tiem to tidb enterprise manager

tiem: rename tiem to tidb enterprise manager

---

tiflash/use-tiflash.md

fix wrong name import in https://github.com/pingcap/docs-cn/pull/9541
rown_number->row_number

tiflash: correct window desc name.

---

releases/release-6.0.0-dmr.md
system-variables.md

Change the default values of these system variables:
* `tidb_enable_mutation_checker`: `OFF` -> `ON`
* `tidb_txn_assertion_level`: `OFF` -> `FAST`

Fix two sysvars' default values.

---

tune-region-performance.md

Add Region size suggestion when using Dumpling.

Add Region size suggestion when using Dumpling

---

online-unsafe-recovery.md

Change command in online unsafe recovery doc

---

functions-and-operators/tidb-functions.md
garbage-collection-configuration.md

Signed-off-by: TonsnakeLin <lpbgytong@163.com>

gc: add notes for tidb_gc_max_wait_time

---

tiflash/tiflash-configuration.md

TiFlash v6.1 by default use `format_version = 3`.

Revert "Changed format_version default value to 4 (#9507)"

---

.github/workflows/dispatch.yml

disable dispatch 6.1 for now

---

best-practices/high-concurrency-best-practices.md
releases/release-5.3.0.md
tidb-configuration-file.md

`txn-local-latches` configs were removed in https://github.com/pingcap/tidb/pull/15765
- Other reference link(s): https://github.com/pingcap/tidb/pull/15765

remove txn-local-latches from config

---

system-variables.md
tidb-configuration-file.md

v6.1: add experimental warning
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/9585

v6.1: add experimental warning

---

tikv-configuration-file.md

Signed-off-by: pingyu <yuping@pingcap.com>
Fix configuration item `storage.api-version` to right position.

tikv: Fix api-version position

---

production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

tiup bump version 6.1

---

tikv-configuration-file.md
tune-region-performance.md

Add experimental warning for customized region size

---

migrate-small-mysql-shards-to-tidb.md

fix table format

---

sql-statements/sql-statement-add-index.md
sql-statements/sql-statement-alter-index.md
sql-statements/sql-statement-change-column.md
sql-statements/sql-statement-drop-column.md
sql-statements/sql-statement-drop-index.md
sql-statements/sql-statement-modify-column.md
sql-statements/sql-statement-rename-index.md

sql-statement: refine the sqlgram for alter table

---

troubleshoot-data-inconsistency-errors.md

Signed-off-by: ekexium <ekexium@gmail.com>

fix explanation of error 8134

---

clinic/clinic-introduction.md

Add Operator links in clinic-introduction.md

Add Operator links in clinic-introduction.md

---

tune-tikv-memory-performance.md

Remove dynamic-config experimental since v6.1.0

Remove dynamic-config experimental since v6.1.0

---

releases/release-6.1.0.md

fix release notes

---

TOC.md
benchmark/v6.1-performance-benchmarking-with-tpch.md

add tpch for v6.1

---

releases/release-6.1.0.md
releases/release-timeline.md

update release date

---

ticdc/manage-ticdc.md
ticdc/ticdc-avro-protocol.md

make kafka topic rule clear for avro codec

---

develop/dev-guide-build-cluster-in-cloud.md

dev-guide: update Cloud signup URL

---

sql-statements/sql-statement-alter-table-compact.md

Synced some wording change applied in the EN translation https://github.com/pingcap/docs/pull/8722
- This PR is translated from: https://github.com/pingcap/docs/pull/8722

Update wording for ALTER TABLE COMPACT

---

table-attributes.md

trigger pdf build

---

.github/workflows/ci.yaml

ci: update node-version to 16

---

releases/release-6.1.0.md

trigger build: 6.1.0 release notes

---

.github/workflows/link.yaml

- Other reference link(s): https://github.com/pingcap/docs/pull/8894

ci: Use lycheeignore to check broken links

---

explore-htap.md

Close https://github.com/pingcap/docs/issues/8945

tispark: remove description of not supporting Spark 3.x

---

dashboard/dashboard-faq.md

Add a help for ngm not started error when deployed using TiUP Playground.

TiDB Dashboard: Add help for ngm using TiUP Playground

---

migrate-aurora-to-tidb.md

This PR is to fix 404 page detected in GA:

DM: fix 404 caused by removing a dm doc without aliases to stable

---

develop/dev-guide-sample-application-java.md

Close https://github.com/pingcap/docs-cn/issues/9508

[Update] add mybatis example

---

develop/dev-guide-object-naming-guidelines.md

[Update] v6.1 removed lower-case-table-name option

---

releases/release-6.1.0.md
sql-statements/sql-statement-show-variables.md
system-variables.md

6.1: delete tidb_enable_batch_dml

6.1: delete tidb_enable_batch_dml

---

br/backup-and-restore-overview.md

- Other reference link(s): https://github.com/pingcap/docs-tidb-operator/issues/1864

br: fix 404 for backup and restore tool in stable

---

dm/dm-overview.md
releases/release-2.1.8.md
releases/release-3.0.0-beta.1.md
releases/release-3.0.0-rc.1.md

fix broken links
close https://github.com/pingcap/docs-cn/issues/9820

fix broken links

---

releases/release-6.1.0.md

fix dynamic pruning description

---

mysql-compatibility.md

Fix format in mysql-compatibility.md

---

auto-increment.md

close https://github.com/pingcap/docs-cn/issues/9781
- This PR is translated from: https://github.com/pingcap/docs/pull/6911

auto_increment: improve description of monotonic

---

partitioned-table.md

Update an example of partitioned table

Update an example of partitioned table

---

.github/pull_request_template.md

chore: add 6.2 to and remove 6.0 and 4.0 from pr template

---

TOC.md

Fix a TOC display issue

---

tikv-control.md

tikv-control: make a parameter in right places

tikv-control: make a parameter in right places

---

sql-statements/sql-statement-kill.md

sql-statement-kill: remove a typo

---

faq/manage-cluster-faq.md

Fix https://github.com/pingcap/docs/issues/6538

faq: add tiunimanager as a graphical tool

---

tikv-configuration-file.md

Signed-off-by: 5kbpers <hustmh@gmail.com>
close https://github.com/pingcap/docs-cn/issues/9877
Add description about report-region-buckets-tick-interval in `tikv-configuration-file.md`

Add description about report-region-buckets-tick-interval

---

telemetry.md

- TiSpark has telemetry in master branch and will have release the telemetry function in the next version. So we should add TiSpark telemetry instructions in telemtry.md.
- Other reference link(s): [TiSpark Telemetry](https://github.com/pingcap/tispark/blob/master/docs/telemetry.md)

[Update] Add TiSpark telemetry 

---

check-before-deployment.md

Translate from https://github.com/pingcap/docs/pull/8838
- This PR is translated from: https://github.com/pingcap/docs/pull/8838

Add deploy tidb-test step before exec command

---

subquery-optimization.md

Fix a typo in the sql statement.

fix a typo in subquery optimization

---

tiup/tiup-bench.md

add a tutorial of ycsb bench in TiUP

---

tiunimanager/tiunimanager-install-and-maintain.md

Rearrange order for the offline installation to avoid misoperation.

tiunimanager: rearrange order

---

pd-control.md

add tikv label merge policy description

---

performance-tuning-overview.md
performance-tuning-practices.md

performance tuning: minor wording updates

---

generated-columns.md

Add examples for generated columns

Add examples for generated columns

---

config-templates/complex-tidb-binlog.yaml
deploy-monitoring-services.md
ticdc/manage-ticdc.md
ticdc/ticdc-canal-json.md
tidb-binlog/binlog-consumer-client.md
tidb-binlog/deploy-tidb-binlog.md

The Grafana and Kafka versions in the current docs are outdated.

Update Grafana and Kafka versions

---

best-practices/haproxy-best-practices.md

Update a path in haproxy guide

Update a path in haproxy guide

---

br/br-usage-restore.md

br: change storage path

---

releases/release-6.1.0.md

Fix a wrong issue numer in 6.1 rn

Fix a wrong issue numer in 6.1 rn

---

releases/release-6.1.0.md

- This PR is translated from: https://github.com/pingcap/docs/pull/8939

Use 'Rails' not 'RoR' to talk about Ruby on Rails

---

benchmark/v5.4-performance-benchmarking-with-tpcc.md

- This PR is translated from: https://github.com/pingcap/docs/pull/8903

Fix a typo in v5.4-performance-benchmarking-with-tpcc

---

best-practices/high-concurrency-best-practices.md
deploy-monitoring-services.md
tidb-troubleshooting-map.md

remove links to tidb-ansible
- This PR is translated from: https://github.com/pingcap/docs/pull/8834

remove links to tidb-ansible

---

functions-and-operators/json-functions.md

json-functions: Update status and links
- This PR is translated from: https://github.com/pingcap/docs/pull/8762

json-functions: Update status and links

---

develop/dev-guide-sample-application-spring-boot.md

XML Formatted.
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/9321

[Debug] xml format

---

tiunimanager/tiunimanager-login-and-initialize.md
tiunimanager/tiunimanager-release-notes.md

tiunimanager: clarify the x86 version

tiunimanager: clarify the x86 version

---

releases/release-timeline.md

fix release timeline

---

releases/release-6.0.0-dmr.md

trigger pdf build for release-6.0

---

best-practices/high-concurrency-best-practices.md

- This PR is translated from: https://github.com/pingcap/docs/pull/6808

high-concurrency-best-practices: improve example

---

TOC.md

Move dm architecture to a more obvious position in TOC. As per the discussion.

dm: move up dm arch doc

---

develop/dev-guide-use-common-table-expression.md
develop/dev-guide-use-temporary-tables.md

develop: fix the read data codes

---

tikv-configuration-file.md

Add detailed suggestions for configuring `max-bytes-for-level-base`.
The contents are mostly translated from https://github.com/tikv/tikv/blob/b6cad4e9d989840a9b69465df2706c985ba8b00b/etc/config-template.toml#L689
Because this is an enhancement type change, simply cherry-picking to v6.1 should suffice.
- This PR is …

add more description for max-bytes-for-level-base

---

ticdc/ticdc-overview.md

Close https://github.com/pingcap/docs-cn/issues/10318

ticdc: fix faq link

---

best-practices/massive-regions-best-practices.md
pd-control.md

remove >> in code block
Close https://github.com/pingcap/docs-cn/issues/10305

fix format: remove >> in code block

---

configure-placement-rules.md

Fix typos in placement rules command

Fix typos in placement rules command

---

dm/dm-overview.md

docs.pingcap.com/zh/tidb-data-migration returns 404. We expect the link to redirect users to the overview page of DM.

dm: fix a 404 link

---

tiunimanager/tiunimanager-install-and-maintain.md

tiunimanager: fix version inconsistency issue
close https://github.com/pingcap/docs-cn/issues/10365

tiunimanager: fix version inconsistency issue

---

releases/release-5.3.2.md
releases/release-6.1.0.md

fix 404 link in release notes

---

upgrade-tidb-using-tiup.md

- Other reference link(s): https://github.com/pingcap/docs-cn/pull/10358

tiflash: update upgrade warning

---

TOC.md
releases/release-5.1.0.md
sql-statements/sql-statement-rename-user.md

The `rename user` was supported from v5.1.0 but is not documented.
- Other reference link(s): https://github.com/pingcap/tidb/pull//24413

add the doc for `rename user`

---

br/br-deployment.md

Close https://github.com/pingcap/docs-cn/issues/10391

fix typo in `SHOW BACKUPS|RESTORES` command

---

table-filter.md

Close https://github.com/pingcap/docs-cn/issues/10393

table filter: remove unfriendly special symbols

---

non-transactional-dml.md

fix a link to common-table-expression

---

check-before-deployment.md
download-ecosystem-tools.md
pd-control.md
pd-recover.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
sync-diff-inspector/sync-diff-inspector-overview.md
ticdc/manage-ticdc.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

bump versions for v5.4.2

---

br/backup-and-restore-design.md
br/backup-and-restore-overview.md
migrate-from-tidb-to-tidb.md
releases/release-3.1.0-ga.md
replicate-between-primary-and-secondary-clusters.md

Close https://github.com/pingcap/docs-cn/issues/10384

br: update br code repo address

---

alert-rules.md
troubleshoot-high-disk-io.md

Modify the description of P99 from .99 to 99%

---

system-variables.md

system variable: remove unnecessary examples

---

system-variables.md

Fix a typo for tidb_restricted_read_only

---

develop/dev-guide-connection-parameters.md
develop/dev-guide-timeouts-in-tidb.md

[Debug] wait_timeout default value changed

---

sql-statements/sql-statement-drop-index.md

Close https://github.com/pingcap/docs-cn/issues/10443.
`DROP INDEX idx ON TABLE t` is an alias of `ALTER TABLE t DROP INDEX idx`. There already exists the `ALTER TABLE` doc. Since the title of the doc `sql-statements/sql-statement-drop-index.md` is `DROP INDEX`, it's better to describe the syntax of `DROP INDEX`.
- Other reference …

update the doc of `drop index`

---

tispark-deployment-topology.md

废弃 tiup tispark 组件

---

ticdc/manage-ticdc.md

ticdc: add a warning for the eventually consistent replication feature

---

quick-start-with-tidb.md

fix incorrect relationship between x86_64 and arm

---

tiflash/maintain-tiflash.md

close https://github.com/pingcap/docs-cn/issues/10497 and https://github.com/pingcap/docs-cn/issues/10496

tiflash: add a missing field and fix format

---

develop/dev-guide-optimize-sql-best-practices.md

Close https://github.com/pingcap/docs-cn/issues/10463

[Update] add CREATE INDEX statement in add index optmize doc

---

tidb-lightning/monitor-tidb-lightning.md

Close https://github.com/pingcap/docs/issues/9585

tidb lightning: fix old download location for lightning.json

---

best-practices/pd-scheduling-best-practices.md
dynamic-config.md
pd-configuration-file.md
pd-control.md

- This PR is translated from: https://github.com/pingcap/docs/pull/9592

add unit of schedule.max-merge-region-size

---

experimental-features.md

Remove GA features from experimental doc

Remove GA features from experimental doc

---

sync-diff-inspector/sync-diff-inspector-overview.md

sync-diff-inspector: fix typos

---

develop/dev-guide-sql-development-specification.md

Close https://github.com/pingcap/docs-cn/issues/10595

[Debug] specification typo

---

.github/workflows/dispatch.yml

disable trigger website building from master

---

develop/dev-guide-bookshop-schema-design.md
develop/dev-guide-build-cluster-in-cloud.md
develop/dev-guide-delete-data.md
develop/dev-guide-get-data-from-single-table.md
develop/dev-guide-hybrid-oltp-and-olap-queries.md
develop/dev-guide-insert-data.md
develop/dev-guide-join-tables.md
develop/dev-guide-optimistic-and-pessimistic-transaction.md
develop/dev-guide-optimize-sql-best-practices.md
develop/dev-guide-optimize-sql.md
develop/dev-guide-paginate-results.md
develop/dev-guide-prepared-statement.md
develop/dev-guide-sample-application-golang.md
develop/dev-guide-sample-application-java.md
develop/dev-guide-transaction-restraints.md
develop/dev-guide-update-data.md
develop/dev-guide-use-common-table-expression.md
develop/dev-guide-use-follower-read.md
develop/dev-guide-use-stale-read.md
develop/dev-guide-use-temporary-tables.md

develop: fix simpletab

---

production-deployment-using-tiup.md

remove SimpleTab tag

---

sql-statements/sql-statement-show-processlist.md

doc: add explain for show-processlist

---

information-schema/information-schema-tidb-indexes.md

doc: update information_schema tidb_index 

---

tidb-limitations.md

add TiKV minimal version limit.

---

sync-diff-inspector/sync-diff-inspector-overview.md

sync_diff_inspector: update unsupport types

---

backup-and-restore-using-dumpling-lightning.md
br/backup-and-restore-storages.md
br/backup-storage-S3.md
dm/task-configuration-file-full.md
dumpling-overview.md
encryption-at-rest.md
migrate-aurora-to-tidb.md
migrate-from-csv-files-to-tidb.md
migrate-from-sql-files-to-tidb.md
migrate-large-mysql-to-tidb.md
sql-statements/sql-statement-backup.md
sql-statements/sql-statement-restore.md
sql-statements/sql-statement-show-backups.md

Signed-off-by: WangLe1321 <wangle1321@163.com>
Remove s3.region param in br/lightning/dumpling

br: remove s3 region param

---

tidb-lightning/tidb-lightning-data-source.md

Fix markdown display error

---

tidb-lightning/tidb-lightning-physical-import-mode-usage.md
tidb-lightning/tidb-lightning-physical-import-mode.md

tidb-lightning: update wording and format

---

system-variables.md

system variable: add `tidb_opt_skew_distinct_agg`

system variable: add tidb_opt_skew_distinct_agg

---

tikv-configuration-file.md

Signed-off-by: pingyu <yuping@pingcap.com>
Introduce CDC feature for API v2.
Please note that the related link (https://github.com/tikv/migration/tree/main/cdc) is still under development, and will be finished soon.

tikv,v6.2: Add CDC intro for API v2 

---

tiflash/tiflash-configuration.md

Fix wrong link format

---

tispark-overview.md

add TiSpark 3.0

---

statistics.md

planner: add docs for auto analyze 

---

faq/manage-cluster-faq.md
releases/release-5.0.0-rc.md
releases/release-5.0.0.md

Fix spelling of "true".
- Other reference link(s): https://github.com/pingcap/tidb/issues/36519

Fix spelling of 'true'

---

experimental-features.md

remote the avro support from experimental feature list

---

tikv-configuration-file.md

add description of `raftstore.report-min-resolved-ts-interval`

config: add description of report-min-resolved-ts-interval

---

system-variables.md

v6.2: update tidb_enable_paging default value

---

dm/task-configuration-file-full.md

Signed-off-by: WangLe1321 <wangle1321@163.com>
Remove s3.region parameter in dm

dm: remove s3.region parameter

---

configure-load-base-split.md
dynamic-config.md

Signed-off-by: JmPotato <ghzpotato@gmail.com>
Update the Load Base Split introduction to add the new configuration and refine the wording.
https://github.com/tikv/tikv/issues/12063

tikv: update the Load Base Split introduction

---

functions-and-operators/operators.md

Try to hide escape character

---

identify-slow-queries.md
information-schema/information-schema-slow-query.md
statement-summary-tables.md
system-variables.md

This PR adds a description of the binary plan, which is to support the visual plan feature on the dashboard side.
- Other reference link(s): https://github.com/pingcap/tidb/pull/35698

*: add description about the binary plan

---

tidb-lightning/tidb-lightning-data-source.md

fix table format in tidb-lightning-data-source

---

TOC.md
sql-statements/sql-statement-show-create-database.md

- Other reference link(s):https://github.com/pingcap/docs/issues/9589

doc: show create schema

---

placement-rules-in-sql.md

Signed-off-by: Lloyd-Pottiger <yan1579196623@gmail.com>
close #10606 
change statement in `placement-rules-in-sql.md`

make statement of using rules of Placement Rules in SQL more clear

---

tiflash/tiflash-configuration.md

tiflash: Change format_version default value to 4

---

br/backup-and-restore-design.md

Signed-off-by: Ubuntu <zhanggaoming028@gmail.com>
Add backup file layout description.
- Other reference link(s): https://github.com/pingcap/tidb/issues/30087

br: add backup file layout description

---

alert-rules.md

Fix 2 alert rules

---

upgrade-tidb-using-tiup.md

Fix format error

---

experimental-features.md

add multi-schema change to experimental feature page

---

tiflash/tiflash-configuration.md

tiflash: add a new configuration dt_enable_read_thread

---

develop/dev-guide-overview.md
develop/dev-guide-sample-application-java.md
develop/dev-guide-transaction-overview.md

[Update] add PE link

---

system-variables.md

Revert "v6.2: update tidb_enable_paging default value"

---

system-variables.md

- Other reference link(s): https://github.com/pingcap/tidb/pull/35496

add doc for @@tidb_enable_noop_variables

---

tikv-configuration-file.md

Signed-off-by: pingyu <yuping@pingcap.com>
Add TiKV config item `cdc.raw-min-ts-outlier-threshold`, which is added to TiKV since `v6.2`.
([Rendered](https://github.com/pingyu/docs-cn/blob/tikv-cn-raw-min-ts-outlier-threshold/tikv-configuration-file.md#raw-min-ts-outlier-threshold-%E4%BB%8E-v62-%E7%89%88%E6%9C%AC%E5%BC%80%E5%A7%8B%E5%BC%95%E5%85%A5))
- This PR …

tikv: add config item "raw-min-ts-outlier-threshold"

---

releases/versioning.md

Add a description that links to the TiDB support policy at the PingCAP website
- This PR is translated from: https://github.com/pingcap/docs/pull/9782
- Other reference link(s): https://github.com/pingcap/docs/pull/8486

releases: add a link to release support policy

---

tikv-configuration-file.md

https://github.com/tikv/tikv/pull/12798
- This PR is translated from: https://github.com/pingcap/docs/pull/8901

deprecate gc-merge-rewrite

---

ticdc/manage-ticdc.md

Add description of `--overwrite-checkpoint-ts` for changefeed resume

---

two-data-centers-in-one-city-deployment.md

Signed-off-by: nolouch <nolouch@gmail.com>

two-dc: remove the useless config

---

TOC.md

*: add docs home link in toc

---

tiflash-620-upgrade-guide.md

tiflash: correct major version description

---

br/pitr-usage.md

Fix a typo in pitr-usage.md

---

develop/dev-guide-transaction-troubleshoot.md

- Other reference link(s): https://github.com/pingcap/docs/issues/9825

develop: dev-guide-transaction-troubleshoot-typo.md fix typo

---

br/point-in-time-recovery.md

refine expression of pitr limitations

refine expression of pitr limitations

---

command-line-flags-for-tikv-configuration.md
dynamic-config.md

Fix format and remove ambiguous words

---

TOC.md
_index.md

tidb: add docs home in toc, and updated learning path

---

_index.md

learning path: fix a broken link

---

mysql-compatibility.md
sql-statements/sql-statement-alter-table.md

update the limitations of multi-schema change

---

system-variables.md

- Other reference link(s): https://github.com/pingcap/docs/pull/9813

system variable: correct the description about tidb_min_paging_size

---

sql-statements/sql-statement-explain.md

Add explanation for `explain format = "brief"`.
This functionality was introduced in v5.0 but remains undocumented.
- Other reference link(s): https://github.com/pingcap/tidb/pull/22677

 sql-statements: add explanation for `explain format = "brief"`

---

ticdc/manage-ticdc.md

close https://github.com/pingcap/tiflow/issues/6100

ticdc: add uri encode example

---

tidb-configuration-file.md
tikv-configuration-file.md

add missing doc for enable-forwarding

add missing doc for enable-forwarding

---

releases/release-5.0.0.md
releases/release-5.1.0.md
releases/release-5.2.0.md
statistics.md
tidb-configuration-file.md

https://github.com/pingcap/tidb/pull/35798 remove this configure item, update document for it.

tidb-configuration-file: remove the query feedback related configuration

---

tikv-configuration-file.md

Revert "config: add description of report-min-resolved-ts-interval"

---

tikv-configuration-file.md

br: add intro version for log backup configs

---

experimental-features.md

Add fast analyze to experimental document
- This PR is translated from: https://github.com/pingcap/docs/pull/9905

Add fast analyze to experimental document

---

alert-rules.md

Signed-off-by: 5kbpers <hustmh@gmail.com>
Add alert rules for PD_cluster_slow_tikv_nums

Add alert rules for PD_cluster_slow_tikv_nums

---

br/pitr-monitoring-and-alert.md

Signed-off-by: WangLe1321 <wangle1321@163.com>

br: modify metric name in alert rule and add alert examples

---

TOC.md
dashboard/dashboard-monitoring.md

- This PR is translated from: https://github.com/pingcap/docs/pull/9810
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/10535

dashboard: add a monitoring page

---

br/backup-and-restore-use-cases.md
dm/quick-start-create-task.md
migrate-from-tidb-to-mysql.md
pd-control.md
quick-start-with-tidb.md
replicate-data-to-kafka.md
ticdc/integrate-confluent-using-ticdc.md
ticdc/manage-ticdc.md
tidb-binlog/get-started-with-tidb-binlog.md

v6.2: bump version for tools

---

tidb-binlog/binlog-consumer-client.md

Close https://github.com/pingcap/docs-cn/issues/10804
- Other reference link(s): https://github.com/pingcap/tidb-tools/pull/668

fix broken link in binlog-consumer-client.md

---

tiflash/tiflash-configuration.md

add some config item for PageStorage V3

---

sql-statements/sql-statement-alter-table.md
sql-statements/sql-statement-create-database.md
sql-statements/sql-statement-create-table.md

- Other reference link(s): #10768

placement: add some additional syntax tree

---

tiflash-620-upgrade-guide.md

add more info in tiflash 620 upgrade guide

---

experimental-features.md

Add Cascades Planner to experimental-features
- This PR is translated from: https://github.com/pingcap/docs/pull/9854

Add Cascades Planner to experimental-features

---

.github/workflows/dispatch.yml

chore: disable release-6.2

---

system-variables.md

Although the current document has a clear description of INSTANCE scope variables at the beginning, users may still get confused when they reach the specified item by searching the document.
close #10842

sysvar: add description in INSTANCE sysvars

---

clinic/clinic-user-guide-for-tiup.md
clinic/quick-start-with-clinic.md
develop/dev-guide-delete-data.md
develop/dev-guide-get-data-from-single-table.md
develop/dev-guide-join-tables.md
develop/dev-guide-optimistic-and-pessimistic-transaction.md
develop/dev-guide-paginate-results.md
develop/dev-guide-prepared-statement.md
develop/dev-guide-sample-application-golang.md
develop/dev-guide-sample-application-java.md
develop/dev-guide-transaction-restraints.md
develop/dev-guide-update-data.md
develop/dev-guide-use-stale-read.md
develop/dev-guide-use-temporary-tables.md

Close https://github.com/pingcap/docs-cn/issues/10877

Syncing tab choices using groupId

---

config-templates/complex-tidb-binlog.yaml

Change `tidb-binlog` to `tidb_binlog` in deploy meta.yaml because the former way will make drainer fails.
- Other reference link(s): https://github.com/pingcap/tidb-binlog/issues/1139#event-6215887302

drainer: update config template

---

.github/workflows/dispatch.yml

Enable master on 6.2

---

scale-tidb-using-tiup.md

use scale-in to manually remove a TiFlash node

---

system-variables.md

add 4 missing system variables
- This PR is translated from: https://github.com/pingcap/docs/pull/9875 https://github.com/pingcap/docs/pull/9779 https://github.com/pingcap/docs/pull/9981

add 4 missing system variables

---

faq/migration-tidb-faq.md

- This PR is translated from: https://github.com/pingcap/docs/pull/9336

migration-tidb-faq: update now there is support for load data ... replace into

---

develop/dev-guide-proxysql-integration.md

develop/dev-guide-proxysql-integration.md: fix groupid

---

system-variables.md

This PR only aligns one modification from the source PR (https://github.com/pingcap/docs/pull/6451) because other contents are already there in the docs-cn repo.
- This PR is translated from: https://github.com/pingcap/docs/pull/6451

system-variables: add global scope to tidb_replica_read

---

best-practices/haproxy-best-practices.md

best practice: add link to tidb config `networks`

---

tiflash-620-upgrade-guide.md

- Other reference link(s): https://github.com/pingcap/docs-cn/pull/10866

fix link and update description

---

TOC.md
backup-and-restore-use-cases-for-maintain.md
br-usage-backup-for-maintain.md
br-usage-restore-for-maintain.md

The following three BR docs exist in the first-level directories Maintain and TiDB Tools at the same time:
- [使用 BR 备份集群](https://docs.pingcap.com/zh/tidb/stable/br-usage-backup)
- [使用 BR 恢复集群](https://docs.pingcap.com/zh/tidb/stable/br-usage-restore)
- [BR 备份与恢复场景示例](https://docs.pingcap.com/zh/tidb/stable/backup-and-restore-use-cases)
The navigation tree of the doc website fails to distinguish the files under the two directories. As a result, the location of the navigation jumps unexpectedly.
To address this issue, we change the file names under the Maintain directory.
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a …

br: rename three br docs under maintain for better search experience

---

production-deployment-using-tiup.md
scale-tidb-using-tiup.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

tiup bump version 6.2

---

replicate-data-to-kafka.md

ticdc: refine wording for integrating with kafka

---

.github/workflows/link-fail-fast.yaml
.github/workflows/link.yaml

- This PR is translated from:https://github.com/pingcap/docs/pull/9862

ci: add link fail fast

---

tidb-configuration-file.md

update open-tracing tidb-configuration description

---

_index.md

v6.2: bump version for learning path
- This PR is translated from: https://github.com/pingcap/docs/pull/10030

v6.2: bump version for learning path

---

pd-recover.md

Close https://github.com/pingcap/docs-cn/issues/10981
Update the Go version of PD Recover from v1.13 to v1.16. Since the change was merged into [tikv/pd](https://github.com/tikv/pd/pull/3711) on May 27, 2021, this PR needs cherry pick from v4.0 to v6.2
- Other reference link(s): https://github.com/tikv/pd/pull/3711

PD Recover: update Go version from v1.13 to v1.16

---

TOC.md
ticdc/integrate-confluent-using-ticdc.md

ticdc: highlight integrate with snowflake

---

tune-operating-system.md

feedback from [ASKTug](https://asktug.com/t/topic/902943)
- Add more internal/external links in this document to better understand some concepts
- Fix typo `/proc/interrputs` to `/proc/interrupts`

tune-operating-system.md: add more links and fix format

---

system-variables.md
tidb-configuration-file.md

[Users in TUG](https://asktug.com/t/topic/902999) complain that the description of `force-priority` is not clear.

sysvar, config: improve force-priority

---

integration-overview.md

- This PR is translated from: https://github.com/pingcap/docs/pull/10082

ticdc: emphasize integrating with snowflake in overview

---

TOC.md

- Other reference link(s): https://github.com/pingcap/docs-cn/pull/10970

update version in TOC for sysbench and tpc-c reports

---

TOC.md

Fix a toc issue: If only link anchors are used in TOC, the left navigation doesn't work properly when a user clicks on the anchor.

lightning: fix toc issues

---

migration-overview.md

Added ticdc in migration overview

migration: add ticdc in migration overview

---

tidb-lightning/tidb-lightning-distributed-import.md

Delete contents about diagrams in lightning

lightning: delete contents about diagrams in lightning

---

join-reorder.md
system-variables.md

Update for outer join reorder

---

.github/workflows/dispatch.yml

- This PR is translated from: https://github.com/pingcap/docs/pull/10116

chore: enable build of release 6.2

---

tidb-lightning/deploy-tidb-lightning.md
tidb-lightning/tidb-lightning-requirements.md

Close https://github.com/pingcap/docs-cn/issues/10766

lightning: fix format and typo

---

resources/cdnfresh.txt

add 6.2 to the cdnfresh list

---

.github/workflows/dispatch.yml

chore: enable build of the master branch

---

TOC.md
releases/release-6.2.0.md
releases/release-notes.md
releases/release-timeline.md

refine 6.2 release docs

---

br/br-log-command-line.md
br/pitr-usage.md

Signed-off-by: joccau <zak.zhao@pingcap.com>

modify pitr doc for comments about log-backup.enable

---

tidb-lightning/monitor-tidb-lightning.md

fix typo in monitor-tidb-lightning.md

---

releases/release-5.3.1.md

release 5.3.1: move dm bug fixes from the ticdc module to the dm module

---

releases/release-6.1.0.md

emphasize a ticdc improvement in 6.1 release notes

---

best-practices/haproxy-best-practices.md

Revert "Update a path in haproxy guide"

---

TOC.md
_index.md
faq/faq-overview.md

faq: add a summary page for all TiDB FAQs

faq: add a summary page for all TiDB FAQs

---

faq/faq-overview.md

faq: add k8s to the summary page

faq: add k8s to the summary page

---

faq/migration-tidb-faq.md

fix incorrect description in migration faq

---

ticdc/ticdc-faq.md

Add upstream to clarify the TiCDC stall scenario when using TiDB Lightning and BR.

TiCDC FAQ: clarify the scenario when using TiDB Lightning and BR

---

ticdc/ticdc-open-api.md

- This PR is translated from: https://github.com/pingcap/docs/pull/10088

fix: typo on ticdc open api field description

---

.github/pull_request_template.md

chore: add 6.3 to PR template

---

releases/release-6.2.0.md
tidb-lightning/tidb-lightning-physical-import-mode-usage.md
tidb-lightning/tidb-lightning-physical-import-mode.md

The original description is inappropriate because physical import mode can be used in production environment even before v6.2. 

lightning: fix a heading in physical import mode

---

releases/release-5.1.4.md

Add a new entry in release notes 5.1.4

tidb: add a new entry in release notes 5.1.4

---

clinic/clinic-collect-sql-query-plan.md

clinic: revise clinic plan replayer load

---

develop/dev-guide-use-fastscan.md

dev guide: fix title of fastscan
